### ISSUE TITLE
Not project creator: Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kubeflow-storage error(400): BAD REQUEST

### ISSUE THREAD

**Issue by NicholaiStaalung** [kubeflow/manifests#1004]
I tried installing gcp_iap on GKE and got into the error in the headline.

My steps where:

Followed the official documentation but replaced CONFIG_URI with https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml

Other infomation:

Im the project owner on GCP as stated i should be in the documentation, but im not the project creator. I tried deploying in a new sandbox environment (Which i created) and it moved past the error until it hit a resource error about GPU's not being present in the data center. 

So this must mean that one would have to create the project in order to install kubeflow?

picture of error:
![image](https://user-images.githubusercontent.com/25878853/76637294-c1b3e900-654a-11ea-964a-ede5a5a6cd8b.png)

Full log :

> INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_basic_auth.0.7.1.yaml to /tmp/275262265/tmp.yaml  
> filename="utils/k8utils.go:172"
> INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_basic_auth.0.7.1.yaml to /tmp/414350660/tmp_app.yaml  filename="loaders/loaders.go:71"
> INFO[0000] App directory /root/build/kubeflow_build/kubeflow-deployment/datascience already exists  filename="coordinator/coordinator.go:270"
> INFO[0000] Writing KfDef to kfctl_gcp_basic_auth.0.7.1.yaml  filename="coordinator/coordinator.go:273"
> INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to datascience based on location of config file: /root/build/kubeflow_build/kubeflow-deployment/datascience/kfctl_gcp_basic_auth.0.7.1.yaml.  filename="coordinator/coordinator.go:202"
> INFO[0000] Creating default token source                 filename="gcp/gcp.go:182"
> INFO[0000] Creating GCP client.                          filename="gcp/gcp.go:194"
> INFO[0000] 
> ****************************************************************
> Notice anonymous usage reporting enabled using spartakus
> To disable it
> If you have already deployed it run the following commands:
>   cd $(pwd)
>   kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus
> 
> For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
> ****************************************************************
>   filename="coordinator/coordinator.go:120"
> INFO[0000] Creating directory /root/build/kubeflow_build/kubeflow-deployment/datascience/.cache  filename="kfconfig/types.go:445"
> INFO[0000] Fetching https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz to /root//build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests  filename="kfconfig/types.go:493"
> INFO[0012] updating localPath to /root/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests/manifests-0.7-branch  filename="kfconfig/types.go:540"
> INFO[0012] Fetch succeeded; LocalPath /root/build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests/manifests-0.7-branch  filename="kfconfig/types.go:561"
> INFO[0012] /root/build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
> WARN[0012] Backfilling auth; this is deprecated; Auth should be explicitly set in Gcp plugin  filename="gcp/gcp.go:1946"
> INFO[0012] Setting Email to default: nrs@...com  filename="gcp/gcp.go:2020"
> INFO[0012] Setting Project to default: xxx  filename="gcp/gcp.go:2033"
> INFO[0013] Setting Zone to default: europe-west3-b       filename="gcp/gcp.go:2046"
> INFO[0013] Configuring pipelines persistent storage      filename="gcp/gcp.go:1375"
> INFO[0013] Configuring pipeline, minio, and mysql applications  filename="gcp/gcp.go:2170"
> INFO[0013] Processing application: istio-crds            filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: istio-install         filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: istio                 filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: application-crds      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: application           filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: metacontroller        filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: argo                  filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: kubeflow-roles        filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: centraldashboard      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: webhook               filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: bootstrap             filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: jupyter-web-app       filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: metadata              filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: notebook-controller   filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pytorch-job-crds      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pytorch-operator      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: knative-crds          filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: knative-install       filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: kfserving-crds        filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: kfserving-install     filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: spartakus             filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: tensorboard           filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: tf-job-crds           filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: tf-job-operator       filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: katib-crds            filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: katib-controller      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: api-service           filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: minio                 filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: mysql                 filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: persistent-agent      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pipelines-runner      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pipelines-ui          filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pipelines-viewer      filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: scheduledworkflow     filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: pipeline-visualization-service  filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: cloud-endpoints       filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: profiles              filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: gpu-driver            filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: seldon-core-operator  filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: ambassador            filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: basic-auth            filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: basic-auth-ingress    filename="kustomize/kustomize.go:397"
> INFO[0013] Processing application: default-install       filename="kustomize/kustomize.go:397"
> INFO[0013] /root/build/kubeflow_build/kubeflow-deployment/datascience/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:468"
> INFO[0013] GCP client already configured                 filename="gcp/gcp.go:167"
> INFO[0013] Reading config file: /root//build/kubeflow_build/kubeflow-deployment/datascience/gcp_config/storage-kubeflow.yaml  filename="gcp/gcp.go:286"
> INFO[0013] Reading import file: /root/build/kubeflow_build/kubeflow-deployment/datascience/gcp_config/storage.jinja  filename="gcp/gcp.go:322"
> INFO[0015] Updating deployment datascience-storage       filename="gcp/gcp.go:443"
> INFO[0016] Reading config file: /root//build/kubeflow_build/kubeflow-deployment/datascience/gcp_config/cluster-kubeflow.yaml  filename="gcp/gcp.go:286"
> INFO[0016] Reading import file: /root/build/kubeflow_build/kubeflow-deployment/datascience/gcp_config/cluster.jinja  filename="gcp/gcp.go:322"
> INFO[0018] Updating deployment datascience               filename="gcp/gcp.go:443"
> ERRO[0027] Updating datascience-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'zone' on resource 'datascience-storage-metadata-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:384"
> ERRO[0027] Updating datascience-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'type' on resource 'datascience-storage-metadata-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:384"
> ERRO[0027] Updating datascience-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'zone' on resource 'datascience-storage-artifact-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:384"
> ERRO[0027] Updating datascience-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'type' on resource 'datascience-storage-artifact-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:384"
> Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating datascience-storage error(400): BAD REQUEST

**Comment by JeffersonH44** [comment]
Hello @NicholaiStaalung, you have to check inside deployment manager what is the error. In my case is that in the zone us-east1-b doesn't have k80's so I've change my zone, also you can change you cluster-kubeflow.yaml file to use other GPU

**Comment by hassanzadeh** [comment]
Hey @JeffersonH44, how can I check the deployment manager logs?
