### ISSUE TITLE
GCP resource config: publish CNRM resources  

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#1019]
We should publish CNRM resources config so GCP resources can be created through submitting CNRM config to KCC controller.  
(Currently GCP resources are created through deploy manager configs)

**Comment by jlewi** [comment]
@kunmingg do we need this and #894 or should we mark one as a duplicate of the other? Otherwise lets clarify what the issues are tracking.

**Comment by kunmingg** [comment]
https://github.com/kubeflow/manifests/tree/master/gcp/v2/cnrm
