### ISSUE TITLE
Seldon fails if KF is deployed to a custom namespace

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/manifests#1022]
Kubeflow can be generally deployed to any namespace by specifying `metadata.namespace` in KFDef file.

The current version of Seldon fails though, since the `kubeflow` name is hardcoded in the `resource.yaml`.

e.g.
* https://github.com/kubeflow/manifests/blob/master/seldon/seldon-core-operator/base/resources.yaml#L3473-L3476
* https://github.com/kubeflow/manifests/blob/master/seldon/seldon-core-operator/base/resources.yaml#L3514
* https://github.com/kubeflow/manifests/blob/master/seldon/seldon-core-operator/base/resources.yaml#L3603

The above (and few more occurrences) prevent from deploying to a namespace where name != `kubeflow`.

I was able to parameterize it using Kustomize `vars`, but since the `resource.yaml` is generated it does not make sense to submit a PR for it.

I was also thinking about using my approach with vars and simple using a string `$(namespace)` in `Makefile`, but problem with that is that the namespace is templated into manifests names as well, so the `params.yaml` would be hard to maintain. Is it necessary to have `namespace` in the names of the resources - have you ever run into any conflict? 

Any thoughts what would be the right approach?

cc @cliveseldon

**Comment by vpavlin** [comment]
FYI these were my customizations: https://github.com/vpavlin/manifests/commit/a55a038a0cbad0044d845df2704e61929e1a525c

**Comment by jbottum** [comment]
@cliveseldon fyi, a seldon kubeflow issue

**Comment by vpavlin** [comment]
ping @cliveseldon

**Comment by cliveseldon** [comment]
Sorry @vpavlin missed this. Have you tested with 1.1 release candidate

**Comment by cliveseldon** [comment]
I see yes the namespace is still hardwired in the manifests so will need to remove.

**Comment by ryandawsonuk** [comment]
@vpavlin is this specifically an issue about seldon? Does it not also affect https://github.com/kubeflow/manifests/blob/master/argo/base/deployment.yaml#L8 ?

**Comment by vpavlin** [comment]
@ryandawsonuk The issue is not specific to Seldon, but your example is not causing the trouble.

Kustomize is able to override the namespace in many cases, but there are places where it cannot do automatically - like if there is a service reference (`service.namespace.svc` - e.g. https://github.com/kubeflow/manifests/blob/a6755ffa8892c54a37a2e641f7559458eb308c3b/seldon/seldon-core-operator/base/resources.yaml#L4785) or `namespace` in webhook configurations (https://github.com/kubeflow/manifests/blob/a6755ffa8892c54a37a2e641f7559458eb308c3b/seldon/seldon-core-operator/base/resources.yaml#L4850)..these cannot be hardcoded and have to be templated with namespace parameter

**Comment by cliveseldon** [comment]
Thanks @vpavlin Any pointers to existing manifests that template with namespace parameter for these cases?

**Comment by jlewi** [comment]
@cliveseldon @vpavlin I'm downgrading to P2. I don't consider installing `kubeflow` in non standard namespace to be something that's officially supported. This issue confirms my expectation that the assumption that things are installed in the `kubeflow` is baked into a variety of places. 

If application owners want to start fixing those issues, I think that's great. That said unless/until we have E2E tests verifying that kubeflow works in different namespaces I would hesitate to say this something that officially works. By extension, I think this makes fixing these issues P2 for app owners. I don't want to ask app owners to prioritize fixing these bugs if we don't have the tests that would block us from saying this is actually working and supported.

**Comment by vpavlin** [comment]
That's fine by me, @jlewi. I mainly submitted this issue to keep track of these since we are going to hit them in Open Data Hub when we start to mix ODH and Kubeflow components - we don't really dictate users to which namespace they should deploynsince we know there are some naming patterns/policies they need to follow in production. I'll keep poking around and will try to help fixing these.
