### ISSUE TITLE
Include Tekton in Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1023]
Should we include Tekton in Kubeflow distributions?

If we want to start using Tekton more broadly in Kubeflow (e.g. for container building kubeflow/fairing#454), then we will need to think about how we tell users to install it.

Installing Tekton onto an existing cluster is pretty straightforward.
https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-on-kubernetes

As a stop-gap we could always tell users to install it separately or assume they already have it installed on their cluster.

That's not the greatest user experience though if we want to use it in getting started tutorials and the first thing we have to do is tell people to do additional cluster setup.

**Comment by jlewi** [comment]
@animeshsingh WDYT?

**Comment by animeshsingh** [comment]
+1 and agree to making Tekton the default CI/CD engine being deployed with Kubeflow.

**Comment by jlewi** [comment]
Removing from KF 1.1 since no one is working on this.
