### ISSUE TITLE
kubeflow on GCP: upgrade Istio to ASM

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#1024]
Currently by default kubeflow use Istio 1.1.6 for service mesh.
On GCP we should use ASM which based on Istio 1.4+.
Benefits include:
* leverage new Istio APIs & features
* have a semi-managed service mesh experience

**Comment by jlewi** [comment]
The GCP blueprint is using ASM. So I'm closing this issue.
https://github.com/kubeflow/gcp-blueprints
