### ISSUE TITLE
kfserving-gateway wasn't included in the 1.0.1 tag but is in the YAML so install fails

### ISSUE THREAD

**Issue by holdenk** [kubeflow/manifests#1029]
`Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway`

**Comment by jlewi** [comment]
It looks like this was reverted in #1073 .
#1027 was the original cherry-pick into the v1.0 branch.

It looks like the v1.0.1 tag is pointing at the broken commit (the one that added the kfserving gateway to the YAMLs)
https://github.com/kubeflow/manifests/releases/tag/v1.0.1
https://github.com/kubeflow/manifests/commit/6cb83f8227daaaa80846e5145521d9b7cadba1a6

Do we not have tests for the 1.0.1 specs?

**Comment by jlewi** [comment]
#4834 looks like the tracking bug for the 1.0.1 release

**Comment by jlewi** [comment]
@richardsliu and @Jeffwan Do you know what the state of the 1.0.1 release is?

**Comment by richardsliu** [comment]
This should be fixed in the 1.0.1 release manifests in v1.0-branch.

**Comment by holdenk** [comment]
I think this should be fixed since the 1.0.1 tag was re-created with the missing file.
