### ISSUE TITLE
kfserving not included in AWS kfdef 1.0.1

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/manifests#1035]
The most recent [kfdef for AWS](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws_cognito.v1.0.1.yaml) does not include KFServing (and also not prerequisites such as KNative). I'm not sure if there is a reason for this, but it would be nice if KFServing were rolled out along with the rest of the Kubeflow components.

@Jeffwan

**Comment by Jeffwan** [comment]
@karlschriek 

I will help add to default manifest.

**Comment by Jeffwan** [comment]
I asked @PatrickXYS to pick up work. Thanks.

**Comment by Jeffwan** [comment]
/assign @theofpa  
Update: @theofpa will help on this issue
