### ISSUE TITLE
kfdef on v1.0 branch broken

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#1036]
`kfctl build https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml`

throws error 

`"failed to build kfApp from URI: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway","time":"2020-03-20T20:49:29Z"}`

**Comment by jlewi** [comment]
@kunmingg Can we close this? Is it fixed by #1037?

**Comment by jlewi** [comment]
Duplicate of #1029
