### ISSUE TITLE
[Pipelines] Reuse KFP standalone manifests in kubeflow/manifests

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/manifests#1048]
Part of https://github.com/kubeflow/manifests/issues/1062

Depends on http://bit.ly/kf_kustomize_v3

Above mentioned kustomize v3 plan will allow [Kubeflow Pipelines Standalone deployment manifests](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize) get reused by Kubeflow.

Following OTS strategy:
* set up a bot that syncs kubeflow pipelines standalone manifest changes with a PR to `kubeflow/manifest/pipelines/standalone` after each release
* in kubeflow/manifest repo, use stacks that refer to and customize kfp standalone manifests' specific components using overlays

Then most kfp upstream manifest changes can be synced to kubeflow with minimal maintenance efforts, because `kubeflow/manifest/pipeline/standalone` folder won't have conflicts

/cc @jlewi

**Comment by jlewi** [comment]
@Bobgy To complete http://bit.ly/kf_kustomize_v3 we will want a single kustomize package that installs all the pipeline applications. Should we base that off the manifest that's currently in kubeflow/manifests/pipelines or should we copy for the kfp standalone manifests?

**Comment by Bobgy** [comment]
@jlewi I think copying from kfp standalone manifests is better considering the long term goal.

No matter what, http://bit.ly/kf_kustomize_v3 has to be a big rewrite, so I think it will be cost efficient if we can do both at the same time.

**Comment by Bobgy** [comment]
Some parts of kfp standalone manifests may not be generic enough, I will also structure it using patterns introduced in http://bit.ly/kf_kustomize_v3 to get a good base.

May I ask what would be your rough timeline for kustomize v3 plan, will it be part of KF 1.1? My plan is pretty packed already until end of April, just heads up.

**Comment by Bobgy** [comment]
I can actually adjust my plan accordingly depending on timeline for this. This saves a lot of efforts for KFP and KF's integration.

**Comment by jlewi** [comment]
Yes we are targeting Kubeflow 1.1 which is end of june.

Thanks

**Comment by jlewi** [comment]
@Bobgy any update on this? It would be great to have an updated manifest that we could begin testing with GCP blueprints and multiuser.

**Comment by Bobgy** [comment]
@jlewi Thanks for the reminder. A quick question: is there still any value merging KFP multi user mode to non v3 manifest?

**Comment by jlewi** [comment]
No. I don't think so. I would just putting the new features in the new v3 version of the manifest.

**Comment by Bobgy** [comment]
Thanks for confirmation, I guess so. I will try porting kfp standalone to kustomize v3.

**Comment by jlewi** [comment]
@Bobgy Any update on this?

**Comment by Bobgy** [comment]
@jlewi I'm working on KFP 1.0 release now, will continue after cutting first rc this week

**Comment by jlewi** [comment]
Bump to P1 because we need this to make pipelines deployable with blueprints.

**Comment by Bobgy** [comment]
@jlewi FYI, I reviewed with Jessie today, she has no problem on the plan. I will start on this tomorrow (got some urgent issues today).

**Comment by jlewi** [comment]
Thanks @Bobgy we are trying to target June 19 for cutting the initial RC.
