### ISSUE TITLE
Is there a way to merge Override in configmap

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1057]
I would like to have separate overlays to configure object storage and mysql setting. 
https://github.com/kubeflow/manifests/blob/master/pipeline/api-service/overlays/external-mysql/config-map.yaml

Is there's a way to merge configmap content from different overlays?

**Comment by jlewi** [comment]
You can do strategic patch merges on ConfigMaps but I think this does a strategic patch merge on the ConfigMap not the file contents. So the patch would have to completely override the file.

I think in kustomize you could define a custom plugin that would define a new type of patch that would apply a patch to the file contents.

**Comment by Jeffwan** [comment]
@jlewi Thanks for confirmation. Pipeline has many configurations and I notice it's not very good to override configmap because of this limitation. I will try to check if these pipeline code expose corresponding environment variable. That's straightforward in kustomize.
