### ISSUE TITLE
No source available for istio-adapter

### ISSUE THREAD

**Issue by adrian-plutoflume** [kubeflow/manifests#1070]
We're using the AWS cognito setup and hit some issues with the istio-adapter.

More specifically this is using a docker image `seedjeffwan/istio-adapater` but there's no source code available for that (which is not great from a security perspective) but it's also hindering our ability to debug and fix issues ("Email is not verified false" - fixed it for one person, can't see why it's triggering for others).  

@Jeffwan - I wondered if it's possible to make the source code public? It'd really help us to see where we are going wrong (or what we've missed).

**Comment by Jeffwan** [comment]
@adrian-plutoflume sorry for inconvenience , we are in process of public the repo and move image to AWS dockerhub. 

You have to make sure email is verified when you create Cognito user because we will use `email` to create a new header and this will be used in authorization.

**Comment by Jeffwan** [comment]
Let me public the repo in my personal github and you can debug on your own. This is a mixer adaptor and let me know if you have questions

**Comment by Jeffwan** [comment]
I just make it public. Check logic here https://github.com/Jeffwan/authzadaptor/blob/master/authzadaptor.go

**Comment by adrian-plutoflume** [comment]
Wow! That was super speedy :-)  Great to hear it's in process - I thought maybe it had just been missed (hence raising a ticket).

**Comment by jlewi** [comment]
Can we close this issue?

**Comment by adrian-plutoflume** [comment]
I'm certainly happy if you do, not sure if you want it to track the move to aws public hub (don't think it's needed for that)

**Comment by Jeffwan** [comment]
Yeah. We don't have to track that here. Let's just close this issue. 

/close
