### ISSUE TITLE
Istio cluster-local-gateway: istio rbac

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1078]
I noticed that the Istio cluster-local-gateway doesn't have associated Istio RBAC with it, like the istio-ingressgateway.
This should be fairly simple, like adding this:
```yaml
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: cluster-local-gateway
  namespace: istio-system
spec:
  rules:
  - services:
    - cluster-local-gateway.istio-system.svc.cluster.local

---

apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: cluster-local-gateway
  namespace: istio-system
  resourceVersion: "1984"
spec:
  roleRef:
    kind: ServiceRole
    name: cluster-local-gateway
  subjects:
  - user: '*'
```

@krishnadurai @ryandawsonuk  what do you think?
Will open a PR if we are in agreement.

**Comment by krishnadurai** [comment]
Sure you could add these Istio RBAC rules.

**Comment by jlewi** [comment]
@krishnadurai and @yanniszark Could you provide an update on this? Do we think its going to land for KF 1.1? If not can we down grade it to P2 and remove it?
