### ISSUE TITLE
Change PR template instructions to reflect new unittests scheme

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#1084]
The template shows the following checks:

```
 Unit tests have been rebuilt:
    cd manifests/tests
    make generate-changed-only
    make test
```

The newest change to manifests unittests need to use `make generate` instead of `make generate-changed-only`

/assign @jlewi

**Comment by Jeffwan** [comment]
@krishnadurai 

Does `make generate` work properly in your env?  I see some issues and they are documented in  https://github.com/kubeflow/manifests/issues/1077

**Comment by Jeffwan** [comment]
Never mind, I change kustomize from v3.5.3 to v3.2.3 and it's working now.

**Comment by jlewi** [comment]
@krishnadurai make generate-changed-only and make generate should do the same thing.

The parameter "--all" is no longer used
https://github.com/kubeflow/manifests/blob/f263eb3c28296c036e2985434dc0588aa5f1d336/hack/generate_tests.py#L162

**Comment by krishnadurai** [comment]
@jlewi following from:

https://github.com/kubeflow/manifests/blob/f263eb3c28296c036e2985434dc0588aa5f1d336/hack/generate_tests.py#L166

Do we intend to suggest users to still use it?

**Comment by jlewi** [comment]
@krishnadurai no. Given the direction we are headed I don't think there's a simple way to only regenerate tests that are affected by the changes.

The parameter is still there only so we didn't have to update all the calling locations at once.
