### ISSUE TITLE
Argo V3 Kustomize Manifest

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1090]
We need a v3 kustomize manifest for Argo.  
See:http://bit.ly/kf_kustomize_v3

See #1062 for more info.

@Bobgy will you tackle this as part of #1048

**Comment by Bobgy** [comment]
I can start working on these at early May I think.
If no one else has time before that, let me take it.
/assign @Bobgy

**Comment by jlewi** [comment]
@Bobgy Any update on this?

**Comment by Bobgy** [comment]
@jlewi I will start on these this week.
