### ISSUE TITLE
kustomize v3 versions for KFServing and KNative

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1091]
We need kustomize v3 versions of the KFServing and KNative packages.

See #1062 for more info on what this means.

@yuzisun @animeshsingh @cliveseldon is there someone from KFServing who would be willing to pick this up?

**Comment by animeshsingh** [comment]
@jlewi I talked to @adrian555 and he will work on it.

/assign @adrian555

**Comment by jlewi** [comment]
@adrian555 any update on this?

**Comment by adrian555** [comment]
@jlewi yes, I just pushed the PR #1156 above with what I think is needed for the v3 update. Please let me know if I missed something. Thanks.

cc @animeshsingh
