### ISSUE TITLE
v3 version of AWS KFDefs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1095]
See: #1062 
AWS KFDefs should follow v3 patterns in order to not depend on kfctl kustomize magic

/cc @Jeffwan

**Comment by Jeffwan** [comment]
Thanks. I will check #1062 and get more details on the migration.

**Comment by Jeffwan** [comment]
@jlewi 

I am in progress of migrate current manifest to follow v3 pattern. I am a little bit confused on the composition. 

Looks like stack gcp has some v3 compatible resources.  https://github.com/kubeflow/manifests/blob/master/stacks/gcp/kustomization.yaml
 and `kfctl_gcp_stacks.experimental.yaml`  also has some manifest like `stack/gcp` and some other components like cert-manager. 
https://github.com/kubeflow/manifests/blob/master/stacks/examples/kfctl_gcp_stacks.experimental.yaml

What's the principles?  I thought we should have a common stack and cloud specific stack?  For example,

```
- stacks/common 
   - common/centraldashboard/
   - common/spartakus
- stack/training-operators
- stack/gcp
   - cloud-endpoint
   - gcp/gpu-driver
```

Seems current example is not organized in this way?

**Comment by jlewi** [comment]
Every platform has the option of being oppinionated about which applications to install. So its not clear that all platforms will want to install all training operators or agree on what the common applications are.

**Comment by jlewi** [comment]
@Jeffwan any update on what your plans for 1.1 are?
