### ISSUE TITLE
v3 version of IBM KFdefs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1096]
See: #1062
IBM KFDefs should follow v3 patterns in order to not depend on kfctl kustomize magic

/cc @Jeffwan

**Comment by jlewi** [comment]
@animeshsingh looks like I cc'd the wrong person. What are your plans regarding installation of KF 1.1? Are you going to recommend people use your operator? Are you going to use the new v3 manifests or the older versions?

**Comment by animeshsingh** [comment]
@jlewi what's the date for 1.1 release? Also wouldn't we encourage everyone to move to kustomizev3 manifests if every component is being moved, though only the entry point (kpt, kfctl/kfdef, operator) will differ?

**Comment by jlewi** [comment]
kubeflow/kubeflow#5022 is tracking the release. Lets say end of june.

>  Also wouldn't we encourage everyone to move to kustomizev3 manifests if every component is being moved, though only the entry point (kpt, kfctl/kfdef, operator) will differ

Yes. I would recommend using the V3 manifests because they should address alot of the pain points raised by users.

**Comment by animeshsingh** [comment]
Makes sense
/assign @adrian555
