### ISSUE TITLE
Update Argo manifest to 2.5.0

### ISSUE THREAD

**Issue by rossella** [kubeflow/manifests#1099]
When using CRI-O, PNS executor fails with "executor error: Failed to determine pid for containerID xxxxxxxxxxxxx: container may have exited too quickly" .
This is due to https://github.com/argoproj/argo/issues/2095
Updating argo fixes the issue.

**Comment by rossella** [comment]
We tested in our environment with argo workflow-controller 2.5.0 and argo-ui 2.4.2.
We had to apply the following changes:
- modify argo/base/custer-role.yaml adding for apiGroups argoproj.io the following resources: cronworkflows and workflowtemplates 

Shall we go on and create a PR?

**Comment by Gsantomaggio** [comment]
I'd add that we ( I and @rossella ) were thinking to split the current Argo deploy in two sections:

- `argo` 
- `argo-ui` 

Since they are two different repositories.
We are already working on it, please let us know what you think about that, so we can prepare the PR.

Thank you

**Comment by Gsantomaggio** [comment]
@rossella I think we can close this issue. See https://github.com/kubeflow/pipelines/pull/3537

**Comment by Ark-kun** [comment]
/reopen
Kubeflow Pipelines does not work well with Argo < 2.4
Some people have issues since they install KFP from Kubeflow and get old Argo version.

**Comment by solarist** [comment]
> Some people have issues since they install KFP from Kubeflow and get old Argo version.

We do too. We have installed a full on-prem installation of 1.1, and still see that the executor image is `argoexec:v2.3.0`, as well the one set in the workflow-controller-configmap.

**Comment by yanniszark** [comment]
The work for upgrading Argo is tracked in the Kubeflow Pipelines repo.
https://github.com/kubeflow/pipelines/issues/4553
https://github.com/kubeflow/pipelines/pull/4693
