### ISSUE TITLE
Update SparkApplication CRD

### ISSUE THREAD

**Issue by wdhorton** [kubeflow/manifests#1117]
I deployed Kubeflow 1.0.1, and I'm seeing this log from the sparkoperator:
```
 reflector.go:125] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: Failed to list *v1beta2.ScheduledSparkApplication: the server could not find the requested resource (get scheduledsparkapplications.sparkoperator.k8s.io)
```

I checked the manifests, and it looks like Kubeflow is still using the v1beta1 version of the CRD: https://github.com/kubeflow/manifests/blob/master/spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml#L1

I believe that updating it to the v1beta2 version will resolve this issue

**Comment by Jeffwan** [comment]
That's the custom resource version. spark CRD version is here https://github.com/kubeflow/manifests/blob/master/spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml#L2522

**Comment by Jeffwan** [comment]
spark-operator actually supports two CRD, `scheduledsparkapplications` is different from `sparkapplication`, it's for cron based spark jobs. 

Can you check if you have this? https://github.com/kubeflow/manifests/blob/master/spark/spark-operator/base/scheduledsparkapplications.sparkoperator.k8s.io-crd.yaml

kubectl get crds | grep scheduledsparkapplications and check it's version
