### ISSUE TITLE
In-compatibility with Kustomize Go API version

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/manifests#1118]
**What happened:**
Given the PR #962 , we updated manifests `go.mod` file:
From: 
```
require sigs.k8s.io/kustomize/v3 v3.2.0
```
To:
```
require sigs.k8s.io/kustomize/v3 v3.2.1
```

But we haven't updated `go.sum`, there are only `v3.2.0` dependency paths:

```
sigs.k8s.io/kustomize/v3 v3.2.0 h1:EKcEubO29vCbigcMoNynfyZH+ANWkML2UHWibt1Do7o=
sigs.k8s.io/kustomize/v3 v3.2.0/go.mod h1:ztX4zYc/QIww3gSripwF7TBOarBTm5BvyAMem0kCzOE=
```

Thus, when users are trying to build, the error occurs:

```
go: sigs.k8s.io/kustomize/v3@v3.2.1: unknown revision v3.2.1
``` 

It will not happen if users have already get `sigs.k8s.io/kustomize/v3 v3.2.1` in their GOPATH, but it will result in errors when users don't have corresponding dependencies. 

**Action Item:**
Update `go.sum` file with corresponding `v3.2.1` dependencies.

/cc @jlewi

**Comment by jlewi** [comment]
Thanks @PatrickXYS 
Would you be interested in providing a PR to fix this?

**Comment by PatrickXYS** [comment]
@jlewi Sure, I'll file a PR for fixing this one.
