### ISSUE TITLE
kfserving is broken in v1.0.2

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1142]
Talked with @yuzisun offline, 

Kfserving-gateway revert in #1111 is incomplete, there're still a few references in kfserving and knative. 

https://github.com/kubeflow/manifests/blob/v1.0-branch/kfserving/kfserving-install/base/config-map.yaml#L93

https://github.com/kubeflow/manifests/blob/v1.0-branch/knative/knative-serving-install/base/gateway.yaml#L30

This breaks kfserving now.

**Comment by yantriks-edi-bice** [comment]
Is this really closed? Does this mean that kfserving should work in kubflow 1.0.2? I've tried upgrading to 1.0.2 (and yes process completes but cannot verify the version - where is that?) and keep getting the following when creating tfjobs etc.

"failed calling webhook "inferenceservice.kfserving-webhook-server.pod-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-pods?timeout=30s: service "kfserving-webhook-server-service" not found"
