### ISSUE TITLE
AWS : Enable enablePodIamPolicy by default 

### ISSUE THREAD

**Issue by akartsky** [kubeflow/manifests#1151]
## Issue
Currently to [Enable IAM for Service Account](https://www.kubeflow.org/docs/aws/iam-for-sa/#enable-iam-role-for-service-account) we need to modify the [kfctl_aws.v1.0.2.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.2.yaml) or [kfctl_aws_cognito.v1.0.2.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws_cognito.v1.0.2.yaml) 

## Solution

Make `enablePodIamPolicy: True` by default for AWS manifest files

**Comment by Jeffwan** [comment]
Thanks for the contribution.

**Comment by Jeffwan** [comment]
This has been addressed in v1.1.0. I will close the issue. Feel free to close it
