### ISSUE TITLE
Delete JupyterHub kustomize manifest

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#116]
It looks like
https://github.com/kubeflow/manifests/tree/master/jupyter/jupyter

is providing a manifest for jupyterhub.

But jupyterhub was removed in 0.5.

I suggest deleting that manifest to avoid confusion about whether jupyterhub is supported or not.

@ashahba Interested?

**Comment by whiletruelearn** [comment]
I would like to take this up. Can I pick it up @jlewi

**Comment by adepuravikrishna** [comment]
I closed PR since other people on the list already. apologies on that.

**Comment by jlewi** [comment]
@adepuravikrishna @whiletruelearn Does one of you want to pick this up? If you do just go ahead and send out a PR please and make a note on the issue; you can "/assign the PR to me".

We will want to delete the entire directory
jupyter/jupyter

Since that whole package is for JupyterHub.

**Comment by jlewi** [comment]
@whiletruelearn it would be great to get #253 fixed and merged; I just think the tests need to be updated.
