### ISSUE TITLE
Release versions discrepancy in the UI after upgrading from 0.6 to 1.0.2 

### ISSUE THREAD

**Issue by yassine-labidi** [kubeflow/manifests#1160]
Hi,
We've recently upgraded our kubeflow upgraded from `0.6` to `1.0.2`. And when looked at the ui we noticed, the version that was displayed was `dev_local`.

Here's the link of the manifest we used to perform the upgrade:
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml

And when digging a bit in the source code, it same that discrepancy might come from [this line](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/webpack.config.js#L22)

**Comment by yassine-labidi** [comment]
Sorry, this should have been submitted on the kubeflow bug tracker.

**Comment by revolutionisme** [comment]
@yassine-labidi Did you manage to get a solution for that? I tried to check the kubeflow issues but I couldn't find any issues there regarding the same.
