### ISSUE TITLE
Encountered error applying application mpi-operator

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/manifests#1166]
Getting this error installing latest master manifest 

> time="2020-05-14T22:16:48Z" level=warning msg="Encountered error applying application mpi-operator:  (kubeflow.error): Code 500 with message: Apply.Run  Error unable to recognize \"/tmp/kout844630924\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1\"" filename="kustomize/kustomize.go:202"

**Comment by apryiomka** [comment]
it seems like [this](https://github.com/kubeflow/manifests/blob/master/mpi-job/mpi-operator/base/crd.yaml#L1) should be `apiVersion: apiextensions.k8s.io/v1beta1`?

**Comment by apryiomka** [comment]
Another formatting error: https://github.com/kubeflow/manifests/blob/master/aws/nvidia-device-plugin/overlays/application/application.yaml#L26

> Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for nvidia-device-plugin Error accumulating resources: accumulating resources from 'overlays/application/application.yaml': YAML file [overlays/application/application.yaml] encounters a format error.
>  error converting YAML to JSON: yaml: line 25: did not find expected '-' indicator

**Comment by terrytangyuan** [comment]
Thanks for reporting this. I just submitted the fixes.
