### ISSUE TITLE
kubeflow istio gateway should be in istio-namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1169]
Right now the kubeflow ISTIO gateway is in namespace kubeflow. Based on the [docs](https://istio.io/docs/reference/config/networking/gateway/) it looks like the gateway should be in the same namespace as the pods running the envoy servers at the edge providing ingress to the cluster.

Having the ISTIO gateway in the kubeflow namespace is currently working with Kubeflow 1.0 and ISTIO 1.1.6. I was told though that this might be due to a bug which got fixed in ISTIO (~1.5.X). 

Either way we probably want to move the ISTIO gateway into the istio namespace. This likely means we will need to update all of our virtual services referencing the gateway to refer to it in the appropriate namespace.

**Comment by Jeffwan** [comment]
Any plan to upgrade istio? 1.1.x is too old and if isito gateway in `kubeflow` doesn't work in higher istio versions, we might want to upgrade istio first. Some other components depends on istio may need corresponding changes.

**Comment by jlewi** [comment]
@Jeffwan I think the answer about which version of ISTIO to install will vary from platfom to platform.

On GCP we are planning on switching to ASM (managed ISTIO)  (kubeflow/manifests#1024) . Right now this will install ISTIO 1.4. Really what it means is on GCP ISTIO versioning will be determined by ASM.  

This will likely lead to version incompatible issues which we will have to surface upstream to the various applications in order to find suitable work arounds to support a suitable range of ISTIO versions.

I think this is most pronounced right now in KFServing since KFServing has very tight coupling between KFServing versions, knative, and ISTIO.

@johnugeorge @yanniszark @animeshsingh

**Comment by yanniszark** [comment]
> Any plan to upgrade istio? 1.1.x is too old and if isito gateway in kubeflow doesn't work in higher istio versions, we might want to upgrade istio first. Some other components depends on istio may need corresponding changes.

@Jeffwan we already have Istio 1.3.1 committed in manifests, thanks to @krishnadurai.
The `kfctl_istio_dex` config already uses it successfully.

> Having the ISTIO gateway in the kubeflow namespace is currently working with Kubeflow 1.0 and ISTIO 1.1.6

It still works for 1.3.1 (and maybe 1.4, haven't tried though).
However, I see indeed that the docs say:

> the Gateway resource must reside in the same namespace as the gateway workload instance.

I wonder if this is a practical issue or a best-practice issue.
Agreed that it would be best to follow the Istio recommendation.
We also need to find out which controllers are affected. I know the `notebook-controller` is.

**Comment by nrchakradhar** [comment]
Thought will add references to the finer documentation and isito issue.
Documentation: Specifically in [Gateway section](https://istio.io/docs/reference/config/networking/gateway/#Gateway)
<img width="602" alt="Gateway" src="https://user-images.githubusercontent.com/38882990/82326624-c093b200-99fa-11ea-9990-a637554d15c1.PNG">
[Istio issue](https://github.com/istio/istio/issues/19970)
[Comment](https://github.com/istio/istio/issues/19970#issuecomment-627739244)

@yanniszark 
In Kubeflow only one gateway is created as much as I have seen. However multiple virtual services are created as and when new notebooks are created. For VirtualServices this restriction does not seem to apply.
https://istio.io/docs/reference/config/networking/virtual-service/#VirtualService
<img width="594" alt="VirtualService" src="https://user-images.githubusercontent.com/38882990/82327210-ac9c8000-99fb-11ea-9568-45af64f0dc8f.PNG">

Please correct me if my understanding is incorrect.

**Comment by jlewi** [comment]
THanks @nrchakradhar  Virtual services can reside in any namespace. We already have virtual services in multiple namespaces. VS  can refer to gateways in other namespaces.

**Comment by shawnzhu** [comment]
IMHO, there're at least 4 places need to change:

1. component `istio/istio`: remove hard coded namespace plus adding a variable named `namespace`:
https://github.com/kubeflow/manifests/blob/299f4669c9e467ad1234f96a6192aca94fc09801/istio/istio/base/kustomization.yaml#L6
2. anywhere that refer to `kubeflow/kubeflow-gatway` no matter virtual-services or ConfigMap, need to use `Istio-system/kubeflow-gateway` instead.
3. in all existing kfdef depends on master branch, will need to add `namespace` variable for kustomize config `istio`
