### ISSUE TITLE
Upgrade cert-manager to 0.15; add probes to deal with readiness failures during deployment

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1234]
It looks like we are currently on cert-manager 0.11. The latest is 0.15. It looks like 0.12 added readiness and liveness probes for the webhook.
https://github.com/jetstack/cert-manager/pull/2245

This might fix issues during deployment. Currently, if we try to create cert-manager resources (e.g. certificates for the kubeflow admission-webhook) then we will get an error like

```
Error from server (InternalError): error when creating ".build/kubeflow-apps/cert-manager.io_v1alpha2_certificate_admission-webhook-cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
```

Adding kubectl wait statements like the following doesn't work

```
kubectl --context=$(KFCTXT) -n cert-manager wait --for=condition=Available --timeout=600s deploy cert-manager-webhook
	kubectl --context=$(KFCTXT) -n cert-manager wait --for=condition=Available --timeout=600s deploy cert-manager
	kubectl --context=$(KFCTXT) -n cert-manager wait --for=condition=Available --timeout=600s deploy cert-manager-cainjecto
```

This is likely because our deployment for the webhook doesn't include readiness and liveness probes.
https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L68

I think if we upgrade to 0.15 then we should be able to add readiness and liveness probes.

@krishnadurai looks like you did the upgrade to 0.11. Do you think it would be worth trying to upgrade to 0.15 for KF 1.1?

**Comment by krishnadurai** [comment]
@jlewi it looks like this will help the situation with cert-manager readiness. We should look to upgrade to 0.15.
Can kfctl leverage waiting for availability to deploy cert-manager resources?

**Comment by jlewi** [comment]
@krishnadurai in principle kfctl can run any arbitrary code.

The approach we are taking with GCP blueprints is much simpler. We just use `kubectl`
https://github.com/kubeflow/gcp-blueprints/blob/5734f2693f89ea45fa0c404bd3330caf70e4cba8/kubeflow/Makefile#L203

So we can call `kubectl wait`. I'm hoping that if the deployment includes readiness probes then `kubectl wait` will wait until its actually ready to serve.

**Comment by PatrickXYS** [comment]
Can we make the change to upgrade cert-manager from `0.11.0` to `0.15.0`? I can help sending a PR for this.

@krishnadurai  @jlewi  @Jeffwan  Any concerns you can share given the update?

**Comment by krishnadurai** [comment]
@PatrickXYS yes you can send in the PR.

**Comment by jlewi** [comment]
@PatrickXYS looks like this hasn't been fixed yet; do we want to try to fix for KF 1.2?

**Comment by PatrickXYS** [comment]
@jlewi I would target a patch version to fix this, maybe 1.2.1

**Comment by DavidSpek** [comment]
@yanniszark It looks like upgrading cert-manager is a long running issue. Given that the 0.11 version of cert-manager is probably not validated on the versions most people are running, and the apparent incompatibility with OpenShift, it might be a good idea to update the manifests for cert-manager. [Here](https://github.com/kubeflow/manifests/pull/1820) is a PR for doing this, I've used this to deploy all Kubeflow 1.3 components on multiple clusters and haven't seen any compatibility issues.

**Comment by yanniszark** [comment]
@DavidSpek thank you for the PR, upgrading cert-manager is something we definitely want to do after the 1.3 stable release.
At this point, we are at a feature-freeze, so no new features go in, only fixes. In Openshift's case, the issue was that a kustomization was applied to the wrong namespace and everything worked after fixing that mistake: https://github.com/kubeflow/manifests/issues/1810

Thanks again for doing the effort of making a PR. Would it be possible to create an issue to track this effort? I can open as well if you want.

**Comment by gecube** [comment]
I'd like to see the new cert-manager too. As I reported in #1838 I managed to got kube-flow with cert-manager 1.3.0 installation.

**Comment by thesuperzapper** [comment]
Lets close this, and move discussion to https://github.com/kubeflow/manifests/issues/1838

/close
