### ISSUE TITLE
Manifests release 1.1

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#1252]
Opening this issue to track releasing manifests as part of 1.1.

- Ref: kubeflow/kubeflow#5022
- We will need to
    - [x] Cut a release branch
    - [ ] Generate Manifests for each kfdef

/assign @krishnadurai

**Comment by jlewi** [comment]
Looks like the postsubmit tests are failing. Looks like the TFJob operator tests are out of sync.

[kubeflow-manifests-postsubmit-unit-d6a25c6-5684-13a5-1216454708.log.txt](https://github.com/kubeflow/manifests/files/4813760/kubeflow-manifests-postsubmit-unit-d6a25c6-5684-13a5-1216454708.log.txt)

**Comment by jlewi** [comment]
@krishnadurai Can you fix the tests and then once the tests are fixed cut the branch?

**Comment by jlewi** [comment]
@krishnadurai looks like the tests are still failing

```
===== ACTUAL END ==========================================
  EXPECTED                                                                ACTUAL
  --------                                                                ------
  apiVersion: admissionregistration.k8s.io/v1beta1                        apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration                                      kind: MutatingWebhookConfiguration
  metadata:                                                               metadata:
    annotations:                                                            annotations:
      cert-manager.io/inject-ca-from: kubeflow/admission-webhook-cert         cert-manager.io/inject-ca-from: kubeflow/admission-webhook-cert
    labels:                                                                 labels:
      app: admission-webhook                                                  app: admission-webhook
      app.kubernetes.io/component: poddefaults                                app.kubernetes.io/component: poddefaults
      app.kubernetes.io/name: poddefaults                                     app.kubernetes.io/name: poddefaults
      kustomize.component: admission-webhook                                  kustomize.component: admission-webhook
    name: admission-webhook-mutating-webhook-configuration                  name: admission-webhook-mutating-webhook-configuration
  webhooks:                                                               webhooks:
  - clientConfig:                                                         - clientConfig:
      caBundle: ""                                                            caBundle: ""
      service:                                                                service:
        name: admission-webhook-service                                         name: admission-webhook-service
        namespace: kubeflow                                                     namespace: kubeflow
        path: /apply-poddefault                                                 path: /apply-poddefault
    name: admission-webhook-deployment.kubeflow.org                         name: admission-webhook-deployment.kubeflow.org
X    rules:                                                                  namespaceSelector:
X    - apiGroups:                                                              matchLabels:
X      - ""                                                                      app.kubernetes.io/part-of: kubeflow-profile
X      apiVersions:                                                          rules:
X      - v1                                                                  - apiGroups:
X      operations:                                                             - ""
X      - CREATE                                                                apiVersions:
X      resources:                                                              - v1
X      - pods                                                                  operations:
X                                                                              - CREATE
X                                                                              resources:
X                                                                              - pods
   TestKustomize: test_util.go:176: Expected not equal to actual
--- FAIL: TestKustomize (5.45s)
```

Even after #1297; My conjecture is that when you generated the tests you weren't based off of the latest master and as a result you are missing #1284

**Comment by jlewi** [comment]
Tests are passing on
https://github.com/kubeflow/manifests/commit/d77107276aaf476aa07d4c9be4ddea8c0fb672c6

We should cut the 1.1 branch on that commit.

**Comment by jlewi** [comment]
Branch 1.1. has been cut.

**Comment by jlewi** [comment]
@krishnadurai Is there any more work here? Are we just waiting to tag a particular commit as 1.1.0?

**Comment by krishnadurai** [comment]
@Jeffwan had mentioned that he wants to patch in a few changes. Otherwise we look good to go for 1.1.0.

**Comment by jlewi** [comment]
Created a Tag from the latest commit
https://github.com/kubeflow/manifests/releases/tag/v1.1-rc.0

**Comment by jlewi** [comment]
@Bobgy What cherry-picks do we want to get onto the 1.1 branch for the next GCP rc?

* We need #1385 for knative
* What PRs do we need for multi-user pipelines

**Comment by Bobgy** [comment]
@jlewi all required cherry picks for multi-user pipelines are already in. Just double checking we are not publishing the public release right now? I found some issues in https://github.com/kubeflow/pipelines/issues/3241#issuecomment-657963091, and need some time to investigate.

**Comment by jlewi** [comment]
@Bobgy We need to get the fixes for the KptFiles in kubeflow/gcp-blueprints#89

**Comment by jlewi** [comment]
On GCP side we got broken by changes in kpt (kubeflow/gcp-blueprints#89). This is now fixed on master. 
Master is now green except for 2 tests which appear to be failing due to problems in the tests
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-gcp-blueprints-periodic-master

Plan is to get the fixes for kubeflow/gcp-blueprints#89 cherry-picked into the 1.1 branch and then cut an RC.

**Comment by jlewi** [comment]
New RC is cut:
https://github.com/kubeflow/manifests/tree/v1.1-rc.1

**Comment by jlewi** [comment]
New RC
https://github.com/kubeflow/manifests/releases/tag/v1.1-rc.2

This one is an actual release (tag) and not a branch. This is what we want

**Comment by jlewi** [comment]
v1.1.0 has been finalized.
https://github.com/kubeflow/manifests/releases/tag/v1.1.0

Note I had to create a tag and not a release because subsequent changes had been cherry-picked onto the branch and GitHub only allows creating a release from the of a branch.
