### ISSUE TITLE
Makefile generate swallows errors

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1269]
https://github.com/kubeflow/manifests/blob/6bc84d9d8661ec6dc74f3e5ac6388a321dc1d2b8/tests/Makefile#L38

As discovered here:
https://github.com/kubeflow/testing/issues/631#issuecomment-645648231

`make generate` doesn't return an error if there is a problem running the python script to generate the tests.

I think the problem is the line

```
	$(PYTHON_BIN) ../hack/generate_tests.py --all || echo done
```

I think `||` is the logical or operator; so if the LHS returns an error we end up executing the RHS which returns success.

We should probably change this to 

```
	$(PYTHON_BIN) ../hack/generate_tests.py --all
```

If we want Make to continue on error I think we can just preface the line with "-"

**Comment by pingsutw** [comment]
It could be closed. 
Resolved in https://github.com/kubeflow/manifests/commit/92c774b5f0c4b078e8c718870ba983dae0ca3e83
