### ISSUE TITLE
fix names for Application and VirtualService in jupyter-web-app/base_v3 and notebook-controller/base_v3 

### ISSUE THREAD

**Issue by adrian555** [kubeflow/manifests#1285]
As mentioned in the [comment](https://github.com/kubeflow/manifests/pull/1246#issuecomment-645103438), open this issue to track.

Basically the current `base_v3` for jupyter-web-app and notebook-controller applications are using `namePrefix` in kustomization.yaml. Hence the name for Application and VirtualService ends up as `jupyter-web-app-jupyter-web-app`. Would like to remove the namePrefix for these resources, but also make sure that the change should not break any current use of `base_v3`.

**Comment by yanniszark** [comment]
Closing as there is no base_v3 any longer.
