### ISSUE TITLE
Unable to deploy kubeflow with istio manifest

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/manifests#1290]
I tried to deploy Kubeflow using this manifest: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml.

I ran:
1. `kfctl build -V -f https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml`
2. `kfctl apply -V -f kfctl_k8s_istio.yaml`

I got this error:

```
ERRO[0013] error evaluating kustomization manifest for metadata Error env source files: [secrets.env]: evalsymlink failure on '/<path-to-kubeflow>/kustomize/metadata/secrets.env' : 
lstat /<path-to-kubeflow>/kustomize/metadata/secrets.env: no such file or directory  filename="kustomize/kustomize.go:175"

Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for metadata Error env source files: [secrets.env]: evalsymlink failure on '/<path-to-kubeflow>/kustomize/metadata/secrets.env' : lstat /<path-to-kubeflow>//kustomize/metadata/secrets.env: no such file or directory
```

I believe the path to the secret.env is incorrect.

I checked kfctl generated kustomize for metadata and saw this:
```yaml
secretGenerator:
- behavior: unspecified
  envs:
  - secrets.env
  name: metadata-db-secrets
```

I also generated manifests for v1.0-branch using this config: https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml.

On generated kustomize I saw this:

```yaml
secretGenerator:
- behavior: unspecified
  env: overlays/db/secrets.env
  name: metadata-db-secrets
```

Seems that path for secrets are generated not correct.

/kind bug
/assign @jlewi @thesuperzapper @zhenghuiwang

**Comment by andreyvelich** [comment]
Found this: https://github.com/kubeflow/kfctl/pull/356.
New version of kfctl should fix this problem, right @adrian555 ?

**Comment by adrian555** [comment]
@andreyvelich yes, it should be fixed by https://github.com/kubeflow/kfctl/pull/356.

**Comment by andreyvelich** [comment]
Thanks @adrian555, after using the latest changes from kfctl master I was able to use master istio config.
I think it would be good to point somewhere that 1.1 Kubeflow release works only with 1.1 kfctl release.

**Comment by supertetelman** [comment]
It looks like this issue randomly showed up in v1.0.2. I've been using the same script to install Kubeflow and it stopped working due to this error around the 24th. I ran into this issue running v1.0.2.


kfctl: https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_linux.tar.gz
manifest: ttps://raw.githubusercontent.com/kubeflow/manifests/928cf483361730121ac18bc4d0e7a9c129f15ee2/kfdef/kfctl_k8s_istio.yaml

**Comment by adrian555** [comment]
> it stopped working due to this error around the 24th

@supertetelman by saying `error`, are you referring to the same error reported here?
```
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for metadata Error env source files: [secrets.env]: evalsymlink failure on '/<path-to-kubeflow>/kustomize/metadata/secrets.env' : lstat /<path-to-kubeflow>//kustomize/metadata/secrets.env: no such file or directory
```

If not, could we please have a new issue to track and please provide the detailed error messages. Thanks.

**Comment by supertetelman** [comment]
Yes, that same error message with the same root cause.

I just wanted to update this issue in case someone else hit this trying to deploy the v1.0.2 release on-prem.

**Comment by Utkagr** [comment]
```
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for metadata Error env source files: [params.env]: evalsymlink failure on '<path-to-kubeflow>/kustomize/metadata/params.env' : lstat <path-to-kubeflow>/kustomize/metadata/params.env: no such file or directory
```
I'm facing the same error.

**Comment by thesuperzapper** [comment]
@jlewi do we need to do a v1.0.3 release?

**Comment by jlewi** [comment]
@thesuperzapper If you think a 1.0.3 is needed please open an issue and try to find an owner.

**Comment by jlewi** [comment]
IIUC the problem is with
https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml.

And not necessarily all of KF 1.0

/cc @krishnadurai @johnugeorge

**Comment by fahdrazavi** [comment]
> Thanks @adrian555, after using the latest changes from kfctl master I was able to use master istio config.
> I think it would be good to point somewhere that 1.1 Kubeflow release works only with 1.1 kfctl release.

Can you please share the kfctl version and manifest yaml you used for the deployment?

**Comment by andreyvelich** [comment]
@fahdrazavi I was using this manifest: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml and this release version for kfctl: https://github.com/kubeflow/kfctl/releases/tag/v1.1-rc.0 should work.

**Comment by supertetelman** [comment]
Strange, I'm still seeing

```
ERRO[0053] Error evaluating kustomization manifest for metadata: env source files: [secrets.env]: open /kubeflow-install/kustomize/metadata/secrets.env: no such file or directory  filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for metadata: env source files: [secrets.env]: open /kubeflow-install/kustomize/metadata/secrets.env: no such file or directory
```

With

```
# Download URLs and versions
export KFCTL_URL="https://github.com/kubeflow/kfctl/releases/download/v1.1-rc.0/kfctl_v1.1-rc.0-0-g31fdc70_linux.tar.gz"

CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/928cf483361730121ac18bc4d0e7a9c129f15ee2/kfdef/kfctl_k8s_istio.yaml" # Corresponds to current master .yaml file as of 7/21/2020
```

Any idea why I would still be seeing this error on a freshly installed K8S cluster? Or any tips on an easy workaround?

**Comment by adrian555** [comment]
@supertetelman could you run `kfctl version` and verify you are using the latest kfctl? Thanks.

**Comment by Utkagr** [comment]
The issue occurs with latest kfctl stable release https://github.com/kubeflow/kfctl/releases/tag/v1.0.2 and https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml as well.

**Comment by adrian555** [comment]
@Utkagr please take a look at https://github.com/kubeflow/kfctl/pull/356. If you are using the master branch's kfdef such as `kfctl_k8s_istio.yaml`, you need to use the `kfctl` built from the master branch, not the v1.0.2. Thanks.

**Comment by Utkagr** [comment]
@adrian555 how can we install kfctl from the master branch? Can you help me with it?

**Comment by adrian555** [comment]
@Utkagr to build from the master branch, you will need to clone the kfctl repo, set up dev environment and build, that will be some effort. 

Now since there is a recent rc release is cut in kfctl repo https://github.com/kubeflow/kfctl/releases/tag/v1.1-rc.1, you can get the binary from that link and I think it includes the fix for the problem and should work with the manifests in the manifests repo's master branch.

**Comment by Utkagr** [comment]
@adrian555 I'm using latest kfctl release now https://github.com/kubeflow/kfctl/releases/tag/v1.1.0 with https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml.
But it can't seem to work either. After a lot of tries, it fails with this error, 
```
Resource: "cert-manager.io/v1alpha2, Resource=clusterissuers", GroupVersionKind: "cert-manager.io/v1alpha2, Kind=ClusterIssuer"
Name: "kubeflow-self-signing-issuer", Namespace: ""
Object: &{map["apiVersion":"cert-manager.io/v1alpha2" "kind":"ClusterIssuer" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cert-manager.io/v1alpha2\",\"kind\":\"ClusterIssuer\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/component\":\"cert-manager\",\"app.kubernetes.io/instance\":\"cert-manager-v1.0.0\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"cert-manager\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"v1.0.0\",\"kustomize.component\":\"cert-manager\"},\"name\":\"kubeflow-self-signing-issuer\"},\"spec\":{\"selfSigned\":{}}}\n"] "creationTimestamp":"2020-07-21T10:42:57Z" "generation":'\x01' "labels":map["app.kubernetes.io/component":"cert-manager" "app.kubernetes.io/instance":"cert-manager-v1.0.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"cert-manager" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"v1.0.0" "kustomize.component":"cert-manager"] "name":"kubeflow-self-signing-issuer" "resourceVersion":"73771091" "selfLink":"/apis/cert-manager.io/v1alpha2/clusterissuers/kubeflow-self-signing-issuer" "uid":"f0886f4b-cb3e-11ea-aa99-d017c212d537"] "spec":map["selfSigned":map[]] "status":map["conditions":[map["lastTransitionTime":"2020-07-21T10:42:57Z" "reason":"IsReady" "status":"True" "type":"Ready"]]]]}
for: "/tmp/kout025472600": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request]
```

**Comment by Utkagr** [comment]
I tried using the latest manifest from v1.1 branch but couldn't get any luck either. https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml
```
failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for application Error accumulating resources: accumulating resources from '../application-crds/base': evalsymlink failure on '/<home-directory>/kubeflow/kustomize/application-crds/base' : lstat /<home-directory>/kubeflow/kustomize/application-crds: no such file or directory
```

**Comment by adrian555** [comment]
@Utkagr In general, during the Kubeflow deployment,  it is expected to see such message several times

```WARN[0278] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout510042550": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:283"```

and it is explained here https://github.com/kubeflow/kfctl/blob/master/pkg/kfapp/kustomize/kustomize.go#L256.

So you can ignore that and let the `kfctl` command continue for several tries. If at the end, `kfctl` still fails, you should look at your `cert-manager` namespace, check what could be the reason that the webhook failed to start there. You can check `cert-manager-webhook` deployment in `cert-manager` namespace and see for clues.

As for your second question on `application-crds` directory not found, I suspect it is because you did not remove the `kustomize` and `.cache` directories when you applied that yaml. But I am not sure. If you continue to have such problem, please open an issue that someone is responsible for the manifest will respond. Thanks.

Also it does not make sense to me keeping discussions of these unrelated problems in this already closed issue. Could you please open a different issue so that other contributors may see and help? Thanks.

**Comment by Utkagr** [comment]
@adrian555 Sure, thanks.
