### ISSUE TITLE
Bug in AWS manifest should be networking.k8s.io/v1beta1 not v1?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1291]
https://github.com/kubeflow/manifests/blob/92c774b5f0c4b078e8c718870ba983dae0ca3e83/aws/istio-ingress/base/ingress.yaml#L1

Was recently changed in #1245 

I think it should be v1beta1

/assign @Jeffwan

**Comment by Jeffwan** [comment]
Yeah. I think I carelessly brings this problem. Just double check it and It should be `v1beta1`

**Comment by Jeffwan** [comment]
Thanks for @jlewi to brings this up. We have not integrated master branch yet.
