### ISSUE TITLE
ml-metadata image no longer exists, breaking all new installations

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1321]
/kind bug

**What steps did you take and what happened:**

Install Kubeflow from any v1.x release.
The metadata deployment uses an image (` gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1`) that is no longer available.
Because of this, the metadata component will fail in all existing installations.
In platforms like MiniKF where every component is health checked before continuing, the whole process fails.

**What did you expect to happen:**
Kubeflow components all come up healthy and ready.

**Anything else you would like to add:**
We should try to prevent things like that from happening. Maybe by mirroring all images to a repo we control (`kubeflow-public-images`)?

/priority p0
/cc @jlewi @zhenghuiwang

**Comment by yanniszark** [comment]
Raised the issue with the `ml-metadata` folk, @numerology was very helpful and restored the image so our deployments aren't broken anymore.
Also, it seems that ml-metadata doesn't use `v` in front of the tag anymore.
So the new image is `0.21.1` vs `v0.21.1`.

**Comment by Ark-kun** [comment]
> Also, it seems that ml-metadata doesn't use `v` in front of the tag anymore.
> So the new image is `0.21.1` vs `v0.21.1`.

They just did the opposite thing. `0.22.1` was recently removed in favor of `v0.22.1` breaking the KFP tests

**Comment by numerology** [comment]
> > Also, it seems that ml-metadata doesn't use `v` in front of the tag anymore.
> > So the new image is `0.21.1` vs `v0.21.1`.
> 
> They just did the opposite thing. `0.22.1` was recently removed in favor of `v0.22.1` breaking the KFP tests

Yeah...It seems like it was incorrectly purged. Should be recovered now.
