### ISSUE TITLE
Increase istio replicas to 2+ for better availability and because of PodDisruptionBudgets

### ISSUE THREAD

**Issue by linkvt** [kubeflow/manifests#1343]
/kind bug

**Edit** wups wanted to create this in the manifests repo, please tell me if I should recreate the issue.

**What steps did you take and what happened:**
The PodDisruptionBudgets for istio currently require always 1 pod available while the affected istio deployments have only 1 replica. Draining individual nodes is impossible as the PodDisruptionBudgets would be violated.

**What did you expect to happen:**
**Edit:** After reading a bit more also in https://github.com/istio/installer/pull/212 it seems to be not really clear if 2 replicas can be handled by every component that has no HPA (e.g. galley)
**Edit2:** This seems to be resolved in more recent istio versions: https://github.com/istio/istio/issues/18565
There should be either 2+ replicas of the Istio pods that have PodDisruptionBudgets set so that individual nodes can be drained in rolling node upgrades - also of course for a higher availability of Istio or no PDBs at all.
See also https://github.com/istio/istio/issues/12602#issuecomment-489449657

**Anything else you would like to add:**
These are the deployments (ignore prometheus and citadel):
```
 k get deploy
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
cluster-local-gateway    1/1     1            1           8d
istio-citadel            1/1     1            1           8d
istio-galley             1/1     1            1           8d
istio-ingressgateway     1/1     1            1           8d
istio-pilot              1/1     1            1           8d
istio-policy             1/1     1            1           8d
istio-sidecar-injector   1/1     1            1           8d
istio-telemetry          1/1     1            1           8d
prometheus               1/1     1            1           8d
```
and the PodDisruptionBudgets:
```
$ k get poddisruptionbudgets.policy 
NAME                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
cluster-local-gateway    1               N/A               0                     8d
istio-galley             1               N/A               0                     8d
istio-ingressgateway     1               N/A               0                     8d
istio-pilot              1               N/A               0                     8d
istio-policy             1               N/A               0                     8d
istio-sidecar-injector   1               N/A               0                     8d
istio-telemetry          1               N/A               0                     8d
```

**Environment:**

- Kubeflow version: `build version dev_local` but we use the 1.0.2 manifests
- kfctl version: 1.0.2
- Kubernetes platform: vanilla with kubespray 
- Kubernetes version: (use `kubectl version`): 1.14 eager to upgrade after our migration from kubeflow 0.5 :D
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by linkvt** [comment]
Seems like this is still an issue, see e.g. https://github.com/kubeflow/manifests/blob/c728bc737cfadc2816ecd50c5c96ee59cd1d9b1a/istio/istio-install/base/istio-noauth.yaml#L14289

**Comment by yanniszark** [comment]
Closing as individual platforms/admins will be able to use kustomize in order to change Istio settings to fit their needs OR install their own Istio.
