### ISSUE TITLE
Can't find a working manifest with kfctl v1.0.2 while trying to setup kubeflow on linux machine using minikube and kfctl

### ISSUE THREAD

**Issue by Utkagr** [kubeflow/manifests#1348]
When I'm using the latest istio manifest from master ([link](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml)), I'm getting the error discussed [here](https://github.com/kubeflow/manifests/issues/1290).
According to the conversation there, this PR https://github.com/kubeflow/kfctl/pull/356 seems to resolve this but the kfctl team hasn't released a version with the latest changes. So, looks like there's no way of installing kfctl with latest changes in master.
I'm wondering If there is any way I can get kubeflow installed neatly. Any help along these lines would be appreciated.

I'm following this one for the setup. https://www.kubeflow.org/docs/started/workstation/minikube-linux/

**Comment by supertetelman** [comment]
You can try using the istio_dex manifest instead of the istio manifest. That is working fine for me.

**Comment by Utkagr** [comment]
I tried with [this](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.yaml) manifest and kfctl v1.0.2-0-ga476281. It failed again. Can you please post your kfctl version and manifest link which worked for you?

**Comment by Utkagr** [comment]
However, [this](https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.v1.0.2.yaml) one worked just fine. Thanks!

**Comment by Utkagr** [comment]
Hi @supertetelman, 

This seemed to work but some of pods in the istio-system namespace are waiting for too long to be created.

I checked logs and found this.
```
Error from server (BadRequest): container "istio-proxy" in pod "istio-ingressgateway-77f74c944c-b5bkd" is waiting to start: ContainerCreating
```

Any idea on what's happening? It has been more than an hour.

**Comment by supertetelman** [comment]
What's the describe from that Pod?

**Comment by jbottum** [comment]
Hi @Utkagr did you get this resolved ?   Have you looked at MiniKF ? it has a team supporting it.   https://www.arrikto.com/s/6c15b060-62f8-4c9b-9364-8e2a6b4ade53/?submissionGuid=fd86e035-2011-4de4-a090-ad2c76c0cf74

**Comment by Utkagr** [comment]
@jbottum I deleted my Minikube setup and I'm continuing with an on-prem setup now. Hence, will close the issue for now.
