### ISSUE TITLE
Run kfctl E2E tests on kubeflow/manifests presubmits

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#135]
Right now we don't run the kfctl E2E tests on presubmits to kubeflow/manifests.

As a result, we can end up submitting changes that break kubeflow deployments.
See for example: kubeflow/kubeflow#3475

To address this we should run the kfctl E2E tests as pre/post submit tests on kubeflow/manifests

@swiftdiaries Any chance you could take  look at this? I think this is high priority to help stabilize the release.

**Comment by swiftdiaries** [comment]
I'll take a look at this.
/assign @swiftdiaries

**Comment by jlewi** [comment]
@swiftdiaries any update on this? What's blocking #139?

**Comment by swiftdiaries** [comment]
I'm getting a kubeconfig not found error. I'm not sure where it originates from

**Comment by jlewi** [comment]
@swiftdiaries It looks like #139 has been merged. Can we close this? Are the tests running as expected on presubmit?

**Comment by jlewi** [comment]
@swiftdiaries ping?

**Comment by swiftdiaries** [comment]
/close 
Closing as pre-submits are running as expected.
