### ISSUE TITLE
Refactor katib packages into katib/v1alpha1 and katib/v1alpha2

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#136]
#131 created two top level directories for different versions of the Katib package
katib-v1alpha1
katib-v1alpha2

The alternative proposal was to create subdirectories
katib/
       /v1alpha1
       /v1alpha2

I think the reason we went with toplevel packages was because the way [KfDef](https://github.com/kubeflow/kubeflow/blob/5f1762a5a973d3441f010096357ba882f2c9386e/bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go#L126) and kfctl currently works it makes an assumption about the kustomize package being at depth 2.
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/v2/pkg/kfapp/kustomize/kustomize.go#L546

We should consider refactoring the katib packages if/when KfDef gets fixed

**Comment by jlewi** [comment]
See kubeflow/kubeflow#3478

**Comment by johnugeorge** [comment]
currently, only one version is added in manifests.
