### ISSUE TITLE
[AWS] Upgrade auth adapter to istio 1.3.x compatible

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1362]
AWS cognito solution use mixer adapter to decode JWT token and retrieve userid_header. 

In istio 1.2.x , this has been removed and we need to explicitly enable following options in `istio-pilot`.

```
Removed Previously deprecated Adapter and Template CRDs are disabled by default. 
Use mixer.templates.useTemplateCRDs=true and mixer.adapters.useAdapterCRDs=true install options to re-enable them.
```

We need to either make the configuration change in istio or change auth adapter to 1.3.x compatible way. 

Reference:
https://istio.io/latest/news/releases/1.2.x/announcing-1.2/change-notes/

**Comment by Jeffwan** [comment]
This is for Kubeflow 1.2.

**Comment by Jeffwan** [comment]
Remove from 1.2 kanban. @PatrickXYS  will determinate the support plan

**Comment by PatrickXYS** [comment]
After a few investigations, we should patch `istio-telemetry` to add two parameters for `mixer`

**Comment by PatrickXYS** [comment]
Close this in favor of https://github.com/kubeflow/manifests/issues/1695
