### ISSUE TITLE
jupyter-web-app: VirtualService and Service mismatch

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#137]
The service in front of the Jupyter Web App deployment is called `jupyter-web-app-service`.
https://github.com/kubeflow/manifests/blob/fea53c8c0e7ea84a31b6935129fb643d53090b13/jupyter/jupyter-web-app/base/service.yaml#L16
https://github.com/kubeflow/manifests/blob/fea53c8c0e7ea84a31b6935129fb643d53090b13/jupyter/jupyter-web-app/base/kustomization.yaml#L12

The Istio VirtualService for the Jupyter Web App is for a Service called `jupyter-web-app`.
https://github.com/kubeflow/manifests/blob/fea53c8c0e7ea84a31b6935129fb643d53090b13/jupyter/jupyter-web-app/overlays/istio/virtual-service.yaml#L22
This causes the notebooks page to be inaccessible.

**Comment by jlewi** [comment]
@prodonjs @avdaredevil  Can we open up a separate issue to add E2E tests that verify the apps are accessible on the appropriate URLs?

**Comment by prodonjs** [comment]
Yes, we currently have https://github.com/kubeflow/kubeflow/issues/3398 in progress which should be revamped to ensure that all top-level UIs are accessible and render appropriate content when brought up within a new deployment in an E2E test. I'm hoping to spend some time on this this week.

**Comment by yanniszark** [comment]
@jlewi @prodonjs thanks for the quick answers.
I have submitted a fix for this in #138

**Comment by yanniszark** [comment]
@kunmingg does your PR (https://github.com/kubeflow/manifests/pull/155) close this?
If yes, please also close the PR I had submitted (#138)

**Comment by yanniszark** [comment]
Fixed by #155
