### ISSUE TITLE
What to do about dynamic creation of admission hooks and other resources?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1379]
Misconfigured or misbehaving webhooks are an ongoing source of problems see:

* kubeflow/kubeflow#4808
* kubeflow/kfserving#568
* kubeflow/katib#1261

In kubeflow/manifests#1213 we started adding testing to verify that webhooks are well behaved.

However, this only works if an application configures webhooks explicitly as part of its kustomize package.

We have at least two applications (katib, and kfserving) in which the webhooks are dynamically and automatically created. This has a couple disadvantages

1. Operator doesn't know beforehand what resources will be created
1. Operator has no way to customize the webhooks if needed
1. Controllers need sufficient RBAC permissions to create webhooks

Should we recommend or require that all applications support at least optionally explicit creation of their webhooks and provide YAML resources to do so?

Should we enforce that by adding tests similar to kubeflow/manifests#1213 to disallow RBAC permissions to create webhooks?

/cc @andreyvelich @johnugeorge @ellistarn @yuzisun @cliveseldon @animeshsingh

**Comment by yuzisun** [comment]
@jlewi As of KFServing 0.3 which is in kubeflow 1.1 release branch now the webhook is no longer auto-generated, see [here](https://github.com/kubeflow/manifests/blob/master/kfserving/kfserving-install/base/webhook.yaml).

**Comment by andreyvelich** [comment]
@jlewi I think we can add Katib YAML webhooks as part of Kustomize package. That can also help when we clean-up resources after Kubeflow deletion. 
What do you think @gaocegege @johnugeorge ?

**Comment by ellistarn** [comment]
For a little bit of insight on this, Kubebuilder 1.0 used dynamic webhooks, so any controller built on that version will have this (Katib, etc). Kubebuilder 2.0 uses static webhooks.

**Comment by jlewi** [comment]
Thanks @ellistarn for the explanation. So it looks like we should probably figure out which controllers if any besides katib are still using dynamic webhooks and get them updated.

**Comment by andreyvelich** [comment]
Katib doesn't use dynamic webhook creation, we can close this.
/close
