### ISSUE TITLE
Katib don't enable metrics collector in kubeflow namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1380]
Related to: kubeflow/katib#1261

We currently have it enabled here
https://github.com/kubeflow/manifests/blob/5cc6fd3ca0eac7c46aad116c04713d6944f249fd/namespaces/base/namespaces.yaml#L8

Should we remove it so that the metrics collector webhook can't interfere with pods in the kubeflow namespace?

**Comment by andreyvelich** [comment]
@jlewi Does every config to deploy Kubeflow relate on this manifest?
Should we modify kfctl or other tools that deploys Kubeflow?

**Comment by jlewi** [comment]
@andreyvelich I think only GCP blueprints is using that config. I think kfctl might still be hardcoding namespace creation. I think kfctl should move in the direction of using config files so its easier for users to customize but that's a question for the kfctl folks.

**Comment by andreyvelich** [comment]
Ok, will remove it.
/assign @andreyvelich

**Comment by jlewi** [comment]
Fixed by #1387 and #1388
