### ISSUE TITLE
Using local manifests tarball

### ISSUE THREAD

**Issue by williamyeh** [kubeflow/manifests#1382]
Hi,

I'm working on deploying kubeflow in an air-gapped k8s environment.
Got this yaml file from the kubeflow getting started page.
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Any idea if I could change the second to last line of the yaml file pointing to the path of the yaml file I downloaded locally in my environment?
I have tried path or PATH, but both failed.
Anyone know what keyword I could use?

  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz
  version: v1.0.2

Thanks,
William

**Comment by jazzsir** [comment]
@williamyeh That's what you should do

name: manifests
uri: file:/PATH/v1.0.2.tar.gz
version: v1.0.2
