### ISSUE TITLE
cache server failing for KFP multi-user installation

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/manifests#1390]
**Description**
We are trying the Kubeflow with the KFP multi-user installation using Kustomize on a internal deployment stack. All services are working as expected, we are able to login, launch namespaced experiments via the SDK, and deploy with kfserving. We found an issue with the cache server not deploying correctly. 

```
cache-deployer-deployment-66bc686785-65t6x               2/2     Running    1          26h
cache-server-6746f557c7-7hkv2                            0/2     Init:0/1   0          26h
```

```
Events:
  Type     Reason       Age                    From                                      Message
  ----     ------       ----                   ----                                      -------
...
  Warning  FailedMount  3m33s (x780 over 26h)  kubelet, aks-default-15061138-vmss000000  MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
```

These are the logs from the cache deployer: 
```
+ echo 'Start deploying cache service to existing cluster:'
Start deploying cache service to existing cluster:
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflow
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ kubectl get mutatingwebhookconfigurations cache-webhook-kubeflow --namespace kubeflow --ignore-not-found
+ kubectl get secrets webhook-server-tls --namespace kubeflow --ignore-not-found
+ webhook_config_exists=false
+ grep cache-webhook-kubeflow -w
cache-webhook-kubeflow   2020-07-13T13:14:12Z
+ webhook_config_exists=true
+ webhook_secret_exists=false
+ grep webhook-server-tls -w
Webhook config and secret are already installed. Sleeping forever.
+ '[' true '==' true ]
+ '[' true '==' true ]
+ echo 'Webhook config and secret are already installed. Sleeping forever.'
+ sleep infinity
```

**Expected Results**
Cache server deploys without issues. 

**Actual Results**
Cache server fails to deploy due to missing secret.

**Installation Details**
The installation follows the new Kustomize pattern, we created a stack that installs Istio 1.6 + Dex, and it also installs Kubeflow pipelines with multi-user enabled. This installation is deployed to an Azure AKS cluster.

**Comment by maganaluis** [comment]
@Bobgy FYI I created it on the manifests repo.

**Comment by Bobgy** [comment]
Thanks @maganaluis!
https://github.com/kubeflow/pipelines/pull/4186 and https://github.com/kubeflow/pipelines/pull/4171 has been merged to fix this. They were released as 1.0.0-rc.5.

We'll mark this resolved when updating kubeflow manifest to KFP 1.0.0.

**Comment by HassanOuda** [comment]
Hey @Bobgy, I'm still getting this issue, the secret is missing. I'm using v1.1 branch in manifests.

**Comment by adrshm91** [comment]
Same problem here

`MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found`

**Comment by arshashi** [comment]
same problem here too.  MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
--

Warning | FailedMount | MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found | a minute ago
-- | -- | -- | --
Warning | FailedMount | Unable to mount volumes for pod "cache-server-65596854d-9r77s_kubeflow(645871c2-acb6-4a72-a0ee-e1c276a639e3)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-65596854d-9r77s". list of unmounted volumes=[webhook-tls-certs]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-55pr6 istio-envoy sds-uds-path istio-token] | 6 minutes ago
Warning | FailedMount | Unable to mount volumes for pod "cache-server-65596854d-9r77s_kubeflow(645871c2-acb6-4a72-a0ee-e1c276a639e3)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-65596854d-9r77s". list of unmounted volumes=[webhook-tls-certs istio-token]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-55pr6 istio-envoy sds-uds-path istio-token] | an hour ago


Environment:

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.1.0 tried with both with DEX and without

kfctl version: (use kfctl version): kfctl v1.1.0-0-g9a3621e

Kubernetes platform: (e.g. minikube)

Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

OS (e.g. from /etc/os-release): CentOS 7.8

**Comment by khangtrantri** [comment]
I have same issue too:

**Environment**
Kebernetes version: 1.15
Kubernetes platform: Rancher
Host OS: Ubuntu 18.04

**Deployment**
kfctl version: `kfctl v1.1.0-0-g9a3621e`
Kubeflow manifest: `kfctl_istio_dex.v1.1.0.yaml`
Kubwflow branch: 1.1

**Logs**
`  Warning  FailedMount  10m (x247 over 9h)   kubelet, kubeflow-worker-1  Unable to mount volumes for pod "cache-server-65596854d-8qg8k_kubeflow(5675edbb-a50c-420b-8beb-65cf3cd0c8f5)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-65596854d-8qg8k". list of unmounted volumes=[webhook-tls-certs]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-655rv istio-envoy sds-uds-path istio-token]
  Warning  FailedMount  5m7s (x286 over 9h)  kubelet, kubeflow-worker-1  MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found`

**Comment by arshashi** [comment]
Can someone update on the issue please.  This seems to be an issue/bug with cert-manager v0.15.

To fix one issue, Upgraded cert-manager which by default comes with kfv1.1 from -0.11 to 0.15 and with v0.15 also this hasn't fixed.

**Comment by arshashi** [comment]
@Ark-kun can you please spare sometime on this issue?

**Comment by HassanOuda** [comment]
@Ark-kun @Bobgy no updates on this?

**Comment by HassanOuda** [comment]
I figured out the issue, if you are using Rancher kubernetes, then you have to add this extra configuration to enable CSR approval which will create the webhook secrets and mutatingwebhook and make cache server work.

https://github.com/cockroachdb/cockroach/issues/28075#issuecomment-420497277

**Comment by DavidSpek** [comment]
It seems some of the reports here might be related to this issue: https://github.com/kubeflow/pipelines/issues/4505.
