### ISSUE TITLE
Argo Workflow: allow to set default ttlStrategy

### ISSUE THREAD

**Issue by desaintmartin** [kubeflow/manifests#1392]
According to https://argoproj.github.io/argo/workflow-controller-configmap/, one can set a default ttlStrategy for Workflows.

Unfortunately, https://github.com/kubeflow/manifests/blob/master/argo/base/config-map.yaml does not allow such customization.

Would it be possible to add a kustomize option to set such a default?

**Comment by alfsuse** [comment]
@desaintmartin did you check manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml ? You may want to change:
```JSON
          - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
            value: "86400"
```
That should be  default value equivalent to the 
```JSON
ttlStrategy:`
    secondsAfterCompletion:
```
keep in mind that 86400 is 24 hrs.. I've changed that to 10 seconds to try out and work as expected.

**Comment by desaintmartin** [comment]
Nice, indeed! I was looking for a default but if we have to edit the manifests themselves, I suppose that's ok!

**Comment by jbottum** [comment]
Hi @desaintmartin is this resolved?  which platform are you deploying into i.e. AWS, GCP, on-prem ?

**Comment by desaintmartin** [comment]
It has been resolved by manually editing the deployment manifest. I'm using kubeflow 1.0 on gcp and on-prem.

**Comment by yanniszark** [comment]
Closing as resolved.
