### ISSUE TITLE
Application v3 manifest - Istio and Dex

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/manifests#1424]
Ref: https://github.com/kubeflow/manifests/issues/1062

I wonder if we'll migrate Istio and Dex components to V3. It will be great for us to have at least a `base_v3` directory under the components folder.

By following below principals to establish base_v3 without changing original base+overlay folder:

```
Applications in KFDef should not use parameters field
Applications should fetch global paramaters from the configmap "kubeflow-config"
Applications should fetch application parameters from application specific config maps
Application specific config maps should be named "${APPNAME}-config"
Use of vars should be minimized
The most common and supported use case should be to substitute parameters into
fields that don't support referencing a configmap directly
In this case var names should be unique enough that they won't conflict with vars from
other applications
```

Since we AWS side has dependencies on Istio and Dex, there's motivation for us to help with migration.

**Comment by PatrickXYS** [comment]
/cc @krishnadurai @yanniszark 

I can help with the work if you're tied up with 1.1 release.

Also, it would be great if you can share any thoughts on this issue.

**Comment by krishnadurai** [comment]
@PatrickXYS I would be glad to accept work on migration.
I can help review.

**Comment by yanniszark** [comment]
@PatrickXYS that would be great, thanks!
