### ISSUE TITLE
cannot generate manifests due to error in pipeline/minio

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#146]
steps to reproduce

1. build kfctl on master
2. run `kfctl init ~/dls-kf --platform gcp --project XXX --package-manager kustomize --version master --namespace=dls-kf --skip-init-gcp-project --verbose --use_basic_auth`
3. cd ~/dls-kf
4. run `kfctl generate all --zone=us-west1-a`

error is 
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: error generating kustomization for pipeline/minio Error open /Users/kdkasrav/dls-kf/.cache/manifests/master/pipeline/minio/base/persistent-volume-claim-patch.yaml: no such file or directory

**Comment by yanniszark** [comment]
Opened https://github.com/kubeflow/kubeflow/issues/3490 because this may be a kfctl issue.

**Comment by lluunn** [comment]
cc

**Comment by lluunn** [comment]
we need https://github.com/kubeflow/manifests/issues/135!
