### ISSUE TITLE
Running the tests against master fails for me

### ISSUE THREAD

**Issue by crobby** [kubeflow/manifests#1476]
I'm looking into setting up the tests to run on our OpenShift ci system, but I'm seeing the following problem when running against master:

Is there something that I'm missing in my steps?  Are these tests ran as part of a PR submission or nightly?

make generate
make test | grep FAIL

```
--- FAIL: TestKustomize (0.90s)
FAIL	github.com/kubeflow/manifests/tests/stacks/aws	0.933s
--- FAIL: TestKustomize (0.91s)
FAIL	github.com/kubeflow/manifests/tests/stacks/examples/alice	0.938s
--- FAIL: TestKustomize (0.80s)
FAIL	github.com/kubeflow/manifests/tests/stacks/gcp	0.830s
--- FAIL: TestKustomize (0.78s)
FAIL	github.com/kubeflow/manifests/tests/stacks/ibm/multi-user	0.813s
```

**Comment by Jeffwan** [comment]
It should give you the detail failure. Could you scroll up and have a check? What's your kustomize version BTW?

**Comment by crobby** [comment]
> It should give you the detail failure. Could you scroll up and have a check? What's your kustomize version BTW?

kustomize version: {Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}

Attaching the output from my run.
[testoutput.txt](https://github.com/kubeflow/manifests/files/5050805/testoutput.txt)

**Comment by crobby** [comment]
> > It should give you the detail failure. Could you scroll up and have a check? What's your kustomize version BTW?
> 
> kustomize version: {Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}
> 
> Attaching the output from my run.
> [testoutput.txt](https://github.com/kubeflow/manifests/files/5050805/testoutput.txt)

To me, it looks like maybe it's failing due to some line wrapping in some of the description fields.  Is that plausible?

**Comment by crobby** [comment]
Update:  I took a look at one of the images ran for the presubmit test.  It appears to be running an older version of kustomize:
```
# kustomize version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T16:26:36Z GoOs:linux GoArch:amd64}
```

When I grab that version (3.2.0) and run locally, my make generate && make test does seem to pass.  Are we really targeting that version of kustomize though?  It's nearly a year old.

**Comment by yanniszark** [comment]
@crobby we will be targetting later versions as of 1.3, as part of the manifests refactor.
See: https://github.com/kubeflow/community/tree/master/wg-manifests

Closing this as the original issue is resolved.
