### ISSUE TITLE
Example on how to use keycloak gatekeeper and connect it to redirect to the dashboard

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/manifests#1489]
Hi,

I was wondering if there is an kfdef example that has keycloak-gatekeeper integrated with OIDC authentication to kubeflow.

Thanks!

**Comment by Hmr-ramzi** [comment]
@krishnadurai any ideas from your side? I would like to integrate keycloak to kubeflow (even if dex is involved no problem)

**Comment by AshokKuramdasu** [comment]
Hi Team, Please provide steps to connect to keycloak from kubeflow as need to login keycloak users.

**Comment by AshokKuramdasu** [comment]
Please update on keycloak and kubeflow integration?

**Comment by AshokKuramdasu** [comment]
Hi Team,
Please reopen this issue.

**Comment by PatrickXYS** [comment]
I don't think there's any folks helping on this issue 

What's the proposal we have to maintain another manifests for `keycloak-gatekeeper`, in general, we provide generic manifest and users can use them to customize by themselves.
