### ISSUE TITLE
Use GitHub Actions for presubmit checks

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/manifests#1498]
The current Prow tests are too bulky for the requirements for the repo. 
What do folks feel about a GitHub Action replacing it?

**Comment by PatrickXYS** [comment]
I would prefer keep consistent with all the repos.

Which means if we want to use Github action for `kubeflow/manifests`. And we might also want to use it for `kubeflow/kfctl` and other components. 

So my suggqestion might be keep Github action and existing Presubmit-Check together, and when they failed, we can check Github Action Results.

But I think it's a breaking change when we migrate Presubmit-Checks to Github action. So we'd better get some feedbacks from kubeflow/testing folks.

/cc @jlewi @Jeffwan @Bobgy

**Comment by jlewi** [comment]
@swiftdiaries 

> The current Prow tests are too bulky for the requirements for the repo.

Could you please explain what you mean by too bulky? 

Answering the question about what to do about the tests is probably blocked based on figuring out which working group will own this repository and how that will relate to the working group owning the individual applications.

**Comment by swiftdiaries** [comment]
> Could you please explain what you mean by too bulky?

Yeah, sure thing. So I was going off of Katib's approach to testing.

- Unit, integration tests:
  - They have [Travis CI](https://github.com/kubeflow/katib/blob/master/.travis.yml) for their Go-based unit tests and   integration tests. They have good mocking to test their APIs.
- E2E tests:
  - They use [Prow] based tests for their e2e examples on presubmits.

My primary intention is to increase the number of levels at which we test manifests so that we can make changes with confidence.

> Answering the question about what to do about the tests is probably blocked based on figuring out which working group will own this repository and how that will relate to the working group owning the individual applications.

I agree. We should identify clear OWNERS and a WG for the repo.

**Comment by jlewi** [comment]
Manifests has unittests.
https://github.com/kubeflow/testing/tree/master/tests

And these run just fine under prow/tekton.  If the WG that owns manifests prefers to use GitHub actions or Travis that sounds good to me.

I think we need to figure out which WG owns manifests before we make any changes to the infra so we know who the deciders are.

**Comment by PatrickXYS** [comment]
I think manifest will still use prow for testing.

/close
