### ISSUE TITLE
where do role and role-binding in jupyter-web app manifest getting used ?

### ISSUE THREAD

**Issue by chetanoruganti** [kubeflow/manifests#1505]
/kind question 

The serviceaccount attached to jupyter-web app deployment bound to clusterrole and clusterrolebinding . 
In the jupyterweb-app base kustomization 
 resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml

**Comment by jbottum** [comment]
@chetanoruganti Hi, did you get this resolved?   which environments are you deploying into i.e. GCP, AWS ?

**Comment by chetanoruganti** [comment]
Hi @jbottum , using on-premise cluster . 
In the jupyter-web app base Kustomization file role.yaml & role-binding.yaml are included but  look like this resources are not really need(service account mentioned in role-binding is not created as part of any yaml) . service account created in service-account.yaml is bound to clusterrole and clusterrole binding .
**Looks like some cleanup is needed on the base manifest**
