### ISSUE TITLE
Does Kubeflow 1.1 support K8s 1.16?

### ISSUE THREAD

**Issue by mttcnnff** [kubeflow/manifests#1508]
/kind question
/platform k8s

The docs are outdated on this and don't show an entry for KF 1.1 👇 
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/17532157/91082432-a7f8f080-e616-11ea-8b70-00e3ed9acc3b.png">

I know this [issue](https://github.com/kubeflow/manifests/issues/375) exists which is closed, but can't find any final confirmation that 1.1 will run on 1.16

**Comment by Jeffwan** [comment]
based on our test in the past, 1.16 is supported and we update a few breaking api changes for 1.16 in 1.1 release. I think this can be marked as done.

**Comment by Jeffwan** [comment]
I think we need a doc update in website project

**Comment by Jeffwan** [comment]
See https://github.com/kubeflow/manifests/issues/869 https://github.com/kubeflow/manifests/issues/585  https://github.com/kubeflow/manifests/issues/585

I will close the issue and feel free to reopen
