### ISSUE TITLE
Notebook CRD allows misconfigured notebooks that make the notebook-controller crash

### ISSUE THREAD

**Issue by axelgobletbdr** [kubeflow/manifests#1509]
It is possible to create a Notebook with a configuration that is not accepted by notebook-controller. The current notebook controller will crash when trying to read these resources. This blocks any notebook statefulset from being created. 

The problem lies in the resources fields of the pod spec. The cpu and memory fields expected their value to follow this regex: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

by specifying this pattern in the notebook CRD, we can block notebooks that do not adhere to this pattern from being created in the first place. This solves the issue mentioned above.

**Comment by kimwnasptd** [comment]
In order to also make the CPU/RAM inputs simpler and more intuitive for the user we could only permit number inputs in the form for such fields.

**Comment by kimwnasptd** [comment]
Also here are the docs regarding the correct string values for RAM
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
