### ISSUE TITLE
How's the DNS record pointing to the kubeflow domain (gcp_iap manifest) created ?

### ISSUE THREAD

**Issue by yassine-labidi** [kubeflow/manifests#1514]
/kind question

**Question:**
For a kubeflow installation using the `gcp_iap` version `1.0.2` manifest, how is the DNS record pointing to the `kubeflow.project.cloud.goog` created. Would you be so kind as to mention reference in the code where this record is actually created?

**Comment by jlewi** [comment]
https://github.com/danisla/cloud-endpoints-controller

**Comment by yanniszark** [comment]
Closing as answered
