### ISSUE TITLE
centraldashboard: clusterrole and clusterrolebinding are not created

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#152]
The centraldashboard needs a ClusterRole+ClusterRoleBinding.
These were added in this commit (https://github.com/kubeflow/manifests/commit/bb185e61a93b94e29205bc4b7306f52ef0131f83#diff-cc9344bde3bcc826a388ee4735ab5d58).

However, they weren't added to the  kustomization.yaml resources and so they are not created.

/priority p1

cc @kkasravi @jlewi

**Comment by prodonjs** [comment]
My apologies when created that previous PR for not including them in the resources section. #159 should resolve this.

**Comment by Brajen259** [comment]
I am stuck with this issue as well. new to kubernetes. @yanniszark  yanniszark who do we fix it?
