### ISSUE TITLE
Reinstalling kubeflow (gcp_iap, 1.0.2) on the same endpoint fails to acquire a valid managed certificate

### ISSUE THREAD

**Issue by yassine-labidi** [kubeflow/manifests#1520]
/kind bug

**What steps did you take and what happened:**

 - I Installed kubeflow with the `gcp_iap` manifest with the endpoint name `kubeflow`. This first install was successful. The managed certificate is successfully created and active. The UI is accessible.
 - After that I delete the previous kubeflow installed, deleted the associated ssl certificate which remained dangling.
 - Then I re-installed kubeflow with the same KF_NAME/endpoint name: `kubeflow`

The re-install process went fine, except for the managed certificate failing with a status `FAILED_NOT_VISIBLE`, making the UI inaccessible. This was repeated several times with different values for $KF_NAME and endpoint and consistently failed.

**What did you expect to happen:**
Upon a reinstall, the managed certificate to be properly created and active.

**Environment:**

- Kubeflow version: `1.0.2`
- kfctl version: `1.0.2`
- Kubernetes platform: `gcp`

**Comment by jlewi** [comment]
Did you follow the troubleshooting guide?
https://www.kubeflow.org/docs/gke/troubleshooting-gke/#troubleshooting-ssl-certificate-errors

Are you hitting: kubeflow/kubeflow#5048 ?

**Comment by yassine-labidi** [comment]
Hi @jlewi 
Yes I did follow the troubleshooting guide. And it didn't help much to figure out the problem.
I am not sure if it is [kubeflow/kubeflow#5048](https://github.com/kubeflow/kubeflow/issues/5048). If it is, is there where a workaround to fix it (and would be a way to validate it is issue 5048) ?
