### ISSUE TITLE
Remaining use of vars in manifests and the problems they cause

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1523]
We are moving towards having our manifests buildable with plain kustomize (without kfctl).
With `kfctl`, we used `vars` extensively. However, this presented many issues, as it disallowed composing packages. See:
https://github.com/kubeflow/manifests/issues/1007

The following variables still remain in the stacks uber-kustomization:
https://github.com/kubeflow/manifests/blob/6dcebbe263bc98c62aee9bff4364f7dfb3efe254/stacks/kubernetes/kustomization.yaml#L36-L59

They are _all_ related to VirtualServices:. For example:
https://github.com/kubeflow/manifests/blob/91c22388f5d1d9bf0f337185dcb36aca5c0f5ee8/common/centraldashboard/overlays/istio/virtual-service.yaml#L18
https://github.com/kubeflow/manifests/blob/806138020b7d509da4d0adeaeab9ba525a790913/tests/katib/installs/katib-standalone-ibm/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml#L22

Vars are defined at the top level kustomization (stack) because otherwise they would cause conflicts between packages.
This causes the following problems:
- Building individual applications produces invalid YAML. Individual apps should be buildable on their own.
- We are moving towards a model where manifests will originate from the app owners' repo and then we will define overlays/compositions on top of the imported manifests. The manifest that application owners give must be buildable on its own (because they test/deploy with it) but shouldn't contain vars (otherwise we can't compose it). So we can't expand the current way of doing things to the new model.

**Proposed solution:**

We could build a VirtualService transformer to use with kustomize, for this exact use-case.
This transformer would be able to:
- Change the cluster domain of the hosts field for the VirtualService, to a user-defined value.
- (optionally) Change the namespace of the Service referenced in the hosts field to match the VirtualService namespace.

These are the two reasons we use vars currently. A design for the transformer has been proposed here:
https://github.com/kubeflow/manifests/issues/1007#issuecomment-599257347
We could follow something similar to that, but also supporting wildcards (e.g., transform `*.svc.cluster.local` to `*.svc.custom.tld`

The individual app-level kustomizations would use this transformer for the namespace if they need it.
The uber-kustomization can use it for mass changing the cluster domain.

WDYT @jlewi @krishnadurai @swiftdiaries @Jeffwan ?

cc @ioandr

**Comment by jlewi** [comment]
@yanniszark I would probably recommend just using a kpt/kustomize function. In part because we are already using them on GCP. 

We already have a kustomize function for transforming the gateway on all virtual services.
https://github.com/kubeflow/kfctl/tree/master/kustomize-fns/virtual-service

We could extend that to handle changing the cluster suffix.
