### ISSUE TITLE
deploy with istio-1.7

### ISSUE THREAD

**Issue by caffeinism** [kubeflow/manifests#1535]
New features are continuously being added to istio, but istio1-3-1 is still used in kubeflow.

The incompatible parts of istio 1.3 and istio 1.7 in kubeflow are 

- sni_hosts property change to sniHosts
- ClusterRbacConfig, ServiceRole and ServiceRoleBinding change to AuthorizationPolicy.

I think it's silly to keep istio out of date to keep this legacy.

**Comment by thesuperzapper** [comment]
related to: #1548

**Comment by DavidSpek** [comment]
Related to: https://github.com/kubeflow/kubeflow/issues/5313
