### ISSUE TITLE
upgrade from dex v2.22.0

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1550]
Currently we are using an old version of dex (`v2.22.0`), we should upgrade this.
https://github.com/dexidp/dex/releases

**Comment by thesuperzapper** [comment]
I guss @krishnadurai @swiftdiaries are the main people who might want to discuss this.

**Comment by swiftdiaries** [comment]
I think there's some amount of exploratory work required to check if there will be breaking changes and address backwards compatibility with older versions.
Is the Dex V2 API changes part of the latest v2.25.0?

**Comment by yanniszark** [comment]
Planned as part of v1.3 and the manifests refactor:
https://github.com/kubeflow/community/tree/master/wg-manifests

/remove-lifecycle stale
/remove-priority p2
/priority p1

**Comment by thesuperzapper** [comment]
@yanniszark the version of dex in [common/dex/base](https://github.com/kubeflow/manifests/blob/master/common/dex/base/kustomization.yaml#L15) is `v2.24.0`, the latest version of dex is `v2.28.1` (https://github.com/dexidp/dex/releases), we should probably upgrade.
