### ISSUE TITLE
AWS Kubeflow 1.1 kfdef files are missing from master

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1555]
Currently, the following files are missing from `master` but are present in `v1.1-branch`, this means users may not be able to find them:
- `./kfdef/kfctl_aws.v1.1.0.yaml`
- `./kfdef/kfctl_aws_cognito.v1.1.0.yaml`

This relates to PR #1434 being into `v1.1-branch` rather than  `master`.

@Jeffwan I assume you want to fix this?

**Comment by Jeffwan** [comment]
I will add it back.

**Comment by Jeffwan** [comment]
We can close this issue now
