### ISSUE TITLE
enabling notebook culling feature in notebook controller by setting required env verables as part of notebook controller manifest

### ISSUE THREAD

**Issue by chetanoruganti** [kubeflow/manifests#1556]
/kind question 

By default in notebook controller culling feature is disabled or set to false .
To enable it notebook controller expects env variable ENABLE_CULLING set to true .
is it a good idea to add overlay for culling in the notebook manifest to set the  env variable ENABLE_CULLING in notebook controller deployment and getting this env from KDef.yaml notebook manifest kustomizeConfig  as parameter

**Comment by thesuperzapper** [comment]
More generally, we are talking about how to improve the Kubeflow install process (See: #1554)

But for now you can just modify the `./kustomize/kubeflow-apps/kustomization.yaml` which is generated when you run `kfctl build -f kfdef_xxx.yaml`, with a `patchesStrategicMerge:` field.

**Comment by chetanoruganti** [comment]
Thanks you @thesuperzapper

**Comment by thesuperzapper** [comment]
I saw that this was STILL not done in 1.6.1, so have raise a PR to fix it: https://github.com/kubeflow/kubeflow/pull/6689
