### ISSUE TITLE
Merge auto PRs made by the kubeflow-bot

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/manifests#1568]
We currently have around [19 open PRs](https://github.com/kubeflow/manifests/pulls?q=is%3Apr+is%3Aopen+auto+PR+author%3Akubeflow-bot) made by the @kubeflow-bot. 

These are all image tag updates after changes have been merged into the respective applications.
It is the responsibility of the application OWNERs / WG OWNERs to go through these PRs after every change is merged to follow-through with the corresponding auto PR to update the image tag.

Notebooks/Jupyter related auto PRs:
/assign @kimwnasptd 

For central-dashboard related auto PRs:
/asssign @SachinVarghese 
/assign @StefanoFioravanzo 

For training related auto PRs:
/assign @PatrickXYS 
/assign @gaocegege 

The rest of the PRs need attention as well. I'll bring this up in the next community meeting to bring up a more formal process around this workflow.

/cc @thesuperzapper 
Relates to https://github.com/kubeflow/manifests/issues/1553

Small note: Going forward it would be nice to setup a similar process for all applications in the manifests repo.

**Comment by PatrickXYS** [comment]
Some of the autoPR are redundant or out-of-dated. 

Let's keep up with latest auto PR for one component. 

E.g, we got several tf-operator PR, only merge the latest PR and close other PRs is good enough.

**Comment by thesuperzapper** [comment]
Also, are these auto-PRs even aware of the new `base_v3` manifests?

**Comment by jlewi** [comment]
@PatrickXYS I believe the auto push pipeline is only keeping one PR open for a given target. Do you have an example of PRs that are outdated or duplicated?

@thesuperzapper yes they are. See [comment](https://github.com/kubeflow/manifests/issues/1553#issuecomment-693752428) and the linked PR kubeflow/manifests#1479 for Jupyter which shows it is updating v3.

**Comment by Jeffwan** [comment]
I will close outdated PR and only leave most up-to-date one in the list.

/assign @Jeffwan

**Comment by Jeffwan** [comment]
I clean up most PRs and also assign something I can not handle to right WG. I will double check the list before the rc release

**Comment by thesuperzapper** [comment]
/close

The CI bot which builds images is broken https://github.com/kubeflow/testing/issues/812.

But we have cleared the backlog of these PRs.
