### ISSUE TITLE
RBAC: access denied for ml-pipeline-ui

### ISSUE THREAD

**Issue by majorinche** [kubeflow/manifests#1569]
try to visit ml-pipeline-ui, but report RBAC: access denied error

previously, i can visit, only after i enable the feature about "tokenrequest"

kfctl version
kfctl v1.1.0-0-g9a3621e

k8s version: 1.17.9

[root@d0404 kubeflow]# kubectl get pod -n kubeflow -o wide | grep ml-pipeline-ui
ml-pipeline-ui-7db96549d8-n9bcg                          2/2     Running   0          29m   10.233.93.144    d0404   <none>           <none>
[root@d0404 kubeflow]# curl 10.233.93.144:3000
RBAC: access denied

**Comment by jbottum** [comment]
Hi @majorinche, what platform are you running on i.e. AWS, GCP ?

**Comment by majorinche** [comment]
standard k8s, installed on bare mental

**Comment by Bobgy** [comment]
This is a current limitation: https://www.kubeflow.org/docs/pipelines/multi-user/#in-cluster-api-request-authentication.
You can find more discussion and some vision how this limitation will be removed in https://github.com/kubeflow/pipelines/issues/4440.
