### ISSUE TITLE
most Application Resource Selectors are Incorrect

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1573]
Most of the Application `matchLabels` don't match the Resources they should.

This is partially caused by not merging auto-PRs as raised here: #1568

I think we can reduce the complexity of these label selectors significantly, but this is really a symptom of the mess in this Repo, and highlights a need to clean it up, as raised here: #1554

A few quick examples (NOTE: there are MANY more, as pretty much every Application is affected):
* jupyter-web-app:
   * https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/overlays/application/application.yaml#L7
* pipelines:
   * https://github.com/kubeflow/manifests/blob/master/pipeline/installs/generic/application.yaml#L11
* centraldashboard:
   * https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/overlays/application/application.yaml#L7
* kfserving-install:
   * https://github.com/kubeflow/manifests/blob/master/kfserving/kfserving-install/overlays/application/application.yaml#L7

**Comment by jlewi** [comment]
/assign @thesuperzapper 

@thesuperzapper What is your plan for fixing this for notebooks?

**Comment by Jeffwan** [comment]
Let's solve all the labels issue in 1.2 release

**Comment by Jeffwan** [comment]
I will make a change for this issue.

/assign @Jeffwan

**Comment by thesuperzapper** [comment]
/open

This is still an issue for some components, https://github.com/kubeflow/manifests/pull/1646 only fixed it for wg-notebook owned components.

**Comment by Bobgy** [comment]
Thanks for raising the issue! I'll fix it for KFP

**Comment by Bobgy** [comment]
After taking a look, I think the selector is correct for KFP.

**Comment by Jeffwan** [comment]
@Bobgy Thanks for the confirmation.  Then we don't have pending PR for this issue

**Comment by thesuperzapper** [comment]
@Bobgy, are you sure?

It looks like the [Application](https://github.com/kubeflow/manifests/blob/master/pipeline/installs/generic/application.yaml#L12) is selecting `app.kubernetes.io/application: kubeflow-pipelines`, but [commonLabels](https://github.com/kubeflow/manifests/blob/master/pipeline/installs/generic/kustomization.yaml#L4) only has:
- `app.kubernetes.io/name: kubeflow-pipelines`
- `app.kubernetes.io/component: ml-pipeline`

**Comment by thesuperzapper** [comment]
@Jeffwan I am pretty sure [katib also has this issue](https://github.com/kubeflow/manifests/blob/master/katib/katib-controller/overlays/application/application.yaml#L60), who should we cc?

**Comment by Bobgy** [comment]
> @Bobgy, are you sure?
> 
> It looks like the [Application](https://github.com/kubeflow/manifests/blob/master/pipeline/installs/generic/application.yaml#L12) is selecting `app.kubernetes.io/application: kubeflow-pipelines`, but [commonLabels](https://github.com/kubeflow/manifests/blob/master/pipeline/installs/generic/kustomization.yaml#L4) only has:
> 
> * `app.kubernetes.io/name: kubeflow-pipelines`
> * `app.kubernetes.io/component: ml-pipeline`

My mistake. lol, the names are too similar.

**Comment by Bobgy** [comment]
Sent https://github.com/kubeflow/manifests/pull/1663 to fix this

**Comment by Jeffwan** [comment]
@thesuperzapper  We should ask @andreyvelich to help fix the label

**Comment by andreyvelich** [comment]
@thesuperzapper Do you mean we should leave only `component` and `name` here:
https://github.com/kubeflow/manifests/blob/338b1241a2214e898a0f9cd5a70ee11e9556c272/katib/katib-crds/overlays/application/application.yaml#L59-L63

Since we are using only them here:
https://github.com/kubeflow/manifests/blob/338b1241a2214e898a0f9cd5a70ee11e9556c272/katib/components/katib-crds/kustomization.yaml#L10-L11

/cc @Jeffwan

**Comment by thesuperzapper** [comment]
@andreyvelich I have raised https://github.com/kubeflow/manifests/pull/1669 to fix this issue for katib, which you can review

**Comment by Jeffwan** [comment]
em. If we are confident, we can bring it back to 1.2-branch

**Comment by PatrickXYS** [comment]
Removed this issue from 1.2, let's deliver fix by 1.3

**Comment by yanniszark** [comment]
This should be fixed in each app respectively. I wonder if we could perhaps address this with [KRM functions](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md), which are a new way to extend `kustomize`. Essentially, we could have a plugin that autogenerates the Application CRD so that we don't have to manually keep it in check.

**Comment by thesuperzapper** [comment]
After the refactor of the manifests, this is no longer an issue for most apps, as they have removed the "Application" resources
/close
