### ISSUE TITLE
Add network and subnetwork to the ContainerCluster manifest

### ISSUE THREAD

**Issue by kelvins** [kubeflow/manifests#1577]
It would be great to add `network` and `subnetwork` properties to the `ContainerCluster` manifest (management):

https://github.com/kubeflow/manifests/blob/c728bc737cfadc2816ecd50c5c96ee59cd1d9b1a/gcp/v2/management/cluster/cluster.yaml#L5-L23

For example:

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
...
spec:
  # Use a regional cluster. Regional offer higher availability and the cluster management fee is the same.
  location: location # {"$kpt-set":"location"}
  network: network # {"$kpt-set":"network"}
  subnetwork: subnetwork # {"$kpt-set":"subnetwork"}
  ...
```

These new values should also be included in the `set-values` command from the `Makefile`.

**Comment by jlewi** [comment]
Did you consider just defining an overlay with kustomize to do this type of customizaiton?  

kustomize uses a template free approach which makes it easy to define unanticipated customizations.

**Comment by kelvins** [comment]
Thank you @jlewi. Yes, we ended up using a kustomize overlay to include it, but we spent several minutes trying to figure out how to do that, since it wasn’t very clear.

This is just a suggestion, but maybe using `kpt` to set these values would be easier to other people facing a similar issue.

**Comment by jlewi** [comment]
@kelvins Any suggestion about how we can document the use of overlays better?

Is there a particular reason why you think these values are ripe for additional kpt substitutions? I think we want to use kpt substitutions sparingly otherwise we just end up templatizing the entire manifest as a set of key values.

So I lean towards a high bar; i.e. only those values that almost all users need to set (e.g. project, name, location).

**Comment by kelvins** [comment]
> @kelvins Any suggestion about how we can document the use of overlays better?

:thinking: Perhaps including a section about this specific use case (for example, "Setting custom network and subnetwork") in a FAQ or Troubleshooting section (or even in the GKE documentation) would be sufficient.

> Is there a particular reason why you think these values are ripe for additional kpt substitutions? I think we want to use kpt substitutions sparingly otherwise we just end up templatizing the entire manifest as a set of key values.
So I lean towards a high bar; i.e. only those values that almost all users need to set (e.g. project, name, location).

I understand. It makes sense to use the values ​​most used by users.

In our case, we always use specific `network` and `subnetwork` for our GCP projects (this is the reason I opened the issue), but I don’t know if this is the case for most users.

Feel free to close the issue if you think it isn't a general use case.

**Comment by jlewi** [comment]
Thanks. Feel free to open an issue about adding to an FAQ; or hopefully people looking for an answer will come across this issue.

**Comment by krish0005** [comment]
> Thank you @jlewi. Yes, we ended up using a kustomize overlay to include it, but we spent several minutes trying to figure out how to do that, since it wasn’t very clear.
> 
> This is just a suggestion, but maybe using `kpt` to set these values would be easier to other people facing a similar issue.

I need exactly that kind of information, since it is hours now i'm trying to figure this out.

I'm trying on Kubeflow 1.2.0 creating the Management Cluster with kpt.

(In the past i was able to do it successfully with Kubeflow 1.0.2 with Kustomize and Kfctl)

I tried this:

```
kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: XXXXXX # {"$kpt-set":"gcloud.core.project"}
commonAnnotations:
  # Annotation required by anthoscli
  gke.io/cluster: "bootstrap://"
resources:
- network.yaml
- enable-services.yaml
- cluster.yaml
- nodepool.yaml`

network.yaml 

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: XXXXXX
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: XXXXXX
spec:
  ipCidrRange: 10.132.0.0/20
  region: europe-west1
  networkRef:
    name: XXXXXX
  secondaryIpRange:
  - rangeName: servicesrange
    ipCidrRange: 10.140.0.0/20
  - rangeName: clusterrange
    ipCidrRange: 10.12.0.0/14

cluster.yaml

# TODO(jlewi): Use a regional cluster? There should no longer be any cost savings to using zonal
#
# User specific values should be defined in a patch inside the blueprint package.
# Exception is the name since that needs to be changed in teh base package as well.
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: XXXXXX # {"$kpt-set":"name"}
  annotations:
    # We are defining the nodepool in nodepool.yaml
    cnrm.cloud.google.com/remove-default-node-pool: "true"
spec:
  # Use a regional cluster. Regional offer higher availability and the cluster management fee is the same.
  location: europe-west1-b # {"$kpt-set":"location"}
  initialNodeCount: 3
  # See https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#sharing_identities_across_clusters
  # Currently there is only one pool per project
  workloadIdentityConfig:
    identityNamespace: XXXXXX.svc.id.goog # {"$kpt-set":"wi-pool"}
  releaseChannel:
    channel: REGULAR
  networkingMode: VPC_NATIVE
  networkRef:
    name: XXXXXX
  subnetworkRef:
    name: XXXXXX
  ipAllocationPolicy:
    servicesSecondaryRangeName: XXXXXX-services      
    clusterSecondaryRangeName: XXXXXX-pods

```
You can see i tried both adding creation of new VPC and Subnet but also to hardcode an existing one i have already created.
Both attempts to use a custom VPC fails, i'm still getting this error:

```
Unexpected error: error reconciling objects: error reconciling ContainerCluster:acn-cpaascgp/XXXXXXX: error creating GKE cluster XXXXXX: googleapi: Error 400: Project "XXXXX" has no network named "default".
make: *** [apply-cluster] Error 1
```
@kelvins any help or suggestion you can give about how you did it with would be welcomed !

@jlewi i don't know how / where to open this issue in the FAQs but i got that problem in 1.0.2 and now i'm having issues also with 1.2.0 so can you please consider adding the fields to manage a custom VPC in the scripts and kpt/kustomize files provided with Kubeflow ?

The "default" VPC is not safe, we always remove it and use custom VPC with our safe firewall rules which we can control per each project. Actually by company security compliancy rules we cannot use the "default" VPC at all.

Thanks !

**Comment by kelvins** [comment]
@krish0005 I don't think it will help in your case, but we just created the overlay in the `instance` folder (`instance/gcp_config/cluster.yaml`) and included it as a `resource` in the `kustomization.yaml`. As we already had the `network` and `subnet`, we used the `external` feature, for example:

```yaml
...
spec:
  networkRef:
    external: https://www.googleapis.com/compute/v1/projects/project-name/global/networks/network-name
  subnetworkRef:
    external: https://www.googleapis.com/compute/v1/projects/project-name/regions/region-name/subnet-name/public
  ...

```

**Comment by krish0005** [comment]
Thanks @kelvins ! 
I tried your suggestion anyway and sadly it didn't work.

I build from this path: `/home/mykubeflowuser/kubeflow/mykubeflowproject/management/`
Applied your suggestion as following:
```
/home/mykubeflowuser/kubeflow/mykubeflowproject/management/upstream/management/cluster/cluster.yaml

	apiVersion: container.cnrm.cloud.google.com/v1beta1
	kind: ContainerCluster
	metadata:
	  name: aip-kubeflow-mgmt # {"$kpt-set":"name"}
	  annotations:
	    cnrm.cloud.google.com/remove-default-node-pool: "true"
	spec:
	  location: europe-west1-b # {"$kpt-set":"location"}
	  initialNodeCount: 3
	  workloadIdentityConfig:
	    identityNamespace: acn-cpaascgp.svc.id.goog # {"$kpt-set":"wi-pool"}
	  releaseChannel:
	    channel: REGULAR
	  networkRef:
	    external: https://www.googleapis.com/compute/v1/projects/mygcpproject/global/networks/mykubeflowproject
	  subnetworkRef:
	    external: https://www.googleapis.com/compute/v1/projects/mygcpproject/regions/europe-west1-b/mykubeflowproject/public
```
Built, checked, applied:
```
make apply-cluster

make -f ./upstream/management/Makefile hydrate-cluster
make[1]: Entering directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
The management cluster name "myproject-mgmt" is valid.
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf build/cluster
mkdir -p build/cluster
kustomize build ./instance/cluster -o build/cluster
make[1]: Leaving directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
make -f ./upstream/management/Makefile apply-cluster
make[1]: Entering directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
# Create the cluster
anthoscli apply -f build/cluster
I0211 15:34:40.932055   15959 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I0211 15:34:42.070023   15959 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster myproject-mgmt
Unexpected error: error reconciling objects: error reconciling ContainerCluster:mygcpproject/myproject-mgmt: error creating GKE cluster myproject-mgmt: googleapi: Error 400: Project "mygcpproject" has no network named "default".
make[1]: *** [apply-cluster] Error 1
make[1]: Leaving directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
make: *** [apply-cluster] Error 2
```
The build files reflect my config, but looks like it is ignored.

**Comment by krish0005** [comment]
@jlewi  nowhere here it is reported that you need to have a "default" VPC in your GCP project to be able to deploy this product: https://www.kubeflow.org/docs/gke/deploy/project-setup/
