### ISSUE TITLE
The image gcr.io/ml-pipeline/visualization-server is hardcode within the source code

### ISSUE THREAD

**Issue by naveensrinivasan** [kubeflow/manifests#1581]
We are deploying kubeflow within `eks` and we want to pull all the images from our own repo in `ecr`. We were able to utilize the `Kustomize`, but we ran into an issue with https://github.com/kubeflow/manifests/blob/5cc6fd3ca0eac7c46aad116c04713d6944f249fd/pipeline/installs/multi-user/pipelines-profile-controller/sync.py which uses images from `gcr.io` and it is hardcoded. Are there any workarounds? Do we have to fork to solve this problem?

**Comment by Bobgy** [comment]
@naveensrinivasan Recommend go ahead and fork `sync.py` to suit your own needs. It is designed this way to allow easy forking.
