### ISSUE TITLE
kustomize build error

### ISSUE THREAD

**Issue by chongchuanbing** [kubeflow/manifests#1583]
```
./kfctl_mac build -V -f kfctl_istio_dex.v1.1.0.yaml
./kustomize_kustomize.v3.2.1_darwin_amd64 build kustomize/application | tee yaml/application.yaml
```

tools:
kfctl  v1.1
kustomize v3.2.1
manifests v1.1.0

The error info:

2020/10/15 10:59:10 got file 'cluster-role.yaml', but '/Users/chongchuanbing/Downloads/kubeflow_manifests/.cache/manifests/manifests-1.1-branch/application/application/base/cluster-role.yaml' must be a directory to be a root
Error: accumulating resources: recursed accumulation of path '../../.cache/manifests/manifests-1.1-branch/application/v3': accumulating resources: accumulating resources from '../application/base/cluster-role.yaml': security; file '/Users/chongchuanbing/Downloads/kubeflow_manifests/.cache/manifests/manifests-1.1-branch/application/application/base/cluster-role.yaml' is not in or below '/Users/chongchuanbing/Downloads/kubeflow_manifests/.cache/manifests/manifests-1.1-branch/application/v3'

**Comment by dfarr** [comment]
I am seeing the same behaviour, is there is a specific version of kustomize we should be using?

**Comment by rochaporto** [comment]
Same here. Any luck?

**Comment by dfarr** [comment]
I updated the manifests to kustomize v3 in #4785, seems to solve the issue for me

**Comment by yanniszark** [comment]
This is a security warning because a kustomization is trying to include files that are not under the folder or subfolders of the `kustomization.yaml` file. You can make it work with `--load_restrictor=none`. This flag is used so that we can shared files/patches between kustomizations.
http://bit.ly/kf_kustomize_v3
