### ISSUE TITLE
ETA on the new doc for Kubeflow 1.1.0?

### ISSUE THREAD

**Issue by EKami** [kubeflow/manifests#1590]
The doc says:
```
The information below is obsolete. It pertains to using kfctl to generate kustomization.yaml. This was how things worked through Kubeflow 1.0.0.
```

but doesn't give any insights on what has changed or how a newcomer like me should approach this project.
Is there any ETA on the release of the new doc? Thank you.

**Comment by jbottum** [comment]
@EKami Hi, where are you trying to install i.e. on-prem, AWS, GCP ?   Have you looked at MiniKF as a way to get started quickly ?   https://www.arrikto.com/f/get-minikf/

**Comment by EKami** [comment]
Hello @jbottum . I tried minikf locally but I'm really looking to install Kubeflow on AWS EKS, not locally :)

**Comment by Jeffwan** [comment]
@EKami Have you checked kubeflow.org. 1.1 has been rolled out for long time. https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

**Comment by EKami** [comment]
@Jeffwan I did, I tried to install it for 2 weeks on aws but I was constantly facing issues with the various pods crashing so I ended up giving up.

**Comment by PatrickXYS** [comment]
Though we don't have Kubeflow-Kubernetes version matrix, but at least I have tried on 1.17 EKS cluster, it works fine.

Will try on 1.18

**Comment by johnchenghk01** [comment]
The doc for use external mysql is outdated with kubeflow 1.1.0
