### ISSUE TITLE
Manifests 1.2 release

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1597]
Please help link all 1.2 release related issues here. 

- Openshift kubeflow/manifests#1567

**Comment by thesuperzapper** [comment]
I am trying to link blocking issues in the Kubeflow 1.2 GitHub project: https://github.com/orgs/kubeflow/projects/41

**Comment by Jeffwan** [comment]
@thesuperzapper Thanks! I got updates from serving/pipeline/automl. Do you have some updates on notebook?

**Comment by Jeffwan** [comment]
We will just use https://github.com/kubeflow/kubeflow/issues/5371 to track the issues. Close this one
