### ISSUE TITLE
Remove use of ksonnet in tests

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1608]
ksonnet was deprecated over a year ago the tests should no longer be using ksonnet to define tests.

Related to #774

**Comment by jlewi** [comment]
We have stock Tekton pipelines for go and py unittests so it should be pretty straightforward to add them.

just copy what we do in kubeflow/testing
https://github.com/kubeflow/testing/blob/master/prow_config.yaml#L16

**Comment by PatrickXYS** [comment]
I'm not sure what's the best practice to move forward, Tekton Pipeline / ArgoCD / other solutions. (I'm experimenting those solutions)

As of now, WG folks have experience in using Argo Workflow, and it should give them more confidence in adopting ArgoCD afterwards. 

Tekton Piepline is another tool for CI/CD, but I can't tell the strong reason to move with Tekton pipeline instead.

**Comment by yanniszark** [comment]
@PatrickXYS I think we have tests in both Argo and Tekton at this point.
IMO, this warrants a separate issue to go over the current situation and see what are the alternatives.

In Kubernetes controller, we have found that E2E testing with k3d has been immensely useful, as it's super fast.
The downside is that we need admin privileges to run docker-in-docker.

**Comment by yanniszark** [comment]
AFAIK this is the only ksonnet part remaining: https://github.com/kubeflow/manifests/blob/b6e6d9eacc0607536263fdc0172d0776d52fee0e/prow_config.yaml#L8-L15
@PatrickXYS I saw that you did some work in this area, are you aware of what is the remaining test and if it's needed anymore?

**Comment by PatrickXYS** [comment]
@yanniszark So for ksonnet, they are responsible for unit test, let me check if I can switch from ksonnet unit test to python unit test

**Comment by PatrickXYS** [comment]
Related with https://github.com/kubeflow/manifests/issues/1708
