### ISSUE TITLE
kfserving metrics server service has incorrect selector

### ISSUE THREAD

**Issue by connorlwilkes** [kubeflow/manifests#1666]
The KFserving metrics server service has the following selector:
```
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
```
This is incorrect, as per the kfserving-controller-manager stateful set (and other related services) the correct selector should be:
```
      control-plane: kfserving-controller-manager
      controller-tools.k8s.io: "1.0"
```
This shouldn't impact the system but will prevent prometheus scraping. Happy to fix this

**Comment by pvaneck** [comment]
Seems like this issue is also in the kfserving repository from which the kferserving.yaml here is based: https://github.com/kubeflow/kfserving/blob/master/config/rbac/auth_proxy_service.yaml

I'd say go ahead and open a PR there to fix it if you can, then we can update it here as well.

**Comment by yanniszark** [comment]
Fixed in https://github.com/kubeflow/kfserving/pull/1239
