### ISSUE TITLE
Migrate away from DockerHub

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1668]
As of November 2nd 2020, DockerHub is now enforcing [rate limits for public images](https://www.docker.com/increase-rate-limits). 

As Kubeflow is used by many companies, it is quite likely that we will exceed these limits, we should aim to have all the default images in this repo hosted on a reliable source. 

In past we have used GCR, but Google seems hesitant to continue donating to Kubeflow, so potentially AWS's new public registry will work better.

**Comment by thesuperzapper** [comment]
/p 1

The main offenders in this repo are:
* katib
* argo
* istio
* seldon

**Comment by thesuperzapper** [comment]
@kubeflow/wg-automl-leads

**Comment by PatrickXYS** [comment]
Hi all, we'd love to help as well. 

Alongside with public ECR registry launching next month, we'll be starting some migration work as well

/priority p1

**Comment by PatrickXYS** [comment]
https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/

ECR Public Registry launched today!

**Comment by yanniszark** [comment]
This is the responsibility of each separate WG. Closing this issue...
