### ISSUE TITLE
Jupyter web app config not compatible with latest jupyter web app image

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#167]
Got error when click `New Server`
`KeyError: 'notebook-name'`

`notebook-name` is not in client side request.

Related:
https://github.com/kubeflow/manifests/pull/163

**Comment by kunmingg** [comment]
@abhi-g 
@kimwnasptd

**Comment by kimwnasptd** [comment]
@kunmingg the new config is not compatible with the old implementation of the UI. It was meant for the [new](https://github.com/kubeflow/kubeflow/pull/3448) one.

Try it out with the new image which has the `dcaeee7` tag
