### ISSUE TITLE
Clean up stale repo branches

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/manifests#1674]
We should clean up kubeflow/manifests branches except for formal release branches, thus, I collected data points as below:

https://github.com/kubeflow/manifests/branches/all

Otherwise, it's weird to end-user that other branches exist alongside the release branches

```
Bobgy-patch-1
terrytangyuan-patch-1
zhenghuiwang-test-v1
automated-cherry-pick-of-#949-upstream-v1.0-branch
pdmack-patch-1
update_centraldashboard_
revert-323-feature/istio_update
zhenghuiwang-patch-1
richardsliu-patch-1
revert-134-admission-webhook
revert-109-notebookcrd1
```

/cc @kubeflow/wg-manifests-leads

**Comment by Jeffwan** [comment]
Thanks @PatrickXYS driving this. I think you should have write access to this repo and non of these branches are active. You can remove them

**Comment by PatrickXYS** [comment]
Looks like I don't have access to delete protected branches

![image](https://user-images.githubusercontent.com/23116624/100256516-c0202a80-2ef9-11eb-94f8-f10e539145d2.png)

**Comment by Jeffwan** [comment]
@PatrickXYS Yeah, if some branches can not be deleted. I think it's fine for someone with permission to clean up later. Not a big deal

**Comment by kimwnasptd** [comment]
I'd also like to give this effort a last push. Let's first try to get an explicit ACK from the creators of the branches, and then we can move forward and delete them.

I'm looking at the following branches right now https://github.com/kubeflow/manifests/branches/stale:
* `richardsliu-patch-1`
* `zhenghuiwang-patch-1`
* `update_centraldashboard_`
* `pdmack-patch-1`
* `zhenghuiwang-test-v1`
* `terrytangyuan-patch-1`

All of them are either `closed` or `merged`, so we should be OK deleting them. But let's also ask from a final ACK from their authors. If we don't have a response in something like a month, then I think we are OK removing them.

So @richardsliu @zhenghuiwang @kkasravi @terrytangyuan @pdmack are you OK with removing these stale branches?
cc @zijianjoy

**Comment by terrytangyuan** [comment]
Yes, please remove mine. I don't know why it's been made a protected branch.

**Comment by juliusvonkohout** [comment]
@kimwnasptd can this be closed?

**Comment by juliusvonkohout** [comment]
@zijianjoy 

could please delete the following old branches?

* [gcp-v1.2-branch](https://github.com/kubeflow/manifests/tree/gcp-v1.2-branch)
* [v1.1-rc.1](https://github.com/kubeflow/manifests/tree/v1.1-rc.1)
* [terrytangyuan-patch-1](https://github.com/kubeflow/manifests/tree/terrytangyuan-patch-1)
* [zhenghuiwang-test-v1](https://github.com/kubeflow/manifests/tree/zhenghuiwang-test-v1)
* [pdmack-patch-1](https://github.com/kubeflow/manifests/tree/pdmack-patch-1)
* [update_centraldashboard_](https://github.com/kubeflow/manifests/tree/update_centraldashboard_)
* [zhenghuiwang-patch-1](https://github.com/kubeflow/manifests/tree/zhenghuiwang-patch-1)

**Comment by zijianjoy** [comment]
After review, I have removed the branch protection rules for the following branches:

```
richardsliu-patch-1
zhenghuiwang-patch-1
update_centraldashboard_
pdmack-patch-1
zhenghuiwang-test-v1
terrytangyuan-patch-1
```

Owners can now delete them as needed.

**Comment by juliusvonkohout** [comment]
Thank you very much. Cleaned and closed

/close
