### ISSUE TITLE
Azure OIDC authentication doesn't work in KF 1.2

### ISSUE THREAD

**Issue by slenky** [kubeflow/manifests#1676]
Hi folks,

## Summary 
According to the [documentation](https://www.kubeflow.org/docs/azure/authentication-oidc/), I tried to get an Azure authentication working.
I have an external domain configured with https, istio gateways also works on 443, and all the properties configured inside `stacks/azure/application/oidc-authservice`.

When I try to login it brings me to Azure login website and after actual authorization I end up with a 504 error & stacktrace in oidc-authservice:
```
2020/11/26 09:26:23 http: panic serving 10.240.0.229:50112: interface conversion: interface {} is nil, not string
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc0003380a0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x88ee00, 0xc00010b560)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.(*server).callback(0xc000104100, 0x9b6ce0, 0xc0002d8c40, 0xc000108300)
	/go/src/oidc-authservice/handlers.go:150 +0x1061
net/http.HandlerFunc.ServeHTTP(0xc0000f4330, 0x9b6ce0, 0xc0002d8c40, 0xc000108300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f60c0, 0x9b6ce0, 0xc0002d8c40, 0xc0000a8400)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
main.whitelistMiddleware.func1.1(0x9b6ce0, 0xc0002d8c40, 0xc0000a8400)
	/go/src/oidc-authservice/handlers.go:225 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc00007fac0, 0x9b6ce0, 0xc0002d8c40, 0xc0000a8400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000098360, 0x9b6ce0, 0xc0002d8c40, 0xc0000a8400)
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:54 +0x1037
net/http.serverHandler.ServeHTTP(0xc0000aa2a0, 0x9b6ce0, 0xc0002d8c40, 0xc0000a8400)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0003380a0, 0x9b7ea0, 0xc000512000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```
This panic can be related to https://github.com/arrikto/oidc-authservice/issues/19

![image](https://user-images.githubusercontent.com/1599647/100335165-57aa7980-2fdd-11eb-8a05-02e39aeddc94.png)

## Environment info
AKS 1.17 
Kubeflow 1.2 deployed with `kfctl_azure_aad.v1.2.0.yaml`
Default oidc-authservice image: gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef
I've tried a newer ones but they didn't worked neither.

Some debug information from oidc-authservice pod:
![image](https://user-images.githubusercontent.com/1599647/100335230-6c870d00-2fdd-11eb-871b-3e83f1a13802.png)

**Comment by PatrickXYS** [comment]
@berndverst  Can you help with this issue?

**Comment by berndverst** [comment]
/assign berndverst sudivate yilun-msft

Thanks @PatrickXYS.

@sudivate @yilun-msft can you help take a look to see why it doesn't deploy? It may be related due to changes to v1.2 or my re refactoring to get the test generation to complete.

I'm on vacation away from home through Tuesday, so unfortunately can't investigate until then.

**Comment by berndverst** [comment]
@slenky can you also share your istio version please? At least 1.6.x needs to be installed in the istio-system namespace

**Comment by berndverst** [comment]
@slenky there were lots of issues in the v1.2 deployment -- apparently I didn't define two variables throughout which led to most VirtualService definitions to be invalid -- hence Istio didn't route requests correctly. I must not have checked those changes in before 😇. Sorry for the inconvenience! 

Once https://github.com/kubeflow/manifests/pull/1679 is merged, try deploying again with the v1.2 definition in the master branch:
`https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_azure.v1.2.0.yaml`

**Comment by yilun-msft** [comment]
Hi @yanniszark, similar to what you have suggested, as is shown in the screenshot, the `USER_CLAIM` was set to `email`. Shall we roll out the authservice again or any more steps to take?

**Comment by slenky** [comment]
Hi @berndverst , thanks a lot! 

I've added those 2 variables into the `stacks/azure/kustomization.yaml` and now all the VirtualServices have the correct paths. However, it's doesn't resolve my issue :) 

I am using a default Istio version from `kfctl_azure_aad.v1.2.0.yaml` - 1.3.1 . Would you suggest me to try out 1.6.* ?

**Comment by slenky** [comment]
On Istio 1.6.14 it never gets me to authentication window.
[https://pastebin.com/a0L3FsDJ](Logs from ingressgateway)

**Comment by slenky** [comment]
Reverted back Istio to 1.3.1. Now I'm trying to configure a more recent version of oidc-authservice and getting the same 504 but with more decent output:
```
time="2020-11-30T14:16:15Z" level=error msg="Couldn't find claim `email' in claims `map[family_name:Astapov given_name:Bohdan name:Bohdan Astapov picture:https://graph.microsoft.com/v1.0/me/photo/$value sub:gfOJIlL7OiI0TOh5n29r4BHe4JteTCLH_cY2KLlRlCw]'" ip=10.240.1.191 request="/login/oidc/callback?code=0.ATkA...........&session_state=4dff28a9-2ca1-47e8-9b1d-65237ddd0553"
```

**Comment by sudivate** [comment]
> Reverted back Istio to 1.3.1. Now I'm trying to configure a more recent version of oidc-authservice and getting the same 504 but with more decent output:
> 
> ```
> time="2020-11-30T14:16:15Z" level=error msg="Couldn't find claim `email' in claims `map[family_name:Astapov given_name:Bohdan name:Bohdan Astapov picture:https://graph.microsoft.com/v1.0/me/photo/$value sub:gfOJIlL7OiI0TOh5n29r4BHe4JteTCLH_cY2KLlRlCw]'" ip=10.240.1.191 request="/login/oidc/callback?code=0.ATkA...........&session_state=4dff28a9-2ca1-47e8-9b1d-65237ddd0553"
> ```

@slenky  looks like your token is missing the `email` claim. Based on the type of user `email` can be optional.  
Can you try below : 
1. Update registered app manifest to set "accessTokenAcceptedVersion": 2
1.  Under your registered app go to "Token configuration" -> "Add an optional claim" and select `email`
![image](https://user-images.githubusercontent.com/28938855/100653753-b897c180-32fd-11eb-8da6-61c921c6d6dc.png)

**Comment by sylus** [comment]
@zachomedia we got this working on ours maybe something we can assist with and help document so we don't have to maintain our own contaner?

**Comment by slenky** [comment]
@sudivate still getting the same error with same output, unfortunately :(

**Comment by sudivate** [comment]
@slenky can you try enabling `email` for both id tokens and access token. If possible can you verify here https://jwt.ms/ with the tokens returned from AAD carry `email` claim

**Comment by slenky** [comment]
@sudivate first part of the code is `?code=0.ATkA`, AFAIU **0** here means that Azure AD doesn't even return a proper header. The rest of the `code` also doesn't seems to be somehow related to JWT.

What steps did I taken to create an App Registration:
1. Added a Redirect URL: https://mydomain/login/oidc
2. Added optional claims `email` to ID and Access
3. Used a `Accounts in this organizational directory only ` for Supported account type.
4. List of API permissions:
![image](https://user-images.githubusercontent.com/1599647/100781381-9db77100-3413-11eb-8b54-ad1d14bae449.png)
5. Tried both checked and unchecked any Implicit grants 
![image](https://user-images.githubusercontent.com/1599647/100781471-c0e22080-3413-11eb-976b-50983bbbe177.png)

**Comment by slenky** [comment]
So, I finally got this working. 

The reason was that the users did not have their mail in the ‘Email’ field on Profile page - it was only specified in ‘User Principal Name’; however that setup worked well for us with Dex and Gitlab Omniauth. 
¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/1599647/100878486-eeca7200-34b2-11eb-87d1-444f2cdd1adf.png)

Thanks to everyone for the help!
