### ISSUE TITLE
[IBM] update jupyter-web-app in ibm stacks/application

### ISSUE THREAD

**Issue by adrian555** [kubeflow/manifests#1687]
The `stacks/ibm/application/jupyter-web-app` was added at the time the base jupyter-web-app's base_v3 version did not work for our stack. With the issue #1686, we need to investigate a better approach for this application with ibm stack. If the current base_v3 version works then we can also switch to use that too.

**Comment by adrian555** [comment]
cc @animeshsingh @pvaneck @evan-hataishi

**Comment by pvaneck** [comment]
@adrian555 Hey, I would like to just switch to using the base_v3 directories directly as opposed to the custom setup we have in our stacks directory. This works fine except for the naming [issue](https://github.com/kubeflow/manifests/issues/1285) as mentioned earlier. Do you think it is okay to make the switch regardless?

**Comment by adrian555** [comment]
@pvaneck if this is not going to impact GCP, of course it is the better choice. I would also like to see that the naming is fixed through #1285.
