### ISSUE TITLE
[AWS] Istio 1.3.1 not compatible with Cognito Kubeflow solution

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/manifests#1695]
**TL;DR**

We use [aws-istio-authz-adaptor](https://github.com/kubeflow/manifests/tree/master/aws/aws-istio-authz-adaptor) for authorization for Cognito solution, but this only works in istio 1.1.X, after 1.2, adaptor was removed.

Ref: https://istio.io/latest/news/releases/1.2.x/announcing-1.2/change-notes/#installation-and-upgrade

Side Effects:

* KFServing 0.4.1 require istio 1.3.1+, which does not work in v1.2 Kubeflow Cognito.

**Comment by PatrickXYS** [comment]
/cc @karlschriek 

I created the issue to keep track and working on it now.

**Comment by PatrickXYS** [comment]
Related issue: https://github.com/kubeflow/manifests/issues/1362

**Comment by yanniszark** [comment]
@PatrickXYS isn't this issue the same as #1362?
Should we keep only one of the two?

In addition, Mixer is deprecated in later Istio versions. I am not familiar with how you set it up right now, but perhaps I can offer some suggestions as to how to integrate Cognito (as another OIDC provider).
https://www.datacenterknowledge.com/devops/latest-istio-release-removes-single-points-failure-installation-friction

**Comment by PatrickXYS** [comment]
@yanniszark Thanks for reminding of `Mixer is deprecated in later Istio versions.`

Seems like we need to keep up with at least istio 1.6, let me see if I can refactor aws-istio-authz-adaptor. 

And yes this is dup of #1362 , we can keep this and close the other one.

**Comment by karlschriek** [comment]
@PatrickXYS is this something that can be fairly easily upgraded to what is expected in Istio 1.3.1, since that is currently the version that that seems to be targeted by the rest of the Kubeflow components? Or are you thinking of going directly to a more recent Istio version?

**Comment by karlschriek** [comment]
@PatrickXYS anything we can do to help here? It fairly important for us to get this fix in soon!

**Comment by PatrickXYS** [comment]
@karlschriek I'm in the middle stage of deciding if bumping istio into 1.3.1 or 1.6 above.

The reason I want to bump to 1.6 is because we've seen some kubeflow app started to require higher versions

E.g, https://github.com/kubeflow/manifests/issues/1707

KFP has already started engineering work towards istio 1.6 above.

**Comment by karlschriek** [comment]
Any thoughts on a quick fix that would allow use of 1.3.1 with the current KF 1.2 distribution? I've played around with the '--useAdapterCRDs=true' and '--useTemplateCRDs=true' in the mixer args without really know what that would do, but couldn't get it to work, so I presume more is needed.

**Comment by Mykolaichenko** [comment]
@PatrickXYS @james-jwu May you share some insight about it? Does the community schedule to fix Istio + Cognito for Pipelines 1.2?

**Comment by james-jwu** [comment]
@Bobgy Is anything blocking KFP from upgrading to Istio 1.6 right now?

**Comment by Bobgy** [comment]
No, KFP side is ready

**Comment by karlschriek** [comment]
Would there be any blockers for KFServing? Getting Pipelines and KFServing
to work correctly with Cognito were the biggest issues for us in KF 1.2.

**Comment by Mykolaichenko** [comment]
What I can do to make it resolved? How I can help? 
That's really valuable issue blocks upgrade pipelines to 1.2
