### ISSUE TITLE
Deploying with GCP: Issues with persistentvolumes

### ISSUE THREAD

**Issue by scottcantreid** [kubeflow/manifests#1696]
Hello, I've followed all of the boilerplate steps that are found in [Kubeflow on Google Cloud Platform](https://www.kubeflow.org/docs/gke/deploy/). I get the following error when I try to run `make apply` for my new cluster:
```
Error from server (Forbidden): error when creating ".build/kubeflow-apps/v1_persistentvolume_minio-pv.yaml": persistentvolumes "minio-pv" is forbidden: error querying GCE PD volume kf-cluster-1-storage-artifact-store: disk is not found
Error from server (Forbidden): error when creating ".build/kubeflow-apps/v1_persistentvolume_mysql-pv.yaml": persistentvolumes "mysql-pv" is forbidden: error querying GCE PD volume kf-cluster-1-storage-metadata-store: disk is not found
make: *** [apply-kubeflow] Error 1
```

For context, here are the contents of the two yaml files in `.build/kubeflow-apps/` that are referenced in the error:

### v1_persistentvolume_minio-pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/name: minio
  name: minio-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: kf-cluster-1-storage-artifact-store
```

### v1_persistentvolume_mysql-pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: kf-cluster-1-storage-metadata-store
```

**Comment by scottcantreid** [comment]
This seems relevant to #1294 , which was closed a while back

**Comment by scottcantreid** [comment]
I was able get around this issue by manually creating disks with the required names (`kf-cluster-1-storage-metadata-store` and `kf-cluster-1-storage-artifact-store`). My kubeflow cluster is now live.

I'm leaving this issue open because the documentation for deploying a kubeflow cluster doesn't mention manually launching metadata and artifact-store disks. I imagine that these disks are meant to be created automatically when the user calls `make apply`.

**Comment by ElnazBigdeli** [comment]
@scottcantreid I am running to the same issue, and everything here is pretty new for me. Where should I create this disks?

**Comment by scottcantreid** [comment]
Hi @ElnazBigdeli, I used the google cloud console, though I suppose you could create the disk using the `gcloud` command line. Go to https://console.cloud.google.com/compute/disksAdd?_ga=2.211915472.577394515.1609777078-1867275885.1605660962 to create two new disks using the console. 
Some things to watch out for:
- Make sure that you give the disks enough space (I decided to give my 50 GB). 
- Make sure that you are in the same google cloud project as your kubeflow cluster
- Name one disk `{YOUR-CLUSTER-NAME}-storage-artifact-store`, name the other `{YOUR-CLUSTER-NAME}-storage-metadata-store`
- Make sure that both disks are created in the same region as your cluster.

**Comment by ElnazBigdeli** [comment]
@scottcantreid Thanks for your reply. I will try that. 
I have a side question, I have seen that we can create Kubeflow pipeline on GCP with specifying few things. That will create all the resources for my Kubeflow using AIplatform. My question is having this, should I through the process of deploying the Kubeflow on GCP based on the https://www.kubeflow.org/docs/gke/deploy/?

**Comment by scottcantreid** [comment]
I wasn't aware that google's AI Platform has a tool to automatically deploy a kubeflow cluster. The steps seem to be here: https://cloud.google.com/ai-platform/pipelines/docs/getting-started. This looks considerably simpler than following the "Kubeflow on GCP" guide, so I'd say it's worth trying to see if it works for you.

**Comment by ElnazBigdeli** [comment]
@scottcantreid Yes, I followed the steps and I created the pipeline. The only question I have in my mind is, if I could create the kubeflow pipeline that easy, that means I would have Kubeflow deployed. However, does this means I have limitations on using any  other services that Kubeflow provides like Katib?

**Comment by parthmishra** [comment]
I ran into this issue as well but for me, the issue stemmed from kubeflow deploying a regional cluster and not regional pds so they weren't found. 

I went back and modified my Makefile to use a single zone for LOCATION and ZONE values and then redeployed which resulted in a successful deployment of the cluster zonally. I believe regional deployments are not supported perhaps?
