### ISSUE TITLE
bundled cert-manager not compatible with Kubernetes <1.16

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/manifests#1705]
After looking into https://github.com/kubeflow/kubeflow/issues/5501#event-4181603464, it seems that the bundled cert-manager installation is not compatible with kubernetes versions lower than 1.16. According to https://cert-manager.io/docs/installation/kubernetes/. For version lower than 1.16 there is a [legacy installation](https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager-legacy.yaml) for cert-manager. 

I suggest that the kubernetes installation guide on the website make note of this, and possibly that a footnote is added to the compatibility chart regarding this issue.

I'd also like to suggest updating the cert-manager installation to v1.2 (currently v0.11 is used, the formatting of certificates has changed slightly I believe) and adding Kubernetes 1.20 to the compatibility chart as having no known issues (I have been running vanilla Kubeflow on 1.20 on-prem for a bit now and have not experienced any issues yet).

**Comment by yanniszark** [comment]
@DavidSpek I seriously doubt that's the case. We have successfully installed that cert-manager version (0.11) for quite some time now.

**Comment by DavidSpek** [comment]
@yanniszark Also 0.14? As that also has this issue related to it: https://github.com/jetstack/cert-manager/issues/2208. 
If the manifests are updated to use the latest version of cert-manager (v1.1), this issue is something we will run into as the docs state:
```
Note: If you’re using a Kubernetes version below v1.15 you will need to install the legacy version of the manifests. This version does not have API version conversion and only supports cert-manager.io/v1 API resources.
```
Though I think this has a type as there are 2 different CRD instructions given, one for 1.16+ and one for <1.16. This also brings up the issue I stated in https://github.com/kubeflow/website/pull/2451 about validating newer versions of Kubernetes.

**Comment by yanniszark** [comment]
As per: https://github.com/kubeflow/website/pull/2451#issuecomment-781601413
The bundled cert-manager IS compatible with K8s < 1.16

**Comment by DavidSpek** [comment]
@yanniszark Can cert-manager be updated in the manifests? Using version 0.11 instead of 1.2 seems a bit extreme.
