### ISSUE TITLE
[Manifests Distribution] Distribute and Sync kubeflow app manifests

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/manifests#1710]
From the wg-manifests meeting, we had some discussion about the work that how do we distribute kubeflow application manifests and sync them back to kubeflow/manifests repo.

As we discussed, the rough plan is:

0. Communicate with different wgs about the change
0.0. Define best practices and give an example
0.1. Open issues in respective repositories
1. Move manifests development for each application back to the application’s upstream repository
2. Create automation to sync and track manifests from upstream repos TO the manifests repo
3. Validate with e2e tests in the manifests repository

**Comment by Bobgy** [comment]
Sounds good to me

When do you plan to do step 0?
Manifest WG meetings are not friendly to my timezone, so I'd hope you can share a doc that people can collaborate offline.

**Comment by PatrickXYS** [comment]
@yanniszark I think we should have:

1. A fully-covered doc about Step 0
2. A Github Project which is created specifically for this manifest distribution project

Not sure if you have any documentation ready

**Comment by yanniszark** [comment]
@PatrickXYS thanks for opening the issue.

> When do you plan to do step 0?

@Bobgy next week is the goal.

> so I'd hope you can share a doc that people can collaborate offline.

Of course.

**Comment by yanniszark** [comment]
Superceded by:
https://github.com/kubeflow/manifests/issues/1735
