### ISSUE TITLE
Upgrade argo to 2.12

### ISSUE THREAD

**Issue by arllanos** [kubeflow/manifests#1722]
Part of kubeflow/pipelines#5017

Upgrade Argo from 2.3 to 2.12 so Pipelines can support separate artifact repository for each namespace (`artifactRepositoryRef` field in argo workflow manifest)

Note: Although `artifactRepositoryRef` feature seems to be available since 2.9 we are upgrading version 2.12 which will be LTS as mentioned [here](https://github.com/kubeflow/pipelines/issues/4649#issuecomment-763481043).

**Comment by yanniszark** [comment]
@arllanos this seems like an issue for the pipelines wg.
cc @Bobgy I think there is a similar issue in pipelines already. 
https://github.com/kubeflow/pipelines/issues/4553
