### ISSUE TITLE
about kfctl_k8s_istio.v1.2.0.yaml didnot have istio-crds istio-install?

### ISSUE THREAD

**Issue by 15162162323** [kubeflow/manifests#1727]
in this website: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

**Disabling istio installation - If your Kubernetes cluster has an existing Istio installation you may choose to not install Istio by removing the applications istio-crds and istio-install in the configuration file kfctl_k8s_istio.v1.2.0.yaml**
this context say removing istio-crds istio-install in kfctl_k8s_istio.v1.2.0.yaml ,but i did not see that.  
[offical version kfctl_k8s_istio.v1.2.0.yaml](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.v1.2.0.yaml) 
![image](https://user-images.githubusercontent.com/23089871/105953722-9d9fbe80-60ae-11eb-9751-4de69f7301d0.png)

**Comment by PatrickXYS** [comment]
It should be `istio-1-3-1-stack`, you need to dig into it and remove istio related installation

**Comment by 15162162323** [comment]
thanks


| |
侯海涛
|
|
15162162323@163.com
|
签名由网易邮箱大师定制
On 1/28/2021 01:07，Yao Xiao<notifications@github.com> wrote：

It should be istio-1-3-1-stack, you need to dig into it and remove istio related installation
