### ISSUE TITLE
Xgboost controller is going to error state due to wrong CRD file

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/manifests#1728]
xgboost controller is failing with the below reason

`{"level":"error","ts":1611742542.4809206,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}`

manifest CRD(https://github.com/kubeflow/manifests/blob/master/xgboost-job/xgboost-operator/base/crd.yaml & https://github.com/kubeflow/manifests/blob/v1.2-branch/xgboost-job/xgboost-operator/base/crd.yaml )  should be updated with https://github.com/kubeflow/xgboost-operator/blob/master/config/crds/xgboostjob.kubeflow.org_xgboostjobs.yaml

**Comment by yanniszark** [comment]
@hemantha-kumara thanks for the report. As part of 1.3, the source of truth for manifests will become each app's upstream repo. As such, this issue will be fixed in 1.3.

/priority p1

**Comment by yanniszark** [comment]
@hemantha-kumara an update on this. XGBoost manifests now live in the respective upstream app repo:
https://github.com/kubeflow/xgboost-operator/tree/master/manifests

**Comment by hemantha-kumara** [comment]
@yanniszark  looks like crd.yaml is not correct
I am getting the below error
```
{"level":"info","ts":1616507584.3887925,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1616507584.3891013,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1616507585.743865,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1616507585.7442534,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1616507585.744295,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1616507585.7444658,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1616507585.7445085,"logger":"controller","msg":"Running controller in in-cluster mode"}
there is an error for the input config
{"level":"info","ts":1616507585.7447307,"logger":"controller","msg":"gang scheduling is set: ","gangscheduling":false}
{"level":"info","ts":1616507585.7448194,"logger":"entrypoint","msg":"setting up webhooks"}
{"level":"info","ts":1616507585.74483,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1616507585.7450688,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1616507585.745186,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"xgboostjob-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1616507588.5953572,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"XGBoostJob.xgboostjob.kubeflow.org","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477"}
{"level":"error","ts":1616507588.595602,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

**Comment by hemantha-kumara** [comment]
https://github.com/kubeflow/xgboost-operator/blob/master/manifests/base/kustomization.yaml 
```
- name: gcr.io/kubeflow-images-public/xgboost-operator
  newName: gcr.io/kubeflow-images-public/xgboost-operator
  newTag: vmaster-g56c2c075
```

the above docker is having changes to work with xgboost crd version v1 but  the crd present in the URL https://github.com/kubeflow/xgboost-operator/blob/master/manifests/base/crd.yaml is having v1alpha1

**Comment by hemantha-kumara** [comment]
Changing the docker version to `gcr.io/kubeflow-images-public/xgboost-operator:v0.1.0` should solve the issue. But this is only a workaround not the fix for the issues present in the xgboost-operator repo
https://github.com/kubeflow/xgboost-operator/issues/108
https://github.com/kubeflow/xgboost-operator/issues/92

**Comment by yanniszark** [comment]
@hemantha-kumara I opened an issue in the xgboost-controller repo, since it;s their issue.
Let's continue there: https://github.com/kubeflow/xgboost-operator/issues/115
