### ISSUE TITLE
Xgboost example error with CRD v1 version

### ISSUE THREAD

**Issue by Focke-Wulf** [kubeflow/manifests#1729]
<img width="1105" alt="2021-01-28 1 33 16" src="https://user-images.githubusercontent.com/26343300/106094933-d8b4f700-616d-11eb-9b4d-83dcb75607b1.png">

Hello 
as this log shows the problem when I am trying to use  iris dataset example. 

I have already updated v1 crd . and still have this problem

**Comment by yanniszark** [comment]
Hi @Focke-Wulf. Could you raise this issue in the XGBoost operator repo?
They will be able to help you resolve your issue.
