### ISSUE TITLE
Uber Issue: Manifests WG Steps for release 1.3

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1735]
## Intro

I know that many are eager to track the progress of the manifests working group,
so I'm opening this issue to document the plan, as was presented in the
wg-manifests meeting on 2021/02/05
([recording](https://drive.google.com/file/d/1_7Se0CoSyEWrI_R9A2W3gtVDorFjwkdd/view?usp=sharing)).

More details about the mission of wg-manifests can be found in its charter:
https://github.com/kubeflow/community/blob/master/wg-manifests/charter.md

## Plan

This plan will be updated regularly.

### Step 1: Migrate Manifests to a new Folder Structure

Currently, the manifests repo is a flat namespace with everything mangled.
We plan to reorganize the folder structure into sections that will reflect the
following properties:
- Applications with their source code in upstream KF maintained by Kubeflow WGs (e.g., notebook-controller)
- Common services (Dex, Istio, Cert-Manager, KNative), maintained by the
  Manifests WG.
- Applications contributed by community members, not owned by any Kubeflow WG.
- Distribution-specific manifests (kfdef, stacks, aws, gcp, etc.). The goal is
  for this folder to become empty in subsequent releases.

Issue: https://github.com/kubeflow/manifests/issues/1738

### Step 2: Consolidate manifests development upstream

Consolidate manifests development upstream. Move all manifests from
`kubeflow/manifests` to their respective upstream repos.

To give an example from the `notebook-controller`, the diagram shows the current
situation. Manifests are in two repos, blurring separation of responsibilities
and making things harder for application developers.

![diagram_1](https://user-images.githubusercontent.com/6123106/107092187-c9881600-680b-11eb-9993-fc04c5e5b6dd.PNG)

Instead, we will copy all manifests from the manifests repo back to each
upstream's repo. From there, they will be imported in the manifests repo. The
following diagram presents the desired state:

![diagram_2](https://user-images.githubusercontent.com/6123106/107092197-cd1b9d00-680b-11eb-8123-7fa5424c5cb2.PNG)

Issue: https://github.com/kubeflow/manifests/issues/1740

### Step 3: Upgrade Istio

The manifests working group is responsible for certain common services (Dex,
Istio, Cert-Manager, KNative). Out of those, we plan to provide a newer version
of Istio, to leverage the new AuthorizationPolicy API that will be supported
across the board in 1.3.

The work to refactor every component to use Istio AuthorizationPolicy is tracked
in https://github.com/kubeflow/kubeflow/issues/5313#issuecomment-762271002.

Issue: https://github.com/kubeflow/manifests/issues/1753

### Step 4: Consolidate manifests with multiple versions into 1

Some manifests (e.g., notebooks controller, katib) have multiple versions. Take
the example of `notebook-controller`:

![diagram_3](https://user-images.githubusercontent.com/6123106/107092215-d86ec880-680b-11eb-9705-e6fd25891104.PNG)

There are the following versions of manifests:
- The ones living in the upstream repo, used in development and testing.
- The `base` and `overlays` folders, in `kubeflow/manifests`. These were
  optimized to work with `kfctl`'s kustomization combination magic.
- The `base_v3` folder, designed to eschew vars and be buildable with
  `kustomize`. It imports files from `base`.

There is no need for such complexity and duplication. We will provide an example
(of the notebook-controller) and guide for how to consolidate them into a
proposed structure.

## Deadlines

| Date | Steps |
| - | - |
| 2021/02/09 | Steps 1-3 |

## Common Questions

- **Q:** Will `kfctl` be supported? \
  **A:** Kubeflow applications publish kustomize packages. Any tool that can
  work with kustomizations should work. Manifests are not tied to any specific
  deployment tool and more information on `kfctl` development can be found in
  the [deployments-wg](https://github.com/kubeflow/community/blob/master/wg-deployment/charter.md).

- **Q:** What Istio version will be included? \
  **A:** Will be decided as part of step (3) of the plan above. In principle,
  you can use any version of your choosing, as long as it supports
  AuthorizationPolicy (1.4+).

cc @kubeflow/wg-manifests-leads

**Comment by Bobgy** [comment]
This is absolutely awesome! Thank you so much for driving these! @yanniszark

**Comment by Jeffwan** [comment]
> From there, they will be imported in the manifests repo

What's the best practice to manage versions? Not all projects use exact same version syntax as kubernetes versions.. for example, some training operator doesn't have v1.2-branch or v1.3-branch. I assume it's WG owner's responsibility to choose which version goes to kubeflow/manifest just like we did?

**Comment by marziman** [comment]
2 comments here:
- @yanniszark Why not using a newer version of Istio 1.9, instead of 1.6?
The breaking change will be Authz policies,
and the rest can be upgrade without issues. Istio is providing a new update mechanism, which makes it easier to upgrade

- @Jeffwan Ithink using a version repo might be also a good idea to have a unified versioning with semver

**Comment by yanniszark** [comment]
> What's the best practice to manage versions? Not all projects use exact same version syntax as kubernetes versions.. for example, some training operator doesn't have v1.2-branch or v1.3-branch. I assume it's WG owner's responsibility to choose which version goes to kubeflow/manifest just like we did?

@Jeffwan Exactly. I know some apps follow different versioning / release schemes. The respective WG owner is responsible for choosing the version the want to include.

> Why not using a newer version of Istio 1.9, instead of 1.6?

The version hasn't been decided yet. Please check the last section (Common Questions) in the first message.

**Comment by yanniszark** [comment]
All steps completed, closing issue.
