### ISSUE TITLE
Step 2: Move manifests development upstream

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1740]
Part-of: https://github.com/kubeflow/manifests/issues/1735
Depends-on: https://github.com/kubeflow/manifests/issues/1738

### Background

As part of the work of wg-manifests for 1.3 (https://github.com/kubeflow/manifests/issues/1735), we are moving manifests development in upstream repos. This is the second step of our plan for 1.3.

### Current State

Applications have manifests in two places:
- In their upstream repos.
- In the manifests repo.

This is a table of every KF app in manifests, along with its upstream repo and the folder in the upstream repo where authors currently store manifests:

| Application | Manifests Path | Upstream Path | Upstream Repo |
| --- | --- | --- | --- |
| TFJob Operator | apps/tf-training/upstream | manifests | https://github.com/kubeflow/tf-operator |
| PyTorch Operator | apps/pytorch-job/upstream | manifests | https://github.com/kubeflow/pytorch-operator |
| MPI Operator | apps/mpi-job/upstream | manifests | https://github.com/kubeflow/mpi-operator |
| MXNet Operator | apps/mxnet-job/upstream | manifests | https://github.com/kubeflow/mxnet-operator |
| XGBoost Operator | apps/xgboost-job/upstream | manifests | https://github.com/kubeflow/xgboost-operator |
| Kubebench | apps/kubebench/upstream | manifests | https://github.com/kubeflow/kubebench |
| Notebook Controller | apps/jupyter/notebook-controller/upstream | components/notebook-controller/config | https://github.com/kubeflow/kubeflow |
| Central Dashboard | apps/centraldashboard/upstream | components/centraldashboard/manifests | https://github.com/kubeflow/kubeflow |
| Profiles + KFAM | apps/profiles/upstream | components/profile-controller/config | https://github.com/kubeflow/kubeflow |
| PodDefaults Webhook | apps/admission-webhook/upstream | components/admission-webhook/manifests | https://github.com/kubeflow/kubeflow |
| Jupyter Web App | apps/jupyter/jupyter-web-app/upstream | components/crud-web-apps/jupyter/manifests | https://github.com/kubeflow/kubeflow |
| Katib | apps/katib/upstream | manifests/v1beta1 | https://github.com/kubeflow/katib |
| KFServing | apps/kfserving/upstream | config | https://github.com/kubeflow/kfserving |
| Kubeflow Pipelines | apps/pipeline/upstream | manifests/kustomize | https://github.com/kubeflow/pipelines |

### Desired State

Consolidate all manifests development in the upstream repo. The manifests repo will include a copy of the manifests under the relevant folder.

**Comment by yanniszark** [comment]
I will use the following table to track the progress of issues / PRs:


| Application | WG | Issue | PR |
| --- | --- | --- | --- |
| TFJob Operator | kubeflow/wg-training-leads | https://github.com/kubeflow/tf-operator/issues/1246 | :x: |
| PyTorch Operator | kubeflow/wg-training-leads | https://github.com/kubeflow/pytorch-operator/issues/318 | :x: |
| MPI Operator | kubeflow/wg-training-leads | https://github.com/kubeflow/mpi-operator/issues/325 | :x: |
| MXNet Operator | kubeflow/wg-training-leads | https://github.com/kubeflow/mxnet-operator/issues/88 | :x: |
| XGBoost Operator | kubeflow/wg-training-leads | https://github.com/kubeflow/xgboost-operator/issues/109 | :x: |
| Kubebench | kubeflow/wg-training-leads | https://github.com/kubeflow/kubebench/issues/216 | :x: |
| Notebook Controller | kubeflow/wg-notebooks-leads | https://github.com/kubeflow/kubeflow/issues/5592 | :x: |
| Central Dashboard | kubeflow/wg-notebooks-leads | https://github.com/kubeflow/kubeflow/issues/5594 | :x: |
| Profiles + KFAM | kubeflow/wg-notebooks-leads | https://github.com/kubeflow/kubeflow/issues/5595 | :x: |
| PodDefaults Webhook | kubeflow/wg-notebooks-leads | https://github.com/kubeflow/kubeflow/issues/5596 | :x: |
| Jupyter Web App | kubeflow/wg-notebooks-leads | https://github.com/kubeflow/kubeflow/issues/5593 | :x: |
| Katib | kubeflow/wg-automl-leads | https://github.com/kubeflow/katib/issues/1431 | :x: |
| KFServing | kubeflow/wg-serving-leads | :x: | :x: |
| Kubeflow Pipelines | kubeflow/wg-pipeline-leads | :x: | :x: |

**Comment by juliusvonkohout** [comment]
@yanniszark i noticed that e.g. https://github.com/kubeflow/manifests/tree/master/apps/pipeline/upstream/mysql/base is a bit outdated compared to the real upstream manifests. Will you update all manifestes before the 1.3 release or link on the filesystem level to  the upstream repositories?

**Comment by yanniszark** [comment]
@juliusvonkohout exactly, please follow this issue for the work of syncing manifests:
https://github.com/kubeflow/manifests/issues/1775

Closing this issue as it is complete
