### ISSUE TITLE
private GKE

### ISSUE THREAD

**Issue by gregbarkerdcsg** [kubeflow/manifests#1745]
Following these instructions to deploy to a private GKE cluster - https://www.kubeflow.org/docs/gke/private-clusters/

We ended up with these additional changes:

gcp/v2/privateGKE/cluster-private-patch.yaml
* add nodeLocations attribute for regional clusters configurable with kpt setter
* make enablePrivateEndpoint configurable with kpt setter
* make masterIpv4CidrBlock configurable with kpt setter
* add ContainerCluster required attribute `masterGlobalAccessConfig.enabled` configurable with kpt setter
* remove invalid attributes `ipAllocationPolicy.useIpAliases` and `ipAllocationPolicy.createSubnetwork`.
* add `networkingMode: VPC_NATIVE` instead of `ipAllocationPolicy.useIpAliases`

gcp/v2/privateGKE/firewall.yaml
* ranges to keep in sync with masterIpv4CidrBlock in container-cluster using the same kpt-setter

There ares some related issues in the gcp blueprints repo: 
* https://github.com/kubeflow/gcp-blueprints/issues/33
* https://github.com/kubeflow/gcp-blueprints/issues/32
* https://github.com/kubeflow/gcp-blueprints/issues/191

**Comment by zsatterfield** [comment]
How did you add in the following:

> add ContainerCluster required attribute masterGlobalAccessConfig.enabled configurable with kpt setter

I have tried to do it several ways in our attempt to automate the deployment using Terraform, but I end up with one of the two following errors:

> The ContainerCluster "" is invalid: spec.privateClusterConfig.masterGlobalAccessConfig: Invalid value: "string": spec.privateClusterConfig.masterGlobalAccessConfig in body must be of type object: "string"

> The ContainerCluster "" is invalid: spec.privateClusterConfig.masterGlobalAccessConfig: Invalid value: "boolean": spec.privateClusterConfig.masterGlobalAccessConfig in body must be of type object: "boolean"

**Comment by gregbarkerdcsg** [comment]
Set it with `kpt cfg set`. For example:
`kpt cfg set distributions/gcp master-global-access-enabled true`
Confirm with:
`kpt cfg list-setters distributions/gcp master-global-access-enabled`
