### ISSUE TITLE
Step 3: Upgrade Istio

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1753]
Umbrella Issue: https://github.com/kubeflow/manifests/issues/1735

The manifests working group is responsible for certain common services (Dex,
Istio, Cert-Manager, KNative). Out of those, we plan to provide a newer version
of Istio, to leverage the new AuthorizationPolicy API that will be supported
across the board in 1.3.

The work to refactor every component to use Istio AuthorizationPolicy is tracked
in kubeflow/kubeflow#5313 (comment).

**Comment by pvaneck** [comment]
Istio 1.9 docs mention compatibility with K8s 1.17 - 1.20. Is it safe to say that those deploying KF 1.3 with the manifests in this repo should have at least K8s 1.17?

**Comment by dpaks** [comment]
@yanniszark Istio AuthorizationPolicy is something that I was longing for some time

**Comment by yanniszark** [comment]
> Istio 1.9 docs mention compatibility with K8s 1.17 - 1.20. Is it safe to say that those deploying KF 1.3 with the manifests in this repo should have at least K8s 1.17?

@pvaneck I have tested with Kubernetes 1.16 successfully! So I am confident that there won't be a problem there as well.

**Comment by jidemoski** [comment]
/help
What time can we upgrade istio? I need the new version to upgrade the server. Beauseof  tha envoyfilter can't support subdomain auth
