### ISSUE TITLE
Update Knative version

### ISSUE THREAD

**Issue by pvaneck** [kubeflow/manifests#1754]
The current version of Knative is 0.14.3. With Istio being updated soon (https://github.com/kubeflow/manifests/issues/1753), we should also update the versions for Knative serving/eventing to ensure that they work with the new Istio once it lands.

Not sure which version yet, as it will likely depend on the minimum Kubernetes version we decide to support. This issue can be used to track progress on the Knative front.

**Comment by yanniszark** [comment]
@pvaneck thanks for opening an issue to track a future KNative upgrade.
I want to also stress though, that I have tried running KFServing examples with the older KNative serving v0.11 and Istio 1.9 and everything worked fine! Thus, I don't expect this to be a blocker.
That said, I agree that it's good to keep our dependencies up-to-date.

**Comment by pvaneck** [comment]
@yanniszark Ah good to hear that KFServing worked with even Knative v0.11. From what I've gathered, some KFServing features might need newer versions of Knative-eventing, so probably worth giving both serving and eventing a bump. I did the update from 0.11 to 0.14.3, so I can handle the next update if need be.

**Comment by danishsamad** [comment]
@pvaneck Any reason for not updating to ver 0.18 (or higher) instead of 0.17? There seem to be a few config options in 0.18 that may come in handy in case of serving.

**Comment by pvaneck** [comment]
@danishsamad I was basing the selected release on the [Knative release principles](https://knative.dev/community/contributing/mechanics/release-versioning-principles/#knative-serving-version-table)  and the desire to ensure compatibility for K8s 1.16 and above since some users are still on 1.16. However once the PR is merged it should be easier for end users to integrate newer versions of Knative themselves since it largely is the same as what one would get upstream with only a few small patches.

**Comment by DavidSpek** [comment]
Personally, I don't think we should bother with trying to have backwards support for unsupported version of Kubernetes. Trying to support old versions of Kubernetes might end up hurting support for the latest version. There of course needs to be a balance between the two, but I think most cloud providers and other software support the latest version of Kubernetes and the 2/3 previous ones, so that would be 1.21, 1.20, 1.19 (and for "legacy" users 1.18).
