### ISSUE TITLE
spartakus-volunter uses incomaptible image

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#1757]
```
  Warning  Failed     10s (x5 over 48s)  kubelet, minikube  Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root (pod: "spartakus-volunteer-558f8bfd47-v56qd_kubeflow(06a28722-0634-446b-96c0-1e3ee3ea0d54)", container: volunteer)
```
This happens because https://github.com/kubeflow/manifests/blob/master/contrib/spartakus/base/deployment.yaml uses gcr.io/google_containers/spartakus-amd64:v1.1.0

The fix is very simple. You just have to add USER xxxx where xxxx != 0 at the end of the dockerfile.
The spartakus project seems to be not longer maintained https://github.com/kubernetes-retired/spartakus
Is there a new upstream project?

If not we could also just a securitycontext to the deployment
```
kubectl -n kubeflow edit deployment spartakus-volunteer 
...
        image: gcr.io/google_containers/spartakus-amd64:v1.1.0
        imagePullPolicy: IfNotPresent
        name: volunteer
        securityContext:
          runAsUser: 1007550000
...

Please tell me whether i should create a merge request.

**Comment by PatrickXYS** [comment]
I think we can move forward with removing sparktakus for short-term fix since it's not maintained

**Comment by juliusvonkohout** [comment]
> I think we can move forward with removing sparktakus for short-term fix since it's not maintained

Alright, how shall we proceed? Should I make a pull request or do you want to?

**Comment by PatrickXYS** [comment]
Feel free to send a PR for fixing, you can cc me for review

**Comment by juliusvonkohout** [comment]
@PatrickXYS 

I do not think that what you suggested in the pull request is the right way to do it. spartakus is installed in https://github.com/kubeflow/manifests/blob/81e5fb6fbcd159a89d9d20ecdc510aed3354f024/distributions/kfdef/kfctl_k8s_istio.yaml#L209
We should remove it there.
It has already been removed from the dex version. 

Sadly the non-dex version in master is currently broken 
```
kfctl exited with error: failed to build kfApp from URI https://raw.githubusercontent.com/kubeflow/manifests/master/distributions/kfdef/kfctl_k8s_istio.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: Kustomize generate failed:  (kubeflow.error): Code 500 with message: couldn't copy application istio-crds: lstat /home/julius/kf_deployments/kf1/.cache/manifests/manifests-master/istio/istio-crds: no such file or directory
```

The same command works with the istio+dex version.

**Comment by juliusvonkohout** [comment]
For me it is totally fine to just remove it for plain kubernetes at the moment. So what you call on premises. If you do not have any objections, I will just remove it in that single file.

**Comment by PatrickXYS** [comment]
I don't have objections, but if we only target on-prem manifests, that should be fine.
