### ISSUE TITLE
Resolve pkg inconsistency between ksonnet and manifests.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#176]
Seems now ksonnet has more pkgs than manifests.
including:
- [ ] nvidia-inference-server
- [ ] pachyderm
- [x] seldon
- [ ] spark
- [ ] tf-batch-predict
- [ ] tf-serving

And under pkg `gcp` manifests still missing:
- [ ] google-cloud-filestore-pv
- [ ] metric-collector
- [x] prometheus

Training components:
- [ ] chainer
- [ ] MPI
- [ ] Mxnet
- [ ] XGBoost

**Comment by jlewi** [comment]
@kunmingg Can we split this into multiple issues it will make it easier to track.

* tf-serving

   * I don't think we need a kustomize package for this; users can just create the YAML spec directly.
   * We should probably just add docs/examples with the spec.

* nvidia-inference-server
 
   * Same argument as for TFServing; I think the better pattern is to just provide example YAML specs which users can copy and edit

   * /cc @pdmack 

#122 for spark-operator

* tf-batch-predict
   
   * This code probably needs to be updated so I don't think its 0.6 blocking.

**Comment by jlewi** [comment]
#10 for Seldon Core.

**Comment by jlewi** [comment]
#18 for TFServing

**Comment by kunmingg** [comment]
For monitoring / prometheus:
https://github.com/kubeflow/manifests/issues/183

**Comment by sarahmaddox** [comment]
>tf-serving
>I don't think we need a
> * package for this; users can just create the YAML spec directly.
> * We should probably just add docs/examples with the spec.

Please would you add the instructions to this doc, including example of YAML file:
https://www.kubeflow.org/docs/components/serving/tfserving_new/

**Comment by jlewi** [comment]
Thanks @sarahmaddox 
Filed kubeflow/website#958

**Comment by jlewi** [comment]
kubeflow/website#959 for nvidia inference server

**Comment by jlewi** [comment]
kubeflow/website#842 for updating cloud filestore

**Comment by jlewi** [comment]
#227 for mpi job

**Comment by jlewi** [comment]
#228 for mxnet

**Comment by jlewi** [comment]
#229 for xgboost

**Comment by jlewi** [comment]
#230 for prometheus
#231 for metrics collector

**Comment by jlewi** [comment]
#232 for chainer

**Comment by jlewi** [comment]
#233 for pachyderm

**Comment by jlewi** [comment]
Closing this issue since we now have individual issues.
