### ISSUE TITLE
Decouple 3rd Party Components of Kubeflow

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/manifests#1760]
Greetings,

Its great that Kubeflow uses tech like Dex, Istio, Tekton Pipelines, Knative, Argo, etc.

Instead of bundling a specific version of these components (an ANTI PATTERN) instead, provide instructions defining these as pre-requisites or install them from their well known distribution locations (Helm, OperatorHub, etc.) followed by customization as needed by Kubeflow.  The current kustomize capability is poorly described, poorly laid out on disk, and poorly documented as to how customizations should occur - it represents a NON standard way to deploy Dex, Istio, Tekton, Knative, etc.

If any of these products ends up with a security problem requiring immediate patching, it is unclear how a user is supposed to apply a patch when you've locked up the mechanism for deployment as well as hiding the underlying versions from customers.

As of now, Kubeflow 1.2.0 is a non-starter because its components are vulnerable to attack and the versions supported in Kubeflow are no longer supported by the individual product groups - it is unclear if bugs being reported are due to old versions of components or defects in the Kubeflow core.

The current approach is untenable when maintenance of an operational system is concerned.

**Comment by thesuperzapper** [comment]
Absolutely, this is currently proposed in https://github.com/kubeflow/community/issues/460

The work to refactor the kubeflow/manifests repo https://github.com/kubeflow/community/issues/460, should help with the unbundling work.
