### ISSUE TITLE
Keycloak Gatekeeper has been deprecated

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/manifests#1766]
The manifests located at https://github.com/kubeflow/manifests/tree/master/common/dex-auth/keycloak-gatekeeper use `keycloak/keycloak-gatekeeper:5.0.0`. This registry has not been updated in two years and is EOL and no longer maintained. References to this registry have recently also been removed from the keycloak-containers repository: https://github.com/keycloak/keycloak-containers/commit/74d301c5fe3d44bb6d4671deac1691dcdd2346cf. 

Is this component currently used? If so, how should we go about replacing it with something that is actively maintained? If not, can we delete the keycloak folder from the repository?

**Comment by yanniszark** [comment]
@DavidSpek I have moved Gatekeeper under `contrib`, since it is not maintained by the Manifests WG.
I don't think any distribution was using it anyway. Should we close this issue now that it was placed under the `contrib` folder, which comes with no guarrantees?

**Comment by DavidSpek** [comment]
Sorry for the late response, GitHub notifications were a bit hectic and I missed this one. Sounds good to me. 

/close
