### ISSUE TITLE
openshift deploy

### ISSUE THREAD

**Issue by 912988434** [kubeflow/manifests#1770]
Hello, would you like to know whether to deploy on OpenShift 4.6 using https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift.v1.2.0.yaml file or using  https://github.com/opendatahub-io/manifests/blob/v1.0-branch-openshift/kfdef/kfctl_openshift.yaml?

**Comment by PatrickXYS** [comment]
The openshifthub one should be built on top of kubeflow one

Openshift should have some doc/official page for deploying kubeflow
