### ISSUE TITLE
Release 1.3 - Sync manifests from upstream repos

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1775]
In order to cut the 1.3 release, we need to sync manifests from the upstream repos. For this reason, the manifests wg needs to gather the git revisions from each upstream repo, in order to sync them here.

| Application | Manifests Path | Upstream Path | Upstream Repo | Revision |
| --- | --- | --- | --- | --- |
| TFJob Operator | apps/tf-training/upstream | manifests | https://github.com/kubeflow/tf-operator | `v1.1.0 ` |
| PyTorch Operator | apps/pytorch-job/upstream | manifests | https://github.com/kubeflow/pytorch-operator | `v0.7.0` |
| MPI Operator | apps/mpi-job/upstream | manifests | https://github.com/kubeflow/mpi-operator | `b367aa55886d2b042f5089df359d8e067e49e8d1` |
| MXNet Operator | apps/mxnet-job/upstream | manifests | https://github.com/kubeflow/mxnet-operator | `v1.1.0` |
| XGBoost Operator | apps/xgboost-job/upstream | manifests | https://github.com/kubeflow/xgboost-operator | `v0.2.0` |
| Notebook Controller | apps/jupyter/notebook-controller/upstream | components/notebook-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Central Dashboard | apps/centraldashboard/upstream | components/centraldashboard/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Profiles + KFAM | apps/profiles/upstream | components/profile-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| PodDefaults Webhook | apps/admission-webhook/upstream | components/admission-webhook/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Jupyter Web App | apps/jupyter/jupyter-web-app/upstream | components/crud-web-apps/jupyter/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Volumes Web App | apps/volumes-web-app | components/crud-web-apps/volumes/manifests | https://github.com/kubeflow/kubeflow |  `origin/v1.3.0-rc.0` |
| Tensorboards Web App | apps/tensorboard/tensorboards-web-app | components/crud-web-apps/tensorboards/manifests | https://github.com/kubeflow/kubeflow |  `origin/v1.3.0-rc.0` |
| Tensorboard Controller | apps/tensorboard/tensorboard-controller | components/tensorboard-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Katib | apps/katib/upstream | manifests/v1beta1 | https://github.com/kubeflow/katib | `v0.11.0` |
| KFServing | apps/kfserving/upstream | config | https://github.com/kubeflow/kfserving | `e189a510121c09f764f749143b80f6ee6baaf48b` |
| Kubeflow Pipelines | apps/pipeline/upstream | manifests/kustomize | https://github.com/kubeflow/pipelines | `1.5.0-rc.0` |

**Comment by yanniszark** [comment]
cc @kubeflow/wg-automl-leads 
cc @kubeflow/wg-deployment-leads 
cc @kubeflow/wg-manifests-leads 
cc @kubeflow/wg-notebooks-leads 
cc @kubeflow/wg-pipeline-leads 
cc @kubeflow/wg-serving-leads 
@kubeflow/wg-training-leads

**Comment by Bobgy** [comment]
For KFP, let's use https://github.com/kubeflow/pipelines/releases/tag/1.5.0-rc.0 first, and we'll do another release after the remaining last minute fixes are in.

**Comment by andreyvelich** [comment]
For Katib we can take: https://github.com/kubeflow/katib/tree/v0.11.0. This is the tag for Katib 0.11 release.

**Comment by pvaneck** [comment]
For KFServing, can sync with the latest commit on this branch: https://github.com/kubeflow/kfserving/tree/release-0.5 (https://github.com/kubeflow/kfserving/commit/e189a510121c09f764f749143b80f6ee6baaf48b).

**Comment by PatrickXYS** [comment]
For tf-operator, we can use latest commit `f564bce4ac856d347ef1e3f8b131d10740d54972` (https://github.com/kubeflow/tf-operator/commit/f564bce4ac856d347ef1e3f8b131d10740d54972)

**Comment by Jeffwan** [comment]
> For tf-operator, we can use latest commit `f564bce4ac856d347ef1e3f8b131d10740d54972` ([kubeflow/tf-operator@f564bce](https://github.com/kubeflow/tf-operator/commit/f564bce4ac856d347ef1e3f8b131d10740d54972))

em. I doubt we want to use master commit in official release. Let's have another check if we want to cut a tag and use it in release.

**Comment by ChanYiLin** [comment]
@Jeffwan tf-operator's  e2e tests has covered almost every use case, if the commit can pass the case, then I believe we can use the one.

**Comment by DavidSpek** [comment]
@yanniszark It seems like you are missing some of the things from the `kubeflow/kubeflow` repo. 


Application | Manifests Path | Upstream Path | Upstream Repo | Revision
-- | -- | -- | -- | --
Volumes Web App | **Missing** | components/crud-web-apps/volumes/manifests | https://github.com/kubeflow/kubeflow |  
Tensorboards Web App | **Missing** | components/crud-web-apps/tensorboards/manifests | https://github.com/kubeflow/kubeflow |  
Tensorboard Controller | **Missing** | components/tensorboard-controller/config | https://github.com/kubeflow/kubeflow |

**Comment by yanniszark** [comment]
@DavidSpek thanks! Including them now...

**Comment by yanniszark** [comment]
Thanks @DavidSpek, I included the components.
An update on this, Jiaxin will coordinate with @kubeflow/wg-training-leads and provide revisions for the training operators.

**Comment by Jeffwan** [comment]
> @Jeffwan tf-operator's e2e tests has covered almost every use case, if the commit can pass the case, then I believe we can use the one.

Double check with Yao and seem we don't necessary to use tag here since it is for manifest sync. We just need to make image tag in that commit correct. Agree to use commit directly

**Comment by Jeffwan** [comment]
@kubeflow/wg-training-leads Hi team, I give manifest or tag id for all training operators. Please have a check. 
For Tf and MPI, I just attach latest master commit. This doesn't mean we will release latest master in v1.3.  For rest of the repos and I did some test and cut a new release. 

It means the image tag we defined in manifest in that commit will be deployed in v1.3. For example. 

https://github.com/kubeflow/tf-operator/blob/f564bce4ac856d347ef1e3f8b131d10740d54972/manifests/overlays/kubeflow/kustomization.yaml#L12-L13

https://github.com/kubeflow/mpi-operator/blob/b367aa55886d2b042f5089df359d8e067e49e8d1/manifests/base/kustomization.yaml#L16-L18

Please let me know if there're concerns or questions
