### ISSUE TITLE
How to update kubeflow from 1.0.2 to 1.2.0?

### ISSUE THREAD

**Issue by asahnovskiy** [kubeflow/manifests#1781]
Are any docs/tutorials on how to update kubeflow without losing data for Minio and MySql?

**Comment by yanniszark** [comment]
@asahnovskiy I don't think we have any such guides. What distribution are you using?
Perhaps the people involved there will be interested to help you migrate.

**Comment by asahnovskiy** [comment]
@yanniszark I use kfctl_istio_dex.v1.0.2.yaml. Basically, I want to update to 1.2.0 with PV's from currently version 1.0.2 which are used, without losing data, if it is possible.
