### ISSUE TITLE
Bundling of Istio & Cert-manager with Kubeflow Manifests

### ISSUE THREAD

**Issue by munagekar** [kubeflow/manifests#1796]
Kubeflow Manifests should NOT bundle Istio & Cert-Manager, instead these could be listed as dependencies along with recommended versions. Both these applications are distributed as helm charts and can be installed independently. 

Installation of Kubeflow on existing clusters is difficult if istio & cert-manager already exist. This would also make it possible to upgrade istio & cert-manager independently on such clusters.

**Comment by yanniszark** [comment]
Hi @munagekar! We have detailed instructions on how to install each Kubeflow component and common service here:
https://github.com/kubeflow/manifests#install-individual-components
If you want to customize your installation, skip the components (e.g., Istio) you don't want and install your own.

**Comment by munagekar** [comment]
@yanniszark Thank you for your response. I tried this out with Kubeflow 1.2 and it didn't work. I will try this out with Kubeflow 1.3.
