### ISSUE TITLE
Distributions: Readiness for 1.3 Kubeflow Release

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1798]
### Problem Statement

We have a 6 step plan for releasing Kubeflow 1.3: https://github.com/kubeflow/manifests/issues/1777
This issue is for the 6th step: distributions use instructions from wg-manifests for how to use kustomizations and create distributions for 1.3.

| Distribution | Owners | Readiness for 1.3 |
| - | - | - |
| Arrikto EKF | @kubeflow/arrikto | ✔️  |
| Arrikto MiniKF | @kubeflow/arrikto | ✔️  |
| Azure | @kubeflow/azure | :x: |
| AWS | @kubeflow/aws | ✔️  |
| Charmed Kubeflow | @RFMVasconcelos | ✔️  |
| Google Cloud | @kubeflow/google | ✔️ |
| IBM | @kubeflow/ibm | ✔️  |
| Kubeflow on MicroK8s | @RFMVasconcelos | ✔️  |
| Kubeflow Operator | @kubeflow/red-hat | ✔️  |
| Kubeflow with Argo CD | @DavidSpek | ✔️  |
| kfctl_istio_k8s | | Support dropped, remove from docs |
| kfctl_istio_dex | | Support dropped, remove from docs |
| Openshift | @kubeflow/red-hat | ✔️  |

Distributions should have owners and update their process/docs for 1.3 installations.

Distributions can use the instructions for installing Kubeflow 1.3 components and common services, provided by wg-manifests, to perform their integration:
https://github.com/kubeflow/manifests/tree/v1.3.0-rc.0#readme

I would like to ask all distribution owners to check-in in this issue to confirm that they will support their distributions for Kubeflow 1.3.

Current Issues:
- [x] https://github.com/kubeflow/kubeflow/issues/5813
- [x] https://github.com/kubeflow/manifests/issues/1810
- [x] https://github.com/kubeflow/kubeflow/issues/5821
- [x] https://github.com/kubeflow/kubeflow/issues/5814
- [x] https://github.com/kubeflow/manifests/issues/1812

**Comment by DavidSpek** [comment]
Guess you can add Kubeflow On-Prem/ArgoFlow/Argo CD to this list with https://github.com/kubeflow-onprem/ArgoFlow and status Ready. 
/cc @jtfogarty @tbaums @RFMVasconcelos

**Comment by nakfour** [comment]
@yanniszark we plan to update the Openshift distribution, however not sure if one week will be enough, it will depend on the issues we run into.

**Comment by RFMVasconcelos** [comment]
Hi Yannis, 

Thank you for leading this so effectively :) 

For reference, I am only a small part of the Canonical team, @knkski @evilnick and @DomFleischmann are the stars :) I will create @kubeflow/canonical next week for simplicity in the future.

**Comment by yanniszark** [comment]
> Guess you can add Kubeflow On-Prem/ArgoFlow/Argo CD to this list with https://github.com/kubeflow-onprem/ArgoFlow and status Ready.

@DavidSpek sounds awesome! I'd love to include the Argoflow distribution, but I want to ask first. Distributions are usually backed by vendors, who have a commercial interest in supporting and maintaining them. This ensures a good user experience and sufficient support. Who will be the owners of Argoflow? Is Argoflow something that its owners plan to maintain and support throughout the release and in later releases?

> @yanniszark we plan to update the Openshift distribution, however not sure if one week will be enough, it will depend on the issues we run into.

Thanks for the reply @nakfour. I understand that issues may come up during testing, so let's communicate frequently on the status and decide accordingly. Could you also inform me if Red Hat is planning to support the Kubeflow Operator distribution? I believe Red Hat is the main stakeholder there, correct?

**Comment by DavidSpek** [comment]
@yanniszark ArgoFlow is just using the upstream manifests (sometimes with a fix I have implemented), so the maintenance is all in the upstream manifests and Argo CD itself working. Basically, it is automating and simplifying the steps from the README in this repository. I don't think a distribution needs to be backed by a vendor, there can also be a community distribution. Having a commercial vendor doesn't necessarily mean there will be a good user experience, as I've seen very many unanswered issuer related to vendor distributions and their KfDef files.

For the time being, I will be active with the ArgoFlow repository. I think the on-prem working group wants to pick it up as well. But honestly I think it might be better suited for the manifests working group, as it is not much more than the manifests to begin with.

**Comment by nakfour** [comment]
@yanniszark yes we are using the KF Operator for our KF distribution  in Open Data Hub on Openshift, we are interested in taking over Kubeflow Operator distribution, however not at the moment. Maybe we can discuss this after KF 1.3 is released.

**Comment by DavidSpek** [comment]
@yanniszark I think it should be: Kubeflow with Argo CD. Also, status can be set to ready.

**Comment by berndverst** [comment]
FYI OIDC Auth Service Manifest is broken. PR here: https://github.com/kubeflow/manifests/pull/1805

**Comment by DavidSpek** [comment]
Cross-posting [my comment](https://github.com/kubeflow/manifests/issues/1777#issuecomment-814732240) here as well as it directly affects distributions. 

@yanniszark After discussing with @Bobgy it might be a blocking issue for the distributions to not include the new Jupyter Web App which allow for spawning VSCode and RStudio notebook servers due to the use of their respective logos. I'll be looking into a mitigation route for distributions to avoid potential problems here, but they will need to be notified about this. 

@Bobgy Also suggested to bring up that RStudio is licensed under the AGPL license, so the example image with RStudio might also be something distributions need to look into if they can include this or not. The above mitigation will also address this problem, but it is something distributions might want to look into separately. 

Mitigation:
Use `public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:master-121d97f4` for the jupyter web app. 
Remove the `imageVSCode:` and `imageRStudio:` from the `spawner_ui_config.yaml` in the `jupyter-web-app-config` configmap.

**Comment by nakfour** [comment]
@yanniszark bumped into first issue here https://github.com/kubeflow/manifests/issues/1810

**Comment by Bobgy** [comment]
kubeflow/kubeflow#5816 is a common inconvenience for us, I'd like to hear what others think about it.

**Comment by Bobgy** [comment]
@yanniszark we identified root cause for https://github.com/kubeflow/kubeflow/issues/5813, it should affect any distribution using profile plugins -- GCP and AWS, therefore I think it's a blocking issue we need to resolve before the release.

**Comment by DavidSpek** [comment]
The fix for the trademark issue described in my previous comment has been created in https://github.com/kubeflow/kubeflow/pull/5823.

**Comment by Bobgy** [comment]
Update for GCP, after resolving https://github.com/kubeflow/manifests/issues/1798#issuecomment-815437471, @zijianjoy and I got KFP and notebooks multi-user mode working on GCP. We are looking into other kubeflow applications.

**Comment by karlschriek** [comment]
@kubeflow/aws I would be happy to also test out the AWS distribution and help with any issues. This current code in https://github.com/kubeflow/manifests/tree/master/distributions/stacks/aws looks fairly old. Is there something more recent somewhere?

**Comment by yanniszark** [comment]
@kubeflow/cisco any update on the `kfctl_istio_k8s` distribution?

**Comment by andreyvelich** [comment]
> @kubeflow/cisco any update on the `kfctl_istio_k8s` distribution?

From our side we will use the default Dex + OIDC installation for Kubeflow 1.3.
I think we can deprecate `kfctl_istio_k8s` and `kfctl_istio_dex`.
cc @ramdootp @amsaha

**Comment by nakfour** [comment]
For OCP we ran into this issue :https://github.com/kubeflow/kubeflow/issues/5803# , we have a workaround as described in the comment

**Comment by DavidSpek** [comment]
@yanniszark @PatrickXYS Seems like there is an issue with AwsIamForServiceAccount plugin for the profile controller. https://github.com/kubeflow/kubeflow/issues/5812

**Comment by yanniszark** [comment]
@DavidSpek I took a look at the issue and I believe it's a duplicate of https://github.com/kubeflow/kubeflow/issues/5813, which we have fixed.

**Comment by nakfour** [comment]
@yanniszark an update on OCP distribution, we are about 80% done, I dont think we will be done by Monday. I wanted to see if we can delay the KF 1.3 release since looks like most distributions on the list above are still not ready. If not, do we have a target date for KF 1.3.1 tag so we can have our code tagged? 
Also for next release, I wonder if we can do like a two tier release, one for KF and one a couple of weeks later for distributions. Just a thought, since with all the issues and a lot of components to test it takes longer time. 
Thanks

**Comment by RFMVasconcelos** [comment]
[Green light] - Charmed Kubeflow distribution: We have no pending issues with the manifests and expect to release our distribution within our typical 2 weeks timeframe of upstream to distribution release. @knkski and @DomFleischmann are leading this. cc @yanniszark @castrojo

**Comment by moficodes** [comment]
@yanniszark For IBM release for IKS I am about 95% done. Just a couple of minor changes and clean up. Should be done in a few hours.

**Comment by PatrickXYS** [comment]
@yanniszark  From AWS side, we're pretty good, 90% done. Should be able to finish the PR by today or over the weekends.

**Comment by Bobgy** [comment]
@yanniszark I'm sending a PR to update KFP doc in manifests root README to resolve some confusions.
https://github.com/kubeflow/manifests/pull/1851

**Comment by yanniszark** [comment]
Thanks @Bobgy! I merged the README PR, thanks for taking the time to create that one.
For upgrading the kfp manifests to `1.5.0-rc.2`, I'd love to but I think we are too close to the release to do that. A lot of distributions would need to rebase and redo their testing, pushing the release further. I think we should put it in 1.3.1, along with other important changes like upgrading cert-manager and Knative.
What do you think?

**Comment by nakfour** [comment]
@yanniszark OCP KF 1.3 distribution is ready, just pending review and merge of https://github.com/kubeflow/manifests/pull/1811
Also the operator at the moment does not need any specific changes to get KF 1.3 installed.

**Comment by PatrickXYS** [comment]
@yanniszark AWS EKS 1.3 manifest is ready, I'll find someone help review as well. https://github.com/kubeflow/manifests/pull/1832

**Comment by Bobgy** [comment]
> Thanks @Bobgy! I merged the README PR, thanks for taking the time to create that one.
> For upgrading the kfp manifests to `1.5.0-rc.2`, I'd love to but I think we are too close to the release to do that. A lot of distributions would need to rebase and redo their testing, pushing the release further. I think we should put it in 1.3.1, along with other important changes like upgrading cert-manager and Knative.
> What do you think?

[The difference between KFP 1.5.0-rc.2 and 1.5.0-rc.3](https://github.com/kubeflow/pipelines/compare/1.5.0-rc.2...1.5.0-rc.3) is very minimal, most of the commits are either components or sdk. The only real changes are: https://github.com/kubeflow/pipelines/pull/5446, https://github.com/kubeflow/pipelines/pull/5408, https://github.com/kubeflow/pipelines/pull/5424 (5424 is an important bug fix).

So I'd it's basically a drop-in replacement of KFP 1.5.0-rc.2 that we do not need to worry about re-integration.

**Comment by Bobgy** [comment]
> @Bobgy Also suggested to bring up that RStudio is licensed under the AGPL license, so the example image with RStudio might also be something distributions need to look into if they can include this or not. The above mitigation will also address this problem, but it is something distributions might want to look into separately.

in https://github.com/kubeflow/manifests/issues/1798#issuecomment-814748504

I've been consulting with Google lawyers about RStudio being AGPL and haven't got the conclusive answer yet. GCP distribution might consider disabling RStudio support altogether. We are also confirming whether https://github.com/kubeflow/kubeflow/tree/master/components/example-notebook-servers/rstudio should be considered AGPL as well, which might break [kubeflow/kubeflow's license declaration of Apache 2.0](https://github.com/kubeflow/kubeflow/blob/master/LICENSE).

**Comment by moficodes** [comment]
IBM Distribution is ready https://github.com/kubeflow/manifests/pull/1823 
Waiting for review and merge

**Comment by yanniszark** [comment]
Thanks @bobgy! I took a look at kubeflow/pipelines#5424 and it seems that it's very similar to a recent bug we fixed in KFP. I viewed the manifests diff, deployed them and tested them and all seems good with no incompatibilities. Thus, I will make a PR to include `1.5.0`, since it has an important bugfix.

> @yanniszark sorry I keep getting confused of our timeline, from previous emails, I thought current release will be 1.3.0-rc.1. When is 1.3.0 planned?

We released `1.3.0-rc.1` over the weekend, as per the email I had sent to the list saying that I would move forward with an rc1. I didn't send a separate email after the actual cut, which now seems I should have, so perhaps this is why there was confusion. The plan is to cut `1.3.0` today.

**Comment by berndverst** [comment]
There is insufficient information that explains which manifests or overlays must be used for multi-user and which must be used for single user Kubeflow.

Additionally, dependencies between components from `apps` and components from `common` aren't clear.

Further, the example provided by @yanniszark (https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml) deploys both OIDC auth service and a Dex Istio Overlay. Why? I thought people use either Dex or OIDC Auth Service (https://github.com/arrikto/oidc-authservice)? Is there a dependency between these? Can I safely remove the Dex overlay and OIDC Auth Service should still work?

I really need these things documented and explained properly before I (or anyone else contributing in their free time) can complete the Azure distribution.

https://github.com/kubeflow/manifests/issues/1873

**Comment by DavidSpek** [comment]
@berndverst Indeed, there is no information regarding single user deployments. Regarding the OIDC authservice and Dex, they are both necessary. The OIDC authservice is the OIDC client that while Dex is the OIDC provider. Dex could be replaced with another OIDC provider (keycloak or AWS Cognito for example) by changing the OIDC authservice configuration.

**Comment by zijianjoy** [comment]
Update: Kubeflow v1.3 on Google Cloud is available. Documentation is also updated: https://www.kubeflow.org/docs/distributions/gke/deploy/overview/
