### ISSUE TITLE
convert TF serving manifest to kustomize

### ISSUE THREAD

**Issue by lluunn** [kubeflow/manifests#18]
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/tf-serving
we need 
- tf-serving-service-template.libsonnet
- tf-serving-template.libsonnet

tf-serving.libsonnet is old one and can be removed

**Comment by jlewi** [comment]
Are we sure we want to do this? How useful is a kustomize manifest for TFServing (TFJob, Katib, and other Kubeflow resources) compared to just providing specific examples in the form of YAML that people can copy and paste for their particular use case?
