### ISSUE TITLE
Unable to prevent installing of PyTorch Operator , MXNET and Seldon during kubeflow install locally

### ISSUE THREAD

**Issue by subramaniankarthik** [kubeflow/manifests#1801]
I am trying to install kubeflow 1.2.0 locally and I just want tf-operator to be installed in my kubernetes cluster. For some reason, PyTorch, MXNET, Seldon all get installed. I am not sure how to solve this problem of just having a subset of services installed. Any help is appreciated.

My manifest file is as below

apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  clusterName: minikube
  creationTimestamp: null
  name: kubeflow-local
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: istio/istio/base
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/add-anonymous-user-filter
    name: add-anonymous-user-filter
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/spartakus
    name: spartakus
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator/overlays/application
    name: tftrain
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
status: {}

**Comment by DavidSpek** [comment]
@subramaniankarthik Personally I would recommend installing 1.3 as the installation is much simpler. You mentioned you are installing it locally. I just did a write up on how to install 1.3 locally using a Kind cluster and Argo CD which should be very easy to follow. The components you don't want to install you can just comment out in the [kustomization.yaml](https://github.com/kubeflow-onprem/ArgoFlow/blob/master/kustomization.yaml) in the root of the repository (you will need to fork the repo as explained after the Kind section of the README). For my purpose I used Kind, but the installation is the same for any Kubernetes cluster really so you can use whatever you want.

**Comment by subramaniankarthik** [comment]
@DavidSpek , thank you for the above suggestion. I have tried implementing the above solution and when I run kubectl apply kubeflow.yaml, it tells me that kubeflow was added to the argoproject , but I don't see a pod running in my namespace. Not sure if I am doing something wrong here

**Comment by DavidSpek** [comment]
@subramaniankarthik Could you open an issue on https://github.com/kubeflow-onprem/ArgoFlow so it can be tracked properly? The manifests working group is not related to that deployment so we shouldn't fill up their issues with problems related to that deployment.

**Comment by subramaniankarthik** [comment]
@DavidSpek , Perfect, I just opened an issue in the ArgoFlow repo along with my issue. Thanks much

**Comment by yanniszark** [comment]
@subramaniankarthik I see that you are using Kubeflow 1.2.
I think you will have better luck following the 1.3 Release Candidate guide, which addresses installing each component individually:
https://github.com/kubeflow/manifests/tree/v1.3.0-rc.0#readme

**Comment by subramaniankarthik** [comment]
@yanniszark , Thanks yannis. Will kubeflow 1.3.0 work with AWS EKS?
