### ISSUE TITLE
Unable to log in to Dex with kubeflow 1.3

### ISSUE THREAD

**Issue by HassanOuda** [kubeflow/manifests#1803]
I have been trying to install Kubeflow 1.3 manifests with all of common/apps using example kustomization provided. Everything was installed successfully and all pods are running. Whenever I port forward the istio ingressgateway, I get this error in the browser:

Bad Request
Invalid client_id ("kubeflow-oidc-authservice").

Not sure what the issue is here. I checked that OIDC authservice does actually have that client id and so does Dex.

**Comment by HassanOuda** [comment]
If I go back to using id and secret in the staticClients fields in the configmap, this issue goes away.

**Comment by yanniszark** [comment]
@HassanOuda did you try to install on a clean cluster?
It's the first time I am hearing of this issue, so I am wondering if perhaps your environment was not clean.
How did you end up resolving this issue?

**Comment by DavidSpek** [comment]
@HassanOuda You mentioned you went back to using `id and secret in the staticClients fields in the configmap`, how did you have it configured before that was causing the issues?

**Comment by HassanOuda** [comment]
No it wasn't a clean cluster, had kubeflow 1.2 installed before and I tried uninstalling it myself and installing 1.3. instead of using idEnv and secretEnv, I used id and secret and pointed it to a params.env like it was in 1.2 and it worked. When I have time later, i will test again and see why it gave me this error

**Comment by yanniszark** [comment]
@HassanOuda any updates on this?

**Comment by HassanOuda** [comment]
yea I was able to get it to work using original manifests on 1.3 rc. Ill close this.
