### ISSUE TITLE
profile-controller: add userid-header and userid-prefix cli flags to parameters

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#181]
Sub-issue for https://github.com/kubeflow/kubeflow/issues/3553.
Add parameters to configure:
* Which header we read for the user info (now it's only X-Goog-Authenticated-User-Email)
* What prefix is expected (now it's expected to be in the form of accounts.google.com:<user>, so the prefix is accounts.google.com:)

These are controlled by the cli flags `userid-header` and `userid-prefix`.

/priority p0

cc @jlewi @lluunn @kunmingg

**Comment by jlewi** [comment]
/assgin @yanniszark 

@yanniszark Why would the profile controller need to be aware of which header contains the user id? The profile controller doesn't handle http requests that go through the ISTIO gateway. The user only interacts with the profile controller by creating profile resources.

@yanniszark Can we close this?

**Comment by yanniszark** [comment]
@jlewi it's needed for the IstioServiceRoleBinding.
See here in the code: 

https://github.com/kubeflow/kubeflow/blob/7ca3cfb39368eb49042992f4e16215e41e1953c6/components/profile-controller/pkg/controller/profile/profile_controller.go#L308
