### ISSUE TITLE
Istio Readme references file that does not exist

### ISSUE THREAD

**Issue by moficodes** [kubeflow/manifests#1837]
https://github.com/kubeflow/manifests/blob/master/common/istio-1-9-0/README.md

split-istio-packages python script in the script folder. Where is this file exactly?

@yanniszark

**Comment by yanniszark** [comment]
@moficodes thanks, this is an error in the README. The script is inside the `istio-1-9-0` folder.

**Comment by moficodes** [comment]
The `scripts/` threw me off. Found the file. Closing
