### ISSUE TITLE
Issue with installing Kubeflow behind proxy

### ISSUE THREAD

**Issue by jhattingh** [kubeflow/manifests#1845]
Hi all, 

I would appreciate some assistance. I've been trying to get Kubeflow running behind a proxy, following these steps:
https://www.kubeflow.org/docs/other-guides/kubeflow-behind-proxy/

Ultimately I run into the following issue below:

kfctl build -V -f kfctl_istio_dex.v1.1.0.yaml
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to kf1.1 based on location of config file: kfctl_istio_dex.v1.1.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000] Deleting cachedir .cache/manifests because Status.ReposCache is out of date  filename="kfconfig/types.go:477"
INFO[0000] Fetching /home/ec2-user/kf1.1/v1.1-branch.tar.gz to .cache/manifests  filename="kfconfig/types.go:498"
INFO[0000] Fetch succeeded; LocalPath .cache/manifests   filename="kfconfig/types.go:586"
INFO[0000] Processing application: namespaces            filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/namespaces          filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: application           filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/application         filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: istio-stack           filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/istio-stack         filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/cluster-local-gateway  filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: istio                 filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/istio               filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/cert-manager-crds   filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: cert-manager-kube-system-resources  filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/cert-manager-kube-system-resources  filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: cert-manager          filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/cert-manager        filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: metacontroller        filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/metacontroller      filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: oidc-authservice      filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/oidc-authservice    filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: dex                   filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/dex                 filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: bootstrap             filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/bootstrap           filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: spark-operator        filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/spark-operator      filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: kubeflow-apps         filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/kubeflow-apps       filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: knative               filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/knative             filename="kustomize/kustomize.go:613"
INFO[0000] Processing application: kfserving             filename="kustomize/kustomize.go:515"
INFO[0000] Creating folder kustomize/kfserving           filename="kustomize/kustomize.go:613"
[ec2-user@ip-10-195-241-100 kf1.1]$ kfctl apply -V -f kfctl_istio_dex.v1.1.0.yaml
INFO[0000] No name specified in KfDef.Metadata.Name; defaulting to kf1.1 based on location of config file: kfctl_istio_dex.v1.1.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0000] Deleting cachedir .cache/manifests because Status.ReposCache is out of date  filename="kfconfig/types.go:477"
INFO[0000] Fetching /home/ec2-user/kf1.1/v1.1-branch.tar.gz to .cache/manifests  filename="kfconfig/types.go:498"
INFO[0000] Fetch succeeded; LocalPath .cache/manifests   filename="kfconfig/types.go:586"
INFO[0000] Processing application: namespaces            filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/namespaces exists            filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: application           filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/application exists           filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: istio-stack           filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/istio-stack exists           filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/cluster-local-gateway exists  filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: istio                 filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/istio exists                 filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/cert-manager-crds exists     filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: cert-manager-kube-system-resources  filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/cert-manager-kube-system-resources exists  filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: cert-manager          filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/cert-manager exists          filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: metacontroller        filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/metacontroller exists        filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: oidc-authservice      filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/oidc-authservice exists      filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: dex                   filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/dex exists                   filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: bootstrap             filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/bootstrap exists             filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: spark-operator        filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/spark-operator exists        filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: kubeflow-apps         filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/kubeflow-apps exists         filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: knative               filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/knative exists               filename="kustomize/kustomize.go:611"
INFO[0000] Processing application: kfserving             filename="kustomize/kustomize.go:515"
INFO[0000] folder kustomize/kfserving exists             filename="kustomize/kustomize.go:611"
INFO[0000] .cache/manifests exists; not resyncing        filename="kfconfig/types.go:473"
INFO[0000] namespace: kubeflow                           filename="utils/k8utils.go:431"
INFO[0001] Log cluster name into KfDef: arn:aws:eks:eu-central-1:563460779143:cluster/pareto-prod  filename="kustomize/kustomize.go:242"
INFO[0001] Deploying application namespaces              filename="kustomize/kustomize.go:248"
2021/04/15 13:06:36 absolute path error in '/home/ec2-user/.cache/manifests/namespaces/base' : evalsymlink failure on '/home/ec2-user/.cache/manifests/namespaces/base' : lstat /home/ec2-user/.cache/manifests/namespaces: no such file or directory
ERRO[0001] Error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../.cache/manifests/namespaces/base': open /home/ec2-user/.cache/manifests/namespaces/base: no such file or directory  filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../.cache/manifests/namespaces/base': open /home/ec2-user/.cache/manifests/namespaces/base: no such file or directory
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                                        export CONFIG=./kfctl_gcp_iap.yaml
                                or a URL:
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                                kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for namespaces: accumulating resources: accumulating resources from '../../.cache/manifests/namespaces/base': open /home/ec2-user/.cache/manifests/namespaces/base: no such file or directory

Looking at the actual folder structure, the path is actually:
/home/ec2-user/.cache/manifests/manifests-1.1-branch/namespaces/base (manifests-1.1-branch)

How do I align these paths for successful installation?

Thank you in advance.
Johan

**Comment by gecube** [comment]
What I have done:
1. I run kfctl on the cluster with direct internet access
2. kfctl made the directory structure in `/opt/kubeflow` (including .cache catalogue etc.)
3. I copied this `/opt/kubeflow` catalogue to the machine behind proxy.
4. because all manifests are in place, you can safely run `kfctl apply -f ...` and it will install kubeflow components. 
5. Also I was forced to rewrite the images' names because I have no access to docker hub, gcr.io and other registries, but after some monkeypatching everything works like a charm.

**Comment by jhattingh** [comment]
@gecube Thank you for the response. It's a bit unfortunate that such a process is needed. That being said, I'll definitely try in. 

Thanks once again.
