### ISSUE TITLE
Installation in air-gap environment

### ISSUE THREAD

**Issue by gecube** [kubeflow/manifests#1850]
Hello!

I was playing around the installation of Kubeflow in air-gap environment. I need it because of restrictions applied in our company. There is no possibility to use docker proxy registry to the docker hub, gcr.io and other registries with the source images.

What'd I like to see:

1. script for downloading all necessary images (like [rancher made for it's customers](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/))
2. working option `kfctl alpha --set-image-name` - it doesn't work as intended, because substitution of private images' names don't happen in every places (for example, it doesn't change image names burned into configmaps of Istio, Argo Workflows etc.) OR simple way of overriding base image names
3. consistency across the base images, because, for instance, istio uses images from different registries like - docker.io/istio/galley:1.1.6 or gcr.io/istio-release/galley:release-1.3-latest-daily It's very difficult to find every dependency and patch it.

**Comment by thesuperzapper** [comment]
I somewhat think that is more of a question for the distributions, as its specific to the user environment.

The manifests from this repo are only intended for advanced users and distribution owners (as an "authoritative" reference/starting-point for each kubeflow version), and I think we should avoid implementing features which are specific to one kind of deployment environment.

But perhaps something to help download all the container images (from their various hosts) would help distribution owners too.

@yanniszark thoughts?

**Comment by thesuperzapper** [comment]
@kubeflow/wg-manifests-leads @DavidSpek I think we should consider releasing some kind of script to help both users and distributions mirror the container images onto their private container registry, (or at least we could auto-generate csv with all the images and where they are hosted).

/priority p2

**Comment by jpic** [comment]
I created such a script, meant for any kustomize project, problems:

- it fails to pick up some keys (perhaps change KEYS const)
- kubeflow-user-example-com still creates deployments based on gcr.io images...

```python

#!/usr/bin/env python
"""
Kubeflow airgap deployment helper.

This script downloads all images necessary for a kustomize directory, and
retags them to use the private registry URL as prefix.

Usage:

    python airgap.py your.registry.domain

This usage example will download all images necessary for the kustomize.yaml in
the current working directory, retag them with the ``your.registry.domain/``
prefix, and create local overrides so that ``kustomize`` will use them new
tags.
"""

import json
import subprocess
import sys
import yaml


KEYS = ('image', 'queueSidecarImage')


def get_images(document):
    images = []

    if isinstance(document, list):
        for item in document:
            if isinstance(item, (list, dict)):
                images += get_images(item)
    elif isinstance(document, dict):
        for key, value in document.items():
            if isinstance(value, (dict, list)):
                images += get_images(value)
            else:
                for search in KEYS:
                    if search == key:
                        images.append(value)
    else:
        raise Exception(f'What to do with {document}?')

    return images


def check_call(*args):
    cmd = ' '.join(args)
    print(f'+ {" ".join(args)} ...')
    subprocess.check_call(args)


def handle_image(prefix, image):
    kustomized = False
    if image.startswith(prefix):
        new_image = image
        image = new_image[len(prefix):]
        kustomized = True
    else:
        new_image = prefix + image

    if not kustomized:
        check_call(
            'kustomize',
            'edit',
            'set',
            'image',
            f'{image}={new_image}',
        )

    check_call(
        'docker',
        'pull',
        image,
    )

    if '@sha256:' in image:
        # strip sha from new_image
        _, image_tag = new_image.split('@sha256:')
        new_image_tag, _ = new_image.split('@sha256:')
        output = subprocess.check_output(['docker', 'image', 'inspect', image])
        data = json.loads(output)
        image_tag = data[0]['Id']
    else:
        image_tag = image
        new_image_tag = new_image

    check_call(
        'docker',
        'tag',
        image_tag,
        new_image_tag,
    )
    return new_image_tag


def main(*argv):
    if not len(argv):
        print(__doc__)
        sys.exit(1)
    prefix = argv[0] + '/'

    print('kustomize build...')
    kustomize = subprocess.run(
        ['kustomize', 'build'],
        capture_output=True,
    )
    if kustomize.returncode != 0:
        print(kustomize.stdout)
        print(kustomize.stderr)
        print(f'kustomize build command exit code: {kustomize.returncode}')
        print('Aborting')
        sys.exit(kustomize.returncode)

    print('Loading YAML documents...')
    documents = [
        yaml.safe_load(document)
        for document in kustomize.stdout.split(b'\n---')
    ]

    print('Getting images...')
    new_images = []
    for document in documents:
        for image in get_images(document):
            new_images.append(handle_image(prefix, image))

    print('Tar-ing images...')
    check_call(
        'sh',
        '-c',
        f'docker save {" ".join(new_images)} > kubeflow-images.tar',
    )

if __name__ == '__main__':
    main(*sys.argv[1:])
```
