### ISSUE TITLE
repoRef paths in KfDef files are outdated

### ISSUE THREAD

**Issue by ashrafgt** [kubeflow/manifests#1852]
I'm looking to install the components configured in this `KfDef`: https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_k8s_istio.yaml

But the `kustomizeConfig.repoRef.path` values do not match the contents of master.

**Comment by thesuperzapper** [comment]
@yanniszark do you think we can remove the files under `manifests/distributions/kfdef/` as they wont work anymore (because of these link issues), and people could theoretically see them under the `1.2-branch` etc.

**Comment by moficodes** [comment]
Any kfdef pointing to master should be updated or removed. All the branch kfdef will continue to work.

**Comment by thesuperzapper** [comment]
@yanniszark what are we planning to do with the old `./distributions/kfdef/...` files in the master branch, as most of them won't work anymore (after the manifests repo refactor).
