### ISSUE TITLE
KFP-Tekton pipeline-agnostic error Running Example coin flip

### ISSUE THREAD

**Issue by nakfour** [kubeflow/manifests#1856]
Using KFP Tekton pipeline-agnostic gives and error in pod ml-pipeline-scheduledworkflow ```Processing object (conditional-execution-pipeline-ac839): object has no owner." Workflow=conditional-execution-pipeline-ac839``` When creating a run for the example ``coin-flip`` pipeline. The dashboard just for the run is blank.
This part of the work in this PR https://github.com/kubeflow/manifests/pull/1811

**Comment by moficodes** [comment]
@Tomcli

**Comment by Tomcli** [comment]
Thanks @nakfour, I commented on your PR on the necessary changes to run tekton on kubeflow openshift

**Comment by nakfour** [comment]
Thanks @Tomcli its working.
