### ISSUE TITLE
adding resource on new namespace for dynamic user creation on openshift

### ISSUE THREAD

**Issue by moficodes** [kubeflow/manifests#1858]
When we create a new user we dynamically create some new resources using `sync.py` from https://github.com/kubeflow/manifests/tree/master/apps/kfp-tekton/upstream/base/installs/multi-user/pipelines-profile-controller or https://github.com/kubeflow/manifests/tree/master/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller. This serves the desired components that gets picked up by the profile controller. 

In openshift because of the security constraints we need more scc to be created on a new namespace to be able to run components that has a sidecar and uses deafult usergroup. We would need some way of creating these resources dynamically for new namespaces. 

we can use this issue to discuss possible steps. This is needed to enable multi user kubeflow. 

@Tomcli @nakfour @animeshsingh

**Comment by nakfour** [comment]
@moficodes I agree, was looking into the code and this is where we need to add lines of code to dynamically add new scc in the namespace just created: https://github.com/kubeflow/kubeflow/blob/d73e468aba82bdcf04fc9b02fa6b73347fae9e81/components/profile-controller/controllers/profile_controller.go#L127

**Comment by moficodes** [comment]
I think we can also do something similar to pipeline and create something like openshift-profile-controller with a sync.py that serves the resource that needs to be created. To my understanding profile controller will pick this changes up and create the resources as needed. This way we have full control over what gets created and also this becomes configurable for future changes. I dont think we need / want to change this in the profile controller itself.

**Comment by animeshsingh** [comment]
cc @yanniszark

**Comment by moficodes** [comment]
As an experiment, I added the istio-cni and scc in the sync.py from kfp-tekton. The idea was if we can get the cni and scc created in the new namespace we can automate the setup of the profile and have the necessary permission of anyuid so the pods in the new namespace can start. 

The cni was created just fine. But the scc was not created. I think it has to do something with scc being a clusterwide resource. But I am not sure. I did not see any error in pipelines profile controller or profile controller.

**Comment by yanniszark** [comment]
I agree with @moficodes that it's better to create an openshift-specific controller that:
- Watches user namespaces (the profile-controller adds a certain label that can identify them)
- Creates the needed resources in each namespace.

This way, Openshift can have complete control without blocking on upstream review. I think @jlewi had proposed a similar pattern some time ago. What do you think?

**Comment by maxdebayser** [comment]
I know this issue is closed, but if anyone else tries to do this it is possible to set up the istio-cni and the scc in sync.py adding these two entries:
```
                {
                    "apiVersion": "k8s.cni.cncf.io/v1",
                    "kind": "NetworkAttachmentDefinition",
                    "metadata": {
                        "name": "istio-cni",
                        "namespace": namespace,
                    }
                },
                {
                    "apiVersion": "security.openshift.io/v1",
                    "kind": "SecurityContextConstraints",
                    "metadata": {
                        "name": "hostmount-anyuid-{}".format(namespace),
                    },
                    "priority": None,
                    "readOnlyRootFilesystem": False,
                    "requiredDropCapabilities": [
                        "MKNOD"
                    ],
                    "runAsUser": {
                        "type": "RunAsAny"
                    },
                    "fsGroup": {
                        "type": "RunAsAny"
                    },
                    "seLinuxContext": {
                        "type": "MustRunAs"
                    },
                    "supplementalGroups": {
                        "type": "RunAsAny"
                    },
                    "volumes": [
                        "configMap",
                        "downwardAPI",
                        "emptyDir",
                        "hostPath",
                        "nfs",
                        "persistentVolumeClaim",
                        "projected",
                        "secret"
                    ],
                    "allowHostDirVolumePlugin": True,
                    "allowHostIPC": False,
                    "allowHostNetwork": False,
                    "allowHostPID": False,
                    "allowHostPorts": False,
                    "allowPrivilegeEscalation": True,
                    "allowPrivilegedContainer": False,
                    "allowedCapabilities": None,
                    "defaultAddCapabilities": None,
                    "groups": ["system:serviceaccounts:{}".format(namespace)],
                    "users": []
                }
```
