### ISSUE TITLE
Kubeflow 1.3 on OpenShift

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/manifests#1867]
Umbrella issue to track KF 1.3 on OpenShift issues in following categories

**OpenShift Versions**

- 4.5
- 4.6

**KF 1.3 for**

- Single user
- Multi-User

cc @moficodes @pvaneck @yhwang @Tomcli @nakfour @crobby

**Comment by animeshsingh** [comment]
Official installation from RH ODH team: OpenShift 4.5 only, and single-user only

**Comment by pvaneck** [comment]
Based on the [1.3 OpenShift KFDef](https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift_v1.3.0.yaml), the default pipelines is Tekton.

In any case, in my testing of this manifest on OpenShift 4.6.22, here are some findings.

1. Minor Issue: *Tensorboards not a valid page*. Clicking on the `Tensorboards` menu item in the dashboard, yields `Sorry, /tensorboards/ is not a valid page`. For this, the Tensorboard component can either be added or the menu item can be removed by patching central dashboard configmap.

2. Clicking on `Experiements (KFP)` from the side menu, leads to a page with `Error: failed to retrieve list of experiments. Click Details for more information.`. Clicking on details shows:  `Invalid input error: In single-user mode, ListExperiment cannot filter by namespace.`.
    * Note this is only with the `kubeflow-user-example-com` namespace selected. If I were to have no namespace selected (by removing the `?ns=kubeflow-user-example-com` from the URL), the error goes away, and I can see experiments.
    * Also when trying to create an experiment from this page, I get: `Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.`

3. Similarly, I can select a pipeline and choose to run it with the  `kubeflow-user-example-com` namespace selected, however won't see it in `Runs` unless no namespace is selected.

4. `Artifacts` doesn't show anything even after pipeline runs and `Executions` shows error `Error: Failed getting executions: Unknown Content-type received.. Code: 2` with no extra details.
    * Inspecting in developer tools, i see some 404s to the `/ml_metadata.MetadataStoreService/GetExecutions` and `/ml_metadata.MetadataStoreService/GetExecutionTypes` endpoints,  so there is likely something wrong with the metadata service.

5. I was able to run one flip-coin pipeline successfully, however subsequent runs fail with logs showing `Error executing command: fork/exec /bin/bash: no such file or directory`. Not sure what happened here, and will try to continue investigating.

**Comment by pvaneck** [comment]
Also, repeating what I mentioned in the Kubeflow OpenShift Slack Channel:

There were some issues with Knative pods starting (on OpenShift 4.6.22). OpenShift 4.5 is fine.

Doing `oc get po -n knative-serving` shows:
```
NAME                                READY   STATUS                 RESTARTS   AGE
activator-6c87fcbbb6-dmdpt          0/1     CreateContainerError   0          53m
autoscaler-847b9f89dc-746rp         0/1     CreateContainerError   0          53m
controller-55f67c9ddb-gnssq         0/1     CreateContainerError   0          53m
istio-webhook-db664df87-khcpg       1/1     Running                0          53m
networking-istio-76f8cc7796-k5w6k   1/1     Running                0          53m
webhook-6bff77594b-wtgpd            0/1     CreateContainerError   0          53m
```
Describing one of the failed pods show:
```
starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```
This is the same case with the knative-eventing namespace.

This seems to have been a regression that is outlined in this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1934177
A comment there mentions that the image Knative is based off of (gcr.io/distroless/static:nonroot) are currently not working out of the box on OpenShift. Looks like a patch was recently added to address this, but not sure when it will be available as a patch release for OpenShift.

In any case, the quickest workaround I found was to do:

```
oc adm policy add-scc-to-group anyuid system:serviceaccounts:knative-serving
```
However, while the knative-serving pods are up with that scc command, that still leaves an issue with the knative sidecar (queue-proxy) that comes with each kfserving inferenceservice pod in the user namespace.

```
NAME                                                              READY   STATUS                 RESTARTS   AGE
sklearn-iris-predictor-default-ll9dh-deployment-5f8b9b69dcgwn28   1/2     CreateContainerError   0          5m4s
```

Same permission issue unless you do another:

```
oc adm policy add-scc-to-group anyuid system:serviceaccounts:user-namespace
```

Not sure how to get around not adding the user ns to the anyuid scc unless maybe the sidecar image is rebuilt.

**Comment by animeshsingh** [comment]
@pvaneck on both your comments on top, before anything else, add and highlight in bold OpenShift version, and whether is single user or multi-user testing.

Like:
**OpenShift 4.6 - Single User** 

Hopefully everyone can follow the same convention.

**Comment by moficodes** [comment]
Multi User OpenShift Dynamic Profile Creation issue #1858

**Comment by yhwang** [comment]
**OpenShift 4.6 - Single User** 

want to follow up the status of single user deployment on OpenShift 4.6, seems those issues in this comment https://github.com/kubeflow/manifests/issues/1867#issuecomment-825324734 haven't been resolved yet. It would be good to know if there is any progress on those issue or workaround
/cc @nakfour
