### ISSUE TITLE
Kubeflow 1.3 on IKS

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/manifests#1868]
Umbrella issue to track KubEflow 1.3 on IKS

**Kubernetes Versions:**

1.8
1.9

**KF 1.3 for**

Single user
Multi-User

cc @moficodes @pvaneck @yhwang @Tomcli

**Comment by Tomcli** [comment]
Kubernetes version Verified with IKS:
- [x] 1.17
- [x] 1.18
- [x] 1.19
- [ ] 1.20

**Comment by yhwang** [comment]
**IKS 1.19 Single/Multi User**

Need to apply [this](https://github.com/kubeflow/manifests/pull/1865) to create `kubeflow-gateway` for the network routing.

Verified the following 3 samples:
- Trusted AI: https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai
- Katib: https://github.com/kubeflow/kfp-tekton/tree/master/samples/katib
- kfserving: https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex

They all work properly.

**Comment by yhwang** [comment]
**IKS 1.20 Single/Multi User**

Repeated the same samples and `kubeflow-gateway` patch from [previous comment](https://github.com/kubeflow/manifests/issues/1868#issuecomment-826982296) on IKS v1.20 and they work properly!

**Comment by yhwang** [comment]
IKS: 1.20
Kubeflow: 1.3.1 

deployment approach:
- kustomize
- kfctl (not verify yet. will do it an update the status later)

verified single and multi-user deployment with the same test cases:
- Trusted AI: https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai
- Katib: https://github.com/kubeflow/kfp-tekton/tree/master/samples/katib
- kfserving: https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex

all passed.
