### ISSUE TITLE
Kubeflow namespace

### ISSUE THREAD

**Issue by neeharika4** [kubeflow/manifests#1872]
we need to change kubeflow namespace name due to our company security compliance and convention
1. Are we allowed to change the name of namespace?
2. Are we allowed to deploy all pods like istio, cert etc on single namespace?
Please let me know if these are possible in kubeflow 1.2 or coming kubeflow 1.3

**Comment by davemaung** [comment]
This seemed related to https://github.com/kubeflow/kubeflow/issues/3967
Can somebody help comment on this? Are there a plan to support custom namespace? I tried kubeflow 1.3. it doesnt work and i tried this steps.

1. download https://github.com/kubeflow/manifests/tree/v1.3.0

2. replace namespace : kubeflow with namespace : mykf in all file in manifests folder

3. run while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done

4.All pods are running except metadata pods
kubectl get pods -n mykf
NAME READY STATUS RESTARTS AGE
metadata-grpc-deployment-9d547547d-72qsj 1/2 CrashLoopBackOff 11 34m
metadata-writer-6cbc87bf5-h977z 1/2 CrashLoopBackOff 9 41m

5. When i checked error on metadata-writer-6cbc87bf5-h977z pods
│
│ Failed to access the Metadata store. Exception: "no healthy upstream" │
│ Traceback (most recent call last): │
│ File "/kfp/metadata_writer/metadata_writer.py", line 63, in │
│ mlmd_store = connect_to_mlmd() │
│ File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd │
│ raise RuntimeError('Could not connect to the Metadata store.') │
│ RuntimeError: Could not connect to the Metadata store. │
│ stream closed

6.When i check mysql database metadb db is not created. where and how metadb is created?

mysql> show databases;
+--------------------+
| Database |
+--------------------+
| information_schema |
| mysql |
| performance_schema |
| sys |
+--------------------+

**Comment by zengqingfu1442** [comment]
I also encountered this issue. 
My env:
k8s: 1.19.16
kubeflow manifests: v1.5.1 tag
kustomize: 3.2.0

install command:
```
while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

metadata-grpc-deployment-6f6f7776c5-pq6hq log:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0321 09:45:37.213575     1 metadata_store_server_main.cc:236] Check failed: absl::OkStatus() == status (OK vs. INTERNAL: mysql_real_connect failed: errno: , error:  [mysql-error-info='']) MetadataStore cannot be created with the given connection config.
*** Check failure stack trace: ***
```

mysql-f7b9b7dd4-5m4tb logs:
```
2023-03-21 09:47:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.33-1debian10 started.
2023-03-21 09:47:27+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
        command was: mysqld --ignore-db-dir=lost+found --datadir /var/lib/mysql --verbose --help --log-bin-index=/tmp/tmp.fbqLrtywDf

```

metadata-writer-d7ff8d4bc-8thjn logs:
```
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 63, in <module>
    mlmd_store = connect_to_mlmd()
  File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd
    raise RuntimeError('Could not connect to the Metadata store.')
RuntimeError: Could not connect to the Metadata store.
```

**Comment by manang** [comment]
did you solve this issue?
