### ISSUE TITLE
Documentation for manifests and overlays (what is what)

### ISSUE THREAD

**Issue by berndverst** [kubeflow/manifests#1873]
This is a request for documentation of manifests and overlays.

Today it is unclear which manifests are required for what functionality and which depend on each other.

For example, which manifests do I require for a single user installation of Kubeflow? Which manifests and overlays do I require for a multi user installation?

It would be great (or for me in fact critical) to have documentation in each manifest and overlay folder to explain their purpose and any dependencies or typical pairings with other manifests.

/kind question

**Comment by Bobgy** [comment]
Hi @berndverst, I completely agree with this, that's why I added some information for KFP there: https://github.com/kubeflow/manifests#kubeflow-pipelines.

I'm curious from your point of view, are there anything remaining that's unclear?
