### ISSUE TITLE
Problem Installing Cert-Manager: TLS server chose an unconfigured cipher suite

### ISSUE THREAD

**Issue by jmdinis** [kubeflow/manifests#1880]
Hi,

I'm trying to install kubeflow on a vanilla (kubeadm) Kubernetes 3-node cluster. When I try to install cert-manager it fails with following output:

`Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://kubernetes.default.svc:443/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s": tls: server chose an unconfigured cipher suite`

This is after running the following command:

[OK]     `kustomize build common/cert-manager/cert-manager-kube-system-resources/base | kubectl apply -f -`
[OK]      `kustomize build common/cert-manager/cert-manager-crds/base | kubectl apply -f -`
[FAIL]    `kustomize build common/cert-manager/cert-manager/overlays/self-signed | kubectl apply -f -`

Env:
- Kubernetes 1.21
- Kustomize 3.2.0
- Ubuntu 18.04

Can any one point to what may be causing the problem?

Kind regards.

**Comment by jmdinis** [comment]
Retried with Kubernetes version 1.17, still the same issue.

**Comment by BenzhaminKim** [comment]
I have the same issue. Anyone solved?

**Comment by biaochen** [comment]
I have the same issue while trying to install kubeflow 1.1 on k8s 1.21

**Comment by jbottum** [comment]
/priority p2
/area installation
/kind question

@jmdinis @BenzhaminKim what this with Kubeflow 1.3 ?  @biaochen did you try with KF 1.3?  All - Did you get this resolved ? @kubeflow/wg-manifests-leads

**Comment by ashokbalaraman** [comment]
@yanniszark 
I have the same problem.  
OS: Ubuntu 20.04 LTS
K8: On-Prem 1.17.17
KF: 1.3

validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.serving.knative.dev unchanged
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
