### ISSUE TITLE
Profile controller access manager image tag was v1.3.0-rc.1

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/manifests#1881]
https://github.com/kubeflow/manifests/blob/v1.3-branch/apps/profiles/upstream/overlays/kubeflow/kustomization.yaml

Should this value be updated to `v1.3.0` for Kubeflow 1.3?

/assign @yanniszark 
/cc @Bobgy

**Comment by DavidSpek** [comment]
The v1.3.0 release was never cut on the `kubeflow/kubeflow` repository, so all the components there have the `v1.3.0-rc.1` tag.

**Comment by zijianjoy** [comment]
@DavidSpek That makes sense David. I also confirm that it is the case, I suggest to make an official cut in the coming v1.3.1 release.

**Comment by DavidSpek** [comment]
I agree, there have been multiple users confused regarding the state of 1.3 because of this.
