### ISSUE TITLE
admission-webhook-mutating-webhook-configuration does not correctly substitute service name

### ISSUE THREAD

**Issue by 814HiManny** [kubeflow/manifests#1894]
Seems like the mutating-webhook-configuration.yaml of the admission-webhook is not correctly substituting the name of the webhook service. This results in PodDefaults not being applied.

The following change should be applied to fix:
```
diff --git a/manifests/v1.3.0-on-202104XX/manifests-1.3-branch/apps/admission-webhook/upstream/base/mutating-webhook-configuration.yaml b/manifests/v1.3.0-on-202104XX/manifests-1.3-branch/apps/admission-webhook/upstream/base/mutating-webhook-configuration.yaml
index 12f9f1a..6c59e90 100644
--- a/manifests-1.3-branch/apps/admission-webhook/upstream/base/mutating-webhook-configuration.yaml
+++ b/manifests-1.3-branch/apps/admission-webhook/upstream/base/mutating-webhook-configuration.yaml
@@ -6,7 +6,7 @@ webhooks:
 - clientConfig:
     caBundle: ""
     service:
-      name: service
+      name: $(podDefaultsServiceName)
       path: /apply-poddefault
   name: $(podDefaultsDeploymentName).kubeflow.org
   namespaceSelector:
```

**Comment by yanniszark** [comment]
@814HiManny hi! I could not reproduce the issue with kustomize v3.2.0.
The Service name is substituted as expected because this file teaches kustomize of the cross-reference:
https://github.com/kubeflow/manifests/blob/c41f71e01ee6f0a8573185e96a9168a18581aa34/apps/admission-webhook/upstream/base/params.yaml#L8-L14

Could you tell me how to reproduce the problem you are seeing?

**Comment by vinayan3** [comment]
I'm having this problem as well. 

## Steps to repro
```
$ git clone git@github.com:kubeflow/manifests.git
$ cd manifests/example
$ kustomize build > manifests.yaml
$  grep  "path: /apply-poddefault"  manifests.yaml -B 15 -A 15
```
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/admission-webhook-cert
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: poddefaults
  name: admission-webhook-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: service
      namespace: kubeflow
      path: /apply-poddefault
  name: admission-webhook-deployment.kubeflow.org
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow-profile
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
```

## Environment
```
$ kustomize version  
{Version:kustomize/v3.8.6 GitCommit:c1747439cd8bc956028ad483cdb30d9273c18b24 BuildDate:2020-10-29T23:07:50Z GoOs:linux GoArch:amd64}
```

**Comment by streamnsight** [comment]
@vinayan3 work around still needed with 1.6.0-rc.3
but the api version is v1, not v1alpha1
