### ISSUE TITLE
Kubeflow 1.3 bugs on Openshift 4.6

### ISSUE THREAD

**Issue by mavencode01** [kubeflow/manifests#1895]
I recently installed kubeflow 1.3 on Openshift 4 cluster using the kubeflow manifest  [kfctl_openshift_v1.3.0.yaml ](https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift_v1.3.0.yaml).

The installation appears successful but found the following issues:
- Missing "Manage Contributors" tab to manage users.
- Tensorboards not working, menu re-appears nested as shown in the screenshot.
- Missing kubeflow version at the bottom of the page.

Are these known limitations or are there any fix or solution for any of these please ?

![kf_openshift](https://user-images.githubusercontent.com/542912/120334784-eff02680-c2be-11eb-8302-dbc5f6d90140.png)

**Comment by nakfour** [comment]
@mavencode01 we are aware of the Tensorboard issue, if you look at the example kfdef, we do not include Tensorboard. We are not aware of the other two issues. FYI KF 1.3 on OCP is limited to OCP 4.5 and earlier, we have known bugs on OCP 4.6/4.7 as captured in this issue https://github.com/kubeflow/manifests/issues/1867
Which version of OCP are you using?

**Comment by DavidSpek** [comment]
@nakfour It might be interesting to coordinate with the Sig on-prem to setup CI/CD using Equinix Metal.

/cc @jtfogarty @RFMVasconcelos

**Comment by mavencode01** [comment]
@nakfour That could explain the issue we are seeing. We are installing it on `OCP 4.6.15`

**Comment by nakfour** [comment]
@DavidSpek I am not clear on your request? Why do we need to setup CI/CD using Equinix Metal?

**Comment by DavidSpek** [comment]
@nakfour I thought it might be interesting to setup CI/CD for Kubeflow on OpenShift. The on-prem SIG has access to Equinix Metal that could be used for this.
