### ISSUE TITLE
Use multi-user, I got bad request

### ISSUE THREAD

**Issue by DonggeunYu** [kubeflow/manifests#1903]
I installed kubeflow in the master branch with the following command. But Bad Request pops up.
I want to use it as multi-user, how can I solve this?

while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done

ERROR in local:8080:
Bad Request
Invalid client_id ("kubeflow-oidc-authservice")

**Comment by yanniszark** [comment]
@DonggeunYu could you please follow the instructions on the latest release tag:
https://github.com/kubeflow/manifests/tree/v1.3.0

Please ensure your Kubernetes cluster is clean before starting. Let me know how it goes.

**Comment by DonggeunYu** [comment]
Yes, Started with a clean cluster
