### ISSUE TITLE
Move distributions out of kubeflow/manifests

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1904]
### Problem Statement

Move [Kubeflow Distributions](https://github.com/kubeflow/manifests/tree/master/distributions) out of the kubeflow/manifests repository.

As detailed in the following guideline:
https://github.com/kubeflow/community/blob/master/proposals/kubeflow-distributions.md

distributions should be developed outside the GitHub org.
In addition to the benefits outlined by the proposal, developing distributions outside the GitHub org allows us to release Kubeflow independently of the distributions and the distributions to make changes without waiting for a Kubeflow release.

In Kubeflow 1.3, we focused on refactoring the manifests repo and allowed for 1 more release so that distribution owners can get ready. In Kubeflow 1.4, we will remove all distributions from the kubeflow/manifests repo.

Distributions should use their own repo to track their issues and custom code.

| Distribution | Owners | Migrated out of kubeflow/manifests |
| - | - | - |
| Azure | @kubeflow/azure | :x: |
| AWS | @kubeflow/aws | :x:  |
| Google Cloud | @kubeflow/google | ✔️ (https://github.com/kubeflow/gcp-blueprints) |
| IBM | @kubeflow/ibm | :x:  |
| Kubeflow Operator | @kubeflow/red-hat | :x:  |
| kfctl_istio_k8s | | Support dropped |
| kfctl_istio_dex | | Support dropped |
| Openshift | @kubeflow/red-hat | :x:  |

### Next Steps

We will remove the distributions folder in **2 months time, on the 14th of August**.
To all affected distributions, please ack this move (with a +1 on this message), or comment if you need more time or are unsure on how to proceed.

cc @kubeflow/wg-manifests-leads 
cc @kubeflow/aws 
cc @kubeflow/azure 
cc @kubeflow/ibm
cc @kubeflow/red-hat

**Comment by kimwnasptd** [comment]
Kind ping for this
@kubeflow/azure @kubeflow/aws @kubeflow/ibm @kubeflow/red-hat

**Comment by goswamig** [comment]
Are we just moving these manfiest out of `kubeflow/manifest` rep but allowing them to stay under `kubeflow` organization? 

Can we get more clarity and guideline where should other distro live? I see Google ones are still inside `kubeflow` org? Whats the guideline or runbook to create something similar for other distro like AWS ?  @yanniszark?

**Comment by thesuperzapper** [comment]
> Are we just moving these manfiest out of `kubeflow/manifest` rep but allowing them to stay under `kubeflow` organization?

@goswamig as agreed in the ["Kubeflow Distributions" proposal](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-distributions.md#proposal), we should be moving all distribution-owned stuff outside the `kubeflow` GitHub org. 

This line is the important one: `"Going forward all distributions of Kubeflow should be owned and maintained outside of Kubeflow."`

> Can we get more clarity and guideline where should other distro live? I see Google ones are still inside `kubeflow` org? Whats the guideline or runbook to create something similar for other distro like AWS ? @yanniszark?

Google's distribution is the only one living under the `kubeflow` GitHub org right now. In the interest of fairness, we should move the [kubeflow/gcp-blueprints](https://github.com/kubeflow/gcp-blueprints) repo into another GitHub org, as other vendors are not be able to host their distributions under the `kubeflow` org.

@Bobgy @james-jwu @zijianjoy what are your thoughts?
