### ISSUE TITLE
Failed for volume "istio-token" error

### ISSUE THREAD

**Issue by kaybon** [kubeflow/manifests#1911]
I'm trying to install kubeflow 1.3 on k8s cluster (version. 1.17.12). follow with **Install individual components**. 
But an error occurred in the 'Istio' _(kustomize build common/istio-1-9-0/istio-install/base | kubectl apply -f -)_. 

![image](https://user-images.githubusercontent.com/17444828/122514876-953d2580-d047-11eb-8171-9c20450ff101.png)

- istio-ingressgateway log
```
│   Type     Reason       Age               From               Message
│   ----     ------       ----              ----               -------
│   Normal   Scheduled    16s               default-scheduler  Successfully assigned istio-system/istio-ingressgateway-78f7794d66-tgt88 to dkosv3-test-kube2-worker-1
│   Warning  FailedMount  7s (x5 over 15s)  kubelet            MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
│   Warning  FailedMount  0s (x6 over 16s)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
```

- istiod log
```
│   Type     Reason       Age                From               Message
│   ----     ------       ----               ----               -------
│   Normal   Scheduled    30s                default-scheduler  Successfully assigned istio-system/istiod-574485bfdc-n5rm7 to dkosv3-test-kube2-worker-1
│   Warning  FailedMount  14s (x6 over 29s)  kubelet            MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```

Kubeflow 1.3 tested with kubernetes version 1.17. According to [istio doc](https://preliminary.istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens), third-party-jwt config is operated in kubernetes 1.20+.

How do i resolve this error of 'MountVolume.SetUp failed for volume "istio-token"'?

**Comment by dboc** [comment]
Hello,

I have the same erro, @kaybon did you solve it?How?

**Comment by dboc** [comment]
Hi, @kaybon 

I solved it, I follow these instructions : 
https://istio.io/latest/blog/2019/trustworthy-jwt-sds/
and
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection
and
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
and
https://istio.io/latest/docs/ops/best-practices/security/

Reading it, i just have to add kube-api-server args. In my case i added it:
```
      service-account-issuer: "api"
      service-account-signing-key-file: "/etc/kubernetes/ssl/kube-service-account-token-key.pem"
      service-account-key-file: "/etc/kubernetes/ssl/kube-service-account-token.pem"
 ```
 
Another solution it is change JWT Policy, but i could not found how to do it

**Comment by chinaboy007** [comment]
me too,求解决

**Comment by kaybon** [comment]
@dboc @chinaboy007 Thank you for reply. 
@dboc i read it now. sorry!
i've tried to add kube-api-server args. but it was not working.
so i just changed JWT policy from third-party to first-party.

in file:
common/istio-1-9-0/istio-install/base/install.yaml
common/istio-1-9-0/cluster-local-gateway/base/cluster-local-gateway.yaml

**Comment by dboc** [comment]
@bytesinger k8s 1.19.6, container runtime is docker 19.3.15 .

**Comment by 631068264** [comment]
not work for k8s v1.18.6
