### ISSUE TITLE
Release 1.3.1 - Sync manifests from upstream repos

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1912]
Previous issue: https://github.com/kubeflow/manifests/issues/1775
Umbrella issue for releasing 1.3.1: https://github.com/kubeflow/manifests/issues/1890

In order to cut the 1.3.1 release, we need to sync manifests from the upstream repos. For this reason, the manifests wg needs to gather the git revisions from each upstream repo, in order to sync them here.

| Application | Manifests Path | Upstream Path | Upstream Repo | Revision |
| --- | --- | --- | --- | --- |
| TFJob Operator | apps/tf-training/upstream | manifests | https://github.com/kubeflow/tf-operator | `v1.1.0 ` |
| PyTorch Operator | apps/pytorch-job/upstream | manifests | https://github.com/kubeflow/pytorch-operator | `v0.7.0` |
| MPI Operator | apps/mpi-job/upstream | manifests | https://github.com/kubeflow/mpi-operator | `b367aa55886d2b042f5089df359d8e067e49e8d1` |
| MXNet Operator | apps/mxnet-job/upstream | manifests | https://github.com/kubeflow/mxnet-operator | `v1.1.0` |
| XGBoost Operator | apps/xgboost-job/upstream | manifests | https://github.com/kubeflow/xgboost-operator | `v0.2.0` |
| Notebook Controller | apps/jupyter/notebook-controller/upstream | components/notebook-controller/config | https://github.com/kubeflow/kubeflow |  |
| Central Dashboard | apps/centraldashboard/upstream | components/centraldashboard/manifests | https://github.com/kubeflow/kubeflow |  |
| Profiles + KFAM | apps/profiles/upstream | components/profile-controller/config | https://github.com/kubeflow/kubeflow |  |
| PodDefaults Webhook | apps/admission-webhook/upstream | components/admission-webhook/manifests | https://github.com/kubeflow/kubeflow |  |
| Jupyter Web App | apps/jupyter/jupyter-web-app/upstream | components/crud-web-apps/jupyter/manifests | https://github.com/kubeflow/kubeflow |  |
| Volumes Web App | apps/volumes-web-app | components/crud-web-apps/volumes/manifests | https://github.com/kubeflow/kubeflow |  |
| Tensorboards Web App | apps/tensorboard/tensorboards-web-app | components/crud-web-apps/tensorboards/manifests | https://github.com/kubeflow/kubeflow |  |
| Tensorboard Controller | apps/tensorboard/tensorboard-controller | components/tensorboard-controller/config | https://github.com/kubeflow/kubeflow |  |
| Katib | apps/katib/upstream | manifests/v1beta1 | https://github.com/kubeflow/katib | `v0.11.1` |
| KFServing | apps/kfserving/upstream | config | https://github.com/kubeflow/kfserving | `v0.5.1`  |
| Kubeflow Pipelines | apps/pipeline/upstream | manifests/kustomize | https://github.com/kubeflow/pipelines | `1.5.1` |
| KFP Tekton | apps/kfp-tekton/upstream | manifests/kustomize | https://github.com/kubeflow/kfp-tekton | `v0.8.0`  |

cc @kubeflow/wg-automl-leads
cc @kubeflow/wg-deployment-leads
cc @kubeflow/wg-manifests-leads
cc @kubeflow/wg-notebooks-leads
cc @kubeflow/wg-pipeline-leads
cc @kubeflow/wg-serving-leads
cc @kubeflow/wg-training-leads

**Comment by pvaneck** [comment]
For 1.3.1: 
KFP-Tekton should be v0.8.0.
KFServing should remain the same at v0.5.1.

**Comment by Bobgy** [comment]
I just released [KFP 1.5.1](https://github.com/kubeflow/pipelines/releases/tag/1.5.1) which only introduces bug fixes on top of KFP 1.5.0.
