### ISSUE TITLE
Unable to create authservice-0

### ISSUE THREAD

**Issue by ankur6ue** [kubeflow/manifests#1913]
I'm trying to install Kubeflow on a local kubernetes cluster, and running into issues with starting the auth service in the istio-service namespace.

k get pods -n istio-system

outputs the following:
authservice-0                            0/1     Pending   0          64m
cluster-local-gateway-7c6b74977c-wpnpv   1/1     Running   0          63m
istio-ingressgateway-56d9b7fdb-qtgnz     1/1     Running   0          68m
istiod-7486c5469f-qmwg2                  1/1     Running   0          68m

k describe pod authservice-0 -n istio-system
says:
Warning  FailedScheduling  75s (x69 over 66m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

k get pvc -n istio-system
NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
authservice-pvc   Pending                                                     67m

The problem appears to be related to lack of default storage class. I tried to create one by running kubectl apply -f on:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

so k get storageclass produces:
NAME       PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
default    kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  20m
standard   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  22m

but the problem remains..

please help?

**Comment by rc-coderepo** [comment]
Unless PVC is **bound** you auth service will not deploy. 
Having a storage class set to default is a pre-requisite for kubeflow install. 
Run kubectl get sc and you have to **(default)** which indicated that storage class is default for the cluster. if this goes well you will see the pvc in **Bound** status. 
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

If you using a local kubernetes install you have to setup a host path provisioner. You can do that by installing the below helm chart. 

https://artifacthub.io/packages/helm/rimusz/hostpath-provisioner

**Comment by silverlining21** [comment]
I got the same issue, while using nfs as as default storgeclass
