### ISSUE TITLE
Define what it means to have a deployable Kubeflow installation

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1921]
As part of the Release Handbook review @DavidSpek mentioned the need to further define what "deployable" Kubeflow manifests mean https://github.com/kubeflow/manifests/pull/1907#discussion_r655227264.

Having manifests with no errors does not necessarily mean that someone can just deploy them and have a functioning platform. 

We will need to better define:
1. The extend to which this is delegated to the WGs to ensure their components manifests are functioning as expected
2. How to test that the WG components are working as expected with the common components in the manifests repo [istio, knative etc]

This will allow us to then create automatic tests for ensuring the health of the project as a whole

cc @kubeflow/wg-manifests-leads

**Comment by DavidSpek** [comment]
I think point 1 and 2 might need to be combined. Is it the responsibility of the Working Groups to ensure their component functions as a part of Kubeflow? For example, that KFSering tests the same environment that is deployed with Kubeflow (so the same Istio confit and the profile controller created authorization policy).

**Comment by james-jwu** [comment]
I'd like to touch on a slightly different but relevant topic of trademark usage and conformance. Teams in Google are working on defining conformance criteria for "Kubeflow" distributions. The concept is similar to [Kubernetes conformance](https://www.cncf.io/certification/software-conformance/), where conformance is based on a standard set of tests, and open to any distribution vendors. Each distribution is free to enforce additional testing beyond what is required by Kubeflow conformance.

There is no immediate action needed right now. Just a heads up as more details will be available in the coming months.
/cc @theadactyl
