### ISSUE TITLE
Kubeflow installation error on kfctl_aws.v1.3.0.yaml

### ISSUE THREAD

**Issue by ranjithmr** [kubeflow/manifests#1923]
Error when applying kfctl apply -f kfctl_aws.v1.3.0.yaml

.cache/manifests/manifests-1.3-branch/common/cert-manager/cert-manager-crds/base: no such file or directory
.cache/manifests/manifests-1.3-branch/common/cert-manager/cert-manager-kube-system-resources/base: no such file or directory

**Comment by ajinkya933** [comment]
I face same issue. This is because some one has removed throse files from https://github.com/kubeflow/manifests/tree/v1.3-branch/common/cert-manager  . As kfctl depends on their location in yaml files. These files are gone from their orignal location.

**Comment by ajinkya933** [comment]
cc @yanniszark please update kfctl_aws.v1.3.0.yaml. According to the restructured paths

**Comment by ajinkya933** [comment]
@yanniszark ?

**Comment by surajkota** [comment]
@mageru @atulyadavtech @ajinkya933 @ranjithmr 

In relation to [this issue](https://github.com/kubeflow/manifests/issues/1904), 
AWS distribution is being developed in this repository - [awslabs/kubeflow-manifests](https://github.com/awslabs/kubeflow-manifests). We are moving away from kfctl and using kustomize to install Kubeflow. Checkout the instructions to deploy Kubeflow with various AWS services here: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples.

Please refer to the following tracking issues for 1.3 and 1.4 release:
https://github.com/awslabs/kubeflow-manifests/issues/26
https://github.com/awslabs/kubeflow-manifests/issues/27
