### ISSUE TITLE
Deploying kubeflow 1.3 with Kfdef and using the kubeflow operator

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/manifests#1926]
Hello,

Is it still possible to deploy kubeflow 1.3 using a kfdef (from the example kustomization)? We are using kubernetes 1.20.5 and we would like to deploy kubeflow 1.3 using the operator. We currently receive different errors when we try to replicate the example kustomization.yaml content into a kfdef. Any resouce of the repo would help make this process quicker?

**Comment by rc-coderepo** [comment]
Just use kustomize directly instead of kfdef for v1.3. Follow the instructions from the below link it worked for me. Install the components one by one instead of all at once. 
cert-manager
istio
knative
profiles
KFAM
kubeflow
jupyter notebook


https://github.com/kubeflow/manifests/tree/v1.3.0
