### ISSUE TITLE
Pipeline minio artifact secret - named mlpipeline-minio-artifact; workflow expects minio-artifact

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#193]
I tried running the pipelines sample exit on run and the containers failed to start.

```
Warning  FailedMount  67s (x12 over 9m22s)  kubelet, gke-kf-vmaster-n03-kf-vmaster-n03-cpu-9b8ee2fb-bxb6  MountVolume.SetUp failed for volume "minio-artifact" : secrets "minio-artifact" not found
```

I have a secret named "mlpipeline-minio-artifact"

```
mlpipeline-minio-artifact
```

My guess is kustomize is adding mlpipeline as a common prefix.

We recently upgraded the pipelines to the latest image. Not sure if that changed things.

**Comment by SoheilSalehian** [comment]
Hi @IronPan I am still getting this on GCP running from OSX, did you ever get a fix for this?

`{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:darwin GoArch:amd64}`

**Comment by edwardzjl** [comment]
> Hi @IronPan I am still getting this on GCP running from OSX, did you ever get a fix for this?
> 
> Here's the error in the pod:
> 
> ```
> Warning  FailedMount  6s (x5 over 14s)  kubelet, gke-kubeflow-staging-new-pool-1123efe7-cq83  MountVolume.SetUp failed for volume "mlpipeline-minio-artifact" : secret "mlpipeline-minio-artifact" not found
> ```
> 
> `{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:darwin GoArch:amd64}`

I got the same error, the reason is secret `mlpipeline-minio-artifact` is in namespace "kubeflow" and the pod requires this secret is in per-user namespace (kubeflow-user-example-com for example)

I found a temporary fix in [this comment](https://github.com/kubeflow/kubeflow/issues/5273#issuecomment-831800422)
