### ISSUE TITLE
Unable to view pipelines UI

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/manifests#1931]
Hello,

I am running into this issue while trying to get kubeflow 1.3 running on my kubernetes cluster. All components are deployed successfully (no errors shown in any pod), however, once i pipelines from the centraldashboard i get this error 
`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`

I think this must be an envoy/istio error any idea what is going wrong? I am using istio version 1.9.3

**Comment by rc-coderepo** [comment]
check [here](https://github.com/kubeflow/kubeflow/issues/5271)

kubectl edit destinationrule -n kubeflow ml-pipeline
kubectl edit destinationrule -n kubeflow ml-pipeline-ui
And edited the spec.trafficPolicy.tls.mode section, changing its value from ISTIO_MUTUAL to DISABLE. The I could visit the pipelines section.

**Comment by Hmr-ramzi** [comment]
@rc-coderepo This will make the encryption disabled. We would like to keep using mode ISTIO_MUTUAL. Anyidea how to keep using it ?

**Comment by thunderboltsid** [comment]
Any updates on this? FYI @johnugeorge @deepak-muley

**Comment by rc-coderepo** [comment]
@thunderboltsid  I have reinstalled kubeflow using v1.3.0 using kustiomize and I did not get this issue. I have installed it on a on-prem kubernetes

**Comment by GerardoGR** [comment]
The suggestion provided by https://github.com/kubeflow/kubeflow/issues/5271#issuecomment-694087514 worked for me but I needed to make sure to restart ALL the pods in the namespace: there was TLS error from the `ml-pipeline` component to `mysql`. 
I'm running version: https://github.com/kubeflow/manifests/commit/3dad839fb0e34a236b89961c7ed490d606ae4dbf. Maybe that can also work for you @Hmr-ramzi ?

**Comment by andre-lx** [comment]
for anyone facing this issue, check this comment: https://github.com/kubeflow/pipelines/issues/5244#issuecomment-844144159

**Comment by saumilsdk** [comment]
Here is how I fixed it for KF 1.4 and K8 1.21

![image](https://user-images.githubusercontent.com/8816702/176830584-4efc8d1a-0b78-40e6-bc6b-07d1c8fbc568.png)

**Comment by cateto** [comment]
```
ISTIO_MUTUAL -> DISABLE 
```
It works for me.
but why does it work?
I'm curious

**Comment by snps-sagarrao** [comment]
> check [here](https://github.com/kubeflow/kubeflow/issues/5271)
> 
> kubectl edit destinationrule -n kubeflow ml-pipeline kubectl edit destinationrule -n kubeflow ml-pipeline-ui And edited the spec.trafficPolicy.tls.mode section, changing its value from ISTIO_MUTUAL to DISABLE. The I could visit the pipelines section.

This resolution fixed the same error message I was receiving in my Azure AKS's Kubeflow section Experiment (KFP) .
