### ISSUE TITLE
Upgrade kubeflow from version 1.2 to version 1.3

### ISSUE THREAD

**Issue by roy-tonal** [kubeflow/manifests#1940]
Is there any document available for upgrading kubeflow from version 1.2 to version 1.3 on AWS EKS cluster ?

I tried to deploy kubeflow version 1.3 on already running version 1.2, but it's giving below error.

```
WARN[0018] Encountered error applying application istio-stack:  (kubeflow.error): Code 500 with message: Apply.Run : [error when creating "/tmp/kout213540586": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
	* envoy filter: unknown message type "udpa.type.v1.TypedStruct"
	* envoy filter: unknown message type "udpa.type.v1.TypedStruct"
	* envoy filter: unknown message type "udpa.type.v1.TypedStruct"
, error when creating "/tmp/kout213540586": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
	* envoy filter: subfilter match requires filter match with envoy.http_connection_manager
	* envoy filter: subfilter match requires filter match with envoy.http_connection_manager
	* envoy filter: subfilter match requires filter match with envoy.http_connection_manager
, error when creating "/tmp/kout213540586": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: unknown message type "envoy.extensions.filters.http.lua.v3.Lua"]  filename="kustomize/kustomize.go:284"
WARN[0018] Will retry in 3 seconds.                      filename="kustomize/kustomize.go:285"
``` 

Any help or documents will be highly appreciated.

Note : - I'm using `kfctl_aws.v1.3.0.yaml` file to deploy kubeflow on EKS cluster.

**Comment by JaimeHolland** [comment]
@roy-tonal  did you make any progress with this as I have the same error?

**Comment by goswamig** [comment]
@roy-tonal @JaimeHolland we provide instructions on how to deploy kf-1.3 on EKS [here](https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples).

I am not sure what process you have followed but istio version has changed in kf-1.3 compared to kf-1.2, so quite possible that istio might have backward compatibility issue during upgrade.

Let us know if you face any issue.
