### ISSUE TITLE
AutoML WG and Kubeflow 1.4 release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1958]
@kubeflow/wg-automl-leads let's use this tracking issue to coordinate the integration of AutoML with the Kubeflow 1.4 release.

First off a heads up that the feature freeze phase will start this Monday (16th August). Before then I'd like to have updated this repo with the manifests of the `kubeflow/katib` repo, in order to be able to cut the first RC tag in this repo.

So what I'd like to ask as a first step before the feature freeze is:
1. What version of Katib would you like to include for the 1.4 release?
2. Could you provide me with a branch/tag for this version? It doesn't have to be final. The branch/tag provided can keep on getting fixes through out the release process, but not new features
3. Are there any open issues/work in progress that you will be working on for your version as the KF release process will be progressing?
3. What will the K8s supported versions be for `kubeflow/katib`?

**Comment by kimwnasptd** [comment]
@andreyvelich @johnugeorge based from today's AutoML WG my current understanding is that there will be an RC branch/tag for `kubeflow/katib` by the end of this week. Is this an accurate description of Plan A?

The main issues that AutoML WG will be working on in parallel and fixing as the KF 1.4 process goes on are described in https://github.com/kubeflow/katib/issues/1597 right?

**Comment by andreyvelich** [comment]
@kimwnasptd Yes, we will cut the RC.0 by end of this week, as you mentioned we can track it here: https://github.com/kubeflow/katib/issues/1597.

> What version of Katib would you like to include for the 1.4 release?

We will have Katib 0.12 release.

> Could you provide me with a branch/tag for this version? It doesn't have to be final. The branch/tag provided can keep on getting fixes through out the release process, but not new features

Once we cut the release, I will give you the first tag for 0.12 release.

> Are there any open issues/work in progress that you will be working on for your version as the KF release process will be progressing?

We are planing to merge these changes in Katib 0.12 release: https://github.com/kubeflow/katib/issues/1534, https://github.com/kubeflow/katib/pull/1613, https://github.com/kubeflow/katib/pull/1617.

cc @kubeflow/wg-automl-leads

**Comment by kimwnasptd** [comment]
Sounds good, thanks for the update!

**Comment by kimwnasptd** [comment]
Small heads, we are now in the Feature Freeze phase and updating the docs in kubeflow.org
https://github.com/kubeflow/manifests/tree/master/docs/releases/release-1.4#timeline

If you have any issues you'd like to work on for updating the docs, for the KF 1.4 release, please add a comment in https://github.com/kubeflow/website/issues/2879 so we can track them.

**Comment by kimwnasptd** [comment]
closing this, since KF 1.4 has been released

/close
