### ISSUE TITLE
Pipelines WG and Kubeflow 1.4 release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1959]
@kubeflow/wg-pipeline-leads let's use this tracking issue to coordinate the integration of Pipelines with the Kubeflow 1.4 release.

First off a heads up that the feature freeze phase will start this Monday (16th August). Before then I'd like to have updated this repo with the manifests of the kubeflow/pipelines repo, in order to be able to cut the first RC tag in this repo.

So what I'd like to ask as a first step before the feature freeze is:
1. What version of Pipelines would you like to include for the 1.4 release?
2. Could you provide me with a branch/tag for this version? It doesn't have to be final. The branch/tag provided can keep on getting fixes through out the release process, but not new features
3. Are there any open issues/work in progress that you will be working on for your version as the KF release process will be progressing?
3. What will the K8s supported versions be for kubeflow/pipelines?

**Comment by kimwnasptd** [comment]
@Bobgy @zijianjoy should I use the https://github.com/kubeflow/pipelines/tree/v1.7.0-alpha.3 tag as a starting point for the RC of the manifests?

**Comment by kimwnasptd** [comment]
@Bobgy @zijianjoy kind ping for this

**Comment by Bobgy** [comment]
1. We want to use 1.7.0
2. We can start with 1.7.0-rc.3, final release ETA next week. We will cut a release branch if patch versions are required.
3. We will finish the release.
4. I am interested in how many distributions can run docker container runtime. For the other distributions, we would recommend emissary executor now. https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/. I think both will support 1.18~ 1.21. 1.22 support is pending https://github.com/kubeflow/pipelines/issues/6014.

**Comment by kimwnasptd** [comment]
Small heads, we are now in the Feature Freeze phase and updating the docs in kubeflow.org
https://github.com/kubeflow/manifests/tree/master/docs/releases/release-1.4#timeline

If you have any issues you'd like to work on for updating the docs, for the KF 1.4 release, please add a comment in kubeflow/website#2879 so we can track them.

**Comment by Bobgy** [comment]
We just released 1.7.0.
It fixes a blocker issue: https://github.com/kubeflow/manifests/issues/1985.

**Comment by kimwnasptd** [comment]
closing this, since KF 1.4 has been released

/close
