### ISSUE TITLE
Serving WG and Kubeflow 1.4 release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1960]
@kubeflow/wg-serving-leads @pvaneck  let's use this tracking issue to coordinate the integration of KFServing with the Kubeflow 1.4 release.

First off a heads up that the feature freeze phase will start this Monday (16th August). Before then I'd like to have updated this repo with the manifests of the kubeflow/kfserving repo, in order to be able to cut the first RC tag in this repo.

So what I'd like to ask as a first step before the feature freeze is:
1. What version of KFServing would you like to include for the 1.4 release?
2. Could you provide me with a branch/tag for this version? It doesn't have to be final. The branch/tag provided can keep on getting fixes through out the release process, but not new features
3. Are there any open issues/work in progress that you will be working on for your version as the KF release process will be progressing?
3. What will the K8s supported versions be for kubeflow/kfserving?

Also note, that we are already tracking the update of Knative to v0.22 in https://github.com/kubeflow/manifests/issues/1957

**Comment by kimwnasptd** [comment]
@yuzisun @pvaneck I'll go on and use the `0.6` version from the https://github.com/kubeflow/kfserving/tree/v0.6.0 tag.

**Comment by pvaneck** [comment]
Hey @kimwnasptd , yea let's go with the 0.6 release.  I just created a PR to pin the image tags in the release-0.5 branch: https://github.com/kubeflow/kfserving/pull/1763 . So once that merges, the PR of that commit can be used to sync with manifests.

**Comment by kimwnasptd** [comment]
Thank you very much @pvaneck! That should be more than enough for now to sync manifests and create the first RC here.

**Comment by kimwnasptd** [comment]
Small heads, we are now in the Feature Freeze phase and updating the docs in kubeflow.org
https://github.com/kubeflow/manifests/tree/master/docs/releases/release-1.4#timeline

If you have any issues you'd like to work on for updating the docs, for the KF 1.4 release, please add a comment in kubeflow/website#2879 so we can track them.

**Comment by kimwnasptd** [comment]
closing this, since KF 1.4 has been released

/close
