### ISSUE TITLE
kubeflow high CPU utilization

### ISSUE THREAD

**Issue by EnasBasset** [kubeflow/manifests#1968]
after deploying kubeflow on our environment, CPU utilization became very high it went above 100% all the time.

Our environment Specs:
we have kubernetes cluster deployed on one server (one node works as master and worker)

- OS: Ubuntu 18.04.5 LTS
- kernel version: 4.15.0-142-generic
- RAM: 256 GB
- Sockets: 2
- Cores per socket: 14
- Threads per core: 2
- CPUs: 56
- Kubernetes version: 1.20.6
- kustomize version: 3.2.0

we have installed kubeflow by following the guide for installing individual components [Kubeflow install individual components](https://github.com/kubeflow/manifests#install-individual-components)

what we did to reduce CPU utilization on server is to apply LimitRange on CPU resources for each namespace related to kubeflow (values are in below table), but this didn’t work for namespace “kubeflow-user-example-com”  (the namespace associated with kubeflow pipelines). we set the LimitRange max to the maximum number of CPU’s we have but it fails with error: **0/1 nodes available: insufficient cpu**

kubeflow pipelines only run when no LimitRange is applied to namespace “kubeflow-user-example-com”
## LimitRange for CPU for kubeflow namespaces:

| namespace | min. CPU | max. CPU |
| ------ | ------ | ------ |
| knative-serving | 1 m | 2000 m |
| kubeflow | 1 m | 5000 m |
| knative-eventing | 1 m | 2000 m |
| istio-system | 1 m | 2000 m |
| auth| 200 m | 800 m |

**Note**: we did a temporary solution to reduce CPU utilization a little bit, we deleted “knative-eventing” namespace. This reduced the utilization but it still high.

**What we want ideally is to diagnose why Kubeflow services are using CPUs to 100% and not leaving any chance for running any application pod . If this is an expected behavior can you suggest the best way to manage the CPU utilization limits? and what are the minimum hardware requirements for deploying kubeflow?**

**Comment by iptizer** [comment]
Are you sure you are talking about "cpu utilization" or about "insufficient cpu".

Please note: "limitrange" is applied on container level! One pod might have multiple containers!

To check whether you mean cpu utilization or only k8s thinks it has to less I recommend posting the output of the following commands:
* `kubectl top nodes`
* `k top pods -A`
* `kubectl describe nodes`
* *maybe more?*
