### ISSUE TITLE
Sync AutoML WG manifests for KF 1.4-RC0

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1970]
Sub issue from #1958 

We need to update the manifests provided by the AutoML WG with this repo, before cutting the first RC of manifests.

cc @kubeflow/wg-automl-leads

**Comment by kimwnasptd** [comment]
We will update based on the upcoming 0.12 version https://github.com/kubeflow/manifests/issues/1958#issuecomment-897991552

**Comment by andreyvelich** [comment]
@kubeflow/release-team Katib 0.12 RC.0 is ready.
You can take manifests from the corresponding tag: https://github.com/kubeflow/katib/tree/v0.12.0-rc.0/manifests/v1beta1.

cc @kubeflow/wg-automl-leads
