### ISSUE TITLE
Sync Training WG manifests for KF 1.4-RC0

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1971]
Sub issue from #1962 

We need to update the manifests provided by the Training WG with this repo, before cutting the first RC of manifests.

cc @kubeflow/wg-training-leads

**Comment by Jeffwan** [comment]
@kimwnasptd we just update the manifest tag. https://github.com/kubeflow/tf-operator/pull/1364

This is good candidate for KF1.4-RC0. Do you want us to update manifest in this repo or release team will take care of it?

**Comment by kimwnasptd** [comment]
Thanks for the heads up @Jeffwan. It's OK we will take it from here for updating the manfiests, thanks for asking though!

I'll do the update based on our conversation here https://github.com/kubeflow/manifests/issues/1962#issuecomment-899662895. 

Also apologies for having duplicate context in two issues. In the future I'll try to keep this context only in the subissues, for things we might to discuss for the release, and link to them from the main tracking issues.
