### ISSUE TITLE
Sync Pipelines WG manifests for KF 1.4-RC0 

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1973]
Sub issue from #1959 

We need to update the manifests provided by the Pipelines WG with this repo, before cutting the first RC of manifests.

cc @kubeflow/wg-pipeline-leads

**Comment by zijianjoy** [comment]
Kubeflow Pipelines 1.7 release is currently in progress. We plan to include KFP 1.7 in Kubeflow 1.4 release.
