### ISSUE TITLE
Discuss proposal to remove patch releases

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#1978]
During the community meeting [Aug 17th](http://bit.ly/kf-meeting-notes), the topic of removing the patch release was brought up (again) for discussion. During the meeting, it was asked that the current 1.4 release team take ownership of the topic to discuss among themselves and bring back a proposal to the community.

@kubeflow/wg-automl-leads @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @kubeflow/kfserving-owners
please share any initial feedback on the topic if you have any

/assign @kimwnasptd @RFMVasconcelos @DavidSpek @mkbhanda (1.4 release team)

**Comment by mkbhanda** [comment]
@annajung I do not understand this question. We mentioned this in the release handbook ... there will be resource contention if we have to deliver a patch release in parallel with a regular release, such as 1.4 and 1.3.2.  It will need to be handled on a case by case basis, depending on number of affected users or criticality of bug, security bug etc to work on the patch release versus fold in a fix into the upcoming regular fix. More likely than not, delivering fix in regular release makes sense if it is not a major release, that is with backward compatible.

**Comment by annajung** [comment]
@mkbhanda my understanding from the community meetings is that previously, kubeflow did not have regularly scheduled releases. However, with the release team forming and with the agreed schedule for future kubeflow releases, to remove the burden of distribution of owners and other dependent for multiple releases happening at the same time, it was suggested to remove and/or find alternatives to patch releases.

It was discussed during the [August 3rd community meeting](https://youtu.be/GZGPfftEvs8) and a little bit during today's community meeting if you want to take a look. I think @kimwnasptd would be able to provide a better perspective of the question as the one who raised the discussion.

**Comment by jbottum** [comment]
I like this discussion.   I think we need to keep our options open.   I would like to learn from 1.3 and minimize our testing & documentation cycles if possible.   Is there difference between (RC0, RC1, RC2-Stable? and then 1.4) vs (RC0, RC1, 1.4 and then 1.4.1) ?  Is this a naming change or a process change ?  will it impact our testing and documentation workload?   will it impact our quality i.e will users adoption / use a RC2-Stable ?

**Comment by thesuperzapper** [comment]
An alternative is to just name them differently, I think using a third-dot implies we adhear to [SemVer](https://semver.org/), but this is NOT the case.

__Here is my proposal for version names:__
- `Kubeflow 1.4` (initial release)
- `Kubeflow 1.4-patch.1` (first post-release patch)
- `Kubeflow 1.4-patch.2` (second post-release patch)

**Comment by annajung** [comment]
> Is there difference between (RC0, RC1, RC2-Stable? and then 1.4) vs (RC0, RC1, 1.4 and then 1.4.1) ? Is this a naming change or a process change ? 

I think the difference between the two is that 1.4.1 implicates another release after 1.4 and during 1.5 release which has a chance of overlaping with 1.5.0-rc.0 resulting in that extra load required for distribution owners mentioned during the community meeting. 

If I understand the concern correctly, I think the overall problem that we're trying to solve is how to solve the overlapping releases. If I misunderstood the problem, feel free to chime in.

**Comment by Jeffwan** [comment]
If the process can be improved to achieve fast release. I would suggest to keep patch release. It's hard to keep minor version correct. semantic versioning is widely used and we don't need to change the process.

**Comment by thesuperzapper** [comment]
@Jeffwan I see two problems:
1. we __currently don't__ use Semantic versioning
2. we should support older versions with bug/security fixes

How we version "Kubeflow" (as a whole, not the components) should be discussed, but personally, I don't think we _should_ use semantic versioning, given how Kubeflow is not 1 application. This is why I propose changing to a clearly non-semantic naming convention: `Kubeflow 1.3-patch.1` and `Kubeflow 1.3`

**Comment by Jeffwan** [comment]
what's diff between 1.3.0 and 1.3.1? From past release experiences, only bug fixes should come to `1.3.1` which is equivalent to `1.3-patch.1` ?

**Comment by Bobgy** [comment]
Maybe from a different point of view, why do we think handling a patch release and a minor release is sth we want to avoid?

Is it because we don't have enough automated testing for all the kubeflow components, so that distribution owners have to test them manually?

Maybe we should fix this problem instead?
