### ISSUE TITLE
install on openshift 4.7 with kfctl_openshift_v1.3.0.yaml hit issue: /tmp/kubeflow/kubeflow/.cache/manifests/manifests-1.3-branch/common/cert-manager/cert-manager-kube-system-resources/base: no such file or directory

### ISSUE THREAD

**Issue by wangjun1974** [kubeflow/manifests#1983]
(kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize: (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for cert-manager: accumulating resources: recursed accumulation of path '../../.cache/manifests/manifests-1.3-branch/distributions/stacks/openshift/application/cert-manager': accumulating resources: accumulating resources from '../../../../../common/cert-manager/cert-manager-kube-system-resources/base': open /tmp/kubeflow/kubeflow/.cache/manifests/manifests-1.3-branch/common/cert-manager/cert-manager-kube-system-resources/base: no such file or directory

**Comment by nakfour** [comment]
wangjun1974  please use this example kfdef that pulls from the tag. In KF tags are stable not branches : https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml
