### ISSUE TITLE
Distro representatives for KF 1.4 release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#1995]
We will need to have a list of distribution representatives that can give updates during the [`Distribution testing`](https://github.com/kubeflow/manifests/blob/master/docs/releases/handbook.md#distribution-representative) phase.

Following the list provided in the docs I've created the following table:
https://www.kubeflow.org/docs/started/installing-kubeflow/#install-a-packaged-kubeflow-distribution

| Distribution | Representatives |
| - | - |
| Arrikto EKF | @kimwnasptd @yanniszark  |
| Arrikto MiniKF | @kimwnasptd @yanniszark  |
| Azure | :question:  |
| AWS | @surajkota  |
| Charmed Kubeflow | @knkski @DomFleischmann  |
| Google Cloud | @zijianjoy  |
| IBM | @yhwang |
| Nutanix | @johnugeorge   |
| Kubeflow on MicroK8s | @knkski @DomFleischmann | :x:  |
| Kubeflow Operator | :question:  | :x:  |
| Kubeflow with Argo CD | @DavidSpek | :x:  |
| Openshift | :question:  | :x:  |

**Comment by kimwnasptd** [comment]
@surajkota I added you based on this comment https://github.com/kubeflow/manifests/pull/1975#issuecomment-899713149

@Bobgy @zijianjoy should I add you as representatives for `Kubeflow on Google` for this release?

@nakfour should I add you as the representative for `Kubeflow Operator` and `Openshift`?

@moficodes @pvaneck who will be the representative for `IBM`? Will it be both? Someone else?

@kubeflow/azure who will be the representative for `Azure`?

**Comment by zijianjoy** [comment]
Thanks @kimwnasptd for identifying distro representatives! I am the point-of-contract for Kubeflow Google Cloud this time.

**Comment by pvaneck** [comment]
@yhwang will be the IBM representative for this release.

**Comment by yhwang** [comment]
@kimwnasptd looks forward to working with you and the community.

**Comment by knkski** [comment]
@kimwnasptd Can @ca-scribner be added as a representative for Charmed Kubeflow and Kubeflow on MicroK8s? Thanks!
