### ISSUE TITLE
[connection refused]error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io"

### ISSUE THREAD

**Issue by Corezcy** [kubeflow/manifests#2004]
When I run the`while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
`  , get the result:
```shell
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.1.104.117:443: connect: connection refused
```
I want to know whether it's a problem of network ? I have tried to install the `kubeflow` for 2 weeks , but still have problems.
> Firstly , I  tried to install kubeflow by  https://github.com/shikanon/kubeflow-manifests ,but still have problems anyway

Wait for reply, thx!

**Comment by MISSEY** [comment]
I am having the same issue  : 

my kubectl version

`ubectl version --v=10
I1210 10:30:01.517955  151960 loader.go:375] Config loaded from file:  /home/sami02/.kube/config
I1210 10:30:01.519059  151960 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.16 (linux/amd64) kubernetes/e37e4ab" 'https://10.249.6.9:6443/version?timeout=32s'
I1210 10:30:01.529846  151960 round_trippers.go:444] GET https://10.249.6.9:6443/version?timeout=32s 200 OK in 10 milliseconds
I1210 10:30:01.529867  151960 round_trippers.go:450] Response Headers:
I1210 10:30:01.529875  151960 round_trippers.go:453]     Cache-Control: no-cache, private
I1210 10:30:01.529885  151960 round_trippers.go:453]     Content-Type: application/json
I1210 10:30:01.529894  151960 round_trippers.go:453]     Content-Length: 265
I1210 10:30:01.529900  151960 round_trippers.go:453]     Date: Fri, 10 Dec 2021 09:30:01 GMT
I1210 10:30:01.533506  151960 request.go:1097] Response Body: {
  "major": "1",
  "minor": "19",
  "gitVersion": "v1.19.16",
  "gitCommit": "e37e4ab4cc8dcda84f1344dda47a97bb1927d074",
  "gitTreeState": "clean",
  "buildDate": "2021-10-27T16:20:18Z",
  "goVersion": "go1.15.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by 1920853199** [comment]
@MISSEY @Corezcy  How did you solve this problem? I'm sorry I also encountered this problem

**Comment by silverlining21** [comment]
Same issue with flollowing setting.
![image](https://user-images.githubusercontent.com/8264748/175235100-e4af4a97-6da0-46f3-93da-bb6ab604880c.png)
