### ISSUE TITLE
Training Operator missing label for service selector

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [kubeflow/manifests#2005]
After this change https://github.com/kubeflow/manifests/commit/54aa7aea1b3c27d8dbe83dcb49f5877661430639 the service use this selector: `name: training-operator` but there is no such label on pod.

Related to https://github.com/kubeflow/tf-operator/issues/1399

**Comment by Jeffwan** [comment]
This has been addressed in https://github.com/kubeflow/tf-operator/pull/1404

/close
