### ISSUE TITLE
XGBoost-operator & not exposed prometheus port

### ISSUE THREAD

**Issue by alexeykaplin** [kubeflow/manifests#2010]
XGBoost-operator has Prometheus port missing in kubeflow deployment.

It is already fixed in a repository.
https://github.com/kubeflow/xgboost-operator/blob/579a656311423762f21873d6ecbbc87fcdff628f/config/default/manager_prometheus_metrics_patch.yaml

It is working in an app:
`{"level":"info","ts":1629077650.1979568,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}`

`xgboost-operator` service has port annotation: `prometheus.io/port=8080`
But bort is blocked.

So ... maybe, we can unblock it?

**Comment by Jeffwan** [comment]
@deepak-muley Can you help verify if latest training operator has similar issue?
