### ISSUE TITLE
training-operator: Service cannot find matching pods

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/manifests#2018]
The training-operator service selector is `name: training-operator`:
https://github.com/kubeflow/manifests/blob/master/apps/training-operator/upstream/base/service.yaml#L18

The training-operator deployment label is `control-plane: kubeflow-training-operator`
https://github.com/kubeflow/manifests/blob/master/apps/training-operator/upstream/base/deployment.yaml#L6

Because the labels and selectors are not matching, training-operator service cannot find any matching pods.

**Comment by kimwnasptd** [comment]
Thanks for catching this @zijianjoy!

/cc @kubeflow/wg-training-leads

**Comment by Jeffwan** [comment]
@deepak-muley  https://github.com/kubeflow/tf-operator/issues/1399 tracked here.

**Comment by Jeffwan** [comment]
@kimwnasptd  How can we update the training operator manifest?
