### ISSUE TITLE
Kubeflow Jupyter Notebook disconnect/reset before headers

### ISSUE THREAD

**Issue by ZA-NVG** [kubeflow/manifests#2029]
I have installed Kubeflow and configured it to listen on HTTPS

When I launched Jupyter Notebook, it shows the error:
![image](https://user-images.githubusercontent.com/90952517/133952259-08c5b695-daae-42c8-a0cc-e83ce9ff4691.png)

Any Ideas how to troubleshoot? Or what went wrong?

**Comment by rc-coderepo** [comment]
Which version did you install and is it using kustomize?

**Comment by ZA-NVG** [comment]
I installed v1.3.0-rc.0-28-g3eab165b and yes, I used kustomize

**Comment by ZA-NVG** [comment]
Attached file is the outputs for:

- kubectl get pods -n kubeflow
- kubectl get svc -n kubeflow
- kubectl get pods -n istio-system
- kubectl get svc -n istio-system



[Kubeflow-istio_status.txt](https://github.com/kubeflow/manifests/files/7214827/Kubeflow-istio_status.txt)
