### ISSUE TITLE
Distributions readiness for KF 1.4

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2038]
Previous issue for 1.3.1: https://github.com/kubeflow/manifests/issues/1949
Pinging people based on: https://github.com/kubeflow/manifests/issues/1995

Lets use this issue to keep feedback from the different distros, how is their progress with the current RC as well as bugs they might bump into with KF 1.4 manifests. I'll use the table bellow for an easier visualization.

| Distribution | Representatives | State | 
| - | - | - |
| Arrikto EKF | @kimwnasptd @yanniszark  | :heavy_check_mark: |
| Arrikto MiniKF | @kimwnasptd @yanniszark  | :heavy_check_mark: |
| Azure | :question:  | :x: |
| AWS | @surajkota  | :x: |
| Charmed Kubeflow | @knkski @DomFleischmann  | :x: |
| Google Cloud | @zijianjoy  | :x: |
| IBM | @yhwang | :white_check_mark: |
| Nutanix | @johnugeorge   | :x: |
| Kubeflow on MicroK8s | @knkski @DomFleischmann | :x:  |
| Kubeflow Operator | :question:  | :x:  |
| Kubeflow with Argo CD | @DavidSpek | :x:  |
| Openshift | :question:  | :x:  |

cc @kubeflow/release-team

**Comment by zijianjoy** [comment]
Release candidate for Kubeflow on Google Cloud is made in https://github.com/kubeflow/gcp-blueprints/releases/tag/v1.4.0-rc.0. And this is documentation (PR in progress) to test out Kubeflow 1.4: https://deploy-preview-2957--competent-brattain-de2d6d.netlify.app/docs/distributions/gke/deploy/deploy-cli/. I am targeting end of next week for completion.

**Comment by annajung** [comment]
Hi everyone, this is the link to the notebook created by @andreyvelich that was shared during the community meeting today (Sept 28th) that might help with your testing

- https://github.com/kubeflow/pipelines/blob/master/samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist.ipynb

In addition, please don't forget to make a PR to the website repo to update [Installing Kubeflow](https://www.kubeflow.org/docs/started/installing-kubeflow/) page to show the latest version and correct link to your docs.

**Comment by surajkota** [comment]
@rrkharse is working on AWS distro

**Comment by yhwang** [comment]
doing testing and verification on IBM Cloud. meanwhile waiting for the rc2 and will re-test again then.

**Comment by rrrkharse** [comment]
currently testing and verifying the AWS distro and will update on the status/any issues

**Comment by yhwang** [comment]
found this issue while testing tfjob: https://github.com/kubeflow/manifests/issues/2040

**Comment by DomFleischmann** [comment]
**Charmed Kubeflow and Kubeflow on Microk8s Update**

Stll updating some of the operators but 80% done, tested the updated ones with rc1 and waiting for rc2 to test again.

Bugs encountered during testing:
https://github.com/kubeflow/kubeflow/issues/6056
https://github.com/kubeflow/kubeflow/issues/6016

**Comment by kimwnasptd** [comment]
Thanks for all the feedback everyone! A heads up that I've cut the new [`v1.4.0-rc.2`](https://github.com/kubeflow/manifests/releases/tag/v1.4.0-rc.2) to include the latest Training Operator RC.

**Comment by yhwang** [comment]
thanks @kimwnasptd I synced up `v1.4.0-rc.2` to IBM/manifests repo, deployed and ran some end-2-end testings. So far I don't see any issue at IKS. awesome!

**Comment by kimwnasptd** [comment]
From Arrikto side we are also done testing for MiniKF/EKF. We've bumped into the following two issues, for which I'll do my best to have PRs for the fixes in asap. in order to be included in the 1.4 release 
* Jupyter web app and autoscaling GPU nodegroups: https://github.com/kubeflow/kubeflow/issues/6161 
* Knative gateways and Dex/Authservice https://github.com/kubeflow/manifests/issues/1966.

**Comment by annajung** [comment]
Hi everyone! Based on your feedback, the release team postponed the release to **Thursday, Oct 7th**. Please check out the [announcement for details](https://groups.google.com/u/1/g/kubeflow-discuss/c/qMbvpK5n6EE).

If there are any urgent release-blocking items, please remember to raise them ASAP to the release team. Thanks!
