### ISSUE TITLE
use of sha256 digests instead of tags for images

### ISSUE THREAD

**Issue by snmohan83** [kubeflow/manifests#2039]
Several images used by knative manifests refer to digests for container images which causes problems when moving them to private registry for deployment. Is it possible to update these manifests to use proper tags instead ? 

Below is the list of images that needs attention:

The digests in manifests maps to a tag "v0.22.1" in these packages.

gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/controller:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/mtpingv0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.22.1
gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.22.1

For the following 4 packages used in the manifests (8 character digest shown), the digests do not match any existing tags. 

gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter: a05b1db9
gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller: a6983f71
gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher: 904f42a7
gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker: a2678934

@juliusvonkohout Please add if you have some comments regarding this issue.

**Comment by juliusvonkohout** [comment]
Yes, please create a pull request for 

```
The digests in manifests maps to a tag "v0.22.1" in these packages.

gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/controller:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress:v0.22.1
gcr.io/knative-releases/knative.dev/eventing/cmd/mtpingv0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.22.1
gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.22.1
gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.22.1
gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.22.1
```

that changes them from a digest to v0.22.1

**Comment by juliusvonkohout** [comment]
Those 4 
```
gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter: a05b1db9
gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller: a6983f71
gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher: 904f42a7
gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker: a2678934
```

are missing an upstream tag (except for latest) and that must be fixed in the knative github repository.
