### ISSUE TITLE
Do pipelines support service account for accessing aws s3 and rds

### ISSUE THREAD

**Issue by khemchandanib-el** [kubeflow/manifests#2061]
Hi - 
When we try to install platform dependent i.e. pipelines on aws, we are forced to provide AccessKey and SecretAccessKey.
Can we use iam roles to access/write to s3 and RDS ?
Using this -
https://github.com/kubeflow/manifests/tree/master/apps/pipeline/upstream/env/aws

**Comment by goswamig** [comment]
@khemchandanib-el this limitation currently comes from minio which is a gateway to S3. You can track the progress in AWS manifest [here](https://github.com/awslabs/kubeflow-manifests/issues/44)

**Comment by goswamig** [comment]
meanwhile to mitigate such issues we recommend our user to use aws secret manager to manage your key and reference those secrets as k8s-secret to access AWS resources. 

You can find more details (instructions and manifest) [here](https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3). 

Let us know if you need any further help.
