### ISSUE TITLE
Kubeflow installation mysql not starting up due to pvc not in namespace

### ISSUE THREAD

**Issue by alexcpn** [kubeflow/manifests#2065]
Kubeflow version

```
kubeflow/manifests$ git branch
* (HEAD detached at v1.4.0)
  master
```
```
kubectl -n kubeflow describe pod mysql-f7b9b7dd4-j52jr
```
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  27s   default-scheduler  0/1 nodes are available: 1 persistentvolumeclaim "mysql-pv-claim" not found.
  Warning  FailedScheduling  25s   default-scheduler  0/1 nodes are available: 1 persistentvolumeclaim "mysql-pv-claim" not found.
```

Correction

```
alex@pop-os:~/kubeflow/manifests$ cat << EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
EOF
```
https://github.com/kubeflow/manifests/blob/d36fc9c0555c936c7b71fd273b8e4604985ebba8/apps/pipeline/upstream/third-party/mysql/base/mysql-pv-claim.yaml

**Comment by rc-coderepo** [comment]
If you installed kubeflow using kustomize the pvc should be create automatically. Are you running a kubernetes multi node cluster or single node cluster?

What type of storage are you using in the cluster? if you are running on single node and using default local node storage you might need to configure local-storage-provisioner -- example: https://github.com/rancher/local-path-provisioner

What do you see when you run  - 
kubectl get sc 
kubectl get pvc

**Comment by alexcpn** [comment]
Sorry to comment late- the pvc was created; but not in the correct namespace. I put it in the correct namespace and it worked
