### ISSUE TITLE
mpi-operator pod crashes with -kubectl-delivery-image flag not defined

### ISSUE THREAD

**Issue by athensofamerica** [kubeflow/manifests#2068]
Deploy kubeflow on aws with kfctl following instruction here
https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/

with https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml

This resulted in mpi-operator pod crashes with  error "-kubectl-delivery-image flag not defined"

Looking at the mpi-operator deployment, the container spec refers to the latest docker image instead of v0.2.3
        image: mpioperator/mpi-operator:latest

Manually change the image tag to v0.2.3 with the following command fixed the issue:
"k edit deployment mpi-operator -n kubeflow"

**Comment by goswamig** [comment]
@athensofamerica do u same the issue in latest versions like 1.3 and 1.4 ?

**Comment by athensofamerica** [comment]
@goswamig I don't have the issue with 1.3 anymore
