### ISSUE TITLE
istio keep running into issue

### ISSUE THREAD

**Issue by leeadh** [kubeflow/manifests#2074]
I keep running into this issue: 

```
  Warning  FailedMount  86s (x9 over 3m33s)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  80s (x9 over 3m31s)  kubelet            MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```

Been at this for 2 whole days and cant resolve it.

Minikube k8 version : v1.19
KustomizeVersion:3.2.0
kubectl: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19
![image](https://user-images.githubusercontent.com/15122358/140958528-80777028-9db6-4791-8746-55355bf546d5.png)
", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/

**Comment by leeadh** [comment]
Is there any help ?

**Comment by mikwieczorek** [comment]
Version that worked for me: Kustomize=3.2, k8s=1.19 

Try adding this flags when starting minikube
```
minikube start \
    --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/sa.key \
    --extra-config=apiserver.service-account-key-file=/var/lib/minikube/certs/sa.pub \
    --extra-config=apiserver.service-account-issuer=api \
    --extra-config=apiserver.service-account-api-audiences=api,spire-server,nats \
    --extra-config=apiserver.authorization-mode=Node,RBAC \
    --extra-config=kubelet.authentication-token-webhook=true \
```

**Comment by kimwnasptd** [comment]
Hi @leeadh, looking at the logs I think this is the root problem
> the API server does not have TokenRequest endpoints enabled

I've seen a similar behavior when I was testing Kubeflow in a KinD cluster, where the `TokenRequest` API was also not enabled there. I think it's the same case with minikube https://github.com/kubernetes/minikube/issues/7855
