### ISSUE TITLE
Is it a way to customize the default-editor service-account for notebooks during kubeflow deployment?

### ISSUE THREAD

**Issue by asahnovskiy-deloitte** [kubeflow/manifests#2080]
Namespace-scoped service-accounts default-editor and default-viewer are created as part of the profile creation.
I can't find templates or manifest for these serviceaccounts in the repository.
How I can customize these servicesaccounts ?
Basically, I want to add the imagePullSecrets directive to  default-editor serviceaccount by default.
Thanks.

**Comment by grudloffev** [comment]
Hi @asahnovskiy-deloitte, did you manage to find a way to do this?

**Comment by juliusvonkohout** [comment]
Please check the profile controller in kubeflow/kubeflow and soon kubeflow/dashboard. There are also some architectural talks if you want to understand the Kubeflow architecture here 

Kubecon / Kubeflow Summit 2024 Speaker:  https://colocatedeventseu2024.sched.com/event/1YFiH
https://www.youtube.com/watch?app=desktop&v=f7C3v0gJRVI&list=WL&index=1

Kubecon 2023 Speaker: https://kccnceu2023.sched.com/event/1HyY8
https://www.youtube.com/watch?v=wQaOa4Kjxs0

Kubeflow Summit 2023 Speaker: https://www.kubeflow.org/events/kubeflow-summit-2023/
https://www.youtube.com/watch?v=XKHVt2yxQFo

Blogposts:
https://blogs.vmware.com/opensource/2023/06/20/hardening-kubeflow-security-for-enterprise-environments-2/
https://www.cncf.io/blog/2023/07/25/kubeflow-brings-mlops-to-the-cncf-incubator/
