### ISSUE TITLE
KF 1.4.1 patch release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2084]
Creating a tracking issue for the 1.4.1 patch release, to keep all the context here as well.

The need for a patch release was triggered by https://github.com/kubeflow/manifests/issues/2082. Because this issue can affect the vast majority of Kubeflow clusters, we (Manifests WG) would like to have a KF 1.4.1 patch release.

As discussed in the Community Meeting on 12/7/2021 we would like to have these two phases:
| Date | Description |
| --- | --- |
| Dec 14th | Finalize the list of other components and their versions, that will need to be upgraded |
| Dec 21th | Create the new patch release |

We would like to also ask other WGs if they'd like us to do a version bump, in case:
1. An important bug fix, for an issue present in KF 1.4, has been added in a later minor version
2. The component upgrade is for the minor version (i.e. 1.2.0 -> 1.2.1)

cc @kubeflow/wg-automl-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @kubeflow/release-team

**Comment by zijianjoy** [comment]
Hello Kimonas, KFP would like to be picked up for a patch version upgrade (v1.7.1), it contains fixes and patches only: https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md#171-2021-10-30

**Comment by kimwnasptd** [comment]
Hey @zijianjoy , thanks for the heads up! Unfortunately I can't update the KFP version, even though it satisfies the requirements, since I don't have the time to test the final manifests. The above deadlines were taking into consideration the holidays, and aimed to have a week to gather version updates and another one for testing.

I'd like to stick to the proposed timeline that we communicated in the past weeks and release the 1.4.1 patch release before the holidays.

To avoid this situation in the future I can think the following actions:
1. I see that I tagged the Pipelines leads, but you are not in that list. From the release team's perspective we will double down on setting up and tagging the [WG liaison](https://github.com/kubeflow/community/blob/master/releases/handbook.md#working-group-liaison) roles instead of all leads of a WG
2. Ensure the liaisons are up to date in each release, so that we are sure to tag the correct people
3. Have e2e tests for manifests to automate testing and avoid the need for manual cycles

**Comment by zijianjoy** [comment]
Hello @kimwnasptd , I understand the year-end holiday and the urgency of fixing this issue. Thank you so much for getting back to me about the reasons and actions we can take to improve in the future releases. The ideas of actions sound good to me, maybe we can add them to the next release's retrospective to turn them into actual action items.

Just to follow up on the latest of Kubeflow patch release. The proposal is to release on Dec 21st, what is the current status? Is there any change to the proposed release date?

**Comment by kimwnasptd** [comment]
> The proposal is to release on Dec 21st, what is the current status? Is there any change to the proposed release date?

We released the 1.4.1 patch release just before the holidays https://github.com/kubeflow/manifests/releases/tag/v1.4.1. The patch only included the Knative fix.

**Comment by zijianjoy** [comment]
@kimwnasptd Got it, thank you Kimonas for the update!

**Comment by kimwnasptd** [comment]
Since we've released the patch [1.4.1 patch release](https://github.com/kubeflow/manifests/releases/tag/v1.4.1), I'll now close this issue.
