### ISSUE TITLE
Can't install kubeflow on AWS EC2 instances

### ISSUE THREAD

**Issue by BenzhaminKim** [kubeflow/manifests#2091]
I'm installing kubeflow v1.4 on EC2 instances using Kubeflow/manifests manual, but it doesn't work when creating isitio-system.
I've created three ec2 instances and made it Kubernetes cluster by using Calico CNI.
So, I have one master node and two worker nodes.

<img width="1004" alt="Screen Shot 2021-12-20 at 5 34 12 PM" src="https://user-images.githubusercontent.com/37145466/146737697-4ce350d7-e48f-48ab-bab6-d40d07b8e300.png">
<img width="899" alt="Screen Shot 2021-12-20 at 5 35 18 PM" src="https://user-images.githubusercontent.com/37145466/146737712-7389bbb8-7ca2-4c06-ae2a-9a68ca97bc8b.png">
<img width="961" alt="Screen Shot 2021-12-20 at 5 33 50 PM" src="https://user-images.githubusercontent.com/37145466/146737713-30d9604b-5b7b-4dfe-b92b-bc875369d53e.png">

**Version**
Kubernetes version -> v1.21.1

kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

Calico CNI version -> 3.17

Docker version -> 20.10.12

**Comment by goswamig** [comment]
@BenzhaminKim  can you describe those pods with error and capture logs from those pods?

**Comment by goswamig** [comment]
On a side note given that individual vendors are working on changes related to their service integration. We (AWS) also has branch (work in progress) for 1.4. Take a look [here](https://github.com/awslabs/kubeflow-manifests/tree/v1.4-branch).
