### ISSUE TITLE
Versions and Timelines for Kubeflow 1.5 Components.

### ISSUE THREAD

**Issue by DomFleischmann** [kubeflow/manifests#2098]
The Kubeflow Release Team would like to know the versions of the components each Working Group would like to ship for the 1.5 Release.

An initial guess was made in the following [PR](https://github.com/kubeflow/kubeflow/pull/6266) but we would like the WG Leads/Liasions to confirm these versions and also the dates  of when they expect to deliver the initial cuts for these versions so we can start testing them.

Therefore, we would appreciate if a representative for each component could clearly state in this issue the version they expect to deliver with Kubeflow 1.5 and when they expect it to be ready for testing.

Tagging WG Liaisons:
@andreyvelich @kimwnasptd @zijianjoy @Jeffwan @yuzisun

Tagging Release Team:
@annajung @DnPlas @thesuperzapper @surajkota @js-ts @jbottum @shannonbradshaw

**Comment by zijianjoy** [comment]
Currently Kubeflow Pipelines is planning to release v1.8.0 for next Kubeflow release. But we are short on time and staffing, so we request at least one more week extension (maybe more) for the Jan 13th, 2022 feature freeze deadline.

**Comment by kimwnasptd** [comment]
Thanks for opening the issue @DomFleischmann! 

Notebooks WG follows the same release version with the KF release, so we'll do 1.5. I would also like to request a delay of two weeks, since there are some efforts that we want to push https://github.com/kubeflow/kubeflow/issues/6270 that https://github.com/kubeflow/kubeflow/issues/5971 that will require a little bit more time than what I had anticipated.

Plus for Manifests I'm pushing with the testing effort https://github.com/kubeflow/manifests/issues/2099 for which I could definitely use a little bit more time to make sure they'll be ready.

**Comment by DomFleischmann** [comment]
@kimwnasptd Would that delay be for the Code Freeze date of the 13th of January?

**Comment by kimwnasptd** [comment]
Following up from the above feedback and the discussions with the release team we will be moving the release schedule 2 weeks later, to help WGs meet their set goals and versions. This delay will affect all phases of the release, so the feature freeze will start on Jan 26th, the day after the Community Meeting.

I'll create also a PR to update the timeline in our release docs.

Let's keep this issue to gather more feedback on the component versions that the other WGs, Training and AutoML, are planning to include in the KF 1.5 release. cc @andreyvelich @johnugeorge

**Comment by Tomcli** [comment]
Hi, the kfp-tekton project has the v1.1.0 release. Can we update the manifests https://github.com/kubeflow/manifests/tree/master/apps/kfp-tekton/upstream to https://github.com/kubeflow/kfp-tekton/tree/v1.1.0/manifests/kustomize? Thanks.

I can also open a PR if necessary

**Comment by DomFleischmann** [comment]
For any new updates regarding the 1.5 release and updates on each component please use issue #2112

**Comment by Tomcli** [comment]
> Thanks for the heads up @Tomcli! I'm preparing some scripts to help automating creating PRs. If you could help review/merge it would be awesome!

Sure no problem.
