### ISSUE TITLE
Tensorboards-controller crash loop in OOM Killed

### ISSUE THREAD

**Issue by edwardzjl** [kubeflow/manifests#2101]
Hello there,

We have encountered a problem about the default resources of tensorboards controller.

We deployed kubeflow following [this section](https://github.com/kubeflow/manifests#install-individual-components) about 60 days ago, starting from v1.3 and upgraded to v1.4.1

We did not keep observing all the service status, but as far as I can remember, all pods were in Running state when we first deploy kubeflow v1.3

Currently we notice that the tensorboard-controller pod keeps crashing because of OOM Killed.

We expanded the memory requests to 40mi and limits to 60mi, and the error is still there.

But both to 100mi the error disappeared.

Is the default resource limit too small?

**Comment by veiii** [comment]
Hi,
Yesterday had same issue when I upgrade Kubeflow 1.4.0 to 1.4.1.
In my case tensorboards-controller and training-operator keeps crashing because of OOM Killed.
Memory limit set to 100Mi fixed issue.

On another cluster i try fresh install of Kubeflow 1.4.1 and I did not observe this issue.

**Comment by jaiganeshp** [comment]
Thank you @veiii for your comments. Increasing the memory to 100Mi for tensorboard-controller and training-operator solved restart issue for us in kubeflow 1.4 deployment.

**Comment by juliusvonkohout** [comment]
/close

this belongs to [Kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/tree/master/components/tensorboard-controller)
