### ISSUE TITLE
Notebooks WG and Kubeflow 1.5 release

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2109]
Will use this issue to coordinate alongside the rest @kubeflow/wg-notebooks-leads around the KF 1.5 release. I'm using a slightly different format than https://github.com/kubeflow/manifests/issues/2106 and https://github.com/kubeflow/manifests/issues/2105 since I'm already a member of both the release team and the Notebook leads.

For the necessary information around the release:
* **Versio:** We follow the same versioning with the KF releases and cut the tags alongside the manifests repo. We are targeting 1.5
* **Branch/Tags:** will have the first `v1.5.0-rc0` tag ready tomorrow
* **In progress issues/PRs:** The ones the require more review work, and we will keep a close eye on the feature freeze phase are https://github.com/kubeflow/kubeflow/pull/6297 https://github.com/kubeflow/kubeflow/issues/5971 (will send PR today)
* **K8s:** I have tested with 1.20

**Comment by kimwnasptd** [comment]
Let's also try out our new 
cc @kubeflow/release-team

**Comment by kimwnasptd** [comment]
For Notebooks we've merged our two big PRs we were targeting for the feature freeze
* https://github.com/kubeflow/kubeflow/pull/6297
* https://github.com/kubeflow/kubeflow/pull/6321

I'm preparing the next RC1 right now. We'll keep our eyes open for any problems, this last week of manifests testing

**Comment by kimwnasptd** [comment]
I've identified two more issues for the Notebooks Controller, one of which is quite important:
* https://github.com/kubeflow/kubeflow/issues/6337 [important]
* https://github.com/kubeflow/kubeflow/issues/6336

I have a PR for the second one and another one for the first tomorrow. Hopefully both fixes will be included in the next RC
cc @kubeflow/release-team

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/kubeflow/issues/6382 seems to be a severe regression.

**Comment by imiller445** [comment]
Hi @kimwnasptd , am working through testing the RCs. I apologize if this is just my incomplete knowledge, but I am wondering if there are any notes on why `sidecar.istio.io/inject` was set to true for the central dashboard deployment in https://github.com/kubeflow/manifests/pull/2123 and thus injecting a sidecar into the central dashboard pod. When I have this on, requests don't get properly routed to central dashboard for me. I'm wondering if there is a missing istio resource in the manifests? When I set that back to false, everything works as before.

**Comment by juliusvonkohout** [comment]
> Hi @kimwnasptd , am working through testing the RCs. I apologize if this is just my incomplete knowledge, but I am wondering if there are any notes on why `sidecar.istio.io/inject` was set to true for the central dashboard deployment in #2123 and thus injecting a sidecar into the central dashboard pod. When I have this on, requests don't get properly routed to central dashboard for me. I'm wondering if there is a missing istio resource in the manifests? When I set that back to false, everything works as before.

Are you using a clean install of 1.5rc1? because it does work fine on our cluster. We need it because otherwise the user management is completely broken from a security perspective. There is a long discussions in the issue and pull requests about that.
