### ISSUE TITLE
Cannot access kubeflow dashboard after installation - err 403

### ISSUE THREAD

**Issue by romanzdk** [kubeflow/manifests#2115]
I followed [single step installation](https://github.com/kubeflow/manifests/tree/v1.4-branch#connect-to-your-kubeflow-cluster).

Installation was successful - no errors. `authservice-0` is Pending as well as few other pods from `kubeflow` namespace (e.g. katib, metadata, minio, mysql)

 When I try to connect to kubeflow via [port-forward](https://github.com/kubeflow/manifests#port-forward) I am getting 403 status code.

Pod log:
`istio-ingressgateway-79b665c95-nljf5 [2022-01-25T18:15:07.206Z] "GET / HTTP/1.1" 403 UAEX ext_authz_error - "-" 0 0 1 - "<ip-address>" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36" "448f13e3-1802-98db-b09f-e66de2f00399" "localhost:8080" "-" - - 127.0.0.1:8080 127.0.0.1:39770 - -`

Env: 
kubernetes 1.21.9
kustomize 3.2.1
kubeflow 1.4

**Comment by romanzdk** [comment]
Issue was with authservice-0 pod - no underlying pvc/pv/sc were set. 

Perhaps this should be mentioned in the documentation? Or add manifests that create storage class and persistent volume?

**Comment by laibruce** [comment]
Hi, do you know how to solve this problem, i have the same problem too.

**Comment by romanzdk** [comment]
As I mentioned - I had a problem with no Storage class, Persistent volumes and persistent volume claims set. Check description of authservice-0.
