### ISSUE TITLE
Periodically syncing manifests

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2136]
This is an idea that we went over in a release team meeting, and proposed by @DomFleischmann and @surajkota.

The proposal is for the manfiests repo to be updated periodically. This will assist distributions and adopters to be following the release throughout the whole release cycle, and not wait for the last phases of the release where the manifests will be solidified.

This will require some important work from both Manifests WG and the other WGs:
1. We will need to setup periodic prow jobs that will help in periodically syncing the manifests from the source repos
2. The source repos will need to be updating their images periodically, so that we can then fetch these update into this repo

Let's use this issue to coordinate this effort, and discuss the resources that will be required for this effort.

I'll also ping WGs, to get some more feedback as well
cc @kubeflow/wg-manifests-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-automl-leads @kubeflow/wg-training-leads @kubeflow/release-team  @zijianjoy

**Comment by johnugeorge** [comment]
this is a great suggestion @kimwnasptd

**Comment by juliusvonkohout** [comment]
Given the reworked synchronization scripts this can be done quite easily on demand.

please reopen if necessary.
