### ISSUE TITLE
403 UAEX ext_authz_error

### ISSUE THREAD

**Issue by romanzdk** [kubeflow/manifests#2161]
When accessing localhost:8080 after port-forwarding `kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80` I get:
`"GET / HTTP/1.1" 403 UAEX ext_authz_error - "-" 0 0 0 - ... *some browser info* ... error    envoy envoy_bug    envoy bug failure: !state_.local_complete_ || status == FilterHeadersStatus::StopIteration. Details: Filters should return FilterHeadersStatus::StopIteration after sending a local reply.` 

All pods are running. 

Installed following [this tutorial](https://github.com/kubeflow/manifests#installation)

Kubeflow 1.4
Kubernetes 1.21.9

**Comment by markqiu** [comment]
I have the same problem too.

**Comment by romanzdk** [comment]
@bottum

**Comment by amostech** [comment]
Im also running into the same issue @romanzdk @markqiu have you guys figured this out? Following the same installation mechanism as you guys.  https://github.com/kubeflow/manifests#installation

**Comment by romanzdk** [comment]
I haven't.

**Comment by richardburakowski** [comment]
I also matched on `GET / HTTP/1.1" 403 UAEX ext_authz_error`

In my case `po/authservice-0` looked healthy but further inspection showed it hadn't logged in hours.  Restarting `po/authservice-0` fixed the issue here

`kubectl -n istio-system delete po -l app=authservice ; watch kubectl -n istio-system get po -l app=authservice`

**Comment by pre** [comment]
We got this unhelpful error message. We were able to find out the actual cause by increasing the istio ingress-gateway log level to trace (using istioctl). Then istio-ingressgateway displayed in the logs that the mTLS certificate between the ingress-gateway and extauthz service had expired. (The reason for the expiry is another story and irrelevant to the ext_authz_error. )

**Comment by Nameyc99** [comment]
Facing the same issue on kubeflow v1.6.0, kubernetes v1.22
Tried deleting the pod/atuhservice-0, works after a redeployed, but couldn't get namespace. Then after awhile, couldn't login again.
Is there any other solution?

**Comment by juliusvonkohout** [comment]
/close
Please Upgrade to a vanilla Kubeflow 1.8
