### ISSUE TITLE
cache-deployer Pod fails for kubeflow 1.5 

### ISSUE THREAD

**Issue by akartsky** [kubeflow/manifests#2165]
When installing kubeflow from [latest master](https://github.com/kubeflow/manifests/tree/039442a950916ad9c28a327bfa78a16f022d9939) and rc2 release `cache-deployer-deployment` fails
```
kubeflow       cache-deployer-deployment-6f4bcc969-jxq2f        1/2     CrashLoopBackOff   23         102m
kubeflow       cache-server-575d97c95-md8bg                     0/2     Init:0/1           0          102m
```
Error logs for `cache-deployer` : 
```
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ [[ '' == '' ]]
+ echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.
+ exit 1
```

`cache-server.kubeflow` looks like this :
```
$ kubectl get csr cache-server.kubeflow -o yaml

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2022-03-09T03:05:10Z"
  name: cache-server.kubeflow
  resourceVersion: "306173"
  selfLink: /apis/certificates.k8s.io/v1/certificatesigningrequests/cache-server.kubeflow
  uid: f6179659-fa58-4c3b-a9af-d69543667415
spec:
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:kubeflow
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJREdEQ0NBZ0FDQVFBd1NERXZNQzBHQTFVRUF3d21jM2x6ZEdWdE9tNXZaR1U2WTJGamFHVXRjMlZ5ZG1WeQpMbXQxWW1WbWJHOTNMbk4yWXpzeEZUQVRCZ05WQkFvTURITjVjM1JsYlRwdWIyUmxjekNDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0lHanhzbS83NmdqRy8yWC91OXJpdVR0TUV6b1VJdDVmZFUKQWdIK0xGbVB5Vll4V1VGSmpEbTVhbUNmcmo1aUpIRll1NmxYMitER2gxWmNsMEVBZXJvYi83dm1VYUFOTUJaRwpVaUExMXFRN1ZkMGVuNll1ZnBqZ29CUVN0MTZnWC9FNTNralhQK1FXQ0ErRUNyY1czZG1UdHN4T09kSW9BODdRCjB5U0VhdFhSZFI4ODU5TjF4V0VFTnhXcElzUDdoL1lJSXJ1ZERDV1RiOU5qWWN1bDJCaU9FRXpuMzE2NkREditzQ1VPNW5NTkdkY0JEaVlaMU9SmRJWS9ycTN1MGkrTDNBUFN3aCtoL3V5S3U2Y0Jrc1dMT1ZpdlJHOXFXRnZhQWtDQXdFQUFhQ0JpakNCCmh3WUpLb1pJaHZjTkFRa09NWG93ZURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRUF3SUY0REFUQmdOVkhTVUUKRERBS0JnZ3JCZ0VGQlFjREFUQkpCZ05WSFJFRVFqQkFnZ3hqWVdOb1pTMXpaWEoyWlhLQ0ZXTmhZMmhsTFhObApjblpsY2k1cmRXSmxabXh2ZDRJWlkyRmphR1V0YzJWeWRtVnlMbXQxWW1WbWJHOTNMbk4yWXpBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUF3OCtoMjlWdkk1UjhIMVNvdFFiV0FDTXIrQ2puNGJIaHpwWmh2VDZXcHNuRWZUMWUKbjdRY2RFTi9RZzZHbzJ6bi90eXRoZ0lFb2FlNnc4QTM0Ly9RUjRzbW54U3ZianZIM1BoR0wwY25DV0ZIZEI1bwpVSGZaWlAyS3RDeENPYzFKSXpYYzRURzZCNEg1WWU4OE16NUXXXXXXXXXXTdIeEdpY2EvU0J4Ck01UFBKcU5aUmFVckd6YUt4aStaVjFBYlkzRXVPZ1MrRG8vTFMvNmVmN2I0Z3JWYlBWVkxCVlVEUUFpVU8wK3EKbnRaa1BxTm1sSmIzS0xoWmpKbTJjRGlDaVlOZDBiOGNsUEtwNEZHSnhjMWpmQU1QY3kwangwU05USVhkZ05sVQorTU14anl6Q2wrQkZmWDN3dVV2K0E2ekFiUFBIUjRJaHZCWWprdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kubelet-serving
  uid: e98f0dd7-1480-42dd-b621-3b5790f53ce0
  usages:
  - digital signature
  - key encipherment
  - server auth
  username: system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa
status:
  conditions:
  - lastTransitionTime: "2022-03-09T03:05:10Z"
    lastUpdateTime: "2022-03-09T03:05:10Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved
```

Due to this `cache-server` pod is stuck in Init state :
```
en-xl2s8 webhook-tls-certs istiod-ca-cert istio-data istio-envoy]: timed out waiting for the condition
  Warning  FailedMount  99s (x107 over 3h23m)  kubelet  MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
```

(This doesn't seem to affect the ability to run pipelines/notebook)

Tested on :
EKS - 1.19, 1.20 and 1.21

**Comment by akartsky** [comment]
Steps to replicate the issue : 
```
eksctl create cluster --name check-kf-new-release-20 --region us-east-2 --nodes=5 --version="1.20" 

git clone https://github.com/kubeflow/manifests.git
while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done

# then just watch for the `cache-deployer` pod
# it initially goes into running state before crashing 
kubectl get pods -n kubeflow
```

**Comment by akartsky** [comment]
Confirmed with EKS team that EKS does not issue certificates for CSRs with signerName [kubernetes.io/kubelet-serving](http://kubernetes.io/kubelet-serving) unless the CSR was actually requested by a kubelet.

One suggested solution if we need a certificate for a non-kubelet application, for 1.21 and below we need to use CSR v1beta1 API and signerName "legacy-unknown". 

I will update this ticket with more info but for now this can be tagged as know issue for KF 1.5 on EKS

**Comment by zijianjoy** [comment]
I am not super familiar with cache-deployer, but can the following PRs be related?

- https://github.com/kubeflow/pipelines/pull/6668
- https://github.com/kubeflow/pipelines/pull/7273

**Comment by surajkota** [comment]
@zijianjoy you are right https://github.com/kubeflow/pipelines/pull/7273 introduced breaking change.

**Comment by surajkota** [comment]
yes, both the PRs(https://github.com/kubeflow/pipelines/pull/6668, https://github.com/kubeflow/pipelines/pull/7273) are related. `cache-deployer-deployment` pod is requesting a cert for CSR with signerName `kubernetes.io/kubelet-serving`.

EKS only issues certificates for CSRs with signerName `kubernetes.io/kubelet-serving` for actual kubelets based on the information in the official K8s documentation: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

_kubernetes.io/kubelet-serving`: signs serving certificates that are honored as a **valid kubelet serving certificate** by the API server, but has no other guarantees. Never auto-approved by kube-controller-manager._

It is not supported since it is not recommended in Kubernetes upstream and Kubernetes is recommending to use cert manger controller. This is already being discussed here: https://github.com/kubeflow/pipelines/issues/4695

An alternative to consider is to revert both the PRs and keep using CSR `v1beta1` API and signerName `legacy-unknown` which would mean pipelines would only work in K8s 1.21 and below. Note `kubernetes.io/legacy-unknown`  is not supported in stable v1 API of CSR and hence it will not work for K8s 1.22 and above.

The long term fix for this issue is to work on https://github.com/kubeflow/pipelines/issues/4695 but given the timeframe, I am not sure if it is feasible to complete this. Since this Kubeflow release does not aim to support 1.22, I think the right call for this release is to use `kubernetes.io/legacy-unknown` signer in CSR

**Comment by juliusvonkohout** [comment]
> But given the timeframe, I am not sure if it is feasible to complete this. Since this Kubeflow release does not aim to support 1.22, an alternative for this release is to revert both the PRs and use CSR `v1beta1` API and signerName `legacy-unknown`. This would mean pipelines would only work in K8s 1.21 and below since `kubernetes.io/legacy-unknown` is not supported in stable v1 API of CSR and hence it will not work for K8s 1.22 and above. [kubeflow/pipelines#4695](https://github.com/kubeflow/pipelines/issues/4695) will need to be addressed for K8s 1.22 and above.
> 
> Another alternative is to release 1.5.1 with the right fix i.e. using cert manager if other distributions do not see this as an issue.

I am in favor of fixing it with Kubeflow 1.5.1. according to @annajung https://github.com/kubeflow/manifests/issues/2112#issuecomment-1063040130 only notebooks do not support Kubernetes 1.22. So you could use 1.5.1 to fully support Kubernetes 1.22 and fix the certificates properly.

**Comment by kimwnasptd** [comment]
Thanks for the detailed summary @surajkota!

From what we know about this bug, that:
1. It depends on the K8s Server of the installation
2. Until now we haven't heard from other distros having this problem
3. It's not a blocking issue. In a worst case scenario the caching mechanism of KFP will not work, but pipelines can still be submitted and run

I'll move on with the KF 1.5.0 release as is. Let's keep the discussion on how to fix this for KF 1.5.1
cc @kubeflow/release-team

**Comment by surajkota** [comment]
> Why not just go with signerName: kubernetes.io/kube-apiserver-client and client auth, instead of server auth?
I have been curious about this as well, we will wait for response from pipelines-wg. I have also added this to the agenda in next pipelines community meeting 03/16.

**Comment by akartsky** [comment]
Found some links on why we should not be using `kubernetes.io/kubelet-serving`

https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1513-certificate-signing-request/README.md#importance-of-specsignername

https://github.com/kubernetes/kubernetes/issues/98146#issuecomment-763669437

**Comment by Tomcli** [comment]
> Regarding next steps, indeed using CertManager looks like a step in the right direction. Kubebuilder is also using this for handling the controller/webhook certificates.
> 
> But we will need to hear the feedback from the KFP folks, on whether they would be OK with such a change for the KF 1.5.1 release. Which also means a new patch version for KFP. cc @zijianjoy @chensun
> 
> If using CertManager is not an immediate option, even for KF 1.5.1, I think another alternative would be to investigate why should we use `signerName: kubernetes.io/kubelet-serving` in the first place. Do we need to generate TLS certificates for a webhook to have an identity of a kubelet?
> 
> My understanding so far is:
> 
> 1. The initial PR [[Backend]Initial execution cache pipelines#3036](https://github.com/kubeflow/pipelines/pull/3036) used the `extendedKeyUsage = serverAuth` and `usages: [..., "server auth"]`
> 2. After KF 1.4, in the KFP effort for K8s 1.22 support there was a PR that [chore: Update CertificateSigningRequest to current api version. pipelines#6668](https://github.com/kubeflow/pipelines/pull/6668):
>    
>    1. Used the `v1` version for `CertificateSigningRequest`
>    2. Explicitly set the `signerName: kubernetes.io/kube-apiserver-client`, which is required for K8s 1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#certificatesigningrequest-v122
> 3. This created the issue in [[backend]  cache-deployer generate CSR with wrong usage  pipelines#7093](https://github.com/kubeflow/pipelines/issues/7093) which was resolved by using the `signerName: kubernetes.io/kubelet-serving` [fix(backend): make cache-deployer generate CSR using kubelet-serving signerName pipelines#7273](https://github.com/kubeflow/pipelines/pull/7273)
> 
> So my question remains: why use `server auth` and `signerName: kubernetes.io/kubelet-serving` in the first place? Why not just go with `signerName: kubernetes.io/kube-apiserver-client` and `client auth`, instead of `server auth`? https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

FYI we did try to use client auth. There was an PR to make it to use client auth but that doesn't work for us. 
https://github.com/kubeflow/pipelines/pull/7094

**Comment by akartsky** [comment]
Thanks @Tomcli 

So looks like we need both `client auth` and `server auth`
then using CSR `v1beta1` API and signerName `kubernetes.io/legacy-unknown` is the right way to do it for now 
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

**Comment by Tomcli** [comment]
> Thanks @Tomcli
> 
> So looks like we need both `client auth` and `server auth` then using CSR `v1beta1` API and signerName `kubernetes.io/legacy-unknown` is the right way to do it for now https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

@akartsky Can `kubernetes.io/legacy-unknown` work on CSR v1? I think the main motivation on moving to CSR V1 is to support Kubernetes 1.22 and above.

**Comment by ryansteakley** [comment]
@Tomcli  Looks like according to https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers . The stable `CertificateSigningRequest `API (version `certificates.k8s.io/v1 `and later) does not allow to set the signerName as `kubernetes.io/legacy-unknown`

**Comment by surajkota** [comment]
Summary of discussion from Kubeflow pipeline meeting today:

Here is a consolidated list of docs which indicate using `kubelet-serving` signerName is a bad practice for non-kubelet applications:
https://github.com/kubernetes/kubernetes/issues/98146#issuecomment-763669437
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1513-certificate-signing-request/README.md#importance-of-specsignername
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

- Cache-v1 is an alpha feature and will eventually be deprecated when KFP v1 is deprecated. Cache-v2 would not need cert anymore since it will be using Argo. Since Cache-v1 is an alpha feature, there is no guarantee for support. There is no timeline for deprecating KFP v1 as of today which means we are looking at 1+year timeline.
- Pipelines WG thinks that introducing a cert manager dependency is hard to maintain and upgrade. It would be fine to introduce the cert manager solution as an overlay.
- Next steps to investigate:
  - Do we need a server auth certificate? https://github.com/kubeflow/pipelines/pull/7273 seems to suggest it is needed but  we did not have a definite answer during the meeting
  - If we need server auth, we can take two routes for a patch release in KFP-1.8 and Kubeflow-1.5.1:
    1. Modify the `cache-deloyer` code and create an overlay to use `legacy-unknown` signerName for EKS if other distributions are fine with `kubelet-serving` signerName. We(AWS) will need to see if there will be some other workaround in EKS-1.22 when it is released
    2. Implement the cert manager overlay and make this the default overlay in Kubeflow. Since Kubeflow already depends on cert-manager, there will be no impact. However, users installing Kubeflow pipelines standalone will need to install cert manager as well. `cache-server` will need to be modified for this

**Comment by akartsky** [comment]
ya I can work on the PR which creates an overlay for AWS with cert-manager

**Comment by ReggieCarey** [comment]
Hope this helps:

Kubeflow 1.5 deployed via manifests onto a conformant Kubernetes 1.2 deployed via juju onto an openstack cloud deployed ontop of baremetal managed by MAAS.

cache-deployer-deployment fails to construct a certificate for cache-server.kubeflow csr leading to subsequent failures.

kubectl command to approve a certificate (kubectl certificate approve cache-server.kubeflow) completes and the status of the csr is marked approved, but no certificate is ever affixed to the status.certificate of the csr.

```bash
$ kubectl get csr cache-server.kubeflow
NAME                    AGE     SIGNERNAME                      REQUESTOR                                                             CONDITION
cache-server.kubeflow   4m24s   kubernetes.io/kubelet-serving   system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa   Approved
```
and the status block of that approved csr:

```bash
$ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status}'|jq
{
  "conditions": [
    {
      "lastTransitionTime": "2022-03-25T18:58:47Z",
      "lastUpdateTime": "2022-03-25T18:58:48Z",
      "message": "This CSR was approved by kubectl certificate approve.",
      "reason": "KubectlApprove",
      "status": "True",
      "type": "Approved"
    }
  ]
}
```

I think this leads to an inability to construct the secret webhook-server-tls.

Analysis indicates that the main container as defined by the deployment uses a serviceAccount of ```kubeflow-pipelines-cache-deployer-sa``` which refers to a secret ```kubeflow-pipelines-cache-deployer-sa-token-gm6cz```

That secret looks fine:  contains a ca.crt, token, and namespace ( set to kubeflow ).

This causes the cache-server deployment to fail due to a missing volume mount - webhook-server-tls

See the log output of the cache-deployer-deployment-**-** pod:
```
Start deploying cache service to existing cluster:
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflow
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ mkdir -p /root/bin
+ export 'PATH=/root/bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ kubectl version --output json
+ jq --raw-output '(.serverVersion.major + "." + .serverVersion.minor)'
+ tr -d '"+'
+ server_version_major_minor=1.21
+ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.21.txt
+ stable_build_version=v1.21.11
+ kubectl_url=https://storage.googleapis.com/kubernetes-release/release/v1.21.11/bin/linux/amd64/kubectl
+ curl -L -o /root/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.21.11/bin/linux/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.5M  100 44.5M    0     0  90.4M      0 --:--:-- --:--:-- --:--:-- 90.4M
+ chmod +x /root/bin/kubectl
+ kubectl get mutatingwebhookconfigurations cache-webhook-kubeflow --namespace kubeflow --ignore-not-found
+ kubectl get secrets webhook-server-tls --namespace kubeflow --ignore-not-found
+ webhook_config_exists=false
+ grep cache-webhook-kubeflow -w
+ webhook_secret_exists=false
+ grep webhook-server-tls -w
+ '[' false '==' true ]
+ '[' false '==' true ]
+ '[' false '==' true ]
+ export 'CA_FILE=ca_cert'
+ rm -f ca_cert
+ touch ca_cert
+ ./webhook-create-signed-cert.sh --namespace kubeflow --cert_output_path ca_cert --secret webhook-server-tls
+ [[ 6 -gt 0 ]]
+ case ${1} in
+ namespace=kubeflow
+ shift
+ shift
+ [[ 4 -gt 0 ]]
+ case ${1} in
+ cert_output_path=ca_cert
+ shift
+ shift
+ [[ 2 -gt 0 ]]
+ case ${1} in
+ secret=webhook-server-tls
+ shift
+ shift
+ [[ 0 -gt 0 ]]
+ '[' -z ']'
+ service=cache-server
+ '[' -z webhook-server-tls ']'
+ '[' -z kubeflow ']'
+ '[' -z ca_cert ']'
++ command -v openssl
+ '[' '!' -x /usr/bin/openssl ']'
+ csrName=cache-server.kubeflow
++ mktemp -d
+ tmpdir=/tmp/tmp.ejjJLb
+ echo 'creating certs in tmpdir /tmp/tmp.ejjJLb '
creating certs in tmpdir /tmp/tmp.ejjJLb 
+ cat
+ openssl genrsa -out /tmp/tmp.ejjJLb/server-key.pem 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
......+++++
.......................................................+++++
e is 65537 (0x010001)
+ openssl req -new -key /tmp/tmp.ejjJLb/server-key.pem -subj '/CN=system:node:cache-server.kubeflow.svc;/O=system:nodes' -out /tmp/tmp.ejjJLb/server.csr -config /tmp/tmp.ejjJLb/csr.conf
+ echo 'start running kubectl...'
+ kubectl delete csr cache-server.kubeflow
start running kubectl...
certificatesigningrequest.certificates.k8s.io "cache-server.kubeflow" deleted
+ cat
+ kubectl create -f -
++ cat /tmp/tmp.ejjJLb/server.csr
++ base64
++ tr -d '\n'
certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow created
+ true
+ kubectl get csr cache-server.kubeflow
NAME                    AGE   SIGNERNAME                      REQUESTOR                                                             CONDITION
cache-server.kubeflow   0s    kubernetes.io/kubelet-serving   system:serviceaccount:kubeflow:kubeflow-pipelines-cache-deployer-sa   Pending
+ '[' 0 -eq 0 ']'
+ break
+ kubectl certificate approve cache-server.kubeflow
certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow approved
++ seq 10
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ for x in $(seq 10)
++ kubectl get csr cache-server.kubeflow -o 'jsonpath={.status.certificate}'
+ serverCert=
+ [[ '' != '' ]]
+ sleep 1
+ [[ '' == '' ]]
+ echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.
```

**Comment by surajkota** [comment]
People facing this issue can use Kubeflow-1.5.1 which uses cert-manager for cache-server certificate.

**Comment by snps-jinto** [comment]
> People facing this issue can use Kubeflow-1.5.1 which uses cert-manager for cache-server certificate.

I just tried the following steps on Rancher kubernetes: v1.20.15

setenv PIPELINE_VERSION 1.5.1
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=$PIPELINE_VERSION"

It was having the same issue:

+ echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.

**Comment by andre-lx** [comment]
> People facing this issue can use Kubeflow-1.5.1 which uses cert-manager for cache-server certificate.

I'm still facing this issue with EKS, kubernetes 1.22 and kubeflow 1.5.1. 

Everything works great in AKS kubernetes 1.22 and kubeflow 1.5.1.
