### ISSUE TITLE
Kserve is not installed with Kubeflow 1.5

### ISSUE THREAD

**Issue by cfloressuazo** [kubeflow/manifests#2178]
There is a problem when deploying kserve by installing all the components of kubeflow via `kustomize build ... kubectl apply -f -`, the installation it is not installing KServe but the previous version of KFServing, which messes up with the cluster roles for new profiles using the models after deploying them as `InferenceService`.

**Comment by kairos03** [comment]
I also faced this problem.

v1.5.0 contain `kfserving` and `kserve` both so default kustomize install both.
if you don't need `kfserving`, you need to edit some kustomization.yaml file.

0. remove previous deployments
you need to sure clean delete. if you created any InferenceServices delete it and after that remove crd and others.
```
kubectl get isvc -A
No resources found in istio-system namespace. 
```
```
kustomize build contrib/kserve/kserve | kubectl delete -f -
```

2. edit `examples/kustomization.yaml`, comment out `KFServing` part
```
...
# KFServing
#- ../apps/kfserving/upstream/overlays/kubeflow
...
```

3. edit `contrib/kserve/kserve/kustomization.yaml`
comment out `kserve.yaml` and `aggregated_roles.yaml`. uncomment `kserve_kubeflow.yaml`.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- kserve.yaml
#- aggregated-roles.yaml
# For KF 1.5 we are including both KFServing and KServe. Thus we install the
# standalone kserve manifests, to avoid conflicts with 0.6.1 KFServing.
- kserve_kubeflow.yaml
```

4. apply it!
for install with a single command: 
```
while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

for install individual components
```
kustomize build contrib/kserve/kserve | kubectl apply -f -
```

I think we need to add this to `README.md`
