### ISSUE TITLE
KF 1.5.1 tracking

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2185]
Following up the release of KF 1.5.1 https://github.com/kubeflow/manifests/issues/2112 let's use this issue to discuss items that could go into a 1.5.1 release. 

Based on the items that we'll gather we can then prioritize what to include and define the timeline. The goal of the patch release will be to only include critical bug fixes and security patches.

The biggest one that was brought up during the release was:
* https://github.com/kubeflow/manifests/issues/2165

Let's track new items until next Tuesday, April 12 on which we'll then decide on the timeline

cc @kubeflow/release-team @kubeflow/wg-automl-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @zijianjoy @pvaneck @yhwang

**Comment by surajkota** [comment]
As discussed on slack, I want to propose https://github.com/kubeflow/kubeflow/issues/5965 to be tracked for 1.5.1. This issue has been open from Kubeflow 1.3. Considering Kserve is the default serving solution for Kubeflow, resolving this issue would improve the serving experience.

Here is a PR in progress which addresses this: https://github.com/kubeflow/kubeflow/pull/6013

**Comment by yhwang** [comment]
is it possible to do the knative update: from `0.22.1` to `0.22.3`?

**Comment by jbottum** [comment]
@kimwnasptd any update on Kubeflow 1.5.1 release timing ?

**Comment by jbottum** [comment]
@kimwnasptd is this release available
