### ISSUE TITLE
KF Release 1.6 tracking

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2194]
This issue will be used to provide high-level updates for the Kubeflow 1.6 release.

- [Release Timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.6/README.md)
- [Release Team](https://github.com/kubeflow/community/blob/master/releases/release-1.6/release-team.md)
- [Release Board](https://github.com/orgs/kubeflow/projects/49/views/1)

cc @kubeflow/release-team

**Comment by annajung** [comment]
- [Docs tracking issue](https://github.com/kubeflow/website/issues/3239)
- WG tracking issues
  - [AutoML](https://github.com/kubeflow/manifests/issues/2195)
  - [Training Operator](https://github.com/kubeflow/manifests/issues/2196)
  - [KServe](https://github.com/kubeflow/manifests/issues/2197)
  - [Pipelines](https://github.com/kubeflow/manifests/issues/2198)
  - [Notebook](https://github.com/kubeflow/manifests/issues/2199)
  - [Manifests](https://github.com/kubeflow/manifests/issues/2200)

**Comment by annajung** [comment]
Discussion around dependency versions for 1.6 https://github.com/kubeflow/manifests/issues/2207

**Comment by Tomcli** [comment]
For kfp-tekton project, we want to use kfp-tekton  [v1.2.1](https://github.com/kubeflow/kfp-tekton/releases/tag/v1.2.1) release for KF v1.6. The update script should be available at https://github.com/kubeflow/manifests/blob/master/hack/sync-kfp-tekton-manifests.sh. Thanks.

**Comment by annajung** [comment]
Due to a blocker that was identified last week, we are delaying the release for 2 weeks, with a possibility of another extension

- Tracking issue: https://github.com/kubeflow/testing/issues/1006
- Email announcement: https://groups.google.com/u/2/g/kubeflow-discuss

**Comment by annajung** [comment]
After checking with all WGs, the release team is delaying the release for 2 more weeks. The new feature freeze date is **Wednesday, Jun 29th, 2022**.

- Email announcement: https://groups.google.com/g/kubeflow-discuss/c/I4l97HvrGEA/m/227aCe_mCgAJ
- New schedule PR: https://github.com/kubeflow/community/pull/562

**Comment by annajung** [comment]
Kubeflow 1.6.0-rc.0 is now available!
- release tag: https://github.com/kubeflow/manifests/releases/tag/v1.6.0-rc.0
- announcement: https://groups.google.com/g/kubeflow-discuss/c/wGZJUpkVVBs/m/-ucjru9RAAAJ

**Comment by kimwnasptd** [comment]
Small heads up that there's a confirmed bug with the latest Jupyter web app included in RC0 https://github.com/kubeflow/kubeflow/issues/6572.

This was because I ended up pushing a locally built image that used incorrect cache. This will be resolved on the next RC, once we'll have rebuilt the images of kubeflow/kubeflow

**Comment by juliusvonkohout** [comment]
> Small heads up that there's a confirmed bug with the latest Jupyter web app included in RC0 [kubeflow/kubeflow#6572](https://github.com/kubeflow/kubeflow/issues/6572).
> 
> This was because I ended up pushing a locally built image that used incorrect cache. This will be resolved on the next RC, once we'll have rebuilt the images of kubeflow/kubeflow

I also left a typo in the networkpolicies for 1.6 https://github.com/kubeflow/manifests/pull/2254

**Comment by jhasm** [comment]
> Small heads up that there's a confirmed bug with the latest Jupyter web app included in RC0 [kubeflow/kubeflow#6572](https://github.com/kubeflow/kubeflow/issues/6572).
> 
> This was because I ended up pushing a locally built image that used incorrect cache. This will be resolved on the next RC, once we'll have rebuilt the images of kubeflow/kubeflow

Hi @kimwnasptd when should we expect the next RC with the Jupyter web app bug fixed? And in the meantime, what are the instructions for folks to work around this? 

I see comments on https://github.com/kubeflow/kubeflow/issues/6572 about building from source. Can you please elaborate on this and point to some instructions? What should we build from source and how?

**Comment by annajung** [comment]
A [release blocking issue](https://github.com/kubeflow/manifests/issues/2221#issuecomment-1211081904) has been identified and needs extra time to resolve the issue. Therefore, the release has been delayed. The new proposed release date is Wednesday, Sep 7th 2022 and seeking feedback from the community

Email announcement: https://groups.google.com/g/kubeflow-discuss/c/h0NX0XyUo74/m/6GTCsD7KAAAJ
New proposed release timeline PR: https://github.com/kubeflow/community/pull/569

**Comment by annajung** [comment]
[Kubeflow RC.3 is available](https://github.com/kubeflow/manifests/releases/tag/v1.6.0-rc.3)

announcement: https://groups.google.com/u/2/g/kubeflow-discuss/c/Kwb6qO2_Hf8

**Comment by juliusvonkohout** [comment]
I have some proposition for 1.6.1 already. Something went wrong with the notebook culling https://github.com/kubeflow/kubeflow/issues/6648

**Comment by juliusvonkohout** [comment]
and another big regression in 1.6 https://github.com/kubeflow/pipelines/issues/8256

**Comment by annajung** [comment]
Thanks for identifying these issues @juliusvonkohout.

@kimwnasptd @kubeflow/wg-notebooks-leads @zijianjoy @kubeflow/wg-pipeline-leads, let's continue using this issue to track progress for 1.6.1.

**Comment by nithin8702** [comment]
Hi @annajung Seldon is not working due to k8s migration 1.22. Shall we also include this?

**Comment by nithin8702** [comment]
> 

https://github.com/kubeflow/manifests/issues/2207#issuecomment-1245664517

**Comment by surajkota** [comment]
@annajung @kimwnasptd Created istio issue as discussed https://github.com/kubeflow/manifests/issues/2285

**Comment by surajkota** [comment]
@annajung @kimwnasptd @zijianjoy Kubeflow pipelines has been updated from 2.0.0-alpha.3 to 2.0.0-alpha.5 in 1.6.1-rc0 and there are several new features in it https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.5/CHANGELOG.md. Patch releases should ideally only include bug fixes. We/AWS would like to have some more time to test it and we should also set the right expectations for the customers.

**Comment by juliusvonkohout** [comment]
@surajkota. Yes because KFP is in a transition phase. As soon as 2.0 is released that will not happen anymore. And trust me you want this version since it includes significant security fixes from me and @difince.

**Comment by annajung** [comment]
https://github.com/kubeflow/kubeflow/pull/6664 was brought up in kubeflow-discuss mailing group
tagging @kimwnasptd @kubeflow/wg-notebooks-leads for their review

**Comment by kimwnasptd** [comment]
I'd like to avoid adding any further fixes for 1.6.1, that are not critical for security or render the platform unusable. So I'd propose to finalize the RC and deliver the release on Monday.

With that said though, we'll review https://github.com/kubeflow/kubeflow/pull/6664 to ensure it'll be part of the next release

**Comment by annajung** [comment]
Hi everyone, [1.6.1](https://github.com/kubeflow/manifests/releases/tag/v1.6.1) is now available

kubeflow-discuss announcement: https://groups.google.com/g/kubeflow-discuss/c/amsxyXbY_nk/m/FaWxOd4VBAAJ

**Comment by juliusvonkohout** [comment]
i do not know how it works for you, but adding common/istio-1-14/istio-install/base/deny_all_authorizationpolicy.yaml from 
https://github.com/kubeflow/manifests/pull/2288 broke DEX and other components for me. You get RBAC access denied everywhere. This is also in line with the istio documentation

```
Authorization policy supports CUSTOM, DENY and ALLOW actions for access control. When CUSTOM, DENY and ALLOW actions are used for a workload at the same time, the CUSTOM action is evaluated first, then the DENY action, and finally the ALLOW action. The evaluation is determined by the following rules:

    If there are any CUSTOM policies that match the request, evaluate and deny the request if the evaluation result is deny.
    If there are any DENY policies that match the request, deny the request.
    If there are no ALLOW policies for the workload, allow the request.
    If any of the ALLOW policies match the request, allow the request.
    Deny the request.
```

so i instead did the following 

```
- ../manifests-1.6/common/istio-1-14/istio-install/base/gateway_authorizationpolicy.yaml
# https://istio.io/latest/docs/reference/config/security/authorization-policy/
# We should not block access to istio-ingressgateway-svc.cluster.local by default or dex will fail
# The authorizationpolicies inside of the users namespaces will do he blocking
#- ../manifests-1.6/common/istio-1-14/istio-install/base/deny_all_authorizationpolicy.yaml
- ../manifests-1.6/common/istio-1-14/istio-install/base/x-forwarded-host.yaml
```

**Comment by annajung** [comment]
With [1.6.1 released](https://github.com/kubeflow/manifests/releases/tag/v1.6.1) and [1.7 release](https://github.com/kubeflow/community/tree/master/releases/release-1.7) started, closing out the issue.
