### ISSUE TITLE
KServe and Kubeflow 1.6 release

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2197]
Hello @pvaneck @yuzisun  

The [1.6 release team](https://github.com/kubeflow/community/blob/master/releases/release-1.6/release-team.md) will use this tracking issue to coordinate the integration of the KServe with the Kubeflow 1.6 release.

Heads up that the **feature freeze** is scheduled for **Wednesday, Jun 1st, 2022**. For the full release schedule, refer to the [1.6 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.6/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/558 and https://github.com/kubeflow/community/pull/560)_

To prepare for the 1.6 release, please provide answers to the following questions:
1. What version of KServe would you like to include for the 1.6 release? (Based on the roadmap presentation from Paul during April 26th community meeting, KServe is aiming for v0.9.0 and v0.8.0 as backup)
2. Could you provide a branch/tag for this version? _(note: It doesn't have to be final)_
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.6?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?
  - Knative
  - Istio
  - Kubernetes
  - Cert-Manager
  - Kustomize

The release team WG liaison for KServe WG will be @MStopa and you can keep track of high-level release updates in the [1.6 tracking](https://github.com/kubeflow/manifests/issues/2194) issue.

**Comment by mstopa** [comment]
Hello @annajung @pvaneck @yuzisun

just to summary the discussion regarding Kubeflow 1.6 from the last KServe meeting, the key question is the minimum Kubernetes version that Kubeflow is going to support, as this will dictate what Knative versions can be included.

Please correct me if I got that wrong or there is anything more that you'd like us to take care of.

**Comment by yuzisun** [comment]
That is correct, Thanks @mstopa !

**Comment by surajkota** [comment]
Facing this issue while updating Kserve mainfests: https://github.com/kserve/kserve/issues/2297

**Comment by pvaneck** [comment]
Once https://github.com/kserve/kserve/pull/2296 merges in master, I'll cherry-pick to the KServe `release-0.8` branch, updating the [install manifests ](https://github.com/kserve/kserve/tree/release-0.8/install/v0.8.0)in the process (which is what is used in kubeflow/manifests).

**Comment by pvaneck** [comment]
release branch updated with fixes: https://github.com/kserve/kserve/tree/release-0.8

**Comment by annajung** [comment]
With KF 1.6 released, closing the issue
