### ISSUE TITLE
Pipelines WG and Kubeflow 1.6 release

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2198]
Hello @kubeflow/wg-pipeline-leads @zijianjoy 

The [1.6 release team](https://github.com/kubeflow/community/blob/master/releases/release-1.6/release-team.md) will use this tracking issue to coordinate the integration of the Pipelines with the Kubeflow 1.6 release.

Heads up that the **feature freeze** is scheduled for **Wednesday, Jun 1st, 2022**. For the full release schedule, refer to the [1.6 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.6/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/558 and https://github.com/kubeflow/community/pull/560)_

To prepare for the 1.6 release, please provide answers to the following questions:
1. What version of Pipelines would you like to include for the 1.6 release?
2. Could you provide a branch/tag for this version? _(note: It doesn't have to be final)_
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.6?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?
  - Knative
  - Istio
  - Kubernetes
  - Cert-Manager
  - Kustomize

The release team WG liaison for Pipelines WG will be @DomFleischmann and you can keep track of high-level release updates in the [1.6 tracking](https://github.com/kubeflow/manifests/issues/2194) issue.

**Comment by zijianjoy** [comment]
Thank you @annajung for the update! If we cannot find testing support, does that mean we need to further delay the release?

**Comment by annajung** [comment]
Hi @zijianjoy, from today's release team meeting, it looks like all other WG leads have decided to migrate to GitHub Actions as a short-term solution and will be able to meet the new feature freeze deadline of June 15th. 

I need to confirm with Training Operators / AutoML WG as they were the only ones not present in the meeting. You can find a detailed update of the meeting [here](https://github.com/kubeflow/testing/issues/1006#issuecomment-1147782063)

**Comment by annajung** [comment]
After checking with all WGs, we are delaying the release for 2 more weeks. The new feature freeze date is **Wednesday, Jun 29th, 2022.**

Email announcement: https://groups.google.com/g/kubeflow-discuss/c/I4l97HvrGEA/m/227aCe_mCgAJ
New schedule PR: https://github.com/kubeflow/community/pull/562

The release team is tracking Pipeline 2.0.0-alpha for the 1.6 release. If there are changes to the branch/tag, please let us know before the new feature freeze deadline.

**Comment by zijianjoy** [comment]
Thank you @annajung , what criteria do we use to determine whether to extend release schedule again on Jun 29th?

**Comment by zijianjoy** [comment]
@annajung Can we make `Notebook supporting Kubernetes 1.22` as the criteria for another extension? It is rather urgent that Kubeflow is able to support Kubernetes 1.22 than introducing new features. We can include the same individual kubeflow component versions as Kubeflow 1.5 except Notebook. With this isolation, it gives Kubeflow components more time to figure out the testing infrastructure solution, while unblocking users to continue using Kubeflow. We can always include all new cool features in Kubeflow 1.7.

**Comment by zijianjoy** [comment]
Thank you @kimwnasptd for the information! Sounds good on waiting Notebook to be ready.

**Comment by ryansteakley** [comment]
@zijianjoy  @kimwnasptd  Please take a look at this short pr https://github.com/kubeflow/pipelines/pull/7946 which simply updates the minio-go versioning.

**Comment by annajung** [comment]
[xposting](https://github.com/kubeflow/manifests/issues/2200#issuecomment-1171507029)

Hi @kubeflow/wg-pipeline-leads @zijianjoy @james-jwu pipeline leads, after various attempts to clarify the version for KF 1.6, the release team hasn't received a response yet on what tag to use for 1.6 since previously mentioned tag v2.0.0 is not available.

With the feature freeze being yesterday, the release team will go ahead with the latest stable version available for pipelines as of June 30th, which is [1.8.2](https://github.com/kubeflow/pipelines/releases/tag/1.8.2).

Please reach out to us if you have any concerns! thank you!

**Comment by zijianjoy** [comment]
Hello @annajung , we have communicated that KFP is going to use 2.0.0-alpha.2 for the upcoming Kubeflow 1.6 release. Looks like you are not able to find the tag, so here it is: https://github.com/kubeflow/pipelines/releases/tag/2.0.0-alpha.2

**Comment by annajung** [comment]
With KF 1.6 released, closing the issue - 1.6.1 related work is tracked at https://github.com/kubeflow/manifests/issues/2194
