### ISSUE TITLE
Notebook WG and Kubeflow 1.6 release

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2199]
Hello @kubeflow/wg-notebooks-leads

The [1.6 release team](https://github.com/kubeflow/community/blob/master/releases/release-1.6/release-team.md) will use this tracking issue to coordinate the integration of the Notebooks with the Kubeflow 1.6 release.

Heads up that the **feature freeze** is scheduled for **Wednesday, Jun 1st, 2022**. For the full release schedule, refer to the [1.6 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.6/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/558 and https://github.com/kubeflow/community/pull/560)_

To prepare for the 1.6 release, please provide answers to the following questions:
1. What version of Notebooks would you like to include for the 1.6 release?
2. Could you provide a branch/tag for this version? _(note: It doesn't have to be final)_
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.6?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?
  - Knative
  - Istio
  - Kubernetes
  - Cert-Manager
  - Kustomize

The release team WG liaison for Notebooks WG will be @kimwnasptd @mstopa and you can keep track of high-level release updates in the [1.6 tracking](https://github.com/kubeflow/manifests/issues/2194) issue.

**Comment by kimwnasptd** [comment]
Thanks for the tracking issue @annajung! 

For K8s we are targeting at least 1.22, but I also want to test out 1.23 and have it as a stretch goal.

I'll also create the, long overdue, roadmap issue for Notebooks and link to it here as well now

**Comment by kimwnasptd** [comment]
The Notebook WG roadmap is in https://github.com/kubeflow/kubeflow/issues/6463

I'll also be posting updates here on how our progress goes, and what features might need to be dropped as we will be getting closer to the feature freeze

**Comment by annajung** [comment]
Due to a blocker that was identified last week, we are delaying the release for 2 weeks, with the **possibility of another extension**. The new feature freeze date is **Wednesday, Jun 15th, 2022**. If another extension is needed, another announcement will be made to notify the community. 

- Tracking issue: https://github.com/kubeflow/testing/issues/1006
- Email announcement: https://groups.google.com/u/2/g/kubeflow-discuss
- New schedule PR: https://github.com/kubeflow/community/pull/561

**Comment by kimwnasptd** [comment]
I've just created the `v1.6-branch` for `kubeflow/kubeflow`. I'll do a couple of follow up commits for:
1. Using the DockerHub registry for now
2. Testing that all images can be build from current release branch

Once done I'll also create the first RC

**Comment by kimwnasptd** [comment]
Also let me put an update regarding K8s 1.22, the RC0 will have support for K8s 1.22**.

** The only issue is the Profile Controller https://github.com/kubeflow/kubeflow/issues/6353. Right now it's using some old K8s libraries and is subject to https://github.com/kubeflow/kubeflow/issues/6484. 

But we have a PR inflight for this https://github.com/kubeflow/kubeflow/pull/6491, which we will also include in KF 1.6

**Comment by annajung** [comment]
Hi @kubeflow/wg-notebooks-leads, could you provide an update on the issue https://github.com/kubeflow/kubeflow/issues/6572? When the 1.6 RC 1 was cut, it was my understanding that the issue wasn't completely fixed based on discussions in the following PRs: https://github.com/kubeflow/kubeflow/pull/6596 and https://github.com/kubeflow/kubeflow/pull/6599.

Can you provide an update on the issue and share if you'll need to provide another RC for the 1.6 release? If another notebook RC is expected, with the release day coming up, when would you be able to provide the RC for the fix?

In addition, please take a look at this PR https://github.com/kubeflow/manifests/pull/2263, which was raised as an issue by one of the distribution owners.

**Comment by annajung** [comment]
With KF 1.6 released, closing the issue - 1.6.1 related work is tracked at https://github.com/kubeflow/manifests/issues/2194
