### ISSUE TITLE
Jupyter notebook user has group 1337

### ISSUE THREAD

**Issue by bigflood** [kubeflow/manifests#2218]
In jupyter notebook, user has strange group, 1137.

![image](https://user-images.githubusercontent.com/537859/171031524-5472ddf2-3dd8-40ba-83df-e48e71c3942c.png)

expected:
```
uid=1000(jovyan) gid=100(users) groups=100(users)
```

tested versions:
-  kubeflow version: 1.5
-  kubernetes version: 1.21.12

i think, the problem caused by istio sidecar injection.
env `ENABLE_LEGACY_FSGROUP_INJECTION=false` should be present.
https://github.com/kubeflow/manifests/blob/v1.5-branch/common/istio-1-11/istio-install/base/install.yaml#L3221

(in istio 1.11, `ENABLE_LEGACY_FSGROUP_INJECTION` is default true)
https://github.com/istio/istio/pull/27367

**Comment by juliusvonkohout** [comment]
This might be interesting for the security WG

**Comment by juliusvonkohout** [comment]
closed with the corresponing PR. Look at the PR for details.
