### ISSUE TITLE
Error while building manifests

### ISSUE THREAD

**Issue by anjaliagarwal8** [kubeflow/manifests#2226]
Hello,
I have been trying to build kubeflow manifests using kustomize following the tutorial given in the repo, but I encounter various errors while running the commands for various components. While running this command `kustomize build common/istio-1-9/istio-install/base | kubectl apply -f -`

I get this error: `unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

I got similar errors while installing other components too. 
I am using version 1.3 of kubeflow manifests. I also tried this with other kubeflow manifests version (1.5 and 1.4) but I got similar errors. 

Version info:
kubectl: 1.22 (both client and server)
kustomize: 3.5.6

Please let me know how I can resolve these issues. 
Thank you!

**Comment by volkermauel** [comment]
Running into the same issue

**Comment by anjaliagarwal8** [comment]
Thank you, I tried editing the yaml files but I was still getting some errors in other components so I switched to kubernetes 1.21 and it works fine now. 

Thank you for you help!
