### ISSUE TITLE
Bugs in image: docker.io/kubeflownotebookswg/jupyter-web-app: v1.6.0-rc.0

### ISSUE THREAD

**Issue by liujun121533** [kubeflow/manifests#2245]
There's a bug in image of ''docker.io/kubeflownotebookswg/jupyter-web-app:v1.6.0-rc.0''.

The code in the image is not same with kubeflow's repo, e.g. https://github.com/kubeflow/kubeflow/blob/v1.6.0-rc.0/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py#L14

code in the image:

```
def create_notebook(notebook, namespace):
    authz.ensure_authorized(
        "create", "kubeflow.org", "v1beta1", "notebooks", namespace
    )

    return custom_api.create_namespaced_custom_object(
        "kubeflow.org", "v1beta1", namespace, "notebooks", notebook
    ) 
```

code in kubeflow's repo:

```
def create_notebook(notebook, namespace, dry_run=False):
    authz.ensure_authorized(
        "create", "kubeflow.org", "v1beta1", "notebooks", namespace
    )

    return custom_api.create_namespaced_custom_object(
        "kubeflow.org", "v1beta1", namespace, "notebooks", notebook,
        dry_run="All" if dry_run else None)
```

**Comment by kimwnasptd** [comment]
@liujun121533 are you sure? 

I'm used the same image and checked the contents of the file `package/build/lib/kubeflow/kubeflow/crud_backend/api/notebook.py` and they are the same with the one you linked above for `v1.6.0-rc0`

**Comment by streamnsight** [comment]
linked to this issue:
https://github.com/kubeflow/kubeflow/issues/6572
