### ISSUE TITLE
Simplistic integration testing for components

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2248]
We've done some first steps on having [tests](https://github.com/kubeflow/manifests/tree/master/.github/workflows) that:
1. Apply all components in a KinD K8s 1.22 cluster
2. Wait for all Pods to become ready

This is done with GH Actions, since these tests are lightweight and can complete relatively quickly.

As a next step we can extend these tests to also:
1. Apply a CR for each component
2. Wait for that object to become Ready/Succeed

This way we add yet another small layer of testing and ensure the components and their functionality is working as expected.

Once we fully move to AWS accounts we can deprecate these in favor of the [e2e test](https://github.com/kubeflow/manifests/tree/master/tests/e2e), which will be doing the same but by deploying a whole Kubeflow installation and ensuring that everything plays along together as expected.

cc @kubeflow/wg-manifests-leads

**Comment by juliusvonkohout** [comment]
I think this is done now for a few components with machine to machine tokens.

Please reopen if necessary.
