### ISSUE TITLE
xgboost operator should have kustomize manifest

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#229]
Code is here:
https://github.com/kubeflow/xgboost-operator

It looks like there is YAML specs in the repo
https://github.com/kubeflow/xgboost-operator/tree/master/config

I think those could be easily turned into a kustomize manifest.

KfDef and Kfctl on master support installing kustomize packages from other repositories; so the kustomize package could continue to live in xgboost-operator rather than moving to kubeflow/manifests

**Comment by hemantha-kumara** [comment]
@jlewi I am working in my organisation to make xgboost dist training available on kubeflow. I am interested to take this PR.

**Comment by merlintang** [comment]
@hemantha-kumara <https://github.com/hemantha-kumara> thanks for your
efforts.

**Comment by johnugeorge** [comment]
@hemantha-kumara You could take a look at manifests of other operators - TFJob/PyTorchJOb

**Comment by hemantha-kumara** [comment]
@johnugeorge  Thanks, Yes I was referring TfJob operator. Once I do some progress I will update the status here.

**Comment by hemantha-kumara** [comment]
@terrytangyuan @merlintang @johnugeorge 
Submitted manifests changes to xgboost-operator repo 
 https://github.com/kubeflow/xgboost-operator/pull/35

**Comment by terrytangyuan** [comment]
Thank you! @hemantha-kumara

**Comment by hemantha-kumara** [comment]
In my opinion it will be good if we move xgboost kustomize manifest under kubeflow/manifests. as you pointed out it will convinient for users to list in kfdef.

**Comment by terrytangyuan** [comment]
How do we make sure it's always in sync? How do other operators deal with this?

**Comment by jlewi** [comment]
@terrytangyuan right now its a manual process. We are working on building Tekton workflows to automate updating the manifests see kubeflow/kubeflow#4112.

The tekton workflow would be used to do things like 

1. Trigger on postsubmit of a PR updating the operator
1. Build a new docker image
1. Update the kustomize manifest to use the new image
1. Create a PR checking in that manifest

So once we have a good setup with Tekton to do that; it should be fairly straightforward to modify it to automate replication of a manifest in xgboost-operator to kubeflow/manifests

**Comment by terrytangyuan** [comment]
Sounds great!

**Comment by terrytangyuan** [comment]
This is done in https://github.com/kubeflow/manifests/tree/master/xgboost-job/xgboost-operator. 
/assign
