### ISSUE TITLE
Update Seldon to be compatible with K8s 1.22 and newer

### ISSUE THREAD

**Issue by umka1332** [kubeflow/manifests#2290]
Currently Seldon manifest are using old CRDs that are not compatible with K8s 1.22 which is supported with Kubeflow 1.6.
Minimal Seldon version that support K8s 1.22 is 1.12.

**Comment by GigliOneiric** [comment]
So die einzige möglichkeit im moment ist ein downgrade auf die Version 1.21.5?

**Comment by juliusvonkohout** [comment]
/close

we are working on Kubernetes 1.26 now in https://github.com/kubeflow/manifests/pull/2532
