### ISSUE TITLE
"knative-eventing" from "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by jaffe-fly** [kubeflow/manifests#2307]
os：centos 7.9
k8s: 1.25.3
when install kubeflow with one commmand line

> error: resource mapping not found for name: "eventing-webhook" namespace: "knative-eventing" from "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first
Retrying to apply resources

so how to resolve?

**Comment by jaffe-fly** [comment]
upgrade istio 1.15 to work with k8s 1.25  

manifests-1.6.1/common/istio-1-14/README.md

**Comment by Dravigon** [comment]
Still issue when applying
kustomize build common/knative/knative-eventing/base | kubectl apply -f -

used the master branch of manifest https://github.com/kubeflow/manifests#installation
