### ISSUE TITLE
Notebook-controller and Profile-and-kfam Docker Image Pull Policy 

### ISSUE THREAD

**Issue by jsitu777** [kubeflow/manifests#2308]
Hi,

We notice the below 3 docker images' `imagePullPolicy` are set to `Always `
* `docker.io/kubeflownotebookswg/notebook-controller:v1.6.1`
* `docker.io/kubeflownotebookswg/kfam:v1.6.1`
* `docker.io/kubeflownotebookswg/profile-controller:v1.6.1`

This could lead to hitting the [docker image pull rate limit](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-error-rate-limit/#:~:text=Docker%20Hub%20uses%20IP%20addresses,pulls%20per%206%2Dhour%20period)  which is set to **100 pull for anonymous users**  in **every 6 hours**.

We are wondering if the pullPolicy for these images is set to `Always` intentionally or it's a miss that can be set as `IfNotPresent` so they can be cached?

**Comment by TobiasGoerke** [comment]
Same goes for:
- `istio-system/authservice`
- `kubeflow/cache-server`
- `kubeflow/ml-pipeline-viewer-crd`

All of the above mentioned Deployments/StatefulSets use immutable image tags. Thus, `imagePullPolicy` could and should be `IfNotPresent`. This not only leads to rate limiting problems (as @jsitu777 mentioned) but also to slow start times, potential failures and network load on both client and registry.

**Comment by juliusvonkohout** [comment]
@kimwnasptd i think we should tackle this. Or @TobiasGoerke are you interested in doing a PR?

**Comment by juliusvonkohout** [comment]
This is probably the wrong repository or what do you think @kimwnasptd  

i still see 
ml-pipeline/cache-deployer:2.0.3
imagePullPolicy: Always
ml-pipeline/cache-server:2.0.3
imagePullPolicy: Always
kserve/kserve-controller:v0.11.1
imagePullPolicy: Always
kserve/models-web-app:v0.10.0
imagePullPolicy: Always
ml-pipeline/viewer-crd-controller:2.0.3
imagePullPolicy: Always
