### ISSUE TITLE
 Distributions and Kubeflow 1.7 release

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2312]
The goal of this issue is to track the progress of distributions alongside the 1.7 release

While we hope all distros will manage to be ready when the KF 1.7 release is out, this is sometimes difficult to achieve. In this issue, we want to both keep track of the progress of distributions towards the KF 1.7 release and also which of the distros will be working on KF 1.7 (testing during the distribution testing cycle) even if they can't meet the KF 1.7 deadline.

Tagging distribution owners identified in kubeflow/community#571 and from previous releases (**Any new or missed distro owners, please comment on this issue**)

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| Arrikto EKF 	| @kimwnasptd 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1323908716) 	|
| Arrikto MiniKF 	| @kimwnasptd 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1323908716) 	|
| AWS 	| @surajkota 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1338403551) 	|
| Charmed Kubeflow 	| @DnPlas  	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1317306489) 	|
| Google Cloud 	| @gkcalat<br>@zijianjoy 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1315597132) 	|
| IBM IKS 	| @yhwang 	|[participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1315593984) 	|
| Nutanix 	| @johnugeorge 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1315736475) 	|
| Kubeflow with Argo CD 	| @DavidSpek 	| ? 	|
| Openshift 	| @VaishnaviHire<br>@LaVLaS 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1341381932) 	|
| Oracle Cloud Infrastructure 	| @julioo 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1321804820) 	|
| Telekom Data Science Platform 	| @juliusvonkohout 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1316689979) 	|
| VMWare 	| @liuqi<br>@xujinheng 	| [participating in 1.7](https://github.com/kubeflow/manifests/issues/2312#issuecomment-1317198976) 	|

Please let us know if you'll be participating in the 1.7 release by answering the following questions:

* Are you planning on having your distro ready in sync with the KF 1.7 release?
* Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?
* If you cannot participate, when can the community expect your distro to be ready for release 1.7?

cc @kubeflow/release-team @jbottum @DomFleischmann

**Comment by yhwang** [comment]
for IBM IKS:
> Are you planning on having your distro ready in sync with the KF 1.7 release?

Yes
> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by gkcalat** [comment]
GCP:

> Are you planning on having your distro ready in sync with the KF 1.7 release?

yes

>Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

yes

Here is our tracker: https://github.com/GoogleCloudPlatform/kubeflow-distribution/issues/395

**Comment by johnugeorge** [comment]
> * Are you planning on having your distro ready in sync with the KF 1.7 release?

Yes 
> * Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout @annajung fyi, I believe Telekom and Vmware should be in the table above.

Hello Josh,

Yes that would be good. Do you have any specific instructions for me? We participated since 1.3 in testing and will try to have 1.7 ready on release day.

I am also trying to add it on the website https://github.com/kubeflow/website/pull/3403 "add Telekom Data Science Platform distribution to "installing kubeflow" table"

**Comment by liuqi** [comment]
For VMware, Jinheng (@xujinheng) and Qi (@liuqi) will be the representatives. We host the project Kubeflow on vSphere on https://vmware.github.io/ml-ops-platform-for-vsphere/ 
> * Are you planning on having your distro ready in sync with the KF 1.7 release?
Yes

> * Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by DnPlas** [comment]
For Charmed Kubeflow: 

> Are you planning on having your distro ready in sync with the KF 1.7 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by julioo** [comment]
For Oracle Cloud Infrastructure

> Are you planning on having your distro ready in sync with the KF 1.7 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by kimwnasptd** [comment]
From the Arrikto side 

> Are you planning on having your distro ready in sync with the KF 1.7 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Definitely yes!

**Comment by surajkota** [comment]
AWS:

> Are you planning on having your distro ready in sync with the KF 1.7 release?

TBD closer to release date

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

> when can the community expect your distro to be ready for release 1.7?

2-4 weeks from the release

**Comment by LaVLaS** [comment]
OpenShift - @LaVLaS @VaishnaviHire

> Are you planning on having your distro ready in sync with the KF 1.7 release?
Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?
Yes

**Comment by yhwang** [comment]
@DomFleischmann I created a tracking issue for the IBM IKS here: https://github.com/IBM/manifests/issues/50
I haven't encountered any issues in my testing yet and am still using customize v3.2.0 for the deployment. I do want to try out the kustomize v5. But I will hold for the decision from the community.

For the documentation you mentioned, I could update the install instruction now. However, the installing page requires the link for the final version of the manifests which hosts on IBM/manifests repo. I will create the tag and update the installing page when we have the final version for v1.7

**Comment by julioo** [comment]
@DomFleischmann I have issue with Istio and Oracle Linux 8.
Following the steps described https://github.com/istio/istio/issues/23009#issuecomment-1049166026
I can manually install and run KF v1.7 with kustomize v3.2.0 but I'm looking for automated way.

**Comment by johnugeorge** [comment]
@nagar-ajay will add Nutanix updates

**Comment by DomFleischmann** [comment]
Hey Distribution owners, just a quick update, we encountered some issues with pipelines and a new alpha.7 version was released. This means we will cut a new RC and there will be additional testing required, delaying the release by 1 or 2 weeks. I will provide more details on Monday regarding the timeline.

More info [here](https://github.com/kubeflow/manifests/issues/2359#issuecomment-1462406491).

**Comment by Syntax3rror404** [comment]
A helm chart would be much better. Than the Distributions doesn't matter anymore.

**Comment by DnPlas** [comment]
Hi folks, @DomFleischmann,

#### Charmed Kubeflow from Canonical

##### Issues
* We are still running into kubeflow/pipelines#7196. This has been present for a while. Is there any plan to fix it soon?

##### Release date

* We have released our [1.7 beta version](https://discourse.charmhub.io/t/charmed-kubeflow-1-7-beta-is-here/8791)
* We are on track with the upstream project, but will probably release a week after the official release date.

**Comment by Syntax3rror404** [comment]
Why no helm chart? :(

**Comment by johnugeorge** [comment]
> here

Reference: https://github.com/kubeflow/katib/issues/2126#issuecomment-1473757468 Please let us know if this solves the issue

**Comment by DomFleischmann** [comment]
@LaVLaS @surajkota @kimwnasptd @julioo @DnPlas @liuqi @gkcalat @yhwang

Hey Distribution owners, thank you for all the updates, it's great to see so many different community members being involved in the testing phase.

just as another reminder, make sure to update the [installing kubeflow](https://www.kubeflow.org/docs/started/installing-kubeflow/) docs page this week if you are planning to support 1.7 on the release date.

**Comment by yhwang** [comment]
@DomFleischmann thanks for the reminder. I created a PR to update the IKS entry in `installing kubeflow` page: https://github.com/kubeflow/website/pull/3469

**Comment by nagar-ajay** [comment]
Hi @DomFleischmann, I have tested rc2 on NKE. I haven't found any issues in my testing yet.
Created an issue for tracking: https://github.com/nutanix/kubeflow-manifests/issues/6

I have also updated installing kubeflow docs page https://github.com/kubeflow/website/pull/3473

**Comment by gkcalat** [comment]
Kubeflow on Google Cloud v1.7.0 [has been released](https://github.com/GoogleCloudPlatform/kubeflow-distribution/releases/tag/v1.7.0). We also updated the [installing kubeflow](https://www.kubeflow.org/docs/started/installing-kubeflow/) page. Thank you @DomFleischmann  and the rest of the release team for the hard work!

**Comment by juliusvonkohout** [comment]
closing since 1.7 is now released and 1.8 on the horizon. 

/close
