### ISSUE TITLE
User options for upgrading to Kubeflow v1.7

### ISSUE THREAD

**Issue by jbottum** [kubeflow/manifests#2323]
When a new Kubeflow release comes out, many Kubeflow users have asked for documentation on upgrading.   Upgrading between Kubeflow releases has many options i.e. what are the existing KF release and dependencies installed and which cloud environment and configuration options.   The vast amount of configuration options make a single upgrade plan difficult to design, test and document.    At this point, a Community provided upgrade documentation plan is not in the scope of the 1.7 Release Team, which means that users will need to create their own plan, or will need to contract with a 3rd party / distribution provider for upgrades.

This issue is designed to collect comments from users, code contributors and distribution owners.   Some potential questions:

- If the Release Team cannot provide an upgrade plan, should the distributions and/or consultants/integrators offer this benefit?
- Can the Community develop an (example) upgrade configuration with a minimal number of options?   
- Will documentation (on a minimized configuration) be useful?
- Can the back-up / upgrade process recover from unexpected failures?  
- Which parts of the testing and documentation could be efficiently automated?  Which parts will be manual ?
- Are there any contributors and/or users who are willing to help to design, test and document a phase 1 of this process?

**Comment by jbottum** [comment]
@DomFleischmann

/priority p2
/area enterprise_readiness
/kind feature

**Comment by juliusvonkohout** [comment]
shall we continue in  #2216 ?

**Comment by juliusvonkohout** [comment]
/close

since 1.8 is released
