### ISSUE TITLE
Kubeflow DashBoard Issue

### ISSUE THREAD

**Issue by vamshikrishna9999** [kubeflow/manifests#2339]
I have installed kubeflow on OpenShift cluster v 4.10. I have verified all the namespaces and all pods are up and then i need to access the kubeflow dashboard via istio-ingressgateway route but am i unable to get the dashboard . I have tried with port-forwarding also will not able to access in the locally .

Version
kubeflow version: v1.5.0
Kubernetes platform: OpenShift
version:4.10

**Comment by Shaheer4636** [comment]
Same issue

**Comment by juliusvonkohout** [comment]
Hello,

we are on Kubeflow 1.7/1.8 now. Is this still relevant for these releases? Otherwise i would like to close this issue.
