### ISSUE TITLE
Document versioning policy

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2358]
As part of the CNCF application process, [the versioning policy has been identified](https://github.com/kubeflow/community/issues/594) as one of the required documents to support the transition. After reviewing the current documentation for the Manifest WG, it's been recognized that documentation around the versioning and release process needs to be created.

As part of the transition effort, a [high-level versioning process](https://github.com/kubeflow/community/pull/597) has been documented. However, it would also be helpful to document the WG-specific process in this repo for Manifest users / Kubeflow release

**Comment by kimwnasptd** [comment]
Isn't it enough to reference the release handbook? The handbook was initially created https://github.com/kubeflow/manifests/pull/1907 to describe the release process in the manifests repo and has specific sections for the Manifests WG for the different phases. 

https://github.com/kubeflow/community/blob/master/releases/handbook.md#feature-freeze-2-weeks
https://github.com/kubeflow/community/blob/master/releases/handbook.md#manifests-testing-1-week
https://github.com/kubeflow/community/blob/master/releases/handbook.md#distribution-testing-3-weeks
https://github.com/kubeflow/community/blob/master/releases/handbook.md#release

Essentially, the Manifests' versioning policy is Kubeflow's versioning policy. Would creating a simple `.md` file to describe the above and provide references be enough?

**Comment by annajung** [comment]
Agree, a doc in the manifest repo that references the release handbook should be enough. Right now, anyone looking for versioning info does not have a pointer to the handbook, adding that to the README or other appropriate doc makes sense

**Comment by surajkota** [comment]
Only thing missing from the release handbook is versioning policy itself e.g. It mentions user needs to use `X.Y` version but does not have guidance/policy on when X or Y should be incremented. This was also discussed during 1.5 release.

Versioning of individual components impacts the version of a Kubeflow/Kubeflow manifests release, e.g. when Kubeflow pipelines version 2.x is GA, will Kubeflow version be 2.x? when introducing the 2.x-alpha version only minor version was incremented.

Atleast documenting the current version defining process should complete the guide
