### ISSUE TITLE
Kubeflow 1.7 Tracking Issue

### ISSUE THREAD

**Issue by DomFleischmann** [kubeflow/manifests#2359]
We are getting closer to 1.7 Release date! Let's use this issue to track all the different efforts to make this release happen.

First lets review the timeline: 
- ~~Week 1 - Release Team is formed: Wednesday, Sep 28th 2022~~
- ~~Week 1 - Release Cycle Begins: Wednesday, Sep 28th 2022~~
- ~~Week 3 - Roadmaps are finalized: Wednesday, Oct 19th 2022~~
- ~~Week 18 - Feature Freeze: Wednesday, Jan 25th 2023~~
- ~~Week 19 - Manifests Testing Start: Wednesday, Feb 8st 2023~~
- ~~Week 20 - Manifests Testing Ends: Wednesday, Feb 15th 2023~~
- ~~Week 20 - Distribution Testing Starts: Wednesday, Feb 15th 2023~~
- Week 23 - Distribution Testing Ends: Wednesday, Mar 22nd 2023
- Week 24 - Docs Update Ends: Tuesday, Mar 28th 2023
- Week 24 - Kubeflow v1.7 Released: Wednesday, Mar 29th 202

This is the current state of all the WG groups regarding the next timeline step and the versions they are expecting to release. 
Manifests | Notebooks, Central Dashboard | KFP | Katib | Training Op | Kserve
-- | -- | -- | -- | -- | --
v1.7 | v1.7 | ~v2.0-alpha.6 | 0.15 | 1.6 | 0.10
green | green | green | green | green |  green

Additionally, these are the dependency versions that will be used for Kubeflow 1.7

K8s | Istio | KNative | Kustomize | Cert Mgr | DEX | Argo
-- | -- | -- | -- | -- | -- | --
1.25 / 1.24 | 1.16 | 1.8.1 | TBD: 4.x or 5.0 | 1.10.1 | (2.31 current) | 3.3.8

For distribution tracking please use issue #2312 

@kimwnasptd @jbottum @akgraner @johnugeorge @andreyvelich @yuzisun @zijianjoy @connor-mccarthy

**Comment by yhwang** [comment]
hi @DomFleischmann I created a PR to update kfp-tekton to v1.5.0 here: https://github.com/kubeflow/manifests/pull/2363
this is the version of kfp-tekton for the v1.7 release. thanks!

**Comment by DomFleischmann** [comment]
@chensun @zijianjoy @connor-mccarthy @gkcalat 
We haven't gotten any news on when pipelines expect to release their Release Candidate. Could you provide us with a clear date? 
For now, we are planning on cutting the first release candidate with the version used in Kubeflow 1.6.

**Comment by gkcalat** [comment]
Hi @DomFleischmann ,

Sounds good to use the previous alpha release used in KF 1.6. As per the date, we are in the process of preparing the beta.0 release. It can take 1-2 weeks from now.

**Comment by johnugeorge** [comment]
@DomFleischmann 

The training operator release tag [v1.6.0-rc.0](https://github.com/kubeflow/training-operator/tree/v1.6.0-rc.0) has been cut from [1.6 release branch ](https://github.com/kubeflow/training-operator/tree/v1.6-branch) 

[Training operator SDK 1.6.0rc0 ](https://pypi.org/project/kubeflow-training/1.6.0rc0/)has been released.

**Comment by yhwang** [comment]
@DomFleischmann updated kfp-tekton to 1.5.1 to fix one issue on k8s 1.25. so v1.5.1 is verified on k8s 1.25!

**Comment by andreyvelich** [comment]
@DomFleischmann 

The Katib release tag [v0.15.0-rc.0](https://github.com/kubeflow/katib/tree/v0.15.0-rc.0) has been created.
You can merge the manifests.

**Comment by surajkota** [comment]
https://groups.google.com/g/kubeflow-discuss/c/89zmWG99rcU?pli=1

@kubeflow/release-team 
To make good use of WGs and Distribution testing timeframe, it will be good to have at least one version updated for each component being tracked for the RC. Ideally the scope of changes should come down with each RC. Additionally, given that Distribution testing is a week away from manifest testing, distributions will also need to test before community testing is complete/atleast priliminary tests are run/incomplete RC.

Let me know your thoughts

**Comment by surajkota** [comment]
@DomFleischmann 
Does it make sense to track the version of oidc-authservice in the dependency version table?

**Comment by johnugeorge** [comment]
@DomFleischmann I have a similar thought.  Can we do realistic e2e testing without kfp release ?

**Comment by DomFleischmann** [comment]
Hey @johnugeorge and @surajkota yes we are currently debating how to move forward. I followed up with @gkcalat to see if it is possible to have a clear deadline for pipelines next week, that way we delay manifest testing for an additional week and include pipelines.

I'm more than happy to delay the timeline a bit, but we need to have clear dates for this.

**Comment by surajkota** [comment]
KServe 0.10 was released last week - https://github.com/kserve/kserve/releases/tag/v0.10.0. Do we need release team to update KServe and KNative manifests or KServe team is handling it?

@yuzisun

**Comment by yuzisun** [comment]
> KServe 0.10 was released last week - https://github.com/kserve/kserve/releases/tag/v0.10.0. Do we need release team to update KServe and KNative manifests or KServe team is handling it?
> 
> @yuzisun

@andyi2it is working on the PR at the moment https://github.com/kubeflow/manifests/pull/2355/files

**Comment by DomFleischmann** [comment]
As agreed in the Community meeting I have updated the timeline delaying manifest testing by one week. The new release date will now be **March 15th**.

**Comment by DomFleischmann** [comment]
We have now released [RC0](https://github.com/kubeflow/manifests/releases/tag/v1.7.0-rc.0) of the Kubeflow 1.7 release and will start Manifest Testing tomorrow February 8th.

**Comment by johnugeorge** [comment]
[v1.6.0-rc.1 ](https://github.com/kubeflow/training-operator/releases/tag/v1.6.0-rc.1) release tag  is cut for training operator from [1.6 release branch](https://github.com/kubeflow/training-operator/tree/v1.6-branch)

**Comment by DomFleischmann** [comment]
[RC1](https://github.com/kubeflow/manifests/releases/tag/v1.7.0-rc.1) has just been released, please go ahead and try it out.

**Comment by DomFleischmann** [comment]
Hello everyone, as @surajkota described in [this issue](https://github.com/kubeflow/pipelines/issues/8938) we encountered a [bug](https://github.com/kubeflow/pipelines/pull/8941) in the MySQL database used in pipelines and also some fixes that occurred in the last months but weren't part of alpha.6. Therefore the pipelines team has decided to backport these fixes and release alpha.7 for Kubeflow 1.7. This means we are going to cut another RC with this new release and we will require further testing of the RC this means the release will have to be delayed by 1 or 2 weeks. I want to discuss concrete timelines with the whole Release Team on Monday and provide an update by then. 

Please let me know of any other bug fixes that you want to include in this RC, I will cut it tomorrow Friday 10th of March.

@kimwnasptd @annajung @jbottum @johnugeorge @andreyvelich @chensun @gkcalat @DnPlas

**Comment by DomFleischmann** [comment]
As mentioned before, we are delaying the release date to **March 29th**, as we have just release [Kubeflow 1.7 RC2](https://github.com/kubeflow/manifests/releases/tag/v1.7.0-rc.2).

**Comment by yhwang** [comment]
Hi @DomFleischmann, not sure if the `Docker Hub Free Teams Organizations will be sunset` will impact the release schedule. I guess some WSs are trying to figure out a solution, including:
- https://github.com/kubeflow/katib/issues/2127
- https://github.com/kubeflow/training-operator/issues/1781
- https://github.com/kubeflow/kfp-tekton/issues/1191

I see Notebook WG is also using their `kubeflownotebookswg` too.

**Comment by johnugeorge** [comment]
[v1.6.0 ](https://github.com/kubeflow/training-operator/releases/tag/v1.6.0) release tag  is cut for training operator from [1.6 release branch](https://github.com/kubeflow/training-operator/tree/v1.6-branch)

**Comment by terrytangyuan** [comment]
Docker has changed its plan https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

**Comment by johnugeorge** [comment]
[v0.15.0](https://github.com/kubeflow/katib/releases/tag/v0.15.0) elease tag is cut for Katib from [release-0.15](https://github.com/kubeflow/katib/tree/release-0.15) branch

**Comment by DomFleischmann** [comment]
Hey everyone Kubeflow 1.7 has been officially [released](https://github.com/kubeflow/manifests/releases/tag/v1.7.0). :tada: 

We are now just waiting for the final Doc updates and the Blog post to be merged to make the official announcement. 

Thank you for all your efforts!

**Comment by juliusvonkohout** [comment]
/close

since 1.7 is released and 1.8 is on the horizon.
