### ISSUE TITLE
Kubeflow 1.7 Security scan of images.

### ISSUE THREAD

**Issue by DomFleischmann** [kubeflow/manifests#2361]
_This issues should be moved to the Security WG repository once it is created._

One of the goals of the 1.7 Release Team is to perform a preliminary security scan of all the images included in the release so that we can try and reduce any critical vulnerabilities before release.

Let's use this issue to track all the issues from the different Working Groups.

@kimwnasptd @andreyvelich @johnugeorge @connor-mccarthy @zijianjoy @jbottum @akgraner @juliusvonkohout

**Comment by zijianjoy** [comment]
Thank you @DomFleischmann for tracking security status, what tool do we plan to use for image scanning?

**Comment by juliusvonkohout** [comment]
@zijianjoy If i remember correctly trivy was chosen..

**Comment by juliusvonkohout** [comment]
/close

we are now at 1.8
