### ISSUE TITLE
Notebook Culling Not Working For VSCode IDE

### ISSUE THREAD

**Issue by AlexandreBrown** [kubeflow/manifests#2366]
Pretty sure this is not a bug but rather simply not supported **yet** but creating an issue to track the progress of it.  
Currently, if we have culling enabled, it does not seem to work when using VSCode.

Tested using Kubeflow 1.7 on AWS.

**Comment by surajkota** [comment]
Similar issue opened by another user - https://github.com/kubeflow/kubeflow/issues/6920

**Comment by juliusvonkohout** [comment]
/close

yes it is a duplicate
