### ISSUE TITLE
kfctl init failed -- unknown config flag

### ISSUE THREAD

**Issue by LukasBlank** [kubeflow/manifests#237]
was following https://www.kubeflow.org/docs/started/getting-started-k8s/ trying to install kubeflow on an existing cluster but already got an error running <code>kfctl init ${KFAPP} --config=${CONFIG} -V</code> looking like this:<br>
<pre><code>
Error: unknown flag: --config
Usage:
  kfctl init <[path/]name> [flags]

Flags:
      --disable_usage_report    disable_usage_report disable anonymous usage reporting.
  -h, --help                    help for init
  -n, --namespace string        namespace where kubeflow will be deployed (default "kubeflow")
  -p, --platform string         one of 'gcp|minikube'
      --project string          name of the gcp project if --platform gcp
  -r, --repo string             local github kubeflow repo
      --skip-init-gcp-project   Set if you want to skip project initialization. Only meaningful if --platform gcp. Default to false
      --use_basic_auth          use_basic_auth use basic auth service instead of IAP.
      --use_istio               use_istio use istio for auth and traffic routing.
  -V, --verbose                 verbose output default is false
  -v, --version string          desired version of Kubeflow or master if not specified. Version can be master (eg --version master) or a git tag (eg --version=v0.5.0), or a PR (eg --version pull/<id>). (default "v0.5.1")

unknown flag: --config
</code></pre>
Running <code>kfctl version</code><br>
gives out this: <code>v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e</code>
Can somebody tell me how to workaround or fix this?

**Comment by yanniszark** [comment]
Hi @LukasBlank.
Did you download the latest, v0.6.0 version of kfctl?
https://github.com/kubeflow/kubeflow/releases/tag/v0.6.0

**Comment by LukasBlank** [comment]
This worked, thanks. Actually i thought that the documentation of how to deploy on an existing cluster was a lot older so that this could not be the reason but i guess i was wrong :$
