### ISSUE TITLE
RKE2 support

### ISSUE THREAD

**Issue by Syntax3rror404** [kubeflow/manifests#2372]
Are these manifests compatible with rke2 (k8s dockerless)

**Comment by wangzheyuan** [comment]
I have installed kubeflow 1.5.0 on RKE2 v1.22 without any issue.

**Comment by shan100github** [comment]
yes, it's supported.
hope https://medium.com/@shan-ops/mlops-platform-on-rancher-rke2-kubernetes-cluster-bare-metal-environment-kubeflow-1-7-upgrade-8def9be07c1d helps you.
