### ISSUE TITLE
Provision Minio bucket lifecycle rules when deploying Kubeflow

### ISSUE THREAD

**Issue by wooleybugger** [kubeflow/manifests#2375]
Is it possible to provision minio bucket lifecycle rules when deploying Kubeflow and if so where/how?

I am looking for the manifest that will allow me to provision lifecycle rules on kubeflow minio storage buckets. The desire is to have the rules in place prior to deployment of Kubeflow. The closest possibility appears to be 
apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml or apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/base/overlays/workflow-controller-configmap.yaml, but no "cigar". 

Thanks

**Comment by juliusvonkohout** [comment]
We are moving away from minio and we ship a 3 year old insecure version.

**Comment by wooleybugger** [comment]
Can you say what storage solution you are moving to and when?

**Comment by juliusvonkohout** [comment]
There are some bugs here regarding the minio replacement https://github.com/kubeflow/pipelines/pull/7725

**Comment by wooleybugger** [comment]
Well there is alot to read there.  My takeaway is that Zenko cloudserver and S3Proxy are the choices, depending if AWS/GCS or on-premises. Not sure if S3proxy equates to "file backend".

" So to summarize we try Zenko cloudserver (Apache 2 licence and actively maintained and proposed by james Liu) in gateway mode for AWS and GCP and with the file backend for on-premises deployments."

**Comment by wooleybugger** [comment]
@juliusvonkohout , Is there a roadmap/timeline for the replacement of Minio?

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout , Is there a roadmap/timeline for the replacement of Minio?

according to google after Q2 2023 the will start working on it.

**Comment by wooleybugger** [comment]
Thanks

**Comment by juliusvonkohout** [comment]
@wooleybugger can jyou join the KFP community meetings and discuss this with google again?
