### ISSUE TITLE
Kubeflow Manifests 1.7.0 example too many redirects

### ISSUE THREAD

**Issue by ryansteakley** [kubeflow/manifests#2384]
As part of the manifest testing took the liberty to attempt to install the basic example that is provided as part of the Kubeflow Manifests repo. ATM it seems that it no longer works due to the changes that were pushed as part of the https://github.com/kubeflow/manifests/commit/a114d5821f87e0ea43298885dfda7bfa23b108bf changes. If we port-forward and try to connect to the dashboard we immediately see this error.

<img width="1301" alt="Screen Shot 2023-02-07 at 12 48 08 PM" src="https://user-images.githubusercontent.com/37981995/217619741-a8deeaf2-51d8-40b2-9289-42e4ed8f7352.png">

Are other members of the community also running into this? Does this have to do with this [issue](https://github.com/arrikto/oidc-authservice/issues/86) that was fixed in this [pr](https://github.com/arrikto/oidc-authservice/pull/99) 

#2359 to track this issue.

**Comment by annajung** [comment]
This should fix it https://github.com/kubeflow/manifests/pull/2386!

**Comment by annajung** [comment]
Closing as it's resolved by https://github.com/kubeflow/manifests/pull/2386

/close
