### ISSUE TITLE
Error: timed out waiting for the condition on pods/authservice-0

### ISSUE THREAD

**Issue by aku134** [kubeflow/manifests#2392]
![image](https://user-images.githubusercontent.com/60403682/219318053-a9531ce2-f207-491d-a5cd-3b1ac27eddcd.png)

**Comment by surajkota** [comment]
Hi, what is your EKS cluster version? and have you installed the EBS CSI driver? See note here regarding `Kubernetes in-tree to container storage interface (CSI) volume migration feature` for K8s versions 1.23 and above - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23
