### ISSUE TITLE
Error: Volumes, Experiments (KFP), Pipelines, Runs, Recurring Runs, Artifacts, Executions

### ISSUE THREAD

**Issue by MustafaHar** [kubeflow/manifests#2393]
Hello,

I have installed Kubeflow on my AKS cluster.
My AKS cluster is running on Kubernetes 1.25.5.
And I used Kustomize version 5.0 (not having found 4.5.7)

I did my installation by the following way, Install individual components.
I ran each command one by one, and when an error appeared, I ran the same command again.
All installed without error except the "Kubeflow Pipelines" part where I encountered the following error:
"Error from server (BadRequest): error when creating "STDIN": CustomResourceDefinition in version "v1" cannot be handled as a CustomResourceDefinition: strict decoding error: unknown field "2023/02/16 10:33:17 well-defined vars that were never replaced"

Now, when I access my dashboard, I get the error: "upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"

For the tabs:
- Experiments (KFP)
- Pipelines
- Runs
- Recurring Runs
- Artifacts
- Executions

And I have a blank page for the "Volumes" tab

Could you help me to solve this problem?

**Comment by juliusvonkohout** [comment]
Do you want to create a proper bug report in an open source project or are you expecting consulting for hourly rates? Also in tandem with https://github.com/kubeflow/manifests/issues/2389#event-8536796122 this sounds more like the latter.

If you want commercial support i can happily redirect you, but otherwise I suggest to read the documentation first and fix the numbers 1.25 and 5.0 in your text according to it.

**Comment by Lejboelle** [comment]
Check this old issue, might still be related (AKS specific).
https://github.com/kubeflow/kubeflow/issues/5271

**Comment by MustafaHar** [comment]
After following these advices, my problem was solved
https://github.com/kubeflow/kubeflow/issues/5271#issuecomment-687218950
Thank you @Lejboelle
