### ISSUE TITLE
Demo script just install TFJob - don't use kfctl

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#24]
I think one of the overarching goals in Kubeflow is to make Kubeflow less monolithic and easier for people to install the particular applications they want e.g. TFJob.

I think a good way to evaluate our use of kustomize would be to see how easy it is to install just a particular CR.

I think a good exercise would be to create a doc with the instructions for installing just TFJob.

It might be nice to evaluate what this looks like using kfctl and without kfctl.

@kkasravi @hougangliu @swiftdiaries WDYT?

**Comment by hougangliu** [comment]
@jlewi make sense

**Comment by swiftdiaries** [comment]
Just to clarify, Do we want to go from a k8s cluster with nothing to installing TFJob both with and without kfctl?

**Comment by kkasravi** [comment]
Great idea. We should add to the README.md a section on deploying a single component either in manifests or some other kustomize target

**Comment by jlewi** [comment]
@swiftdiaries This issue is about installing a single application e.g. TFJob. I'd like to understand what the UX is without using kfctl. My initial expectation is that installing just TFJob using kubectl and kustomize would be pretty straightforward. If its not, I'd like to understand what exactly the pain points/friction is. If its not straightforward to install just via kubectl/kustomize then it suggests to me we might want to think about how we are packaging and distributing various applications.

**Comment by jlewi** [comment]
Should we punt this to 0.7?
