### ISSUE TITLE
Kubeflow generates lots of uninteded metrics after installation.

### ISSUE THREAD

**Issue by fakeskimo** [kubeflow/manifests#2406]
Hello team! 

I have deployed kubeflow 1.7.0 on Anthos on Baremetal 1.14([Link](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/getting-support#version-support)) with v1.25.3 GKE version.

After kubeflow 1.7 installation there was about 5KiB/s of metric has recorded from Kubeflow cluster to Google Cloud Monitoring service. The issue has resolved by fix Anthos on Baremetal's application monitoring configuration ([Link](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/troubleshooting/known-issues#unexpected-monitoring-billing)).

However while I trouble shooting this issue, I found that there are many resource comes with "prometheus.io/scrap=true" annotation which can cause similar issues in different environment.

The current status can improved by changing a istio profile from "demo" to "default" as istio README's note said. ([Link](https://github.com/kubeflow/manifests/tree/v1.7-branch/common/istio-1-16)) So I want to request to make this change once again in here to prevent users meet gathering unwanted metrics from kubeflow.

Thanks,
Junho

**Comment by DomFleischmann** [comment]
@kimwnasptd What exactly was the reasoning for using "demo" instead of "default", could we change this for 1.7?

**Comment by kimwnasptd** [comment]
Not sure tbh, it must had been like this from the very beginning. Definitely +1 to moving on the `default` one, rather that sticking with `demo`.

**Comment by zijianjoy** [comment]
I think it is probably because `demo` is the common profile to get started with. Refer to documentation from https://github.com/kubeflow/manifests/tree/v1.7-branch/common/istio-1-16#upgrade-istio-manifests:


> istioctl comes with a bunch of [predefined profiles](https://istio.io/v1.9/docs/setup/additional-setup/config-profiles/) (default, demo, minimal, etc.). The demo profile enables high levels of tracing and access logging and included monitoring components in the past, which we wanted to install. In the future, we can consider moving to the default profile.
