### ISSUE TITLE
Arrikto copyrights to files

### ISSUE THREAD

**Issue by imiller445** [kubeflow/manifests#2411]
There are arrikto copyright headers retaining all rights on the following files in the istio kustomization folders:

[istio-namespace](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/common/istio-1-16/istio-namespace/base/kustomization.yaml)

[cluster-local-gateway](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/common/istio-1-16/cluster-local-gateway/base/kustomization.yaml)

Is this intentional? Is it meant to convey a different license for these files as opposed to the overall license [here](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/LICENSE)?

**Comment by kimwnasptd** [comment]
Should be bad copy-paste from when these files were created initially, let's completely remove them. @imiller445 would you like to send a PR for this? I can help with the review

**Comment by imiller445** [comment]
Ah okay, awesome. Sure, I can send one. I'll get it submitted later today.

**Comment by imiller445** [comment]
Hey @kimwnasptd , I submitted a PR on it. Let me know if its missing something. This is my first PR to this project.
