### ISSUE TITLE
Fix kustomize 5 warning for /common/istio-1-16/istio-install/

### ISSUE THREAD

**Issue by annajung** [kubeflow/manifests#2418]
Part of https://github.com/kubeflow/manifests/issues/2388 to support kustomize 5 without warnings. Fix the use of deprecated fields in `manifests/common/istio-1-16/istio-install/`

#### Steps To Reproduce
1. Download [kustomize 5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0)

2. Run `kustomize build` using version kustomize 5.0.0 to see the warning
```
git clone https://github.com/kubeflow/manifests.git
cd manifests/common/istio-1-16/istio-install/base
kustomize build . > tmp.yaml
```

#### Current Behavior
Step 2 produces the following warning
```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

#### Expected Behavior
Step 2 completes **without** a warning and produces the same yaml as before the changes

#### Helpful links:
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

#### Where does the fix belong?
`/common` directory is managed by the Manifest WG, PR should be made to the manifests repo

/help
/good-first-issue

**Comment by juliusvonkohout** [comment]
We should rather delete 1.16 and check 1.17

**Comment by juliusvonkohout** [comment]
But let us merge #2455 first. Afterwards just ping me and i can fix it.

**Comment by juliusvonkohout** [comment]
#2536 will fix this please review

**Comment by juliusvonkohout** [comment]
Fixed by https://github.com/kubeflow/manifests/pull/2537 . Please review
