### ISSUE TITLE
[kubeflow 1.8] Katib WG and Kubeflow 1.8

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2443]
Hi @kubeflow/wg-automl-leads @andreyvelich 

The 1.8 release team will use this tracking issue to coordinate the integration of Katib with Kubeflow 1.8.

Please note that communications (announcements, updates, questions, follow ups, etc.) will be done through kubeflow/manifests#2442 exclusively, this issue will be closed once the release team gathers the initial information from the WG.

Heads up that the proposed feature freeze is Aug 2nd, 2023, but the date is still subject to agreement and discussed [here](https://github.com/kubeflow/community/pull/621). Feel free to comment on the issue for suggestions. We will be sharing the finalised timeline before May 8th, 2023.

To prepare for the release, please provide answers to the following questions:

1. What version of Katib would you like to include for the 1.8 release?
2. Could you provide a branch/tag for this version if you have it already? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
4. Is @kubeflow/wg-automl-leads updated? Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
5. If you're using any the following dependencies, could you provide the versions you'll be supporting for each one?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for Katib is @mobin102 and @nagar-ajay and you can keep track of high-level release updates in kubeflow/manifests#2442

**Comment by johnugeorge** [comment]
In KF 1.8 release, Katib v0.16.0 release is planned to be cut from release-0.16 branch

The plan is to support k8s version 1.25, 1.26 and 1.27. No other dependencies are involved.

**Comment by DnPlas** [comment]
Thanks @johnugeorge !
