### ISSUE TITLE
[kubeflow 1.8] Notebooks WG and Kubeflow 1.8

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2445]
Hi @kubeflow/wg-notebooks-leads 

The 1.8 release team will use this tracking issue to coordinate the integration of Notebooks with Kubeflow 1.8. 

Please note that communications (announcements, updates, questions, follow ups, etc.) will be done through kubeflow/manifests#2442 exclusively, this issue will be closed once the release team gathers the initial information from the WG.

Heads up that the proposed feature freeze is Aug 2nd, 2023, but the date is still subject to agreement and discussed [here](https://github.com/kubeflow/community/pull/621). Feel free to comment on the issue for suggestions. We will be sharing the finalised timeline before May 8th, 2023.

To prepare for the release, please provide answers to the following questions:

1. What version of Notebooks would you like to include for the 1.8 release?
2. Could you provide a branch/tag for this version if you have it already? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
4. Is @kubeflow/wg-notebooks-leads  updated? Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
5. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for Notebooks is @NohaIhab and you can keep track of high-level release updates in kubeflow/manifests#2442

**Comment by NohaIhab** [comment]
1. Notebooks v1.8.0
2. There is no branch for 1.8 at the moment, all changes are done in main.
3. [Link](https://github.com/kubeflow/kubeflow/issues/7125) to Notebooks 1.8 roadmap
4. @kubeflow/wg-notebooks-leads is updated. The main point of contact is the slack channel #kubeflow-notebooks
5. Kubernetes v1.26, Kustomize 5 is targeted and issues needed to be fixed to use Kustomize 5 are tracked in [this issue](https://github.com/kubeflow/manifests/issues/2388)

**Comment by DnPlas** [comment]
Thanks @NohaIhab for the information, closing this issue.
