### ISSUE TITLE
[kubeflow 1.8] KServe WG and Kubeflow 1.8

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2447]
Hi,

The 1.8 release team will use this tracking issue to coordinate the integration of KServe with Kubeflow 1.8.

Please note that communications (announcements, updates, questions, follow ups, etc.) will be done through kubeflow/manifests#2442 exclusively, this issue will be closed once the release team gathers the initial information from the WG.

Heads up that the proposed feature freeze is Aug 2nd, 2023, but the date is still subject to agreement and discussed [here](https://github.com/kubeflow/community/pull/621). Feel free to comment on the issue for suggestions. We will be sharing the finalised timeline before May 8th, 2023.

To prepare for the release, please provide answers to the following questions:

1. What version of KServe would you like to include for the 1.8 release?
2. Could you provide a branch/tag for this version if you have it already? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
4. Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
5. If you're using any the following dependencies, could you provide the versions you'll be supporting for each one?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for KServe will be defined in the following days and you can keep track of high-level release updates in kubeflow/manifests#2442

**Comment by yuzisun** [comment]
KServe group plan to include KServe 0.11 in the Kubeflow 1.8 release

**Comment by helloericsf** [comment]
Per KServe community call, notes [here](https://docs.google.com/document/d/1KZUURwr9MnHXqHA08TFbfVbM8EAJSJjmaMhnvstvi-k/edit). 
KServe 0.11 timeline [here](https://github.com/kserve/kserve/issues/2676)
Kserve is certified with Kube 1.26
Knative 1.10 and Istio 1.17 needs testing
