### ISSUE TITLE
[kubeflow 1.8] Distributions and Kubeflow 1.8

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2449]
This issue will be used to track the progress of and coordinate with distributions along the 1.8 release.

While we hope all distros will manage to be ready when the KF 1.8 release is out, this is sometimes difficult to achieve. In this issue, we want to both keep track of the progress of distributions towards the KF 1.8 release and also know which of the distros will be working on KF 1.8 (testing during the distribution testing cycle) even if they can't meet the KF 1.8 deadline.

Tagging distribution owners identified from previous releases (**Any new or missed distro owners, please comment on this issue**)

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| AWS 	| @surajkota 	| not participating in 1.8|
| Charmed Kubeflow 	| @DnPlas  	|participating in 1.8|
| Google Cloud 	| @gkcalat<br>@zijianjoy<br>@Linchin 	|participating in 1.8|
| IBM IKS 	| @yhwang 	|participating in 1.8|
| Nutanix 	| @johnugeorge<br>@nagar-ajay 	|participating in 1.8|
| Kubeflow with Argo CD 	| @DavidSpek 	||
| Openshift 	| @VaishnaviHire<br>@LaVLaS 	|participating in 1.8|
| Oracle Cloud Infrastructure 	| @julioo 	||
| VMWare 	| @liuqi<br>@xujinheng 	| participating in 1.8|

Please let us know if you'll be participating in the 1.8 release by answering the following questions:

* Are you planning on having your distro ready in sync with the KF 1.8 release?
* Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?
* If you cannot participate, when can the community expect your distro to be ready for release 1.8?

Please note the release timelines are being discussed in kubeflow/community#638.

cc @kubeflow/release-team @jbottum

**Comment by gkcalat** [comment]
GCP: +@Linchin 

We will participate in the release process.

**Comment by johnugeorge** [comment]
Please add @nagar-ajay  as well to Nutanix distribution

**Comment by DnPlas** [comment]
Hi folks, I would like to announce that the [Kubeflow 1.8 RC.0](https://github.com/kubeflow/manifests/releases/tag/v1.8.0-rc.0) is out 🎉 and that we have started with manifest testing. We expect to finish this process by the end of this week (September 15th).

I would also like to remind all Distribution owners that once Manifest Testing ends we will begin Distribution Testing on September 15th (as soon as we have the results of manifest testing).  Please get your Distributions and infrastructure ready for that stage. Also remember to confirm your distribution is participating in this release and confirm your representatives in the table above.

I also want to take the opportunity to thank all the community members who have helped with getting to this stage. Let's keep working toward a successful release!

**Comment by juliusvonkohout** [comment]
@DnPlas
Telekom Data Science Platform | @juliusvonkohout

can be removed. i am now at a different company.

**Comment by DnPlas** [comment]
Hi folks,

The release team is happy to announce that we have released [Kubeflow 1.8 RC.1](https://github.com/kubeflow/manifests/releases/tag/v1.8.0-rc.1).

This is now the time for Distributions to start with their testing. The release team kindly asks for feedback by the EOW next week. Feel free to submit issues and comment on the various WGs repositories.

I'd like to encourage community members to start testing the release and provide feedback, as well as file issues if any.

I also want to take the opportunity to thank all the community members who have helped with getting to this stage. Let's keep working toward a successful Release!

Kind regards,

The Kubeflow 1.8 Release Team

**Comment by LaVLaS** [comment]
OpenShift will be participating in the testing of KF 1.8 and hosting our manifests on [opendatahub-io/manifests](https://github.com/opendatahub-io/manifests)

CC @jeremyeder

**Comment by Tomcli** [comment]
IBM will be participating in the distribution testing for Kubeflow 1.8 and hosting our manifests at https://github.com/IBM/manifests

**Comment by nagar-ajay** [comment]
Nutanix will be participating in the distribution testing of KF 1.8. Tracking issue: https://github.com/nutanix/kubeflow-manifests/issues/10

**Comment by liuqi** [comment]
I am sorry that I overlooked this issue. Not sure if there is still window. VMware will be participating in the distribution testing of Kubeflow 1.8 and hosting our manifests at https://github.com/vmware/vSphere-machine-learning-extension

**Comment by yhwang** [comment]
Here is the tracking issue for IBM IKS distribution: https://github.com/IBM/manifests/issues/54

**Comment by DnPlas** [comment]
Great! Thanks @liuqi for confirming and thanks @yhwang for sharing the link to IBMs tracking issue.

**Comment by juliusvonkohout** [comment]
So far all my initial tests are also successful, even with KFP 2.0.2 from 30 minutes ago. So an RC2 makes sense for me.

**Comment by DnPlas** [comment]
Hi distributions,

Just FYI, we just released [1.8.0-rc.2](https://github.com/kubeflow/manifests/releases/tag/v1.8.0-rc.2). Please take a look at it and provide feedback/file issues if any. Thanks for your contributions!

**Comment by DnPlas** [comment]
Hi community,

As discussed in yesterday's community meeting, the following is expected to happen:

1. Kubeflow 1.8 GA release date Nov 1st
2. Kubeflow 1.8 RC3 and RC4 are expected to be ready today
    * [RC3](https://github.com/kubeflow/manifests/releases/tag/v1.8.0-rc.3) - solves all of the issues observed in Notebooks (see [this](https://github.com/kubeflow/manifests/issues/2442#issuecomment-1774694153) comment)
    * RC4 - includes Notebook servers images that support ARM architectures. See https://github.com/kubeflow/kubeflow/pull/7357 for more details.
4. Distributions and users are expected to test with RC4, but if there is any issue related to the images, we should roll back to RC3 and use that for the actual release.

As always, we encourage the community to keep testing and providing feedback. Thanks everyone for your contributions!

**Comment by thesuperzapper** [comment]
@DnPlas there was a slight CI issue with the tagging, which prevented the tags for notebook images from being created for `1.8.0-rc.4`, lets quickly resolve it by merging https://github.com/kubeflow/kubeflow/pull/7386, and then cutting `1.8.0-rc.5`.

**Comment by DnPlas** [comment]
Hi community,

In preparation for the release, from the release team we'd like to provide a last chance to give feedback and file issues you consider as potential blockers. As we approach the release (Nov 1st, 2023), we'd like to ensure we don't leave any unattended issues that may happened on the last [RC5](https://github.com/kubeflow/manifests/releases/tag/v1.8.0-rc.5).

Thanks to all the people that already provided feedback!


The release team

**Comment by DnPlas** [comment]
Closing this issue as the release cycle for 1.8 has come to an end. Thanks to all the distributions that participated and provided feedback!
