### ISSUE TITLE
[kubeflow 1.8] Dependencies versions

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/manifests#2450]
This issue will be used for tracking, discussing and sharing the dependencies versions.

> Please note these versions are subject to agreement of all WG and the release team, and may suffer changes in the following days before the release cycle begins on May 8th, 2023.

| Component    | Version used in 1.7 | Version used in 1.8 |
|--------------|------------------|-------------|
| [Knative](https://knative.dev/docs/reference/relnotes/)      |     1.8.1             |     1.10        |
| [Istio](https://istio.io/latest/news/releases/)        |         1.16         |     1.17       |
| [Kubernetes](https://kubernetes.io/releases/)   |         1.25/1.24         |      1.25/1.26 ~1.27 (stretch goal)~      |
| [Cert-Manager](https://cert-manager.io/docs/installation/supported-releases/) |        1.10.1          |   1.12*          |
| [Kustomize](https://github.com/kubernetes-sigs/kustomize/releases)    |         3.2 or 5.0         |       5.0.1      |
| [Dex](https://github.com/dexidp/dex/releases)          |        2.31          |     2.36        |
| [Argo](https://github.com/argoproj/argo-workflows/releases)         |           3.3.8       |      3.3.10       |
| Tekton       |      x            |    0.47 or 0.48      |
| Oidc         |          e236439       |       e236439      |

* This version EOL is end of August 2023 and it's tied to k8s 1.26. For more info, [here](https://cert-manager.io/docs/installation/supported-releases/#upcoming-releases)

**Comment by annajung** [comment]
Based on the Kubeflow [1.8 release timeline](https://github.com/kubeflow/community/pull/621/files), 1.8 is planned to be released in **early Oct**.

Kubernetes
- Kubernetes 1.25 is [EOL 2023-10-28](https://kubernetes.io/releases/#release-v1-25)
- Kubernetes 1.26 is [EOL 2024-02-28](https://kubernetes.io/releases/#release-v1-26)
- Kubernetes 1.27 is [EOL 2024-06-28](https://kubernetes.io/releases/#release-v1-27)
- Latest version of Kubernetes will be 1.28, planned to be [released on August 15th, 2023](https://www.kubernetes.dev/resources/release/#summary), which is during Kubeflow 1.8 manifest testing phase

GKE - pipeline CI/CD
- [GKE release schedule](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels)
  - Stable version
    - 1.26 will be ready 2023-06
    - 1.27 will be ready 2024-Q1 

Other WG uses minikube and KinD, which already support all Kubernetes versions.

Taking all these into account, **I think we should aim for k8s 1.27, assuming that Kubeflow 1.9 will not be released by EOL for k8s 1.26**

cc @kimwnasptd @andreyvelich @johnugeorge @zijianjoy @gkcalat

**Comment by johnugeorge** [comment]
Agree to the idea aiming at 1.27.  Can we support 1.25 as the the minimum version for supporting existing deployments and their upgrades?

**Comment by DnPlas** [comment]
Distribution owners, I would like to confirm with you these versions are okay. Please comment on this issue if you agree/disagree or have suggestions.

cc: @nagar-ajay @Linchin @surajkota @gkcalat @Linchin @yhwang @DavidSpek @VaishnaviHire @LaVLaS @julioo @juliusvonkohout @liuqi

**Comment by DnPlas** [comment]
After discussing the K8S versions with @kimwnasptd @NohaIhab, we decided to go with v1.25 and 1.26 since some of the components are incompatible with K8S 1.27, that is the case for istio 1.17 and cert-manager 1.12.

**Comment by gkcalat** [comment]
lgtm

/cc @zijianjoy @Linchin

**Comment by nagar-ajay** [comment]
lgtm cc: @johnugeorge

**Comment by DnPlas** [comment]
Closing this issue as we have agreed on the versions for the release. No further action is required.

**Comment by gptbert** [comment]
When will kubeflow support k8s 1.28?

**Comment by kabilan6** [comment]
Any plans for K8s 1.28 support before next ajor kubeflow release ?

**Comment by juliusvonkohout** [comment]
Honestly just try out Kubeflow 1.8 with Kubernetes 1.28 and report back here. It might just work.

**Comment by hume-brian** [comment]
@juliusvonkohout any luck with kubeflow 1.8 on k8s 1.28?

**Comment by juliusvonkohout** [comment]
@hume-brian 1.8.1 runs on 1.27-1.29. Although officially only 1.27
