### ISSUE TITLE
Manifests WG Roadmap for KF 1.8

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2456]
Let's use this issue to track work items for Manifests WG and KF 1.8

More work on `/contrib` components
* https://github.com/kubeflow/manifests/pull/2430
* https://github.com/kubeflow/manifests/pull/2329

Further improvements on both tooling and health of manifests
* https://github.com/kubeflow/manifests/pull/2417
* https://github.com/kubeflow/manifests/pull/2455
* https://github.com/kubeflow/manifests/pull/2383
* https://github.com/kubeflow/manifests/pull/2409

Kustomize 5 work
* https://github.com/kubeflow/manifests/issues/2388
* https://github.com/kubeflow/manifests/issues/2421
* https://github.com/kubeflow/manifests/issues/2418

This is just an initial list based on ongoing efforts. Feel free to propose more work items that you are interested in driving to include them as part of our planning

cc @kubeflow/wg-manifests-leads @annajung @juliusvonkohout

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests/issues/2385 should be there as well

**Comment by juliusvonkohout** [comment]
Also interesting is the seldon update in https://github.com/kubeflow/manifests/pull/2337

**Comment by juliusvonkohout** [comment]
/close

superseeded by #2592

**Comment by juliusvonkohout** [comment]
> @kimwnasptd I would like to install kubeflow in OpenShift that has Kustomize Version: v5.0.1. https://www.kubeflow.org/docs/started/installing-kubeflow/#packaged-distributions-of-kubeflow indicates that I need to install kubeflow from https://github.com/opendatahub-io/manifests , which is forked from https://github.com/kubeflow/manifests. But, I do not see branch for v1.8 in https://github.com/opendatahub-io/manifests. Please let me know if I can install kubeflow v1.8 from https://github.com/kubeflow/manifests for OpenShift.

Some good and bad news

1. This thread is thread and not to be resurrected.
2. Kustomize is mostly independent of openshift, but openshift might need multus networkattachmentdefinitions for istio. So yes i  installed tfrom https://github.com/kubeflow/manifests to openshift for several years.
4. Your question is not related to Kubeflow development, but rather an individual consulting issue. Maybe our Kubeflow slack is a better place to ask. Here are also all our meetings https://www.kubeflow.org/docs/about/community/ wg-manifests is our channel
5. There are commercial distributions and consultants available if you do not manage to workaround openshift stuff that deviates from a normal Kubernetes.

**Comment by pmadugundu** [comment]
@juliusvonkohout Thanks for the info and pointing to the right forum to ask the question.
