### ISSUE TITLE
notebook connect error: upstream connect error or disconnect/reset before headers.

### ISSUE THREAD

**Issue by hakimliang** [kubeflow/manifests#2467]
kubernetes:1.25.10  Single node deployment
kustomize:5.0.3
kubeflow:1.7
I have successfully deployed Kubernetes and Kubeflow on the VMware virtual machine, and I can log in to the dashboard page. When I tried to create a new jupyter, I encountered an error: Could not find CSRF cookie XSRF TOKEN in the request. And then my app_ Secure_ After COOKIES=False, initialization can be successful. However, when I connected to Notebook, I found the following error. Has anyone told me where the specific problem lies?
![image](https://github.com/kubeflow/manifests/assets/23026161/93d217c1-6e7a-4e51-81ed-41c213a19f88)
![image](https://github.com/kubeflow/manifests/assets/23026161/56bbe12e-d46c-4cdc-a3d0-bbeea9648d59)

**upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111**

**Comment by juliusvonkohout** [comment]
This issue is in the wrong repository. Please recreate it in kubeflow/kubeflow

/close
