### ISSUE TITLE
Issues with ARM64(M1/M2 Apple Silicon) Docker Images during Kubeflow v1.7.0 Installation

### ISSUE THREAD

**Issue by hwang9u** [kubeflow/manifests#2472]
Hi! I’m new to Kubernetes and Kubeflow.
During the installation process, I encountered `ErrImagePull` errors in several pods.  
Upon investigation, I discovered that several **Docker images under the `docker.io/kubeflownotebookswg` repository do not support the ARM64 architecture.**
As a temporary workaround, I opted to use Docker images from the https://hub.docker.com/u/vinaychandran , which provided ARM64-compatible versions. By using these alternative images, I was able to successfully complete the installation process.

The images that require modification are as follows:
- poddefaults-webhook
- centraldashboard
- jupyter-web-app
- notebook-controller
- profile-controller
- kfam
- tensorboards-web-app
- volumes-web-app
- models-web-app

I made following changes(https://github.com/hwang9u/manifests/commit/7008414a59ddb251d79ba2f16a87c5acf7d83d12):
<img width="912" alt="image" src="https://github.com/kubeflow/manifests/assets/48237908/5df744d8-4de1-45e0-8dc2-7f3eac04d695">

**So, I kindly request the development team to consider updating the docker.io/kubeflownotebookswg repository to include ARM64-compatible Docker images.**
Thank you for your attention to this issue.
Have a nice day 🐶

---
kubernetes version: v1.23.1 Single node deployment
minikube version: v1.30.1
kustomize version: v5.0.0

**Comment by annajung** [comment]
Hi, thanks for sharing the issue and workaround.

This issue actually needs to be moved to the `kubefow/kubeflow` and `kserve` repo to allow the right folks to track the issue since the Manifest team is not responsible for the images created in `docker.io/kubeflownotebookswg` and `kserve/models-web-app`. 

We can leave this issue open until the issues are copied over the correct repo.

**Comment by juliusvonkohout** [comment]
/close

tracked in https://github.com/kubeflow/kubeflow/issues/2337
