### ISSUE TITLE
Apiversion issue "autoscaling/v2beta2" during on installing kubeflow(#2460)

### ISSUE THREAD

**Issue by chromatices** [kubeflow/manifests#2476]
### Issue
- During install kubeflow at #2460 with k8s 1.26.3, kustomize 5.0.0, error occur by API version "autoscaling/v2beta2".
![image](https://github.com/kubeflow/manifests/assets/56014940/077a132a-d9b1-4645-9627-329de436ee13)

- I edited the file `./common/knative/knative-serving/base/upstream/serving-core.yaml` at line 5797 and install was completed without any issue.

### Version
- K8S : 1.26.3
- kubeflow : master(#2460)
- kustomize : 5.0.0

**Comment by annajung** [comment]
Issue has been resolved by https://github.com/kubeflow/manifests/pull/2486

/close
