### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by N214** [kubeflow/manifests#2495]
Hi,

I am successfully installed kubeflow, but I'm wondering how kubeflow or the different parts should be upgraded in the future?

And how should the upgrade process be? I did not find any documentation for that. 

Thank you

**Comment by juliusvonkohout** [comment]
/close 

duplicate of #2216

**Comment by juliusvonkohout** [comment]
Solved by https://github.com/kubeflow/manifests/pull/2717
