### ISSUE TITLE
Pull images not found for ML Pipelines

### ISSUE THREAD

**Issue by wlargou** [kubeflow/manifests#2496]
Hi,

I'm trying to pull the images for the ML Pipelines but I get this error : 

  Warning  Failed     7m27s (x3 over 8m4s)  kubelet            Failed to pull image "gcr.io/ml-pipeline/cache-server:dummy": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/ml-pipeline/cache-server:dummy": failed to resolve reference "gcr.io/ml-pipeline/cache-server:dummy": gcr.io/ml-pipeline/cache-server:dummy: not found
  
  
  Same goes for the other images : 

nerdctl pull gcr.io/ml-pipeline/metadata-envoy:dummy
nerdctl pull gcr.io/ml-pipeline/persistenceagent:dummy
nerdctl pull gcr.io/ml-pipeline/viewer-crd-controller:dummy
nerdctl pull gcr.io/ml-pipeline/scheduledworkflow:dummy
nerdctl pull gcr.io/ml-pipeline/visualization-server:dummy
nerdctl pull gcr.io/ml-pipeline/metadata-writer:dummy
nerdctl pull gcr.io/ml-pipeline/api-server:dummy
nerdctl pull gcr.io/ml-pipeline/frontend:dummy
nerdctl pull gcr.io/ml-pipeline/inverse-proxy-agent:dummy
nerdctl pull gcr.io/ml-pipeline/cache-server:dummy
nerdctl pull gcr.io/ml-pipeline/cache-deployer:dummy

I have tried to replace dummy with latest still not working,

Any help appreciated

**Comment by wlargou** [comment]
Resolved, thank you @annajung  had to specify the tags

**Comment by wangzhao123456** [comment]
> Resolved, thank you [@annajung](https://github.com/annajung) had to specify the tags

hello, I install kubelfow1.8.1 using kustomize and I face a question that I can't pull nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5 using nerdctl. When I using 'nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5', the result is image not found. Other images such as gcr.io/ml-pipeline/api-server:2.0.5 can be pulled normally. Have you ever encountered such a problem during deployment?  Thanks in advance.

**Comment by wangzhao123456** [comment]
> You can find all the image versions here: https://console.cloud.google.com/gcr/images/ml-pipeline

hello, I install kubelfow1.8.1 using kustomize and I face a question that I can't pull nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5 using nerdctl. When I using 'nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5', the result is image not found. Other images such as gcr.io/ml-pipeline/api-server:2.0.5 can be pulled normally. Have you ever encountered such a problem during deployment? Thanks in advance.

**Comment by juliusvonkohout** [comment]
> > You can find all the image versions here: https://console.cloud.google.com/gcr/images/ml-pipeline
> 
> hello, I install kubelfow1.8.1 using kustomize and I face a question that I can't pull nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5 using nerdctl. When I using 'nerdctl pull gcr.io/ml-pipeline/frontend:2.0.5', the result is image not found. Other images such as gcr.io/ml-pipeline/api-server:2.0.5 can be pulled normally. Have you ever encountered such a problem during deployment? Thanks in advance.

@wangzhao123456 Please install Kubeflow 1.10.2 or the 1.11 prerelease https://github.com/kubeflow/manifests/releases/tag/v1.11.0-rc.1. 1.8 is too old and not supported. If you need help there is commercial support available here https://www.kubeflow.org/docs/started/support/#support-from-commercial-providers-in-the-kubeflow-ecosystem
