### ISSUE TITLE
Kubeflow-node-red migrate to add-on.

### ISSUE THREAD

**Issue by NightLightTw** [kubeflow/manifests#2499]
@thesuperzapper  sir:
I just posted an issue within the manifest group asking for help with the add-on merge of our PR. The link is as follows:
[https://github.com/NightLightTw/kube-nodered](https://github.com/NightLightTw/kube-nodered)
Please help to put it within the kubeflow add-on settings. Also please tell us how to proceed with the rest of the steps to merge.

**Comment by thesuperzapper** [comment]
Cross-linking your previous issue for those coming here: https://github.com/kubeflow/pipelines/issues/9532

**Comment by thesuperzapper** [comment]
@NightLightTw Thanks for sharing this! The Kubeflow community loves it when people make projects in the ecosystem.

First, I want to say, that I understand promoting new projects is hard! 

The Kubeflow community has had many discussions about how to expose related projects on the Kubeflow website, (for example, under the [External Add-Ons](https://www.kubeflow.org/docs/external-add-ons/) section), but we don't really have clear guidelines right now.

I strongly expect that any such guidelines will require a minimum level of adoption and sustained support for projects before they can be listed. Unless I am mistaken I can't see any significant adoption of your tool yet (https://github.com/NightLightTw/kube-nodered)?

Therefore, my recommendations are:

1. Take steps to promote and share your product with potential users:
      - Presenting at Conferences
      - Posting on Reddit
      - Giving demos at community meetings
      - Youtube Videos
      - Responding on the Kubeflow Slack
      - Responding to related GitHub issue threads
      - etc
2. Once you have achieved some level of independent adoption of your tool, I am sure the community will be happy to list it on the Kubeflow website
3. We will also expect any listed project to have clear and active maintainers (and are currently in the process of de-listing some external-add-ons that are inactive from the website)

**Comment by thesuperzapper** [comment]
Also tagging @akgraner and @jbottum because you expressed interest in developing our guidelines on promoting "related projects" on the Kubeflow website.

**Comment by 482170765** [comment]
@thesuperzapper Thank you for your feedback on further steps for our project to become part of add-on repository within Kubeflow community.  Yes, we will make best efforts to make our project publicly available through the channels recommended by you.  As a side kick, I would stress that our project will be a long term development effort joined many graduate students.  This project is supported by our Department of Education for four years.  The purpose of this program is to folster Taiwanese students' capabilities and interests in contributing to world class coding communities such as Kubeflow, Node-red, qiskit, etc.  In addition to putting our initial work in the public channel, we are currently reinforcing the architecture to be more robust and self sustainable.  We will keep updating the states of our product, adn your help is definitely greatly appreciated.
