### ISSUE TITLE
To many open issues and PRs and no stalebot

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#2514]
@kimwnasptd @annajung 

We have 140 open issues. Some of them are against e.g. Kubeflow 1.3 and many are just spam or legacy stuff. Who has the permissions to manage and close them ? https://github.com/kubeflow/manifests/issues?page=6&q=is%3Aissue+is%3Aopen
The same goes for open PRs of which some are from 2021 https://github.com/kubeflow/manifests/pull/1925
[kimonas] Anna to the rescue with /close
[anna] Should we use the stalebot for closing some automatically?
[julius] The stalebot is not  maintained anymore
[anna] maybe we could use GH Apps (not actions) for closing those

I will still go trough them manually on a weekend.

**Comment by juliusvonkohout** [comment]
and now it is down from 140 to 70 issues

**Comment by juliusvonkohout** [comment]
for kubeflow/kubeflow issues down frm 326 to 306

**Comment by annajung** [comment]
Hey @juliusvonkohout, as mentioned in the previous Manifest WG meeting, there is [github action stale](https://github.com/kubeflow/community/issues/643#issuecomment-1679385976) that was shared in the community repo by the pipeline WG.

while issues need to be triaged by the WGs, we should implement this for Manifest to manage the stale issues

**Comment by juliusvonkohout** [comment]
@annajung Yes please let us enable this for kubeflow/kubeflow and kubeflow/manifests

**Comment by juliusvonkohout** [comment]
@rimolive wants to take this

**Comment by juliusvonkohout** [comment]
@hansinikarunarathne

**Comment by juliusvonkohout** [comment]
@hansinikarunarathne Check whether the stalebot works and escalate to KSC members to add the repository secret if needed

**Comment by juliusvonkohout** [comment]
it seems to work so far
