### ISSUE TITLE
PVCViewer manifests weren't copied to v1.8.0-rc.0

### ISSUE THREAD

**Issue by TobiasGoerke** [kubeflow/manifests#2524]
The [manifests](https://github.com/kubeflow/kubeflow/tree/master/components/pvcviewer-controller/config) of the newly added PVCViewer weren't copied to the current release, causing the volumes web app to throw errors when opening a viewer.

Also, we should merge the following PRs before doing so:
* https://github.com/kubeflow/kubeflow/pull/7237
* https://github.com/kubeflow/kubeflow/pull/7247

**Comment by annajung** [comment]
cc @DnPlas @kubeflow/release-team to track for 1.8

**Comment by DnPlas** [comment]
hey @TobiasGoerke , thanks for raising this issue. Regarding the PVCViewer manifests, I recently synced them in `master`, you can find them [here](https://github.com/kubeflow/manifests/tree/master/apps/pvcviewer-controller/upstream) and the change should land soon in `v1.8-branch` https://github.com/kubeflow/manifests/pull/2535.

**Comment by TobiasGoerke** [comment]
Great, thanks for taking care of this, @DnPlas!

Shall we also add the pvcviewer-controller to the `example/kustomization.yaml`? Like:
`- ../apps/pvcviewer-controller/upstream/base`

**Comment by kimwnasptd** [comment]
@TobiasGoerke yes, we'll need to add it. I can make a PR for this
