### ISSUE TITLE
No Namespace

### ISSUE THREAD

**Issue by manang** [kubeflow/manifests#2533]
Good morning,
I've installed kubeflow 1.7.0,  (but with the 1.8.0-rc.0 too) using the single command
`while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done`,
but i'm not able to see the namespaces.
Opening the develper console of chrome i see the following errors:
`
:8080/api/workgroup/exists:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/pipeline/apis/v1beta1/runs?page_size=5&sort_by=created_at%20desc&resource_reference_key.type=NAMESPACE&resource_reference_key.id=undefined:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8080/pipeline/apis/v1beta1/pipelines?page_size=5&sort_by=created_at%20desc:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)` 
Do you have idea how to solve this issue?
Thanks a lot

**Comment by manang** [comment]
anybody that can help me with this issue?

**Comment by manang** [comment]
I found the solution.
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

after setting the values as this document says, it works

**Comment by annajung** [comment]
Hi @manang, glad to hear that you were able to find the fix for the problem. This might be helpful to other users who may run into the same problem, maybe this is something that would be valuable to add to the troubleshooting section in the README? Do you want to update the README?

**Comment by juliusvonkohout** [comment]
This is an issue on his cluster, not Kubeflow. I propose to close.
