### ISSUE TITLE
jupyter notebook not connect only

### ISSUE THREAD

**Issue by Sujittibe123** [kubeflow/manifests#2543]
jupyter notebook not connect only but vs code and r studio notebook successfully connected.
when i check notebook pod logs, i get this runtime error "RuntimeError: Permissions assignment failed for secure file: '/home/jovyan/.local/share/jupyter/runtime/jpserver-9060.json'. Got '0o677' instead of '0o0600'."
and on kubeflow ui i see this error "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111"
<img width="704" alt="jupyter notebook logs" src="https://github.com/kubeflow/manifests/assets/49091383/255ddfe5-afad-4caf-bc54-f9f802ae52d3">
<img width="900" alt="image" src="https://github.com/kubeflow/manifests/assets/49091383/64735b01-7fb6-46ed-bb91-e88cb314c5b2">
<img width="881" alt="image" src="https://github.com/kubeflow/manifests/assets/49091383/e09425db-caca-43b2-8b8c-ef6391604420">

**Comment by juliusvonkohout** [comment]
/close

Hello, please report in the kubeflow/kubeflow repository and try to debug it first.
