### ISSUE TITLE
Kubeflow notebooks fail to start  Internal error occurred: failed calling webhook "admission-webhook-deployment.kubeflow.org": failed to call webhook: Post "https://admission-webhook-service.kubeflow.svc:443/apply-poddefault?timeout=10s": dial tcp 10.43.113.106:443: i/o timeout

### ISSUE THREAD

**Issue by femtonelson** [kubeflow/manifests#2547]
Warm greetings !
Thanks for the great work done so far.

I have an issue with Kubeflow notebooks that suddenly fail to launch with the following error :  
Reissued from statefulset/cmc: create Pod cmc-0 in StatefulSet cmc failed error: Internal error occurred: failed calling webhook "admission-webhook-deployment.kubeflow.org": failed to call webhook: Post "https://admission-webhook-service.kubeflow.svc:443/apply-poddefault?timeout=10s": dial tcp 10.43.113.106:443: i/o timeout

What could be the problem please?

Kubernetes version : RKE1, K8s 1.25.13
Kubeflow : 1.7 
Istio-system authservice docker image version : gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef (authentication fails with v1.7 default docker image)

**Comment by juliusvonkohout** [comment]
/close

The webhook has just been reworked to be more performant in a prior issue.

**Comment by juliusvonkohout** [comment]
For a fix build from master or try 1.8 in the next weeks.

**Comment by juliusvonkohout** [comment]
And this is the wrong repository to report this. Kubeflow/kubeflow is your friend.
