### ISSUE TITLE
[403] Could not find CSRF cookie XSRF-TOKEN in the request. http://114.55.110.169:8090/jupyter/api/namespaces/kubeflow-user-example-com/notebooks

### ISSUE THREAD

**Issue by tiansiyuan** [kubeflow/manifests#2569]
On newly deployed Kubeflow 1.8 on a single node kind cluster, all the pods are in running status. I login using the default user and try to create a notebook server. After I will/choose all needed fields, when I click "LAUNCH", I get:

[403] Could not find CSRF cookie XSRF-TOKEN in the request. http://114.55.110.169:8090/jupyter/api/namespaces/kubeflow-user-example-com/notebooks

Then, it disappears shortly afternoon.

<img width="846" alt="Screenshot 2023-11-08 at 16 48 41" src="https://github.com/kubeflow/manifests/assets/228619/1e08962d-3931-4984-b5fa-30f6057a4b0b">

Is there anyway to debug?

I can attach the list of all running pods and screen shot of Activity if needed.

Thanks!

**Comment by yurkoff-mv** [comment]
Try it on cluster PC http://127.0.0.1:8090/jupyter/api/namespaces/kubeflow-user-example-com/notebooks
After creating notebook you can access it from outside.

I do it like this...
`microk8s kubectl get service istio-ingressgateway -n istio-system` 
Responce:
```
NAME                   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   NodePort   10.152.183.181   <none>        15021:32693/TCP,80:31368/TCP,443:30303/TCP,31400:31034/TCP,15443:31551/TCP   24h
```
Port 80 corresponds to the external port 31368 (`,80:31368/TCP`)
http://114.55.110.169:31368

**Comment by tiansiyuan** [comment]
@yurkoff-mv Thank you for your comment. 

I am not able to create notebook server and the error prompt is what I gave. The cluster PC is in a cloud environment and I have no GUI/browser access. when I use the following command:

curl http://127.0.0.1:8090/jupyter/api/namespaces/kubeflow-user-example-com/notebooks

I get:

<a href="/dex/auth?client_id=kubeflow-oidc-authservice&amp;redirect_uri=%2Fauthservice%2Foidc%2Fcallback&amp;response_type=code&amp;scope=openid+profile+email+groups&amp;state=MTY5OTk0MzIxNnxOd3dBTkUxVk5FdERSRmxYVTFBMk0xTXlNemRJTjBsUk0xVkpXRXhZVTBVek4xVlFOMHRHVjBKS1JsQkVSakpaUjFwVVdrSklUbEU9fJDcxJW06CiNFaK2qU9XI5h80PizKcA9l9kJLGu_C3R9">Found</a>.

When I run:

kubectl get service istio-ingressgateway -n istio-system

I get:

NAME                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                    AGE
istio-ingressgateway   ClusterIP   10.96.6.158   <none>        15021/TCP,80/TCP,443/TCP   4d22h

There is a  difference compared with before:

When I click LAUNCH, I get the message before what I got in the screen shot I mentioned before and it disappears very soon:

Submitting new notebook...

Thanks

**Comment by tunahanertekin** [comment]
Hey there! I'm also encountering the same problem when I try to create a notebook instance. (I used single command deployment in [this tag](https://github.com/kubeflow/manifests/tree/v1.8.0)) Any progress? Thanks.

**Comment by juliusvonkohout** [comment]
/close

please report in kubeflow/kubeflow

**Comment by Player01Sid** [comment]
@tiansiyuan You can run a temporary desktop and RDP environment as a container.
`docker run --privileged --rm -d --network host -e RDP_USER=<rdp-username> -e RDP_PASSWORD=<rdp-password> --device=/dev/tty0 --device=/dev/tty1 --device=/dev/console --env DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/dri:/dev/dri player01sid/deskport
`

Follow for reference [https://hub.docker.com/r/player01sid/deskport](url)
