### ISSUE TITLE
Please update the KServe to the version 0.11.2

### ISSUE THREAD

**Issue by yurkoff-mv** [kubeflow/manifests#2572]
KServe PODs is not restored after rebooting to previous versions: https://github.com/kserve/kserve/issues/3256

**Comment by juliusvonkohout** [comment]
[yurkoff-mv](https://github.com/yurkoff-mv) please test our 1.8 branch with kserve 0.11.2 and report back.

**Comment by juliusvonkohout** [comment]
reopen since we need to do this for master as well in https://github.com/kubeflow/manifests/pull/2633
