### ISSUE TITLE
cannot find a network-attachment-definition (istio-cni) in namespace (kubeflow) 

### ISSUE THREAD

**Issue by sarvasuddi-balaganesh** [kubeflow/manifests#2580]
I have tried to install using istio got the following error in the init containers
error   Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'

Then tired using istio-cni, im facing the following error:
Warning  FailedCreatePodSandBox  91s (x38 over 9m54s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_cache-deployer-deployment-76bf9cbfff-8zqgx_kubeflow_548b8abb-ee7e-46ef-aca2-19287a4b8d31_0(a061b907d111989fb3cf71c9e2f28a9308026f21012fe3572780202b3f526bf9): error adding pod kubeflow_cache-deployer-deployment-76bf9cbfff-8zqgx to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): Multus: [kubeflow/cache-deployer-deployment-76bf9cbfff-8zqgx/548b8abb-ee7e-46ef-aca2-19287a4b8d31]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: cannot find a network-attachment-definition (istio-cni) in namespace (kubeflow): network-attachment-definitions.k8s.cni.cncf.io "istio-cni" not found
  Warning  NoNetworkFound          78s                   multus             cannot find a network-attachment-definition (istio-cni) in namespace (kubeflow): network-attachment-definitions.k8s.cni.cncf.io "istio-cni" not found

**Comment by juliusvonkohout** [comment]
This is known and Openshift specific. It does not follow a standard Kubernetes, which does not need the networkattachmentdefinition. 

I ran Kubeflow on openshift with istio-cni for several years, so if you need professional consulting just contact me. 
Otherwise this is out of scope for the upstream project and i have to 

/close
