### ISSUE TITLE
oidc-authservice-0 is pending 

### ISSUE THREAD

**Issue by shixinlishixinli** [kubeflow/manifests#2582]
kubectl describe pod oidc-authservice-0 -n istio-system
Name:             oidc-authservice-0
Namespace:        istio-system
Priority:         0
Service Account:  authservice
Node:             <none>
Labels:           app=authservice
                  controller-revision-hash=oidc-authservice-5c9d96568b
                  statefulset.kubernetes.io/pod-name=oidc-authservice-0
Annotations:      sidecar.istio.io/inject: false
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/oidc-authservice
Containers:
  authservice:
    Image:      docker.io/kubeflowmanifestswg/oidc-authservice:e236439
    Port:       8080/TCP
    Host Port:  0/TCP
    Readiness:  http-get http://:8081/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      oidc-authservice-client      Secret     Optional: false
      oidc-authservice-parameters  ConfigMap  Optional: false
    Environment:                   <none>
    Mounts:
      /var/lib/authservice from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tprqw (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  authservice-pvc
    ReadOnly:   false
  kube-api-access-tprqw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  73s (x97 over 8h)  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

kubectl  get pod -A |grep authservic
istio-system                oidc-authservice-0                                      0/1     Pending            0                 8h

i am new here. so why this pod is pending and how to solve this bug?

Best
Lisa Shi

**Comment by juliusvonkohout** [comment]
This is a Kubernetes problem, not a Kubeflow problem.

**Comment by marjolein-groupm** [comment]
I am actually having the same issue. Pod "authservice-0" is using the persistent volume that "oidc-authservice-0" tries to use. This happened after upgrading to the latest release.
