### ISSUE TITLE
mlpipeline grpc deployment error

### ISSUE THREAD

**Issue by ChaejinE** [kubeflow/manifests#2587]
![image](https://github.com/kubeflow/manifests/assets/69780812/73d28fb7-5812-4dfd-bb00-4f7c1f95ee56)

- I installed kubeflow v1.7, k8s version 1.26 But grpc deployment pod is not connected with mysql
- mysql's /var/lib/mysql folder's permission uid, gid 999
- On premise (Ubuntu 22.04)

**Comment by juliusvonkohout** [comment]
On premises does not matter, but Kubeflow 1.7 is not supported anymore and definitely not on Kubernetes 1.26. Please use Kubeflow 1.8. You can also create a PR to fix this.

**Comment by ChaejinE** [comment]
<img width="1189" alt="image" src="https://github.com/kubeflow/manifests/assets/69780812/df3aba75-8c9a-4858-87bf-0e3a358aa6be">

<img width="1408" alt="image" src="https://github.com/kubeflow/manifests/assets/69780812/ca228334-3008-48c8-9ed5-2191105b411b">

It was also not working on v1.8 ..

**Comment by juliusvonkohout** [comment]
Then please create a PR with the fsgroup fix.

**Comment by juliusvonkohout** [comment]
Well you can at least join the working group meeting to discuss it.
