### ISSUE TITLE
Manifests WG KF 1.9 tracker

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#2592]
Let's use this issue to track work items for Manifests WG and KF 1.9
follow up of https://github.com/kubeflow/manifests/issues/2456

See also https://github.com/kubeflow/manifests/issues/2613 for version tracking
and security stuff implemented in the manifests repository https://github.com/kubeflow/manifests/issues/2598

- Ray: https://github.com/kubeflow/manifests/pull/2732 https://github.com/kubeflow/manifests/pull/2675
- https://github.com/kubeflow/manifests/issues/2433
- https://github.com/kubeflow/manifests/pull/2667
- https://github.com/kubeflow/manifests/issues/2747
- https://github.com/kubeflow/manifests/pull/2731

More work on `/contrib` components
- https://github.com/kubeflow/manifests/pull/2329

Further improvements on both tooling and health of manifests
- https://github.com/kubeflow/manifests/pull/2750
- https://github.com/kubeflow/manifests/issues/2216
- https://github.com/kubeflow/community/pull/720
- Bentoml:  https://github.com/kubeflow/manifests/pull/2704
- seldon https://github.com/kubeflow/manifests/pull/2719
- https://github.com/kubeflow/manifests/pull/2703
- knative 1.12.4 https://github.com/kubeflow/manifests/pull/2709
- Dex https://github.com/kubeflow/manifests/pull/2710 https://github.com/dexidp/dex/releases/tag/v2.39.1 https://github.com/kubeflow/manifests/pull/2669 https://github.com/kubeflow/manifests/pull/2596 https://github.com/kubeflow/manifests/pull/2590/files
- Kubernetes 1.27-1.29 https://github.com/kubeflow/manifests/pull/2637 https://github.com/kubeflow/manifests/pull/2643 https://github.com/kubeflow/manifests/pull/2716
- https://github.com/kubeflow/manifests/pull/2693
- https://github.com/kubeflow/manifests/pull/2666/
- https://github.com/kubeflow/manifests/pull/2219 and  https://github.com/kubeflow/manifests/issues/2218
- Seldon: https://github.com/kubeflow/manifests/pull/2532 
- Kserve: https://github.com/kubeflow/manifests/pull/2751 https://github.com/kubeflow/manifests/pull/2627 https://github.com/kubeflow/manifests/issues/2553 https://github.com/kubeflow/manifests/pull/2696 https://github.com/kubeflow/manifests/pull/2702
- Pipelines: https://github.com/kubeflow/manifests/pull/2695 https://github.com/kubeflow/manifests/pull/2700
- Model Registry: https://github.com/kubeflow/manifests/pull/2697 https://github.com/kubeflow/manifests/pull/2682
- Training operator: https://github.com/kubeflow/manifests/pull/2699
- Katib: https://github.com/kubeflow/manifests/pull/2698
- PVCviewer https://github.com/kubeflow/manifests/pull/2574

Oauth2-proxy and JWT
- https://github.com/kubeflow/manifests/issues/2469
- https://github.com/kubeflow/manifests/issues/2516
- https://github.com/kubeflow/manifests/issues/2517
- https://github.com/kubeflow/manifests/pull/2544 also includes e2e testing
- https://github.com/kubeflow/manifests/pull/2670
- https://github.com/kubeflow/manifests/pull/2656

Kustomize 5 work
- https://github.com/kubeflow/manifests/issues/2388 Maybe we should close it after 1.9 and open a new one.
- https://github.com/kubeflow/manifests/pull/2586
- https://github.com/kubeflow/manifests/pull/2583
- https://github.com/kubeflow/manifests/pull/2653
- https://github.com/kubeflow/manifests/issues/2548
- https://github.com/kubeflow/manifests/pull/2654
- https://github.com/kubeflow/manifests/pull/2537

This is just an initial list based on ongoing efforts. Feel free to propose more work items that you are interested in driving to include them as part of our planning

cc @kubeflow/wg-manifests-leads @kimwnasptd 

GSOC for 1.10 probably :
- Add the stalebot from https://github.com/kubeflow/manifests/issues/2514
- New issue templates https://github.com/kubeflow/manifests/pull/2708
- New PR templates
- Maybe Switch to Istio CNI as default
- Let’s test if we can have the baseline PSS with the default Istio 
- Istio CNI and setting the kserve-needed annotation across all Pods

**Comment by StefanoFioravanzo** [comment]
Hello @juliusvonkohout , this is a kind reminder that Monday, March 4th will be our Kubeflow 1.9 release development checkpoint, we will be halfway through our dev cycle, and we expect most of the work to be well underway.

Can you please acknowledge your status with respect to the manifests roadmap, comment on the progress made so far, and provide an assessment of the work that remains?

The comment above includes a lot of work streams, part of which are probably related to the Security Working Groups. Can you please update the comment to list only the work that pertains to the Manifests, and clearly call out what's already completed and what remains to be done?

**Comment by juliusvonkohout** [comment]
@StefanoFioravanzo i updated the top post, but the development is still ongoing.

**Comment by juliusvonkohout** [comment]
@StefanoFioravanzo @rimolive i added lots of stuff and it should be more clear now what is left for 1.9.0 rc1

**Comment by StefanoFioravanzo** [comment]
@juliusvonkohout can we close this issue? I guess we are tracking any active item in #2763

**Comment by juliusvonkohout** [comment]
Yes i will close, but our shiny new stalebot would do so as well :-)
