### ISSUE TITLE
Training WG roadmap for KF 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2597]
Hello @kubeflow/wg-training-leads @johnugeorge

The [1.9 release](https://github.com/kubeflow/community/blob/master/releases/release-1./release-team.md) team will use this tracking issue to coordinate the integration of the Training Operator with the Kubeflow 1.9 release.

Heads up that the feature freeze is scheduled for April 15th (needs confirmation). For the full release schedule, refer to the [1.9 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.9/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/687 and https://github.com/kubeflow/community/pull/690)_

To prepare for the 1.9 release, please provide answers to the following questions:

1. What version of Training Operator would you like to include for the 1.9 release?
2. Could you provide a branch/tag for this version? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

* KServe/KNative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for Training Operator WG will be @nagar-ajay and you can keep track of high-level release updates in the https://github.com/kubeflow/manifests/issues/2600 issue.

**Comment by andreyvelich** [comment]
Tracking issue for Training Operator 1.8: https://github.com/kubeflow/training-operator/issues/1994
