### ISSUE TITLE
Many of the used images are incompatible with ARM64

### ISSUE THREAD

**Issue by deltawi** [kubeflow/manifests#2599]
I saw that a lot of pods use images from docker hub with tag `v1.8.0-rc.0` which is `amd64`. Switching to `v1.8.0-rc.5` makes it compatible with both `amd64/arm64`.

**Comment by juliusvonkohout** [comment]
Please do not use the master branch for production deployments. If these images are not properly set in the 1.8.1-rc0 tag please reopen.

/close
