### ISSUE TITLE
ambassador should  be dropped

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/manifests#26]
since kubeflow 0.6 will drop ambassador as [here](https://github.com/kubeflow/kubeflow/issues/3021#issuecomment-484724088), I think maybe we should drop ambassador manifest, too.

**Comment by swiftdiaries** [comment]
Once a VirtualService is defined for all existing components (that use Ambassador) in Istio and Istio is also added to the manifests, we'll be well placed to remove Ambassador

**Comment by jlewi** [comment]
https://github.com/kubeflow/manifests/tree/master/common/ambassador/base

@kunmingg Are we still using Ambassador for basic auth?

Related: kubeflow/kubeflow#3833

**Comment by kunmingg** [comment]
The basic auth still depend on Ambassador, need to switch it to Istio before dropping Ambassador
