### ISSUE TITLE
KF release 1.9 tracking

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2600]
This issue will be used to provide high-level updates for the Kubeflow 1.9 release.
* [Release Timeline](https://github.com/kubeflow/community/tree/master/releases/release-1.9)
* [Release Team](https://github.com/kubeflow/community/blob/master/releases/release-1.9/release-team.md)
* [Release Board](https://github.com/orgs/kubeflow/projects/61)

cc @kubeflow/release-team

**Comment by tarilabs** [comment]
> Model Registry 0.1-alpha (@tarilabs to confirm)

I'd propose `Model Registry 0.2-alpha` to avoid potential confusion with the images produced before onboarding the project into Kubeflow.

**Comment by tarilabs** [comment]
This is actively worked on by the @kubeflow/release-team 

/lifecycle frozen

**Comment by juliusvonkohout** [comment]
i think we can close this, if not please reopen.
