### ISSUE TITLE
KServe roadmap for KF 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2603]
Hello @pvaneck @yuzisun

The [1.9 release](https://github.com/kubeflow/community/blob/master/releases/release-1./release-team.md) team will use this tracking issue to coordinate the integration of the KServe with the Kubeflow 1.9 release.

Heads up that the feature freeze is scheduled for April 15th (needs confirmation). For the full release schedule, refer to the [1.9 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.9/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/687 and https://github.com/kubeflow/community/pull/690)_

To prepare for the 1.9 release, please provide answers to the following questions:

1. What version of KServe would you like to include for the 1.9 release?
2. Could you provide a branch/tag for this version? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for KServe WG will be @ca-scribner and you can keep track of high-level release updates in the 1.9 tracking issue.

**Comment by yuzisun** [comment]
* What version of KServe would you like to include for the 1.9 release? KServe 0.12 which is releasing soon after [RC1](https://github.com/kserve/kserve/releases/tag/v0.12.0-rc1). 

* Could you provide a branch/tag for this version? (note: It doesn't have to be final)
https://github.com/kserve/kserve/tree/release-0.12

* Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?
https://github.com/orgs/kserve/projects/12

* If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?
Knative: 1.12
Istio: 1.18, 1.19, 1.20
Kubernetes: 1.27, 1.28, 1.29

**Comment by rimolive** [comment]
@yuzisun our plan is support k8s 1.29 as the target release but will work on testing on 1.27 and 1.28. We're planning to update to Istio 1.20.

**Comment by yurkoff-mv** [comment]
Please consider [this issue](https://github.com/kubeflow/manifests/issues/2576) when building KServe.

**Comment by juliusvonkohout** [comment]
@yuzisun i wanted to upgrade to 0.11.2 first, but some stuff is missing from the docker.io OCI registry.
 i cannot se the tag 0.11.2 in https://hub.docker.com/r/kserve/models-web-app/tags 

SO we are blocked from upgrading in https://github.com/kubeflow/manifests/pull/2616

**Comment by juliusvonkohout** [comment]
@yuzisun or can you upgrade kserve for us?

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests/issues/2433 is also problematic

**Comment by rimolive** [comment]
Still waiting on updates about MWA

**Comment by rimolive** [comment]
Closing this issue. We had good progress on Models Webapp.

/close
