### ISSUE TITLE
Pipelines WG roadmap for KF 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2607]
Hello @kubeflow/wg-pipeline-leads @zijianjoy

The [1.9 release](https://github.com/kubeflow/community/blob/master/releases/release-1./release-team.md) team will use this tracking issue to coordinate the integration of the Pipelines with the Kubeflow 1.9 release.

Heads up that the feature freeze is scheduled for April 15th (needs confirmation). For the full release schedule, refer to the [1.9 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.9/README.md).

_(note: links are pending https://github.com/kubeflow/community/pull/687 and https://github.com/kubeflow/community/pull/690)_

To prepare for the 1.9 release, please provide answers to the following questions:

1. What version of Pipelines would you like to include for the 1.9 release?
2. Could you provide a branch/tag for this version? (note: It doesn't have to be final)
3. Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?
4. If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize

The release team WG liaison for Pipelines WG will be @milosjava and you can keep track of high-level release updates in the https://github.com/kubeflow/manifests/issues/2600 issue.

**Comment by rimolive** [comment]
Tracking issue https://github.com/kubeflow/pipelines/issues/10402

**Comment by Tomcli** [comment]
For the Tekton version, it will be Tekton 0.53.2 (OpenShift Pipelines 1.13)
