### ISSUE TITLE
Manifests WG Roadmap for KF 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2610]
Hello @kubeflow/wg-manifests-leads @kimwnasptd

The [1.9 release](https://github.com/kubeflow/community/blob/master/releases/release-1./release-team.md) team will use this tracking issue to coordinate the integration of the Manifests with the Kubeflow 1.9 release.

Heads up that the feature freeze is scheduled for April 15th (needs confirmation). For the full release schedule, refer to the [1.9 release timeline](https://github.com/kubeflow/community/blob/master/releases/release-1.9/README.md).

(note: links are pending kubeflow/community#687 and kubeflow/community#690)

To prepare for the 1.9 release, please provide answers to the following questions:

1. Can you share a link to all open / work in progress issues that you're expecting to include in your next version?
2. Is @kubeflow/wg-manifests-leads updated? Who would be the main point of contact of this WG and what communication channel(s) do you folks prefer (e.g. slack, email, gh issue)?
3. If you're using any of the following dependencies, could you provide the versions you'll be supporting for each dependency?

* Knative
* Istio
* Kubernetes
* Cert-Manager
* Kustomize
* Dex-auth

The release team WG liaison for Manifests is @juliusvonkohout and you can keep track of high-level release updates in the https://github.com/kubeflow/manifests/issues/2600 issue.

**Comment by rimolive** [comment]
Tracker issue ##2592

**Comment by tiansiyuan** [comment]
When can I have an early access to release 1.9?

Until Apr 29th 2024 : Week 16 - RC.0 is cut ?

**Comment by juliusvonkohout** [comment]
> When can I have an early access to release 1.9?
> 
> Until Apr 29th 2024 : Week 16 - RC.0 is cut ?

Just use the master branch, that is it.

**Comment by juliusvonkohout** [comment]
This here is the right tracker https://github.com/kubeflow/manifests/issues/2592 @StefanoFioravanzo @rimolive

**Comment by rimolive** [comment]
This is done
