### ISSUE TITLE
[Kubeflow 1.9] Distributions and Kubeflow 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2611]
This issue will be used to track the progress of and coordinate with distributions along the [1.9 release](https://github.com/kubeflow/manifests/issues/2600).

While we hope all distros will manage to be ready when the KF 1.9 release is out, this is sometimes difficult to achieve. In this issue, we want to both keep track of the progress of distributions towards the KF 1.9 release and also know which of the distros will be working on KF 1.9 (testing during the distribution testing cycle) even if they can't meet the KF 1.9 deadline.

Tagging distribution owners identified from previous releases (**Any new or missed distro owners, please comment on this issue**)

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| AWS 	| @surajkota 	| not participating in 1.9 |
| Charmed Kubeflow 	| @DnPlas    	| participating in 1.9 |
| Google Cloud 	| @gkcalat<br>@zijianjoy<br>@Linchin 	| not participating in 1.9 |
| IBM IKS 	| @Tomcli<br>@yhwang 	| participating in 1.9 |
| Microsoft    | | not participating in 1.9 |
| Nutanix 	| @johnugeorge<br>@nagar-ajay 	| participating in 1.9 |
| Red Hat OpenShift AI 	| @rimolive 	| participating in 1.9 |
| Oracle Cloud Infrastructure 	| @julioo 	| participating in 1.9 |
| DeployKF 	| @thesuperzapper 	| participating in 1.9 |
| VMWare 	| @liuqi<br>@xujinheng 	| participating in 1.9 |
| QBO 	| @alexeadem  	| participating in 1.9 |

Please let us know if you'll be participating in the 1.9 release by answering the following questions:

* Are you planning on having your distro ready in sync with the KF 1.9 release?
* Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?
* If you cannot participate, when can the community expect your distro to be ready for release 1.9?

Please note the release timelines are being discussed in kubeflow/manifests#2606.

cc @kubeflow/release-team @jbottum

**Comment by ca-scribner** [comment]
@rimolive can you remove @DnPlas from Charmed Kubeflow and replace her with myself?  ty!

to your questions, for Charmed Kubeflow:
- Are you planning on having your distro ready in sync with the KF 1.9 release?
  - yes
- Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?
  - yes

**Comment by thesuperzapper** [comment]
@rimolive deployKF will participate in 1.9, but it's not 100% clear exactly what that will look like.

---

Separately, given "Kubeflow on AWS" did not participate in 1.8, and announced they were no longer supporting their distribution in https://github.com/awslabs/kubeflow-manifests/issues/794, I think its unlikely they will do 1.9?

Given this, I proposed moving them to "legacy" on the Kubeflow website on this PR https://github.com/kubeflow/website/pull/3641. 

However, I also want to avoid confusion with users, because they might think that Kubeflow no longer supports AWS due to the "Kubeflow on AWS" name. So I also think we should merge https://github.com/kubeflow/website/pull/3643 at the same time, which tells users that "Kubeflow on XXXX" is just a name, and NOT the ONLY way to use Kubeflow on that platform.

**Comment by yhwang** [comment]
For IBM IKS:
> Are you planning on having your distro ready in sync with the KF 1.9 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by liuqi** [comment]
For VMware Distro:

> Are you planning on having your distro ready in sync with the KF 1.9 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by alexeadem** [comment]
For QBO Distro:

> Are you planning on having your distro ready in sync with the KF 1.9 release?

Yes

> Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by tiansiyuan** [comment]
For VMware Distro:

Are you planning on having your distro ready in sync with the KF 1.9 release?

Yes

Will you participate by testing your distro during the distribution testing phase and providing feedback (reporting any issues to the release team)?

Yes

**Comment by rimolive** [comment]
Calling all Distribution owners! I'm proud to announce our first Release Candidate for Kubeflow 1.9!

You can find the release details in the following URL:

https://github.com/kubeflow/manifests/releases/tag/v1.9.0-rc.0

We'll be working on another Release Candidate when we have Notebooks and KServe Models Webapp updated and ready for KF 1.9.

cc @ca-scribner @yhwang @johnugeorge @nagar-ajay @thesuperzapper @liuqi @xujinheng @alexeadem @alex-treebeard

**Comment by juliusvonkohout** [comment]
We also have to update cert-manger, knative and istio which will come in later RCs

**Comment by StefanoFioravanzo** [comment]
@ca-scribner @yhwang @johnugeorge @nagar-ajay @thesuperzapper @liuqi @xujinheng @alexeadem @alex-treebeard Can you please acknowledge that you are aware of Kubeflow 1.9 RC0 and are aware the the distributions testing phase has started? Please react with a thumbs up if everything is okay from your side and you are proceeding with testing.

**Comment by thesuperzapper** [comment]
deployKF is mostly waiting on the updates from Notebooks, but I am aware that a 1.9.0-RC0 was cut with other components.

**Comment by alexeadem** [comment]
What do we mean by  '(around 1.28)' here: https://github.com/kubeflow/manifests/tree/v1.9.0-rc.0?tab=readme-ov-file#prerequisites

Is that  v1.28.0 and v1.27.11?

**Comment by juliusvonkohout** [comment]
@alexeadem please check the updated release notes
https://github.com/kubeflow/manifests/releases/tag/v1.9.0-rc.0 1.27-1.29 officially

**Comment by DnPlas** [comment]
Hi @rimolive @StefanoFioravanzo, a couple of things:

1. Could I please ask to replace @ca-scribner with me as the distribution owner?
2. We are aware that the distribution testing phase has started, but we have identified that components from the `kubeflow/kubeflow` repository are missing. Is this something coming in another RC? Is this planned?

**Comment by rimolive** [comment]
> Hi @rimolive @StefanoFioravanzo, a couple of things:
> 
> 1. Could I please ask to replace @ca-scribner with me as the distribution owner?
Done

> 2. We are aware that the distribution testing phase has started, but we have identified that components from the `kubeflow/kubeflow` repository are missing. Is this something coming in another RC? Is this planned?
We decided to move on with rc0 because many components were upgraded, but there's a plan for rc1 with the remainder components. Is there one specific you are expecting to test?

**Comment by rimolive** [comment]
Just an update: We have just released Kubeflow 1.9.0-rc.1, which includes all updates from the Notebooks WG, Istio 1.18.7 (targetting to fully upgrade to 1.22 until the final release), and Model Registry 0.2.1-alpha. We ask all Distributions a help with testing the new release and open issues so we can work with the Working Groups to fix them until the final release.

You can find the Release Notes in the [releases page](https://github.com/kubeflow/manifests/releases/tag/v1.9.0-rc.1).

cc @ca-scribner @DnPlas  @yhwang @johnugeorge @nagar-ajay @thesuperzapper @liuqi @xujinheng @alexeadem @alex-treebeard

**Comment by nagar-ajay** [comment]
Created an issue to track Nutanix distribution testing - https://github.com/nutanix/kubeflow-manifests/issues/21

**Comment by rimolive** [comment]
We are one week away from the Kubeflow 1.9.0-rc.2 release and we plan to be the last release candidate before final. We really welcome any updates about Distribution testing with bug reports, and anything that the release team should pursuit for rc.2 or final.

cc @ca-scribner @DnPlas @yhwang @johnugeorge @nagar-ajay @thesuperzapper @liuqi @xujinheng @alexeadem @alex-treebeard

**Comment by DnPlas** [comment]
We will start testing in the following two weeks, we'll keep you posted.

**Comment by rimolive** [comment]
Hello Distribution owners! Just wanted to announce Kubeflow 1.9.0-rc.2 release, it's the last one before we go final. Please take a look at the Release Notes [here](https://github.com/kubeflow/manifests/releases/tag/1.9.0-rc.2) and help us validating the manifests by issuing a `/lgtm` comment in this issue.

cc @ca-scribner @DnPlas @yhwang @johnugeorge @nagar-ajay @thesuperzapper @liuqi @xujinheng @alexeadem @alex-treebeard

**Comment by rimolive** [comment]
@liuqi @xujinheng Can you please confirm if you are testing Kubeflow 1.9.0-rc.2 manifests and let us know if it looks good?

**Comment by rimolive** [comment]
@yhwang Please let us know if you tested Kubeflow 1.9.0-rc.2 and it looks good.

**Comment by juliusvonkohout** [comment]
Even better test the 1.9 branch in general because it will contain the final release https://github.com/kubeflow/manifests/commits/v1.9-branch/ and further fixes such as https://github.com/kubeflow/manifests/pull/2791

**Comment by xujinheng** [comment]
Yes, we are currently testing Kubeflow 1.9.0-rc2. Once we complete our testing, we will post the results here to keep you informed.

**Comment by juliusvonkohout** [comment]
> Yes, we are currently testing Kubeflow 1.9.0-rc2. Once we complete our testing, we will post the results here to keep you informed.

As mentioned above, rc.2 does not contain all fixes.

**Comment by rimolive** [comment]
This is the current status of the Distribution Testing on July 10th:

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| Charmed Kubeflow 	| @DnPlas    	| Pending |
| IBM IKS 	| @Tomcli<br>@yhwang 	| LGTM |
| Nutanix 	| @johnugeorge<br>@nagar-ajay 	| Pending |
| Red Hat OpenShift AI 	| @rimolive 	| Pending |
| Oracle Cloud Infrastructure 	| @julioo 	| Pending |
| DeployKF 	| @thesuperzapper 	| Pending |
| VMWare 	| @liuqi<br>@xujinheng 	| Pending |
| QBO 	| @alexeadem  	| LGTM |

We need your updates as quick as possible as our release date is July 22nd and in case of any bug reports we can take actions on time.

**Comment by tiansiyuan** [comment]
https://github.com/kserve/models-web-app/issues/88

Done.

**Comment by juliusvonkohout** [comment]
Hello, please retest with the 1.9 branch given the merge of https://github.com/kubeflow/manifests/pull/2795

**Comment by juliusvonkohout** [comment]
If no further bugs come up,  i will synchronize any last-minute release tags from the other working groups on June 20-21 and do the change log and final release on July 22.

@rimolive if i do not get any more final releases/tags from the other WGs, i probably have to release as is.

**Comment by rimolive** [comment]
@juliusvonkohout hold on, we need the remaining WGs to cut their final releases. We cannot release 1.9 with components in RC releases.

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout hold on, we need the remaining WGs to cut their final releases. We cannot release 1.9 with components in RC releases.

I wont do anything today :-D as i said July 20-22 is when i can do the remaining stuff. But you have to decide what we do if the final releases/tag from other WGs are not available on July 22.

**Comment by rimolive** [comment]
This is the current status of the Distribution Testing on July 15th:

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| Charmed Kubeflow 	| @DnPlas    	| Pending |
| IBM IKS 	| @Tomcli<br>@yhwang 	| LGTM |
| Nutanix 	| @johnugeorge<br>@nagar-ajay 	| LGTM |
| Red Hat OpenShift AI 	| @rimolive 	| Pending |
| Oracle Cloud Infrastructure 	| @julioo 	| Pending |
| DeployKF 	| @thesuperzapper 	| Pending |
| VMWare 	| @liuqi<br>@xujinheng 	| Pending |
| QBO 	| @alexeadem  	| LGTM |

We had no changes in 5 days, and next week it's the Release date for 1.9. Please send us your updates so we can guarantee all Distributions are good with the release.

**Comment by thesuperzapper** [comment]
@juliusvonkohout @rimolive @StefanoFioravanzo I have cut the final [v1.9.0](https://github.com/kubeflow/kubeflow/releases/tag/v1.9.0) tag for the `kubeflow/kubeflow` repo, feel free to sync the manifests for this tag into `kubeflow/manifests`.

**Comment by DnPlas** [comment]
Hey @rimolive, here is my latest update:

version: 1.9.0-rc.2
platform: 
* ubuntu 22.04
* microk8s (k8s) 1.29
tested with oidc-authservice latest version

So far it is looking good, so for that version /lgtm.

**Comment by rimolive** [comment]
Hello,

This is the status for today July 22nd:

| Distribution 	| Representative(s) 	| State 	|
|---	|---	|---	|
| Charmed Kubeflow 	| @DnPlas    	| LGTM |
| IBM IKS 	| @Tomcli<br>@yhwang 	| LGTM |
| Nutanix 	| @johnugeorge<br>@nagar-ajay 	| LGTM |
| Red Hat OpenShift AI 	| @rimolive 	| LGTM |
| Oracle Cloud Infrastructure 	| @julioo 	| Pending |
| DeployKF 	| @thesuperzapper 	| Pending |
| VMWare 	| @liuqi<br>@xujinheng 	| Pending |
| QBO 	| @alexeadem  	| LGTM |

We see the majority of distributions agreed on the state of the release. Thank you so much for everyone involved in the testing. We'll keep receiving feedbacks for cases we can consider work on patch releases for 1.9.

**Comment by juliusvonkohout** [comment]
Is someone here encountering this bug/PR ? 

https://github.com/kubeflow/manifests/pull/2815
https://github.com/kubeflow/manifests/issues/2812
https://github.com/kubeflow/manifests/issues/2766

It has not been changed in 7 months https://github.com/kubeflow/manifests/commits/master/common/dex/base/config-map.yaml , but some users are complaining

**Comment by alexeadem** [comment]
> Is someone here encountering this bug/PR ?
> 
> #2815 #2812 #2766
> 
> It has not been changed in 7 months https://github.com/kubeflow/manifests/commits/master/common/dex/base/config-map.yaml , but some users are complaining

not in QBO
