### ISSUE TITLE
resource mapping not found for name: "kubeflow-user-example-com" namespace: "" from "STDIN": no matches for kind "Profile" in version "kubeflow.org/v1beta1"

### ISSUE THREAD

**Issue by wickedvalley** [kubeflow/manifests#2622]
when i execute command, i got errors
my command is :kustomize build common/user-namespace/base | kubectl apply -f -

i got error:

# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
configmap/default-install-config-9h2h2b6hbk unchanged
error: resource mapping not found for name: "kubeflow-user-example-com" namespace: "" from "STDIN": no matches for kind "Profile" in version "kubeflow.org/v1beta1"
ensure CRDs are installed first

kubectl version 
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

**Comment by juliusvonkohout** [comment]
Hello,

no matches for kind "Profile" in version "kubeflow.org/v1beta1"
ensure CRDs are installed first

tells you that you should check whether the CRDs are there.

**Comment by juliusvonkohout** [comment]
/close

due to inactivity
