### ISSUE TITLE
kubeflow dashboard page unreachable 

### ISSUE THREAD

**Issue by techiechap** [kubeflow/manifests#2624]
after reviewing the external IP and then updating the cert.yaml,  kubeflow dashboard page is unreachable for Edge and chrome, 
I have disabled the cache but it did not help

K8s services and ingress show all the pods in OK status with external Ip being assigned to the istio-ingressgateway.
upon further inspection  i found these 2 issues `Buttons must have discernible text: Element has no title attribute, Images must have alternate text: Element has no title attribute`

Thanks

**Comment by techiechap** [comment]
Hi, 
Following the instructions from the [manifests](https://github.com/intel/intel-cloud-optimizations-azure/blob/main/kubeflow/README.md#prerequisites) on the wiki, I configured the Kubeflow module by:

Installing and adjusting the install.yaml.
Modifying kf-istio-resource.yaml.
Creating certificate.yaml, ensuring it was correctly configured to display the external IP of AKS.
Despite these configurations, the Kubeflow dashboard on the Azure AKS could not load when attempting to access the URL
(URL can be accessed by going to Azure AKS services and click on the  istio-ingressgateway.)
Browser: Edge, Chrome

**Comment by juliusvonkohout** [comment]
Then please ask Intel where you taken the guide from or use the official process https://github.com/kubeflow/manifests/blob/v1.8-branch/README.md

**Comment by techiechap** [comment]
@juliusvonkohout  Thank you, Now am able to get to the landing page however am unable to login with the default user name , i have had tried using custom  username and password but it does not work.

**Comment by techiechap** [comment]
As per the documentation for OpenID Connect Identity, i did change the default password using the python passlib library however it does not take the password, i have changed the password multiple times,  requesting a way forward

**Comment by juliusvonkohout** [comment]
What you have looks more like a support question and not a bug report. Please join the new clack and channel #kubeflow-platform see https://www.kubeflow.org/docs/about/community/ and let this thread rest in peace.

**Comment by thesuperzapper** [comment]
@techiechap Or, if you are using Kubeflow for your business, you might consider using a free but supported distribution like [deployKF](https://www.deploykf.org/) (my company) or Charmed Kubeflow (Canonical).
