### ISSUE TITLE
ERROR  messages while running script hack/extract_images.sh

### ISSUE THREAD

**Issue by tiansiyuan** [kubeflow/manifests#2647]
Error: no matches for Id ConfigMap.v1.[noGrp]/istio.istio-system; failed to find unique target for patch ConfigMap.v1.[noGrp]/istio.istio-system
ERROR:	 Failed "kustomize build" command for directory: ../common/oidc-client/oauth2-proxy/components/istio-external-auth. See error above
Error: merging from generator &{0xc000466000 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"oauth2-proxy-parameters", Namespace:""} does not exist; cannot merge or replace
ERROR:	 Failed "kustomize build" command for directory: ../common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer. See error above
Error: no matches for Id Deployment.v1.apps/centraldashboard.kubeflow; failed to find unique target for patch Deployment.v1.apps/centraldashboard.kubeflow
ERROR:	 Failed "kustomize build" command for directory: ../common/oidc-client/oauth2-proxy/components/central-dashboard. See error above
Error: merging from generator &{0xc000371520 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"istio-m2m-params", Namespace:""} does not exist; cannot merge or replace
ERROR:	 Failed "kustomize build" command for directory: ../common/oidc-client/oauth2-proxy/overlays/m2m/component-overwrite-m2m-token-issuer. See error above
Error: no matches for Id Deployment.v1.apps/cache-deployer-deployment.[noNs]; failed to find unique target for patch Deployment.v1.apps/cache-deployer-deployment.[noNs]
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/cert-manager/dev. See error above
Error: no matches for Id ClusterRole.v1.rbac.authorization.k8s.io/kubeflow-pipelines-cache-deployer-clusterrole.[noNs]; failed to find unique target for patch ClusterRole.v1.rbac.authorization.k8s.io/kubeflow-pipelines-cache-deployer-clusterrole.[noNs]
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/cert-manager/platform-agnostic-multi-user. See error above
Error: accumulating resources: accumulation err='accumulating resources from '../plain-multi-user': evalsymlink failure on '/home/oem/manifests/apps/kfp-tekton/upstream/env/plain-multi-user' : lstat /home/oem/manifests/apps/kfp-tekton/upstream/env/plain-multi-user: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/oem/manifests/apps/kfp-tekton/upstream/env/plain-multi-user' : lstat /home/oem/manifests/apps/kfp-tekton/upstream/env/plain-multi-user: no such file or directory
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user. See error above

----

The whole log with a lot of warnings is attached.

[extract_images-log.txt](https://github.com/kubeflow/manifests/files/14568263/extract_images-log.txt)

**Comment by juliusvonkohout** [comment]
@difince can you take a look at this?

**Comment by tiansiyuan** [comment]
There are still error messages when running this script.

find: ‘-’: No such file or directory

Error: accumulating resources: accumulation err='accumulating resources from '../plain-multi-user': evalsymlink failure on '/home/ecs-user/manifests/apps/kfp-tekton/upstream/env/plain-multi-user' : lstat /home/ecs-user/manifests/apps/kfp-tekton/upstream/env/plain-multi-user: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/ecs-user/manifests/apps/kfp-tekton/upstream/env/plain-multi-user' : lstat /home/ecs-user/manifests/apps/kfp-tekton/upstream/env/plain-multi-user: no such file or directory
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user. See error above

Error: no matches for Id Deployment.v1.apps/cache-deployer-deployment.[noNs]; failed to find unique target for patch Deployment.v1.apps/cache-deployer-deployment.[noNs]
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/cert-manager/dev. See error above

Error: no matches for Id ClusterRole.v1.rbac.authorization.k8s.io/kubeflow-pipelines-cache-deployer-clusterrole.[noNs]; failed to find unique target for patch ClusterRole.v1.rbac.authorization.k8s.io/kubeflow-pipelines-cache-deployer-clusterrole.[noNs]
ERROR:	 Failed "kustomize build" command for directory: ../apps/kfp-tekton/upstream/env/cert-manager/platform-agnostic-multi-user. See error above

**Comment by juliusvonkohout** [comment]
@tiansiyuan i checked and some of them are upstream bugs. "plain-multi-user" just does not exist and is a bug that we cannot fix here for example. This must happen in the kfp-tekton repository, which will anyway be merged into KFP.
