### ISSUE TITLE
Support for arm64 architecture in Kubeflow

### ISSUE THREAD

**Issue by VDliveson** [kubeflow/manifests#2659]
Currently, there are a lot of issues while using Kubeflow with `arm64` based Mac CPUs, what are the workarounds for it and can a solution for this be created if given equivalent efforts to the same. This could be a major improvement for Mac based users, including me, who use Mac for development purposes.

**Comment by juliusvonkohout** [comment]
I am neither an Apple nor Mac user. But we want to support proper ARM64 devices especially from the hyperscalers. Can you provide more details about what exactly is missing?

**Comment by VDliveson** [comment]
As a mac user, what I usually see is that during the build phases, it keeps into running into unknown build errors. Would need to dive more into this. But more importantly I do see that building on Mac is very storage heavy and given the limited memory in Macbook, it might become a bottleneck for most users.

**Comment by juliusvonkohout** [comment]
Lets merge issues https://github.com/kubeflow/manifests/issues/2745
