### ISSUE TITLE
Unable to load local image

### ISSUE THREAD

**Issue by pranavkumar74980** [kubeflow/manifests#2662]
What is happening ?
We have downloaded the image and saved it locally, post deployment of kubeflow component. It is unable to load the image which is present in manifest file
Manifest contains, assuming an image in this format - docker.io/abcd : v1
our local system removes prefix docker.io and just saves in format - abcd : v1

refer below screenshot
![MicrosoftTeams-image (22)](https://github.com/kubeflow/manifests/assets/165282476/1c80e683-0e37-40ce-8617-56c262c057dc)

Due to this it is unable to understand image and resulting into imagepullbackoff.
I

**Comment by juliusvonkohout** [comment]
It is there

https://hub.docker.com/layers/kubeflownotebookswg/poddefaults-webhook/v1.8.0/images/sha256-7541399dfeed8001cc1995e4ab831b86cb7bdda9cf136ab32c62fe2fbf8af504?context=explore

this is a kubernetes and not a Kubeflow issue
