### ISSUE TITLE
Update to Seldon 1.18.x and the corresponding owners file and github workflow

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#2673]
We want to support Kubernetes 1.27 -1.29 in Kubeflow 1.9 and should update to Seldon 1.18+

https://docs.seldon.io/projects/seldon-core/en/latest/reference/upgrading.html

and there is discussion in https://github.com/kubeflow/manifests/pull/2532#issuecomment-2015087459

@rimolive @adriangonz @ramonpzg

**Comment by rimolive** [comment]
Who are the code owners for Seldon? Is there an ETA for that upgrade?

I don't think this is a blocker for KF 1.9 and Seldon is not part of the core components, but if they're willing to do that we can plan for a patch release in 1.9.

**Comment by juliusvonkohout** [comment]
The new code owners are described in https://github.com/kubeflow/manifests/pull/2532#issuecomment-2015087459

We can also write a synchronization script ourselves.

**Comment by rimolive** [comment]
Your call. As far as I know the manifest sync scripts are only for the core components, and since we need to write one for Model Registry (the team is about to send a PR for it) we can try write one for Seldon if, and only if, this won't take much time and effort. We have to set hard feature freeze date by Apr 22nd or the original schedule might be compromised.

**Comment by juliusvonkohout** [comment]
@lampajr can you tackle this and add a github workflow as well?

**Comment by lampajr** [comment]
> @lampajr can you tackle this and add a synchronization script as well?

Hi Julius, I gave it a quick try following https://github.com/kubeflow/manifests/blob/master/contrib/seldon/UPGRADE.md but it looks like the chart for the lates `v1.18.1` release are not present in the helm chart repo https://storage.googleapis.com/seldon-charts 

Do you know how can we get those charts there?

**Comment by juliusvonkohout** [comment]
@lampajr Maybe from here https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-kustomize-install

**Comment by lampajr** [comment]
> @lampajr Maybe from here https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-kustomize-install

I think I can find a way directly cloning the `seldon-core` repo, will try this later today
