### ISSUE TITLE
Kubeflow pods are not coming up in RHEL for multi-node K8, while working with single node

### ISSUE THREAD

**Issue by pranavkumar74980** [kubeflow/manifests#2684]
**We are deploying kubeflow in 2 node k8**

**We are not able to see pod becoming scheduled after deployment in Rhel**
![kubeflow_rhel](https://github.com/kubeflow/manifests/assets/165282476/668fc2f4-3728-4e11-9168-1f82c7326e1b)

**While in single node we are able to deploy it**
![kubeflow_deployment_single_node_rhel](https://github.com/kubeflow/manifests/assets/165282476/ef036e4c-45d3-45af-8842-34503eaa1ca3)

**Describing deployment**
![describe_deployment_rhel](https://github.com/kubeflow/manifests/assets/165282476/40c1a638-f650-4633-b8a1-288ec77ac662)

**I have tried to deploy in other linux box ~ ubuntu 22.04**
**This issue is not seen in ubuntu and we were able to deploy it on ubuntu over 2 node k8 & also over single node.**
![ubuntu_kubeflow](https://github.com/kubeflow/manifests/assets/165282476/bad65c1d-57bf-47a9-a47e-ced503076877)

Please look into these different behavior or is it to do something with K8.

**Comment by pranavkumar74980** [comment]
Kubeflow branch- v1.8.0

**Comment by rimolive** [comment]
Just curious: Did you notice in your `kubectl get node` output from your RHEL-based k8s cluster only one node was marked as Ready?

**Comment by pranavkumar74980** [comment]
I have checked and it was working fine once node came in ready state.
Thanks.
