### ISSUE TITLE
Deprecate optional Knative Eventing components from common manifests

### ISSUE THREAD

**Issue by rawc0der** [kubeflow/manifests#2685]
**Description:**
There are certain components which get deployed alongside all the required core Kubeflow stack. One example is the `knative-eventing` which is installed together with the `KNative` stack of services. 
- [manifests/common/knative/knative-eventing-post-install-jobs/base](https://github.com/kubeflow/manifests/tree/master/common/knative/knative-eventing-post-install-jobs/base)
- [manifests/common/knative/knative-eventing/base](https://github.com/kubeflow/manifests/tree/master/common/knative/knative-eventing/base)

**Suggestion:**
If this component is not required for Kubeflow inner workings, then my suggestion is to deprecate it from the `/common` folder. This install creates a lot of unnecessary deployments and resources on the cluster (which rarely get used for critical functionality).

**Deprecation Note:**
 In order to keep the integration and still allow users to continue installing it if needed, it can be added as separate integration to `/contrib` folder. 
If this introduce inconsistent conventions, then it could simply be commented out from the installation [kustomization](https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml) file such that it is not considered as required.

Any thoughts?

**Comment by hansinikarunarathne** [comment]
@juliusvonkohout for this, Do I need to move knative folder to contrib folder?

**Comment by juliusvonkohout** [comment]
It introduces inconsistent conventions, so it should simply be commented out from the installation [kustomization](https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml) file such that it is not considered as required.

**Comment by juliusvonkohout** [comment]
Solved in https://github.com/kubeflow/manifests/pull/2788
