### ISSUE TITLE
Why does istio 1.16 still exists in this repo?

### ISSUE THREAD

**Issue by aqeelat** [kubeflow/manifests#2691]
Is it still needed? Or should it be cleaned up?

Unrelated question: would newer versions of istio work?

**Comment by juliusvonkohout** [comment]
Hello, such questiona belong to the slack channel wg-manifests. Join here https://www.kubeflow.org/docs/about/community/ , it also contains our meeting schedule. We are targeting istio 1.22 for Kubeflow 1.9
