### ISSUE TITLE
Create Dex Ingress Gateway and Virtual Service to expose dex and related services through Istio

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#272]
Dex and all related services: Dex Login Application and LDAP are being exposed through NodePort. One of the suggested ways to expose these are through creating an Istio Gateway and mapping these through virtual services.

/priority p1
/area manifests

**Related Issues:**
#195 

/cc @yanniszark

**Comment by jlewi** [comment]
@krishnadurai any update on this? Is this issue still relevant given recent discussions about the on prem istio and dex config?
