### ISSUE TITLE
Central Dashboard not visible

### ISSUE THREAD

**Issue by nagar-ajay** [kubeflow/manifests#2735]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [x] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] Join our slack channel using [wg-manifests](https://www.kubeflow.org/docs/about/community/).

### Version

1.9

### Describe your issue

* Central dashboard is not visible.
<img width="1200" alt="Screenshot 2024-05-27 at 3 24 50 PM" src="https://github.com/kubeflow/manifests/assets/122429047/dfd0e720-38f5-4933-a2f8-393af38ca7d2">

### Steps to reproduce the issue

* Installed kubeflow 1.9 using rc0 on k8s version 1.28.5.

**Comment by rimolive** [comment]
cc @juliusvonkohout

**Comment by juliusvonkohout** [comment]
@nagar-ajay are you sure that it is not related to https://github.com/kubeflow/manifests/issues/2646 ?

**Comment by nagar-ajay** [comment]
I'm not sure, can you please provide some pointers to debug this?

FYI: after some time central dashboard came up automatically. But I got the same error when I tried kfp inside the notebook server.

**Comment by juliusvonkohout** [comment]
KFP has multiple authentication mechanisms. Please apply the changes from the cronjob PR to the master branch and check whether the problem persists.

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests/releases 1.9.1-rc.1 is out. Please test it with the cronjob patch

**Comment by nagar-ajay** [comment]
sure

**Comment by nagar-ajay** [comment]
thanks @juliusvonkohout, the central dashboard is working fine now. I tried kfp inside notebook, I'm getting different error.
```
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text[/plain](http://localhost:8080/plain)', 'date': 'Wed, 05 Jun 2024 18:54:25 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied
```
Closing this issue as the above seems unrelated to the current issue.
