### ISSUE TITLE
Issues when adding a user in Dex.

### ISSUE THREAD

**Issue by limdf71** [kubeflow/manifests#2754]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

v1.10-branch
### Describe your issue

I am currently using Kubeflow version 1.10. The installation of Kubeflow is complete, and I can log in using user@example.com. Using Nvidia GPUs and storage also presents no issues.

I have created accounts and namespaces to assign to others, but I am continuously failing to log in via Dex.
(It worked well with version 1.8.)

Could issues with namespace settings cause Dex authentication to fail? (While logging in, I encountered 'bad request unregistered redirect_uri ("/oauth2/callback")' on the Kubeflow Dex UI. I have also tried reinstalling Dex.)"

I've modified the config-map.yaml file, but I'm unsure which command should be used to update it correctly. (I've tried the following three methods):

kustomize build common/dex/overlays/istio | kubectl apply -f -
kustomize build common/dex/overlays/oauth2-proxy | kubectl apply -f -
kubectl rollout restart deployment dex -n auth

Below is the source file located at manifests/common/dex/base/config-map.yaml:
<img width="630" alt="스크린샷 2024-06-19 오후 10 01 28" src="https://github.com/kubeflow/manifests/assets/26616595/d10c2914-ea94-418b-9714-e13b224dc677">

### Steps to reproduce the issue

1. "Added user (lim@gmail.com) in common/dex/base/config-map.yaml."
2. Delete dex
kubectl delete pod dex -n auth
Reinstall
kustomize build common/dex/overlays/istio | kubectl apply -f -
3. namespace apply
<img width="554" alt="스크린샷 2024-06-19 오후 10 37 19" src="https://github.com/kubeflow/manifests/assets/26616595/8c1006e5-a6f2-4b2a-b3f3-774b4cb00115">
<img width="619" alt="스크린샷 2024-06-19 오후 10 51 42" src="https://github.com/kubeflow/manifests/assets/26616595/0f95894d-496a-4720-8025-0b2130a90314">
4. dex login

**Comment by rimolive** [comment]
Hello @limdf71. We are currently working on Kubeflow 1.9.0-rc.2 release, so I believe you are referring to that version instead of 1.10. Is that correct?

Please, let us know if that's correct because we need to fix until we release rc.2.

**Comment by limdf71** [comment]
> Hello @limdf71. We are currently working on Kubeflow 1.9.0-rc.2 release, so I believe you are referring to that version instead of 1.10. Is that correct?
> 
> Please, let us know if that's correct because we need to fix until we release rc.2.

I've installed the v1.10-branch (tag v1.9.0-rc.1.")

**Comment by juliusvonkohout** [comment]
I just pushed the https://github.com/kubeflow/manifests/commits/v1.9-branch branch. Please do not use v1.10

**Comment by juliusvonkohout** [comment]
Can you try https://github.com/kubeflow/manifests/pull/2777 ?

**Comment by juliusvonkohout** [comment]
Should be fixed in https://github.com/kubeflow/manifests/pull/2799
