### ISSUE TITLE
Enforce proper formatting on python, bash and yaml files 

### ISSUE THREAD

**Issue by hansinikarunarathne** [kubeflow/manifests#2773]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

It is not an issue but enhancement

### Steps to reproduce the issue

It is a enhacement

**Comment by juliusvonkohout** [comment]
@hansinikarunarathne i did not see a log message for shellcheck if all files are porperly formated or the information, that no bash files changed. Please also check for yaml files. For python there seems to be a proper message.
