### ISSUE TITLE
argo executor resource quota are missing for default container (e.g. init, wait)

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/manifests#2790]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.8

### Describe your issue

our k8s cluster has setup resource quota per namespace, i.e. each running pods in that namespace should be specify resource.requests / resource.limits.

when our newly installed kubeflow 1.8 (and we checked the code, version after 1.8 have similar issue),
running the following example raised failed quota errors.
```pipeline.py

from kfp import dsl
from kfp import compiler

import os
# In tests, we install a KFP package from the PR under test. Users should not
# normally need to specify `kfp_package_path` in their component definitions.
_KFP_PACKAGE_PATH = os.getenv('KFP_PACKAGE_PATH')


@dsl.component(kfp_package_path=_KFP_PACKAGE_PATH)
def hello_world(text: str) -> str:
    print(text)
    return text


@dsl.pipeline(name='hello-world', description='A simple intro pipeline')
def pipeline_hello_world(text: str = 'hi there'):
    """Pipeline that passes small pipeline parameter string to consumer op."""

    consume_task = hello_world(
        text=text).set_cpu_request('1').set_memory_request('650M').set_cpu_limit('1').set_memory_limit('1G')  # Passing pipeline parameter as argument to consumer op


if __name__ == "__main__":
    # execute only if run as a script
    compiler.Compiler().compile(
        pipeline_func=pipeline_hello_world,
        package_path='hello_world_pipeline.json')

```

with the following error message: 

```
task 'hello-world-w8rxr.root-driver' errored: pods "hello-world-w8rxr-1768006001" is forbidden: failed quota: kf-resource-quota: must specify cpu for: init,wait
```

the message suggests that default argo container (init/wait) requires resources quota too.
The above error message is gone when we patch the configmap of argo with:

```
executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.01
        memory: 32Mi
      limits:
        cpu: 0.5
        memory: 512Mi
```
We also noted that this resources was added before v1.7.0 (including v1.6 and v1.5) but was removed since this Pr #2511  https://github.com/kubeflow/manifests/pull/2511/files#diff-2fb7c70cac207a370318e3f23a14eec22bec6fba5ec87916cb5d1a2e2d8585deL42

seems like these resources are removed accidentally? 
if so I would like to contribute it~

### Steps to reproduce the issue

1. install kubeflow v1.8 (or v1.9)
2. run the above hello world example with resource quota
3. check workflow resources to see errors `kubectl -n <namespace> describe workflow <workflow-name>`

**Comment by juliusvonkohout** [comment]
" Are you posting in the right repository ?" Sadly no, this belongs to Kubeflow/pipelines. We synchronize the manifests from there.

Please reopen there and close here.

**Comment by hsinhoyeh** [comment]
> " Are you posting in the right repository ?" Sadly no, this belongs to Kubeflow/pipelines. We synchronize the manifests from there.
> 
> Please reopen there and close here.

@juliusvonkohout thanks, it is related to https://github.com/kubeflow/pipelines/pull/9089 and There are some directions on specifying resource limits in LimitRange or in the profile itself. closed it.
