### ISSUE TITLE
RBAC Access denied from Pipeline Run pod

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2794]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

Using the RC2 of Kubeflow and trying to create a Pipeline run. The pipeline fails and I see in the logs of the driver pod of the first step:

```
time="2024-07-10T10:58:15.813Z" level=info msg="capturing logs" argo=true
I0710 10:58:15.905160      33 main.go:108] input ComponentSpec:{
  "executorLabel": "exec-preprocess",
  "inputDefinitions": {
...
F0710 10:58:16.006554      33 main.go:79] KFP driver: driver.Container(pipelineName=tutorial-data-passing, runID=486a5fd7-39fe-4ea7-82f0-3162fcd1e421, task="preprocess", component="comp-preprocess", dagExecutionID=2, componentSpec) failed: failure while getting executionCache: failed to list tasks: rpc error: code = PermissionDenied desc = RBAC: access denied
time="2024-07-10T10:58:16.814Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-07-10T10:58:16.814Z" level=error msg="cannot save parameter /tmp/outputs/pod-spec-patch" argo=true error="open /tmp/outputs/pod-spec-patch: no such file or directory"
time="2024-07-10T10:58:16.814Z" level=error msg="cannot save parameter /tmp/outputs/cached-decision" argo=true error="open /tmp/outputs/cached-decision: no such file or directory"
time="2024-07-10T10:58:16.814Z" level=info msg="/tmp/outputs/condition -> /var/run/argo/outputs/parameters//tmp/outputs/condition" argo=true
Error: exit status 1
```

Looks like someone (Istio most probably) is denying a request from the driver to get the `executionCache`

### Steps to reproduce the issue

1. Deploy from RC2
2. Try to create a pipeline run

**Comment by kimwnasptd** [comment]
Not sure if related, but am looking at the `wait` container from the same Pod and see the following logs
```
time="2024-07-10T10:58:17.645Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.4/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:kubeflow-user-example-com:default-editor\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"kubeflow-user-example-com\""
```

Playing a bit around with `kubectl auth can-i` I see the following interesting things:

```bash
kubectl auth can-i \
    create \
    workflowtaskresults.argoproj.io \
    -n kubeflow-user-example-com \
    --as system:serviceaccount:kubeflow-user-example-com:default-editor
# no

kubectl auth can-i \
    create \
    workflows.argoproj.io \
    -n kubeflow-user-example-com \
    --as system:serviceaccount:kubeflow-user-example-com:default-editor
# yes
```

**Comment by kimwnasptd** [comment]
Setting the `ml-pipeline` AuthorizationPolicy to accept requests from everywhere (add a `rues: [{}]`) resolves the issue.

So next step is to understand if the problem is with the communication between the KFP components or from requests from pods in user namespaces to KFP pods

**Comment by kimwnasptd** [comment]
Specifically, adding the to the authorization the following rule makes the runs to succeed
```yaml
  - when:
    - key: request.headers[kubeflow-userid]
      notValues: ['*']
```

So there's a good chance that this was broken because of https://github.com/kubeflow/manifests/issues/2747

cc @juliusvonkohout @kromanow94

**Comment by kimwnasptd** [comment]
My latest understanding is the following:

1. The pipeline steps are sending requests that are from pods that don't have a sidecar
2. The current rules in `ml-pipeline` AuthorizationPolicy allow requests if:
    1. They come from another KFP components (first rule)
    2. The request has a JWT

But the pipeline steps themselves don't set any JWT. So that's the reason we see the error in the steps themselves.

**Comment by kimwnasptd** [comment]
@juliusvonkohout @kromanow94 do you also see the above issue as well?

**Comment by juliusvonkohout** [comment]
I think RC.2 has https://github.com/kubeflow/manifests/commit/43eec94c83a8ea5983b3588f35187529c88a0d9f and people claim that it is working. 

Argo 3.4 in KFP 2.2.0 brought in workflowtaskresults.argoproj.io i guess. Maybe we are missing this permission in the roles. CC also @rimolive 

I am also fine with your authetnetication approach @kimwnasptd, but i am just on vacation until July 20. So i will cut the final relase around June 20-21 and do the changelog for it, but i cannot assist with this topic here much until then.

**Comment by juliusvonkohout** [comment]
A tests might be broken partially and could explain why this has not been detected in https://github.com/kubeflow/manifests/actions/runs/9825018339/job/27124646100

We allow the status failed as well https://github.com/kubeflow/manifests/blob/e73a39603a6f68c78efa8bd7acb33a1a2ef6643a/.github/workflows/pipeline_test.yaml#L93 

But the test should fail if the pipeline status is failed at https://github.com/kubeflow/manifests/blob/e73a39603a6f68c78efa8bd7acb33a1a2ef6643a/.github/workflows/pipeline_test.yaml#L97

**Comment by yhwang** [comment]
@kimwnasptd add some details about my comment about the 1.9.0-rc2 in IKS. In IKS manifest repo v1.9-branch which is downstream of kubeflow/manifests, I did add this patch to make the pipeline works:
```
  - when:
    - key: request.headers[kubeflow-userid]
      notValues: ['*']
```

**Comment by kimwnasptd** [comment]
Thanks for confirming @yhwang! 

Then I propose that we go over with this fix for 1.9 cc @rimolive

**Comment by kromanow94** [comment]
PR is here: https://github.com/kubeflow/manifests/pull/2795

**Comment by juliusvonkohout** [comment]
Thank you for the PR @kromanow94. i adjusted the tests slightly to trigger all KFP tests, checked the outputs and merged it.
I also pushed it to the 1.9 branch. 

Feel free to reopen if that is not enough.

**Comment by papagala** [comment]
I can confirm I had the exact same issue in the latest Kubeflow 1.9 rc2. Thanks @kromanow94

```bash
F0718 09:04:11.900602      20 main.go:79] KFP driver: driver.Container(pipelineName=pipeline, runID=96a02a1a-a08a-4fbf-8d5d-169bcc305326, task="cat-hosts", component="comp-kfp-busybox", dagExecutionID=4, componentSpec, KubernetesExecutorConfig) failed: failure while getting executionCache: failed to list tasks: rpc error: code = PermissionDenied desc = RBAC: access denied
time="2024-07-18T09:04:12.435Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-07-18T09:04:12.435Z" level=error msg="cannot save parameter /tmp/outputs/pod-spec-patch" argo=true error="open /tmp/outputs/pod-spec-patch: no such file or directory"
time="2024-07-18T09:04:12.435Z" level=error msg="cannot save parameter /tmp/outputs/cached-decision" argo=true error="open /tmp/outputs/cached-decision: no such file or directory"
time="2024-07-18T09:04:12.435Z" level=info msg="/tmp/outputs/condition -> /var/run/argo/outputs/parameters//tmp/outputs/condition" argo=true
```
