### ISSUE TITLE
Kubeflow 1.9 follow up: Upstream our authorizationpolicy and oauth2-proxy changes to kubeflow/pipelines and kubeflow/kubeflow

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#2804]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

Follow up of 
https://github.com/kubeflow/manifests/pull/2795
And
https://github.com/kubeflow/manifests/pull/2753

And 
https://github.com/kubeflow/manifests/pull/2734#issuecomment-2145839700

@kimwnasptd @rimolive 

### Steps to reproduce the issue

Stuff will break on the next manifest synchronization for Kubeflow/pipelines and kubeflow/kubeflow

**Comment by juliusvonkohout** [comment]
We also need to decide on the jupyterlab example image tags

**Comment by juliusvonkohout** [comment]
@kimwnasptd we have additional stuff in the upsteam folders from kubeflow/kubeflow and kubeflow/pipelines. This will break on the next synchronization step. See also the comments in https://github.com/kubeflow/manifests/pull/2815. Just try yourself to synchronize with the https://github.com/kubeflow/manifests/blob/master/hack/synchronize-pipelines-manifests.sh and https://github.com/kubeflow/manifests/blob/master/hack/synchronize-kubeflow-manifests.sh and verify that essential stuff is being deleted. For example the requestprincipal in the pipeline autorizationpolicy or the oauth2-proxy overlay for the central dashboard. And all tags for Kubeflow/kubeflow will switch from 1.9.0 to latest.

**Comment by kimwnasptd** [comment]
Ah I see, so it's about manifest syncing from other repos and not overriding the `overlays` that are defined then in the manifests repo (?)

I can see 2 ways but let me know which you think is more feasible:
1. Manifests repo doesn't have `overlays` and those should be handled in the source manifest repos
2. Update the sync scripts to somehow know which folders to not overwrite when copying the manifests from source manifests repos

**Comment by juliusvonkohout** [comment]
let me merge first https://github.com/kubeflow/manifests/pull/2815 and we should upstream at least the kubeflow/pipelines authorization policy with the requestprincipals as soon as we can.

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/pipelines/pull/11347 is probably the last item
