### ISSUE TITLE
Issue of trying to linting on files that deleted in the PR

### ISSUE THREAD

**Issue by hansinikarunarathne** [kubeflow/manifests#2824]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

It tries to linting on files that deleted in the PRwere 

### Steps to reproduce the issue

Delete a Yaml or bash file 
Then GitHub action related to linting will failed

**Comment by juliusvonkohout** [comment]
Can we close this issue?
