### ISSUE TITLE
Upgrade Istio to 1.2+

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#283]
/area manifests
/priority p1

Istio manifests in master branch are at 1.1.6. It would be good to upgrade them to 1.2.4 so that few issues get resolved:

kiali/kiali#1154

/assign @lluunn 
/assign @krishnadurai 

Related Issues:
#281

**Comment by jlewi** [comment]
It looks like #323 is being reverted in #357

**Comment by krishnadurai** [comment]
I think we can reapply the commit after #358 is fixed.
