### ISSUE TITLE
kubeflow-m2m-oidc-configurator job fails

### ISSUE THREAD

**Issue by halilmr** [kubeflow/manifests#2842]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

When installing kubeflow 1.9 on an AWS EKS cluster, I passed all the steps (https://github.com/kubeflow/manifests/actions/runs/10185296898/job/28201968906?pr=2815) but stuck on kubeflow-m2m-oidc-configurator step. kubeflow-m2m-oidc-configurator-28728970 job fails with the error: 
Waiting for a Job to be created by the kubeflow-m2m-oidc-configurator CronJob...
Job kubeflow-m2m-oidc-configurator-28724745 created.
Waiting for the Job kubeflow-m2m-oidc-configurator-28724745 to complete...
Job kubeflow-m2m-oidc-configurator-28724745 failed.
k -n istio-system logs kubeflow-m2m-oidc-configurator-28724745-5vflw
Wait until resource RequestAuthentication m2m-token-issuer in namespace istio-system is ready.
Resource RequestAuthentication m2m-token-issuer in namespace istio-system is ready.
Patch RequestAuthentication with JWKS if required.
Getting RequestAuthentication object.
Issuer Url in RequestAuthentication: https://kubernetes.default.svc.cluster.local/
Current Jwks (escaped):
Jwks Uri from Well Known OpenID Configuration: [https://ip-172-16-49-175.ec2.internal:443/openid/v1/jwks](https://ip-172-16-49-175.ec2.internal/openid/v1/jwks)

### Steps to reproduce the issue

1. Create an EKS Cluster
2. Install kubeflow 1.9 following the step mentioned https://github.com/kubeflow/manifests/actions/runs/10185296898/job/28201968906?pr=2815

**Comment by juliusvonkohout** [comment]
@hansinikarunarathne  @biswajit-9776  this might be related to failing tests
