### ISSUE TITLE
1.9.0 manifests use LATEST tag for Kubeflow Notebooks!

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#2849]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

For some reason the Kubeflow Notebooks `spawner_ui_config.yaml` was not correctly synced from the `kubeflow/kubeflow` repo, resulting in the default spawner using the `:latest` tag, rather than the correct `:1.9.0` tag.

https://github.com/kubeflow/manifests/blob/v1.9.0/apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml

This is a __CRITICAL issue__ which must be rectified by a 1.9.1 release almost immediately, as it will inevitably result in many users using unstable Notebook images without realizing it, as we use `latest` for all dev builds.

### Steps to reproduce the issue

N/A

**Comment by thesuperzapper** [comment]
@juliusvonkohout @kubeflow/release-managers @kubeflow/release-team this is a critical issue for 1.9.1, and its so serious that we should consider releasing a fix with only this.

The only other things which we probably need in that emergency 1.9.1 release would be fixing the regressions which make the Kubeflow Pipelines "outside the cluster" (https://github.com/kubeflow/manifests/issues/2844) and "inside the cluster" no longer work (https://github.com/kubeflow/manifests/issues/2840).

**Comment by juliusvonkohout** [comment]
Yes, this was discussed a few weeks ago in the release team meetings and we also have https://github.com/kubeflow/manifests/issues/2804

I also talked about it with @kimwnasptd

**Comment by juliusvonkohout** [comment]
Please check https://github.com/kubeflow/manifests/pull/2853
