### ISSUE TITLE
Cannot pull image gcr.io/arrikto/kubeflow/oidc-authservice

### ISSUE THREAD

**Issue by tomaszstachera** [kubeflow/manifests#2852]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
[](https://awslabs.github.io/kubeflow-manifests/release-v1.7.0-aws-b1.0.3/docs/deployment/vanilla/guide/)
*  KFP version: 
build version dev_local (https://awslabs.github.io/kubeflow-manifests/release-v1.7.0-aws-b1.0.3/docs/deployment/vanilla/guide/)
*  KFP SDK version: 
1.8.21

### Steps to reproduce

Deploy Kubeflow and check authservice Pod - image cannot be pulled.

```bash
docker pull gcr.io/arrikto/kubeflow/oidc-authservice:e236439
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

### Expected result

Pod is started and image is pulled.

### Materials and Reference

`docker pull gcr.io/arrikto/kubeflow/oidc-authservice:e236439`

---

Impacted by this bug? Give it a 👍.

**Comment by themowski** [comment]
We ran into this problem while deploying Kubeflow 1.4.1 via manifests. Verified that modifying the `common/oidc-authservice/base/kustomization.yaml` as follows fixed the issue for us (YMMV on newer versions of Kubeflow):

```yaml
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: docker.io/kubeflowmanifestswg/oidc-authservice
  newTag: 28c59ef
```

**Comment by thesuperzapper** [comment]
Hey everyone, I am pretty sure that the old `gcr.io/arrikto/kubeflow` will never be live again (because Arrikto no longer exists as a company).

__To resolve this issue, you will need to do one of the following:__

1. Migrate to a Kubeflow distribution that does not use `oidc-authservice`:
      - For example, [__deployKF__](https://www.deploykf.org/) is a popular option which uses `oauth2-proxy`.
      - _NOTE: you could also update to the raw 1.9.0 manifests (which use `oauth2-proxy`), but I always caution that the community does not support the manifests as a product, but rather to help distribution maintainers, so you will be on your own for environment specific issues._
3. Use the mirror at [`docker.io/kubeflowmanifestswg/oidc-authservice`](https://hub.docker.com/r/kubeflowmanifestswg/oidc-authservice)
4. Build [`arrikto/oidc-authservice`](https://github.com/arrikto/oidc-authservice) and host an image yourself

The latest version available on the mirror is:

```
docker.io/kubeflowmanifestswg/oidc-authservice:28c59ef
```

**Comment by rafaeldasilva** [comment]
Thanks a lot for the updates @juliusvonkohout
Do you knows the reason AWS distribution was discontinued after 1.7?

Thanks in advance.

**Comment by juliusvonkohout** [comment]
No, i do not know, but i think kubeflow/manifests matured so much that i do not miss it. https://github.com/kubeflow/manifests?tab=readme-ov-file#installation works in general on all clusters. There are also enough other distributions available that do not have AWS in the name but still support it. We just require Kubernetes and it does not matter that much whether its Kind, rancher, openshift, GKE, AKS, or EKS.
