### ISSUE TITLE
RBAC: Access denied from central dashboard and no namespace found

### ISSUE THREAD

**Issue by carre140** [kubeflow/manifests#2858]
/kind bug

**What steps did you take and what happened:**
In my deployment of kubeflow v1.6.1 from https://github.com/kubeflow/manifests/releases/tag/v1.6.1, I received a "RBAC: access denied" when I log in with default email address to the central dashboard

Default user namespace already exists
This problem comes only with TALOS (I heavily insist cause I did not have issue on other configuration)

**What did you expect to happen:**
I expect to get access to the default user namespace in order to create some notebook

**Anything else you would like to add:**
I have installed this version on a Openstack cluster with same kubernetes version (v1.22.9) on ubuntu target without this issue
I guess this issue comes from TALOS os but I am not an istio expert (newbie in fact)
I have activated istio log in profile-deployment pod and got this rbac error
[2022-11-03T08:38:50.667Z] "GET /kfam/v1/bindings?user=user%40example.com HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "-" "0614bb23-2978-9109-803c-870a6b63734f" "profiles-kfam.kubeflow:8081" "-" inbound|8081|| - 10.254.17.38:8081 10.254.15.161:37922 - -
[2022-11-03T08:38:50.667Z] "GET /kfam/v1/role/clusteradmin?user=user%40example.com HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "-" "c58ac7c1-9ffd-95cf-b5f4-f9550fbfcf06" "profiles-kfam.kubeflow:8081" "-" inbound|8081|| - 10.254.17.38:8081 10.254.15.161:37918 - -
2

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.6.0-rc.1
- Kubernetes platform: Kubernetes Service on top of the Bare metal.
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0",Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9"
- OS (e.g. from `/etc/os-release`):
NAME="Talos"
ID=talos
VERSION_ID=v1.1.2
PRETTY_NAME="Talos (v1.1.2)"
HOME_URL=https://www.talos.dev/
BUG_REPORT_URL=https://github.com/talos-systems/talos/issues

**Comment by harsha1163** [comment]
I am facing unauthorized error when trying to check logs from the pipeline component. I have kubeflow running on Cilium enabled AKS cluster. I tried following the cilium parameters mentioned above but those parameters are already in disabled state. 

Need some help here.. can anyone suggest? Issue is describe here: https://github.com/kubeflow/pipelines/issues/11544

**Comment by juliusvonkohout** [comment]
Please install Kubeflow 1.9.1 from scratch and check the documentation about cilium in the main readme. If necessary create a new issue.

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests#istio for the documentation
