### ISSUE TITLE
kuebflow 1.9 Okta OIDC setup Document Request 

### ISSUE THREAD

**Issue by tppalani** [kubeflow/manifests#2865]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

Hi Team,

I'm looking for documentation to setup Okta OIDC login mechanism instated of using default dex, can you please guide me is that latest release will support Okta login if yes please share the document

### Steps to reproduce the issue

NA

### Put here any screenshots or videos (optional)

NA

**Comment by juliusvonkohout** [comment]
Does Dex or oauth2-proxy work with Okta OIDC?

**Comment by juliusvonkohout** [comment]
> but by question is how to enable okta login in kubeflow dashboard?

Well by configuring Dex to use it.

**Comment by thesuperzapper** [comment]
@tppalani this is what we call an "environment specific issue" meaning we can't support every possible integration for the raw Kubeflow Manifests, which is why Kubeflow Distributions exist.

For example, if you are using the [deployKF](https://www.deploykf.org/), the Okta integration docs are here:
- https://www.deploykf.org/guides/platform/deploykf-authentication/#okta

**Comment by tppalani** [comment]
> @tppalani this is what we call an "environment specific issue" meaning we can't support every possible integration for the raw Kubeflow Manifests, which is why Kubeflow Distributions exist.
> 
> For example, if you are using the [deployKF](https://www.deploykf.org/), the Okta integration docs are here:
> 
> * https://www.deploykf.org/guides/platform/deploykf-authentication/#okta

I’m not using deploykf. I’m using manifest yaml

**Comment by thesuperzapper** [comment]
> > @tppalani this is what we call an "environment specific issue" meaning we can't support every possible integration for the raw Kubeflow Manifests, which is why Kubeflow Distributions exist.
> > For example, if you are using the [deployKF](https://www.deploykf.org/), the Okta integration docs are here:
> > 
> > * https://www.deploykf.org/guides/platform/deploykf-authentication/#okta
> 
> I’m not using deploykf. I’m using manifest yaml

@tppalani if you choose to use the raw manifests, you will need to support yourself, either by hiring someone to help you, or developing the skills yourself.

**Comment by juliusvonkohout** [comment]
Yes, here is the official text:

"The Kubeflow manifests provide a quick way to get a minimum viable Kubeflow Platform up and running. The Kubeflow community support for Kubeflow manifests is only best-effort, non-commercial and not guaranteed for environment-specific issues or custom configurations. Nevertheless, we welcome contributions and bug reports very much. For commercial production-level usage and support there are many options. You can use a third-party commercial distribution, hire consultants or build up the knowledge yourself to maintain and extend your Kubeflow installation."
