### ISSUE TITLE
W0911 03:12:55.601024     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection. I0911 03:12:55.601061     1 metadata_store_server_main.cc:551] Retry attempt 4

### ISSUE THREAD

**Issue by vak890** [kubeflow/manifests#2875]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

When I followed the kubeflow installation guide, metadata grpc deployment couldn't run successfully
kubectl logs -f metadata-grpc-deployment-786f94dc8b-kfrgc  -n kubeflow
W0911 03:12:55.545574     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0911 03:12:55.545694     1 metadata_store_server_main.cc:551] Retry attempt 0
W0911 03:12:55.559099     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0911 03:12:55.559130     1 metadata_store_server_main.cc:551] Retry attempt 1
W0911 03:12:55.572381     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0911 03:12:55.572420     1 metadata_store_server_main.cc:551] Retry attempt 2
W0911 03:12:55.586738     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0911 03:12:55.586771     1 metadata_store_server_main.cc:551] Retry attempt 3
W0911 03:12:55.601024     1 metadata_store_server_main.cc:550] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0911 03:12:55.601061     1 metadata_store_server_main.cc:551] Retry attempt 4
F0911 03:12:55.614584     1 metadata_store_server_main.cc:555] Check failed: absl::OkStatus() == status (OK vs. ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.) MetadataStore cannot be created with the given connection config.
*** Check failure stack trace: ***

### Steps to reproduce the issue

kustomize build apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user | kubectl apply -f -

**Comment by vak890** [comment]
I found that the schema_version field is present in MySQL
![image](https://github.com/user-attachments/assets/fafd0cd3-9e3e-4f58-a035-eea6593b12c7)
mysql log:
![image](https://github.com/user-attachments/assets/4cdbe885-398d-4172-8615-eeecce238a46)

**Comment by vak890** [comment]
@juliusvonkohout The solution is whether the kubeflow platform needs to be deployed in a new Kubernetes cluster, but our current Kubernetes cluster is native without any changes, and only some pods have been deployed in the cluster

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout The solution is whether the kubeflow platform needs to be deployed in a new Kubernetes cluster, but our current Kubernetes cluster is native without any changes, and only some pods have been deployed in the cluster

I do not understand your text. Please follow the new guidelines we just updated in kubeflow/manifests/readme.md.

**Comment by juliusvonkohout** [comment]
/close

due to inactivity

**Comment by Epochex** [comment]
kubectl exec --it <your mysql pod> -n kubeflow -- bash
mysql -u root -p  (code is empty, just push enter)
use metadb;
and execute this sql code
```sql
  create_type_table {
    query: " CREATE TABLE IF NOT EXISTS `Type` ( "
           "   `id` INT PRIMARY KEY AUTO_INCREMENT, "
           "   `name` VARCHAR(255) NOT NULL, "
           "   `version` VARCHAR(255), "
           "   `type_kind` TINYINT(1) NOT NULL, "
           "   `description` TEXT, "
           "   `input_type` TEXT, "
           "   `output_type` TEXT, "
           "   `external_id` VARCHAR(255) UNIQUE "
           " ); "
  }
  create_artifact_table {
    query: " CREATE TABLE IF NOT EXISTS `Artifact` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `type_id` INT NOT NULL, "
           "   `uri` TEXT, "
           "   `state` INT, "
           "   `name` VARCHAR(255), "
           "   `external_id` VARCHAR(255) UNIQUE, "
           "   `create_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   `last_update_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   CONSTRAINT UniqueArtifactTypeName UNIQUE(`type_id`, `name`) "
           " ); "
  }
  create_artifact_property_table {
    query: " CREATE TABLE IF NOT EXISTS `ArtifactProperty` ( "
           "   `artifact_id` INT NOT NULL, "
           "   `name` VARCHAR(255) NOT NULL, "
           "   `is_custom_property` TINYINT(1) NOT NULL, "
           "   `int_value` INT, "
           "   `double_value` DOUBLE, "
           "   `string_value` MEDIUMTEXT, "
           "   `byte_value` MEDIUMBLOB, "
           "   `proto_value` MEDIUMBLOB, "
           "   `bool_value` BOOLEAN, "
           " PRIMARY KEY (`artifact_id`, `name`, `is_custom_property`)); "
  }
  create_execution_table {
    query: " CREATE TABLE IF NOT EXISTS `Execution` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `type_id` INT NOT NULL, "
           "   `last_known_state` INT, "
           "   `name` VARCHAR(255), "
           "   `external_id` VARCHAR(255) UNIQUE, "
           "   `create_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   `last_update_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   CONSTRAINT UniqueExecutionTypeName UNIQUE(`type_id`, `name`) "
           " ); "
  }
  create_execution_property_table {
    query: " CREATE TABLE IF NOT EXISTS `ExecutionProperty` ( "
           "   `execution_id` INT NOT NULL, "
           "   `name` VARCHAR(255) NOT NULL, "
           "   `is_custom_property` TINYINT(1) NOT NULL, "
           "   `int_value` INT, "
           "   `double_value` DOUBLE, "
           "   `string_value` MEDIUMTEXT, "
           "   `byte_value` MEDIUMBLOB, "
           "   `proto_value` MEDIUMBLOB, "
           "   `bool_value` BOOLEAN, "
           " PRIMARY KEY (`execution_id`, `name`, `is_custom_property`)); "
  }
  create_context_table {
    query: " CREATE TABLE IF NOT EXISTS `Context` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `type_id` INT NOT NULL, "
           "   `name` VARCHAR(255) NOT NULL, "
           "   `external_id` VARCHAR(255) UNIQUE, "
           "   `create_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   `last_update_time_since_epoch` BIGINT NOT NULL DEFAULT 0, "
           "   UNIQUE(`type_id`, `name`) "
           " ); "
  }
  create_context_property_table {
    query: " CREATE TABLE IF NOT EXISTS `ContextProperty` ( "
           "   `context_id` INT NOT NULL, "
           "   `name` VARCHAR(255) NOT NULL, "
           "   `is_custom_property` TINYINT(1) NOT NULL, "
           "   `int_value` INT, "
           "   `double_value` DOUBLE, "
           "   `string_value` MEDIUMTEXT, "
           "   `byte_value` MEDIUMBLOB, "
           "   `proto_value` MEDIUMBLOB, "
           "   `bool_value` BOOLEAN, "
           " PRIMARY KEY (`context_id`, `name`, `is_custom_property`)); "
  }
  create_event_table {
    query: " CREATE TABLE IF NOT EXISTS `Event` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `artifact_id` INT NOT NULL, "
           "   `execution_id` INT NOT NULL, "
           "   `type` INT NOT NULL, "
           "   `milliseconds_since_epoch` BIGINT, "
           "   CONSTRAINT UniqueEvent UNIQUE( "
           "     `artifact_id`, `execution_id`, `type`) "
           " ); "
  }
  create_association_table {
    query: " CREATE TABLE IF NOT EXISTS `Association` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `context_id` INT NOT NULL, "
           "   `execution_id` INT NOT NULL, "
           "   UNIQUE(`context_id`, `execution_id`) "
           " ); "
  }
  create_attribution_table {
    query: " CREATE TABLE IF NOT EXISTS `Attribution` ( "
           "   `id` INTEGER PRIMARY KEY AUTO_INCREMENT, "
           "   `context_id` INT NOT NULL, "
           "   `artifact_id` INT NOT NULL, "
           "   UNIQUE(`context_id`, `artifact_id`) "
           " ); "
  }

  create_event_path_table {
    query: " CREATE TABLE IF NOT EXISTS `EventPath` ( "
           "   `event_id` INT NOT NULL, "
           "   `is_index_step` TINYINT(1) NOT NULL, "
           "   `step_index` INT, "
           "   `step_key` TEXT "
           " ); "
  }
  
   create_mlmd_env_table {
    query: " CREATE TABLE IF NOT EXISTS `MLMDEnv` ( "
           "   `schema_version` INTEGER PRIMARY KEY "
           " ); "
  }
  
   create_parent_context_table {
    query: " CREATE TABLE IF NOT EXISTS `ParentContext` ( "
           "   `context_id` INT NOT NULL, "
           "   `parent_context_id` INT NOT NULL, "
           " PRIMARY KEY (`context_id`, `parent_context_id`)); "
  }
  
 create_parent_type_table {
    query: " CREATE TABLE IF NOT EXISTS `ParentType` ( "
           "   `type_id` INT NOT NULL, "
           "   `parent_type_id` INT NOT NULL, "
           " PRIMARY KEY (`type_id`, `parent_type_id`)); "
  }
```
```sql
ALTER TABLE `Artifact`
ADD INDEX `idx_artifact_uri`(`uri`(255)),
ADD INDEX `idx_artifact_create_time_since_epoch` (`create_time_since_epoch`),
ADD INDEX `idx_artifact_last_update_time_since_epoch` (`last_update_time_since_epoch`);
```
```sql
INSERT INTO `MLMDEnv` (`schema_version`) VALUES (10);
```

and back to kubectl
```bash
kubectl scale deployment metadata-grpc-deployment -n kubeflow --replicas=1
kubectl rollout restart deployment metadata-grpc-deployment -n kubeflow
```
for me , the problme has been solved
