### ISSUE TITLE
unable to pull arrikto/istio/pilot

### ISSUE THREAD

**Issue by SZ789** [kubeflow/manifests#2876]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

root@master:/home# docker pull gcr.io/arrikto/istio/pilot:1.14.1-1-g19df463bb
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication.

When I install kubeflow with single command, i can't pull this image.

### Steps to reproduce the issue

docker pull gcr.io/arrikto/istio/pilot:1.14.1-1-g19df463bb

**Comment by juliusvonkohout** [comment]
Hello, please upgrade to Kubeflow 1.8.1/1.9. after the 1.9.1 release in the next months we will drop support for 1.8.1 and older.

You are pointing to very old images. You can either mirror them yourselves or upgrade.

**Comment by thesuperzapper** [comment]
@SZ789 In the short term, you just need to find another publicly available equivalent of your images and patch your manifests as Arrikto (and `gcr.io` for that matter) no longer exist.

In the future you can migrate to one of the currently supported Kubeflow distributions, see this table:

- https://www.kubeflow.org/docs/started/installing-kubeflow/

Personally, I recommend [deployKF](https://www.deploykf.org/), as it makes using GitOps (ArgoCD) much easier, and also has centralized configs for everything rather than requiring manual patching of YAML (for reference, I maintain it).

**Comment by SZ789** [comment]
> Hello, please upgrade to Kubeflow 1.8.1/1.9. after the 1.9.1 release in the next month we will drop support for 1.8.1 and older.
> 
> You are pointing to very old images. You can either mirror them yourself or upgrade.

Thank you，I upgrade my kubueflow  version and solve the problem.

**Comment by SZ789** [comment]
> @SZ789 In the short term, you just need to find another publicly available equivalent of your images and patch your manifests as Arrikto (and `gcr.io` for that matter) no longer exist.
> 
> In the future you can migrate to one of the currently supported Kubeflow distributions, see this table:
> 
> * https://www.kubeflow.org/docs/started/installing-kubeflow/
> 
> Personally, I recommend [deployKF](https://www.deploykf.org/), as it makes using GitOps (ArgoCD) much easier, and also has centralized configs for everything rather than requiring manual patching of YAML (for reference, I maintain it).

Thank for your remind, I find the gcr.io/arrikto/istio/pilot has been moved to docker.io/istio/pilot.
