### ISSUE TITLE
Multiple packages may generate the same parameters ConfigMap resource

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#288]
A pattern we use in kubeflow/manifests is defining a ConfigMap and using its values as variables, to achieve variable substitution.

In addition, there is no CI test to check if two packages in manifests generate the same ConfigMap resource (or any resource for that matter).

Normally, it is rare to have collisions between resources created in different packages.
However, for the parameters ConfigMap, this can easily happen as:
* There is a tendency to disable the ConfigMap name suffix.
* All packages use the same name for the parameters ConfigMap (copy-pasting probably).
* Some packages don't use a namePrefix, which would solve the problem.

Effects:
* `kustomize build` should still work as expected, as the variables are substituted from the ConfigMap generated at that moment, before it is applied to K8s.
* Our strategy now is create if not exists, so only the first ConfigMap of the same name will be applied. If the strategy changes to apply, then the last ConfigMap will be the one to exist in the end.
* In case a component uses a ConfigMap reference instead of a variable substitution, this could potentially break things (eg https://github.com/kubeflow/manifests/blob/8c5b9cee9c637fe6102603fdebfac569c178112e/jupyter/jupyter-web-app/base/deployment.yaml#L14)

Possible mitigations:
* Enforce namePrefix for all components.
* Add CI test.

/cc @kimwnasptd  @kkasravi @jlewi 

/priority p1

**Comment by kkasravi** [comment]
thanks for opening this @yanniszark !
