### ISSUE TITLE
Multi region & Multi Data Center Support

### ISSUE THREAD

**Issue by Ragavendran-Venkataraman** [kubeflow/manifests#2883]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [ ] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

Duplicate of https://github.com/kubeflow/kubeflow/issues/5467
Need help in setting up multi region and multi DC kubeflow setup 

### Steps to reproduce the issue

Duplicate of https://github.com/kubeflow/kubeflow/issues/5467
Need help in setting up multi region and multi DC kubeflow setup

**Comment by juliusvonkohout** [comment]
I think it goes the other way around.

In your CICD you just specify on which cluster to run your KF pipeline.

And if you just want a big Kubernetes cluster spanning multiple Regions, then you have to make sure that it is transparent on the kubernetes level and for Istio-CNI. But that will be the same problem for many other Kubernetes applications, so it is not really a Kubeflow topic.
