### ISSUE TITLE
Kubeflow doesnt work well in a dualstack (IPV4/IPV6) EKS cluster

### ISSUE THREAD

**Issue by ajithkumar6** [kubeflow/manifests#2892]
Does kubeflow work on a Dualstack eks cluster ? .I tried to deploy kubeflow 1.17 on a dual stack EKS cluster ,the kserve-models-web-app pod is continuously failing the readiness and livenessprobe check .Please find the details below.Could you help on what needs to be done

output from pod describe:
Normal Pulling 41s kubelet Pulling image "docker.io/istio/proxyv2:1.17.3"
Normal Pulled 35s kubelet Successfully pulled image "docker.io/istio/proxyv2:1.17.3" in 5.549225966s (5.549233399s including waiting)
Normal Created 35s kubelet Created container istio-init
Normal Started 35s kubelet Started container istio-init
Normal Started 27s kubelet Started container kserve-models-web-app
Normal Pulled 27s kubelet Successfully pulled image "kserve/models-web-app:v0.10.0" in 6.018726427s (6.01873368s including waiting)
Normal Created 27s kubelet Created container kserve-models-web-app
Normal Pulled 27s kubelet Container image "docker.io/istio/proxyv2:1.17.3" already present on machine
Normal Created 27s kubelet Created container istio-proxy
Normal Started 27s kubelet Started container istio-proxy
Warning Unhealthy 3s (x8 over 26s) kubelet Readiness probe failed: HTTP probe failed with statuscode: 500
Warning Unhealthy 3s (x3 over 23s) kubelet Liveness probe failed: HTTP probe failed with statuscode: 500
Normal Killing 3s kubelet Container kserve-models-web-app failed liveness probe, will be restarted
Normal Pulling 2s (x2 over 33s) kubelet Pulling image "kserve/models-web-app:v0.10.0"

**Comment by juliusvonkohout** [comment]
Hello, there are many options to install Kubeflow, which are explained here https://www.kubeflow.org/docs/started/installing-kubeflow/#kubeflow-platform. I myself install the official open-source version from here https://github.com/kubeflow/manifests/releases. If you want to go this route please read the whole readme including https://github.com/kubeflow/manifests?tab=readme-ov-file#upgrading-and-extending.

Kubeflow 1.7 is end of life, so please try with 1.9.1 and reopen if necessary.

"The Kubeflow manifests provide a quick way to get a minimum viable Kubeflow Platform up and running. The Kubeflow community support for Kubeflow manifests is only best-effort, non-commercial and not guaranteed for environment-specific issues or custom configurations. Nevertheless, we welcome contributions and bug reports very much. For commercial production-level usage and support there are many options. You can use a third-party commercial distribution, hire consultants or build up the knowledge yourself to maintain and extend your Kubeflow installation."
