### ISSUE TITLE
logout tab is not working 

### ISSUE THREAD

**Issue by muratyarali** [kubeflow/manifests#2895]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

I recently installed Kubeflow v1.9.1-RC.2, and the logout tab on the Kubeflow UI is unresponsive. Clicking it does nothing, but reloading the page takes me to the login page.

### Steps to reproduce the issue

1. Push the logout tab on the Kubeflow UI. You will see it is unresponsive.
2.Reload the page and go to the login page

**Comment by juliusvonkohout** [comment]
Did this happen in RC1 as well?

**Comment by juliusvonkohout** [comment]
@thesuperzapper do you know about this? I think we had and fixed this problem before.

Could it be that we need to merge https://github.com/kubeflow/kubeflow/pull/7631 and that there was a hotfix in kubeflow/manifest as well?

There is also https://github.com/kubeflow/manifests/blob/master/common/oauth2-proxy/components/central-dashboard/patches/deployment.logout-url.yaml

@tarekabouzeid @muratyarali can you apply the patch and check whether it should be oauth2/logout or oauth2/sign_out?

**Comment by juliusvonkohout** [comment]
@thesuperzapper can you patch this then in kubeflow/kubeflow and sent me a tag for synchronization? 

Nevertheless i still do not like oauth2/logout vs. oauth2/sign_out and will remove one of them.

**Comment by juliusvonkohout** [comment]
CC also @kromanow94 @MaxKavun

**Comment by kromanow94** [comment]
Hey, @MaxKavun and my expertise resolves mostly around backend. But, with some guidance, we can provide help. Let us know if this is something you're interested in.

**Comment by juliusvonkohout** [comment]
We should also extend the test here to cover this https://github.com/kubeflow/manifests/blob/master/.github/workflows/dex_test.yaml.

**Comment by juliusvonkohout** [comment]
An there is also https://github.com/kubeflow/kubeflow/issues/7624 for reference

**Comment by juliusvonkohout** [comment]
And another one https://github.com/kubeflow/kubeflow/issues/7568

**Comment by thesuperzapper** [comment]
As I was saying in https://github.com/kubeflow/manifests/issues/2895#issuecomment-2423375988.

If anyone wants to raise a PR on the central dashboard in the `kubeflow/kubeflow` repo to change the logout button to a simple `<a>` tag (which uses a GET rather than a POST), then the redirect will work properly.

**Comment by juliusvonkohout** [comment]
closed by https://github.com/kubeflow/kubeflow/pull/7654/files 
and i released https://github.com/kubeflow/manifests/releases/tag/v1.9.1-rc.3
