### ISSUE TITLE
"Incorrect Path for 'oauth2-proxy' in README.md of v1.9.1-rc.2 Manifests"

### ISSUE THREAD

**Issue by muratyarali** [kubeflow/manifests#2899]
Hi.

I was examining the manifests folder of the v1.9.1-rc.2 release, and I believe that the README.md file has a small mistake.

There is no "oauth2-proxy" folder in this path "apps/centraldashboard/upstream/overlays/oauth2-proxy". There is "/apps/centraldashboard/overlays/oauth2-proxy" in this path.

This path is truly shown in /example/kustomization.yaml but wrong in README.md. Or maybe there is something else I could not know :)

![Screenshot_4](https://github.com/user-attachments/assets/571d3411-14a1-45da-8062-0b378285fb5a)

**Comment by juliusvonkohout** [comment]
fixed in https://github.com/kubeflow/manifests/pull/2896
