### ISSUE TITLE
Kubeflow Dashboard OIDC Okta Login Setup

### ISSUE THREAD

**Issue by tppalani** [kubeflow/manifests#2900]
I'm Team I'm new to the kubeflow i have completed my kubeflow setup in EKS cluster and i can able login and logout using default authentication mechanism using dex server.  Now i want to setup Okta configuration instead of using default login mechanism  can you please somebody can share the document how to configure this ?

**Comment by juliusvonkohout** [comment]
Yes, you can use connector in Dex or connect ouath2 directly to your IDP see https://github.com/kubeflow/manifests/tree/master/common/oauth2-proxy#change-the-default-authentication-from-dex--oauth2-proxy-to-oauth2-proxy-only

/close
