### ISSUE TITLE
Documentation issue - link to the best practices is not working

### ISSUE THREAD

**Issue by varodrig** [kubeflow/manifests#2902]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

This repository is owned by the [Manifests Working Group](https://github.com/kubeflow/community/blob/master/wg-manifests/charter.md). If you are a contributor authoring or editing the packages please see **[Best Practices](https://github.com/kubeflow/manifests/blob/master/documents/KustomizeBestPractices.md).**

### Steps to reproduce the issue

1. Access https://github.com/kubeflow/manifests/
2. click on [Best Practices](https://github.com/kubeflow/manifests/blob/master/documents/KustomizeBestPractices.md).
3. It redirects to a url that doesn't exists

### Put here any screenshots or videos (optional)

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/7d8993e4-0375-46ea-a746-24a6d0bcedc0">

**Comment by juliusvonkohout** [comment]
@varodrig please open a PR to remove the link or point to https://kubectl.docs.kubernetes.io/references/kustomize/

**Comment by varodrig** [comment]
@juliusvonkohout  please assign to me. thank you

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout please assign to me. thank you

Done

**Comment by juliusvonkohout** [comment]
While you are at it you can also remove the `Kubeflow Tekton Pipelines apps/kfp-tekton/upstream [2.0.5](https://github.com/kubeflow/kfp-tekton/tree/2.0.5` table entry until we get proper manifests again
