### ISSUE TITLE
Better handling of expired auth cookie in kubeflow notebook

### ISSUE THREAD

**Issue by ZxMYS** [kubeflow/manifests#2904]
Hi! 

We are using kubeflow 1.3 and are running notebooks with it. It seems like after the authservice_session cookie expires, all requests to a running kubeflow notebook will be redirected (HTTP 302) to the kubeflow login page; This behavior is fine and natural when a user tries to open a page, but for a user who has already opened a jupyter notebook page and is using it, it is less so: the user will see this error dialog with a confusing error message when they do most actions (save a notebook, create a notebook, open a terminal, etc) on the notebook page:

<img width="325" alt="Screen Shot 2021-10-18 at 3 59 10 PM" src="https://user-images.githubusercontent.com/1507278/137818135-3489d48a-30da-4045-8c68-7595dd23740e.png">

This error message is due to that Jupyter frontend code expects a JSON response to those requests. Since kubeflow redirects the requests to the login page, which is HTML, the notebook frontend can not parse the response properly. 

Given that the authservice_session cookie seems to be valid for a day only, it's not uncommon for a notebook user who works on notebooks continuously to hit this issue.

I wonder if kubeflow can provide a better user experience here - e.g. instead of blindly redirecting all requests to the login page, only redirect the index page of a notebook server and return 403 for other requests. The Jupyter frontend can properly handle the 403 and display a proper error message, which is much less confusing.

To reproduce the error message in the screenshot:

- Login to kubeflow
- Start a notebook server, with an image based on jupyter notebook (the kf default ones are ok)
- Connect to the notebook server (open its web ui) and keep the page open
- Remove kubeflow's 'authservice_session' cookie with the browser's developer tools to simulate its expiration
- Now when you do most actions in the notebook you see the confusing error message

**Comment by juliusvonkohout** [comment]
With the refresh cookie in oauth2-proxy/dex this is already mitigated a lot. I tested it on 1.9.1 with oauth2-proxy only, but someone needs to provide the dex refresh settings as well here.

Is anyone willing to create a PR?

/lifecycle stale
