### ISSUE TITLE
Unit tests in v0.6-branch are not up-to-date and updating them makes tests fail

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#296]
Steps to reproduce:
* Checkout to v0.6-branch (eab125dd42c08b0e2495b7b2d7a7010ac64d3774).
* Regenerate tests: 
```bash
cd tests
make generate
```

Immediately, you will notice changes.
This means that the tests were out of sync, but tests passed either way.

* Run unit tests:

```bash
make test
```

Tests fail:
```
=== RUN   TestIstioBase                                                                                                                                                                                     
--- FAIL: TestIstioBase (0.01s)                                                                                                                                                                             
    istio-base_test.go:157: Err: cannot read file "/manifests/istio/istio/base/params.yaml"                                                                                                                 
```
This essentially means that tests on v0.6-branch are broken.

@jlewi @kkasravi why didn't CI catch this?

/priority p0

**Comment by kkasravi** [comment]
i believe this may be due to not rebasing from master.

I think we add this to the PR template form

1. git fetch upstream master
2. git rebase -i upstream/master
3. cd tests
4. make generate
5. make test

**Comment by yanniszark** [comment]
@kkasravi this is not master though.
This is v0.6-branch.
Shouldn't the E2E tests catch this ?

**Comment by kkasravi** [comment]
yes - we need to update the e2e to do the following

mv tests tests_check
make generate
see if any *.go files differ between tests tests_check
if yes 
  fail
else
  make test
fi

**Comment by kkasravi** [comment]
@gabrielwen you'll need to update run-tests.sh along the lines of what I [suggested](https://github.com/kubeflow/manifests/issues/296#issuecomment-523597616)

**Comment by kkasravi** [comment]
Adding liuhougang6@126.com and adhita.selvaraj@gmail.com

I think this means that something was merged w/o doing a generate.

There is a flaw in the template we use for the PR, any PR should do the following
git fetch upstream master
git rebase -i upstream/master
cd tests
make generate
make test
Yannis do you know how to update the PR template?

**Comment by swiftdiaries** [comment]
The test workflow seems to be running this [run-tests.sh](https://github.com/kubeflow/manifests/blob/master/tests/scripts/run-tests.sh)
But make generate is not part of that, is that intended ?

**Comment by jlewi** [comment]
@kkasravi Are you saying that if PR authors don't run appropriate commands then our presubmits won't catch test failures?

**Comment by kkasravi** [comment]
Presubmits should catch failures. The unit tests are using the last snapshot (the last time generate was called). That is compared with what's in the current repo (eg PR request). 

Each unit test embeds the content of current files in the unit test - for example 
profiles-base_test.go contains the following files 
```
$ ☞  grep write[FK] profiles-base_test.go
	th.writeF("/manifests/profiles/base/crd.yaml", `
	th.writeF("/manifests/profiles/base/service-account.yaml", `
	th.writeF("/manifests/profiles/base/cluster-role-binding.yaml", `
	th.writeF("/manifests/profiles/base/role.yaml", `
	th.writeF("/manifests/profiles/base/role-binding.yaml", `
	th.writeF("/manifests/profiles/base/service.yaml", `
	th.writeF("/manifests/profiles/base/deployment.yaml", `
	th.writeF("/manifests/profiles/base/params.yaml", `
	th.writeF("/manifests/profiles/base/params.env", `
	th.writeK("/manifests/profiles/base", `
```

this is run through `kustomize build` and the current files run through `kustomize build`. Then both are EncodeAsYaml and compared.

**Comment by jlewi** [comment]
#299 is being rolled back.

I think we should rethink how the unittests work per #306

**Comment by jlewi** [comment]
Closing this as obsolete since we are now onto 0.7.
