### ISSUE TITLE
unit test improvements

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#308]
the following improvements should be implemented

- [ ] emulate kfctl's generate so that the top level kustomization.yamls are produced at each target directory
- [ ] the go unit test should use these generated kustomization.yaml's
- [ ] different unit tests should be called for all supported config files (kfctl_gcp_iap.yaml, ...)
- [ ] any non-resolved vars should result in a FAIL with failure indicating the config file and var
- [ ] the resulting yaml stream should be piped to kubectl apply --dry-run --validate -f -
- [x] unit tests should only be generated for changed files in the branch
- [x] there should be a --dry-run option to see what unit tests would be generated
- [x] there should be a --add_app `app=version` relative-path/to/app to generate an application CR

**Comment by jlewi** [comment]
Do we need to call kfctl generate? If we call kfctl generate that adds a lot of complexity; makes our unittests more like E2E tests.

Instead of calling kfctl; can we write one or more kustomization.yaml files equivalent to what we expect kfctl to generate?

**Comment by kkasravi** [comment]
ok, i've updated the description
