### ISSUE TITLE
Why does 'make generate' need to be run from GOPATH? - Document how to run the tests

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#317]
Right now we need to run `make generate` to regenerate the tests after any changes. 

It looks like I need to run the tests from 

```
${GOPATH}/src/github.com/kubeflow/manifests/tests
```

i.e. we have to the manifests repo under ${GOPATH}/src.

Why does the code need to be under ${GOPATH} other programs like kfctl appear to build just fine when they aren't in the GOPATH src tree?

At a minimum we should probably document this in a README.

@kkasravi

**Comment by jbrette** [comment]
@jlewi One of the main issues is that we don't have a go.mod. If you don't have a go.mod you most of the time have to run from GOPATH/src

**Comment by kkasravi** [comment]
We had a go.mod, I can add it back in

**Comment by jlewi** [comment]
I was getting

```
go: cannot find main module, but found .git/config in /home/jlewi/go/src/github.com/kubeflow/manifests
	to create a module there, run:
	cd .. && go mod init
```

when I tried to run the tests.

Here's what I ended up doing to run the tests. We should probably document this

1. Create a symbolic link in ${GOPATH}/src/github.com/kubeflow/manifests to point to where I checked out the rep

    ```
    ln -sf ${LOCAL_CLONE_OF_KUBEFLOW_MANIFESTS} ${GOPATH}/src/github.com/kubeflow/manifests
    ````

1.  Initialize a go.mod file

     ```
    cd      ${GOPATH}/src/github.com/kubeflow/manifests
    go mod init
     ```

1. Run the tests

    ```       
    cd      ${GOPATH}/src/github.com/kubeflow/manifests/tests
    make test
    ```

**Comment by jlewi** [comment]
This has been fixed.

We can now run make from ${MANIFEST_REPO}/tests
