### ISSUE TITLE
Stateful Applications (minio, mysql) are using Deployment instead of StatefulSet

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#326]
/kind bug

**What steps did you take and what happened:**

I noticed that the Minio and MySQL databases used in manifests are using a Deployment instead of a StatefulSet.
The problem with using a Deployment is that it is not guaranteed that only 1 replica is running, despite that being the spec.
There are scenarios where more than 1 replica might be running. 

**What did you expect to happen:**

Stateful applications need to run in a StatefulSet to ensure only 1 instance of each replica is running.

/cc @kkasravi @richardsliu @jlewi 
/priority p1

**Comment by jlewi** [comment]
@jtfogarty this looks like an issue with pipelines.
/area pipelines
/remove-area engprod

**Comment by Bobgy** [comment]
/assign @Bobgy 
That's a good point!
I will pick up this issue

**Comment by Bobgy** [comment]
@yanniszark Can you provide some reference?

After trying to edit a mysql deployment, I found the behavior is: first the existing pod terminates, then the new pod starts. It doesn't seem like an issue.

Also, data is actually stored in the persistence volume mounted in the pod. We have only one persistence volume with ReadWriteOnce. So I think there could never be a case multiple replicas corrupting data in it.

Should we really consider minio and mysql as stateful application in this case? It feels to me state is only in the PV, not in the application.

**Comment by yanniszark** [comment]
> We have only one persistence volume with ReadWriteOnce

ReadWriteOnce refers to the Node, not the Pod.
Multiple Pods can use a ReadWriteOnce PVC, as long as they are on the same Node.
See: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

> After trying to edit a mysql deployment, I found the behavior is: first the existing pod terminates, then the new pod starts. It doesn't seem like an issue.

The only controller that *guarantees* only 1 instance of each member of the application is running at any time, is the StatefulSet.
With deployments, there can be situations where 2 Pods may run simultaneously.

Now, some apps have safety mechanisms in place to deal with that.
For example, MySQL creates a lock when opening the database, to make sure no other MySQL instance messes with it.

However, we shouldn't be counting on the applications to do that.
We should follow the recommended way of running stateful applications by using a StatefulSet.

Finally:
> Should we really consider minio and mysql as stateful application in this case? It feels to me state is only in the PV, not in the application.

Of course. All stateful applications have to keep their state somewhere.

**Comment by Bobgy** [comment]
@yanniszark I found this documentation https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

It uses a deployment with `type: Recreate` to make sure there's only one pod in this deployment (exactly the same as our mysql deployment). It seems that's a valid use-case for deployment. Can you provide any references if there could be any issues to this setup?

I'm still new to Kubernetes, so there's probably something I missed.

**Comment by yanniszark** [comment]
@Bobgy yes, I'm aware of this piece of documentation. Thanks for pointing to the source of confusion.
I argue that it's outdated and should be converted to use StatefulSet.
The StatefulSet provides the following guarantees to stateful software: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets

My main argument is that Deployment does not guarantee that only 1 of each instance of the stateful application is going to be running. There are edge cases where, for example, two Pods of MySQL could be running at the same time.

This can cause a lot of problems, as many stateful applications assume they are the only ones who can access the local storage (which is logical).

**Comment by Bobgy** [comment]
@yanniszark Thanks for the extra explanation! Can you elaborate more on what edge cases for my curiosity? If possible, I'd like links that explains the problems in examples. Because according to https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#updating, `strategy: type: Recreate` already guarantees at most one pod is running.

For stateful sets, it seems to me benefits mentioned in https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets don't apply if there is only one instance.
> Stable, unique network identifiers.

There's only one instance, so using a service is enough.

> Stable, persistent storage.

Satisfied by using a named PVC.

> Ordered, graceful deployment and scaling.
> Ordered, automated rolling updates.

There's only one instance, so order, scaling doesn't have any difference.

**Comment by Bobgy** [comment]
Also I tried editing mysql deployment to have replica of 2.
```
mysql-fb475c7bd-9ztnj                                               1/1     Running             0          3h25m
mysql-fb475c7bd-tzfrk                                               0/1     ContainerCreating   0          104m
```
The new instance couldn't mount the same PV. It seems k8s can guarantee ReadWriteOnce PV is only mounted by one pod.

**Comment by yanniszark** [comment]
> The new instance couldn't mount the same PV. It seems k8s can guarantee ReadWriteOnce PV is only mounted by one pod.

I believe the Pods were scheduled in different Nodes, that's why the mount failed.
Multiple Pods can mount a ReadWriteOnce volume, this is something we have tested and seen in action.

> Can you elaborate more on what edge cases for my curiosity?

You'd have to dive into the code of the Deployment controller for that.
The thing here is that Deployments aren't meant to satisfy this kind of uniqueness guarantee.
This is not a goal and as such, I don't expect people to test or try to fix such scenarios.
So why not use StatefulSets, which come with this guarantee out of the box?

**Comment by Bobgy** [comment]
@yanniszark Sorry, forgot about this for a few days.
> I believe the Pods were scheduled in different Nodes, that's why the mount failed.

I can try with a cluster with only one node then. Will update here.

> So why not use StatefulSets, which come with this guarantee out of the box?
It's a breaking change considering manifest upgrade. So I want to avoid it unless I find real-world reasons.

**Comment by IronPan** [comment]
@yanniszark would there be any concrete issue even if there are two mysql pods created at same time in those edge cases, especially the PVC is what actually maintains the state? Do you mind elaborate a little bit?

This discussion is great to have. And just want to point out that, the in-cluster mysql just provides a demo level service guarantee and it's not intended for production. The single pod/node server is vulnerable to the single point failure and that's why we always recommend to use managed services such as GCP cloudsql or AWS RDS in production.

**Comment by IronPan** [comment]
Here is the reference
https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/gcp
https://github.com/e2fyi/kubeflow-aws/tree/master/pipelines

**Comment by yanniszark** [comment]
/reopen
since this isn't solved.

@IronPan 
> would there be any concrete issue even if there are two mysql pods created at same time in those edge cases, especially the PVC is what actually maintains the state? Do you mind elaborate a little bit?

With strategy `Recreate` in the deployment and only 1 replica, it seems not to present any issues. However, I'm not very comfortable going against Kubernetes guidelines, especially for a Stateful application. For our deployments, we will probably be moving towards using StatefulSets. If you would be open to accepting this contribution upstream, please let me know :)

**Comment by Bobgy** [comment]
my major concern is backwards compatibility.

If kubectl apply --prune or kpt apply can mature, I am okay with the change once we switch to those mechanisms that handle auto GC for obsolete resources.
