### ISSUE TITLE
Upgrade cert-manager to v0.10.0

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#365]
The current version of cert-manager is at v0.4.0 and doesn't support flags like 'isCA' for Issuer resource.

Refer PR: #362 

/assign @krishnadurai 
/cc @yanniszark

**Comment by kunmingg** [comment]
Thanks! 
This is a dependency for our CRD multi-API support:
https://book.kubebuilder.io/multiversion-tutorial/deployment.html

related:
kubeflow/kubeflow#4150

**Comment by kunmingg** [comment]
@lluunn 
Do we install cert manager by default after switch to managed cert?

**Comment by krishnadurai** [comment]
@kunmingg GCP IAP and basic auth configs have removed cert-manager installation by default in preference to managed cert.
https://github.com/kubeflow/kubeflow/pull/3871/files

**Comment by cliveseldon** [comment]
> Thanks!
> This is a dependency for our CRD multi-API support:
> https://book.kubebuilder.io/multiversion-tutorial/deployment.html
> 
> related:
> [kubeflow/kubeflow#4150](https://github.com/kubeflow/kubeflow/issues/4150)

I just want to reiterate this as any new Operator built using Kubebuilder V2 will work easiest out of the box with cert-manager. The core reasons is certificates for webhooks: https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html

Maybe the solution for ingress certificates can be separated from those needed by internal Operators?

@jlewi
