### ISSUE TITLE
upgrade manifests to work with kustomize-v3.0.1

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#372]
- the unit test generation uses kustharness_test.go which needs to be updated to kustomize-v3.0.1
- the hack/gen-test-target.sh needs to write out kustomize3 code, not kustomize
- tests/scripts/run_tests.sh does a `go get sigs.k8s.io/kustomize` and should be changed to get kustomize-v3.0.1

**Comment by jbrette** [comment]
@kkasravi I think we could close this bug.

**Comment by kkasravi** [comment]
thanks @jbrette
