### ISSUE TITLE
kfdef: remove kubeflow repo

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#373]
Alll manifests (including deployment configs for cloud providers) now live in kubeflow/manifests. 
After kubeflow/kubeflow#4121 is merged, kfctl plugins are configured to use the manifests repo instead of kubeflow.
As such, all configs under kfdef should not specify the kubeflow repo anymore.

/assign @yanniszark

**Comment by jlewi** [comment]
Related to: kubeflow/manifests#241
