### ISSUE TITLE
Certificates for Webhooks when no Cert-Manager

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/manifests#385]
Operators created with the latest [Kubebuilder V2 assume cert-manager](https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html) by default for provisioning Webhook certificates.

As Cert Manager has been removed in some configurations how will certificates be provided by GCP whose managed certificates seem more focused on ingress situations?

**Comment by krishnadurai** [comment]
@cliveseldon there's a possibility of cert-manager being brought back to configs through #365 . See Kunming's comment.

**Comment by vpavlin** [comment]
Should this be closed since cert-manager has been updated and added to some/all? of the KFdef configs?
