### ISSUE TITLE
split each app by cluster level resources and namespace resources

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#391]
per best practices [Separate cluster scoped and namespace scoped resources](https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md) we should split app resources into these 2 groups. 

We currently tend to split by crds - for example
```
./istio/istio-crds
./cert-manager/cert-manager-crds
./knative/knative-serving-crds
./dex-auth/dex-crds
./kfserving/kfserving-crds
./application/application-crds
./.git/logs/refs/heads/rm-crds
./.git/logs/refs/remotes/origin/rm-crds
./pytorch-job/pytorch-job-crds
```

we should rename these from -crds to -cluster and add things like cluster-role-binding, cluster-role, etc.

**Comment by vpavlin** [comment]
@kkasravi I believe this is still an issue for some components, right? And it would still be valuable to do this
