### ISSUE TITLE
Remove tensorboard manifest and from KFDef

### ISSUE THREAD

**Issue by Snapple49** [kubeflow/manifests#415]
Hi!

Was poking around in the generated kubeflow installation based on the `kfctl_k8s_istio.yaml` manifest, which, in the version I have, by default contains a Tensorboard deployment. When I asked about it @jlewi pointed out that it should not be there by default and asked me to post an issue about it. I can't find a version number for it, I don't remember what version of kfctl I was using at the time but I downloaded the kfctl manifest at least before September 14, 22:25 if that helps!

**Comment by jlewi** [comment]
We should remove tensorboard from our KFDef's
https://github.com/kubeflow/manifests/blob/67eabbfd907dbb212b2fa39baeddb3a4b7e9e743/kfdef/kfctl_gcp_iap.yaml#L193

And remove the corresponding manifest
https://github.com/kubeflow/manifests/tree/master/tensorboard

This is just causing confusion. All its doing is deploying a single instance of tensorboard. This is harmless but useless and confusing.

If people want to run tensorboard the correct thing to do would be for them to create a Deployment and VirtualService. There's not much point to us providing a kustomize manifest for this.

At best we should publish an example YAML file containing the resources (e.g. in the docs).

**Comment by Jeffwan** [comment]
@jlewi I can help on this. BTW, do we want  `tensorboard-controller` ? I think that is helpful

**Comment by jlewi** [comment]
Thanks @Jeffwan 

I think the tensorboard controller is still a prototype.

kubeflow/kubeflow#3578 is tracking building a web app to manage tensorboard instances. Creating a manifest to deploy the tensorboard-controller would probably be a part of that work; assuming the web app ended up using the controller.

/assign @Jeffwan

**Comment by Jeffwan** [comment]
@jlewi Get it. I will file a PR to remove tensorboard in kfdef
