### ISSUE TITLE
kubeflow/manifests @ master is broken - uber issue

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#426]
Master of kubeflow/manifests appears to be broken.

There appear to be three known issues

1. #420 and #425 are breaking the ISTIO and knative install
1. #342 pinned kubeflow/manifests in kfctl to some presubmits

At issue appears to be some very large PRs #342 and #410 that touched a number of different components.

**Comment by kunmingg** [comment]
We can 
1. set test config to 
```
uri: https://github.com/kubeflow/manifests/archive/3e85b3c83de12fed7d675151d0d4f8474eb04790.tar.gz
```
2. revert broken PRs.

**Comment by jlewi** [comment]
I think we need to roll back all PRs on kubeflow/manifests 1 by 1 so that we roll back master to 
3e85b3c83de12fed7d675151d0d4f8474eb04790.

**Comment by jlewi** [comment]
I suspect that one reason the presubmits didn't catch the breaks to ISTIO is we don't run the test_endpoint test are part of our presubmits.

**Comment by jlewi** [comment]
I manually deployed using 
https://github.com/kubeflow/manifests/pull/429

I hit https://github.com/kubeflow/kfserving/issues/399 but when I retried kfctl apply it succeeded.

I'm still waiting for my endpoint to be ready but otherwise everything looks good.

**Comment by jlewi** [comment]
#429 is merged. 

Here's the follow on work

* Roll forward #424 metadata fix
* Roll forward #401 update jupyter images

Not sure what to do about the 3 other massive PRs

* #342 app instance
* #410 first pass remaining applications
* #405 missing images to kustomization

#405 was probably not the culprit but #342 and #410 were probably causing problems. 

Should we improve the testing before rolling those forward

* Enable test_endpoint to try to ensure ISTIO install is working
* Fix #306 so its easier to manually verify what the expected output of the kustomization is

**Comment by jlewi** [comment]
@yanniszark @neuromage @Tabrizian FYI that your PRs were at least temporarily rolled back see above.

**Comment by yanniszark** [comment]
@jlewi I have #444 made to revert #405.

**Comment by jlewi** [comment]
I'm going to close this issue.

* Master has been fixed
* All the PRs that should be rolled forward either have been rolled forward or are out for review
* @kkasravi is working on revising his PRs to define Application resources for all apps and will break it up into smaller PRs.
