### ISSUE TITLE
Restructure istio/ambassador as overlays

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#51]
Move both the Service and VirtualService under overlays

Theses overlays will be included based on the useIstio flag in ‘kfctl init ...’

**Comment by gabrielwen** [comment]
no, I don't think we need to do this.  Discussed with @lluunn before I started adding VirtualService manifests, we assume that we don't need `useIstio` flag after we migrate to kustomize.  That is, our assumption is we will fully migrate to ISTIO in v0.6

**Comment by kkasravi** [comment]
ok i can close this unless we want to isolate the service layer in this way

**Comment by jlewi** [comment]
I agree with @gabrielwen

**Comment by kkasravi** [comment]
ok, thanks. I'll close.
