### ISSUE TITLE
upgrade all application instance labels to v0.7.0

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#524]
$ ☞  vgrep 'v0.6'|grep -v tests
admission-webhook/webhook/overlays/application/kustomization.yaml
admission-webhook/webhook/overlays/application/application.yaml
admission-webhook/bootstrap/overlays/application/kustomization.yaml
admission-webhook/bootstrap/overlays/application/application.yaml
application/application/overlays/application/kustomization.yaml
application/application/overlays/application/application.yaml
aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
aws/aws-alb-ingress-controller/overlays/application/application.yaml
jupyter/jupyter-web-app/overlays/application/kustomization.yaml
jupyter/jupyter-web-app/overlays/application/application.yaml
jupyter/notebook-controller/overlays/application/kustomization.yaml
jupyter/notebook-controller/overlays/application/application.yaml
mxnet-job/mxnet-operator/overlays/application/kustomization.yaml
mxnet-job/mxnet-operator/overlays/application/application.yaml
pytorch-job/pytorch-operator/base/deployment.yaml
pytorch-job/pytorch-operator/base/kustomization.yaml
seldon/seldon-core-operator/overlays/application/kustomization.yaml
spark/spark-operator/overlays/application/kustomization.yaml
spark/spark-operator/overlays/application/application.yaml
tektoncd/tektoncd-install/overlays/application/kustomization.yaml
tektoncd/tektoncd-dashboard/overlays/application/kustomization.yaml

**Comment by richardsliu** [comment]
Can we put this in a 1-line script?

**Comment by kkasravi** [comment]
yep
