### ISSUE TITLE
add "ZONE" to kfctl_gcp_iap.yaml and kfctl_gcp_basic_auth.yaml

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#544]
User should be able to specify target Zone by editing config file

**Comment by gabrielwen** [comment]
it's in `KfGcpPlugin`?

**Comment by kunmingg** [comment]
Can user specify zone by editing config file?

**Comment by gabrielwen** [comment]
yea they just need to put it in `KfPluginSpec.Zone`: https://github.com/kubeflow/kubeflow/blob/e60ee44ca13820fd256e16f4d717cb82f47f52df/bootstrap/pkg/kfapp/gcp/gcp_plugin.go#L30

**Comment by gabrielwen** [comment]
added a comment for zone.
