### ISSUE TITLE
[GCP] iap-enabler won't pick up changes to the backend id in JWT policy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#561]
IAP enabler script will not pick up changes to the backend id.
https://github.com/kubeflow/manifests/blob/973fba5a2012e7c9e305092727b2da446a2b6b81/gcp/iap-ingress/base/config-map.yaml#L92

We don't reset backend id and backend name each time through the loop so if backend id or backend changes it won't get picked.

The behavior was recently changed #551 to periodically check and update the value

Related to  kubeflow/kubeflow#4342

**Comment by lluunn** [comment]
weird, after my 2nd apply, I got origin authentication failed (which is expected).
But after a while it's back and working.

**Comment by lluunn** [comment]
I checked the pod logs, the backend id never changes.
Not sure why I got origin authentication failed.
