### ISSUE TITLE
istio, dex: make ingress service types configurable

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#566]
For Services that are intended to be exposed (eg istio-ingressgateway, dex) we should have some kind of parameter/overlay to customize them.
Some users work in restrictive environments (eg healthcare https://github.com/kubeflow/kubeflow/issues/4348) and might want to only work through port-forward.

Some other users may want to use a LoadBalancer to expose those Services.

**Comment by krishnadurai** [comment]
area/auth

**Comment by yanniszark** [comment]
/reopen
kpt setters may be a good fit for this issue (vs kustomize overlays).
