### ISSUE TITLE
extend the test harness to incorporate parameters and negative testing

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#57]
currently the test harness is a pending PR #50 that generates golang test cases which compare the concatenation of all resources with the output of `kustomize build`.  This has a few limitations:

- [ ] the parameters most targets take should be passed into the target
- [ ] the other parts of the kustomization file: vars, configMapGenerator, patchesStrategicMerge, patchesJson6902 shouldn't be ignored as be the basis of additional tests
- [ ] negative testing should be done

**Comment by kkasravi** [comment]
steps Ebi and I will collaborate on

- [ ] checkout PR #50 
- [ ] cd tests
- [ ] run make
- [ ] fix any recently merged breakages 
- [ ] convert scripts under hack: gen-test-target,gen-test-targets,utils to golang in #50
- [ ] create a plugin entry point
- [ ] add parameters and other things in kustomization.yaml like vars, createConfigMapGenerator, patchesJson6902 and make tests for them

**Comment by ashahba** [comment]
- [ ] setup prow for gating the repo when new manifests are added or existing ones are modified

**Comment by ashahba** [comment]
+ @hougangliu

**Comment by hougangliu** [comment]
once https://github.com/kubernetes/test-infra/pull/12579 merged, I will create PR from [this branch](https://github.com/hougangliu/manifests/tree/prow-setup) to enable prow.
