### ISSUE TITLE
metadata: grpc server deployment uses apps/v1beta2 which breaks K8s 1.16

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#585]
In the metadata package, the grpc server Deployment uses the `apps/v1beta2` API Group which was retired in K8s 1.16.
https://github.com/kubeflow/manifests/blob/ded8022544963b53d7d68ced02982350c392d650/metadata/base/metadata-envoy-deployment.yaml#L1

User bumping into the issue:
https://kubeflow.slack.com/archives/C7REE0EHK/p1571994295197200

/cc @zhenghuiwang @jlewi 

Would be nice to get this in v0.7.

**Comment by saschagrunert** [comment]
Yeah there are multiple manifests which still have `apps/v1beta2`, this should be fixed.
