### ISSUE TITLE
Presubmits failing No module named testing.tf_job_simple_test

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#595]
```
Test failing with: /usr/bin/python: No module named testing.tf_job_simple_test
```

This code was remove in kubeflow/kubeflow#4437 because it was failing and no longer relevant.

The E2E tests in kubeflow/manifests are depending on the kfctl E2E tests but they depend on the code being duplicated rather than importing it so the workflow in kubeflow/manifests is now out of date.

The long term solution here is to

* Move to using Argo as opposed to ksonnet for the tests 
* import the kfctl_e2e_workflow from the repo where it is defined so it stays in sync

**Comment by jlewi** [comment]
We will need to cherry pick the fix onto the v0.7-branch

**Comment by jlewi** [comment]
#598 cherry picks into the release branch.

**Comment by krishnadurai** [comment]
Thanks for filing this @jlewi, I've lgtm-ed the release branch PR.

**Comment by jlewi** [comment]
This is fixed.
