### ISSUE TITLE
oidc-authservice deployment strategy should be recreate

### ISSUE THREAD

**Issue by devgrok** [kubeflow/manifests#636]
oidc-authservice's deployment strategy needs to be Recreate, as changes to the Deployment that trigger a rolling up get blocked by the persistent volume claim.
The mysql Deployment uses the same strategy.
This may just be limited to AWS with EBS.

**Comment by yanniszark** [comment]
@devgrok this interesting, that's the first time I bump into this.
I have made changes that require rolling updates many times and it has worked (eg change the image).
I deploy on GKE and use Persistent Disk volumes, so similar to EBS.
Could you give more info on the error you're getting?

**Comment by jlewi** [comment]
@yanniszark Could you triage this issue please?
https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md

**Comment by yanniszark** [comment]
/priority p2
/kind bug
/platform aws

Generally, more information is needed at this point.
/cc @Jeffwan who could provide some more info.

**Comment by devgrok** [comment]
I added some detail on how to reproduce it and the output here:
https://github.com/kubeflow/manifests/pull/637#issuecomment-562443714

**Comment by devgrok** [comment]
FYI: the kubernetes docs have section covering [Run a Single-Instance Stateful Application](https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#updating)
So `strategy: type: Recreate` is the recommended approach.
