### ISSUE TITLE
istio: document procedure that generated the manifests

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#644]
Since Istio comes with many available options, it's important to document which were used during generation of the istio we use in manifests.

@krishnadurai can you provide more info on the procedure you followed for the istio 1.3.1 package?
What is the source?
What arguments were used in helm?

/cc @jlewi @kkasravi @apyrgio

**Comment by krishnadurai** [comment]
@yanniszark glad that bring this up. I'll look to soon document how I generated the manifests. Overall, I used the helm charts being maintained at [istio/istio](https://github.com/istio/istio/tree/master/install/kubernetes/helm).
Using kustomize converter - https://github.com/ContainerSolutions/helm-convert - I was able to get these manifests converted to Kustomize manifests and later had to combine resources together manually.

Here are the commands for helm conversion which I used:

```
helm convert --destination <destination> --name istio --namespace "\$(namespace)" install/kubernetes/helm/istio --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml
```

```
helm convert --destination istio_init_kustomize --name istio install/kubernetes/helm/istio-init  --values install/kubernetes/helm/istio-init/values.yaml
```

Refer PR: kubeflow/manifests#413

**Comment by yanniszark** [comment]
@krishnadurai it would be great if we could write that down in a doc.
In addition, I think it's better to refrain from doing manual work, since we want to be able to try different options and easily view the diffs with git to see what has changed.

I'm also a bit sceptical about `helm convert`.
I'm worried that it could introduce bugs.

I believe it would be better to just store the yaml blob that helm outputs.
This way, diffs are easy and we don't risk bugs getting introduced in the helm<->kustomize conversion.
What do you think?

/cc @jlewi

**Comment by xaniasd** [comment]
please keep in mind that helm charts will be deprecated in the future (see [here](https://istio.io/docs/setup/install/helm/)). recommended way is to dump the manifests with `istioctl manifest generate`
