### ISSUE TITLE
HTTPS for AWS ingress without auth

### ISSUE THREAD

**Issue by devgrok** [kubeflow/manifests#652]
Create overlay for the **aws-alb-ingress-controller** allowing the Load Balancer to be created with HTTPS with it performing no auth. 

This is one set of changes to switch from using cognito on the ALB to using the oidc-authservice because in the current setup the users come through without any identity (anonymous). 
See https://github.com/devgrok/kubeflow-manifests/blob/aws-istio-oidc-cognito/kfdef/kfctl_aws_cognito.yaml for the desired final result.

**Comment by jlewi** [comment]
@Jeffwan could you triage this issue please?
https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md

**Comment by Jeffwan** [comment]
@jlewi  Yeah. This should be a feature request and I saw @devgrok already file a PR. I will help review it

**Comment by nrchakradhar** [comment]
@devgrok @Jeffwan Can you please help understand the usage of AWS-ALB-ingress controller along with Istio. What is the functional separation these two are providing. I assume that Istio is not completely bypassed by this configuration.

**Comment by Jeffwan** [comment]
@nrchakradhar  alb-ingress-controller is used to manage external traffic and expose more features like authentication on LB level. Technically, this is unnecessary and user and use some other authentication solutions like dex (software level) to manage access. To AWS, we'd like to use this because ALB is more powerful and reliable

**Comment by nrchakradhar** [comment]
@Jeffwan Thanks for sharing this information.

**Comment by devgrok** [comment]
To expand on what @Jeffwan said:
The AWS-ALB-ingress creates an Application Load Balancer (ELB v2) that at the basic level provides what  K8s Service ClusterIP --> load balancing between the running instances.

It definitely doesn't skip istio - the configuration points all the traffic at the IngressGateway service
The kubeflow's aws-alb-ingress is just set to forward the traffic to the istio-ingressgateway's service NodePort.
So it's an extra layer in front that can 
* perform load balancing (when configured with `target-type=ip``) by directing traffic to the individual running pods.
* allows for CIDR filtering (security groups) to be applied on that port 
* along with "AWS Shield" protection against DDOs and the like
* handling of publically issued certificates private secrets securely and off-loading the compute of TLS
* can do the Cognito or other OIDC authorization flow
  (which is implemented in an odd way, using 2 issuers and a non-standard way of verifying the 2nd issuers key --> see some of my PR's around the issue)

But the point of this issue was to provision a AWS ALB  (load balancer) with HTTPS (default is without). 
Then, if wanted, let authentication be performed by another component in kubeflow (dex or oidc-authenicator).
Ideally the change in the PR https://github.com/kubeflow/manifests/pull/653 would just be a base layer for the other 2 layers, as most of the changes are common. 
(however I couldn't see how to easily generate the test cases to show that).

**Comment by nrchakradhar** [comment]
Thanks @devgrok

**Comment by devgrok** [comment]
That manifest (`Kind: Ingress`) provides configuration for the aws-alb-ingress-controller, which creates resources in AWS with little or no modifications to the kubernetes resources.
It creates an Application Load Balancer, Target Group, Security Groups and registers the EC2 instances with the Target Group by instance-id and port (the NodePort).

The NodePort it refers to is already existing and configured in isitio (`istio-ingressgateway`)
https://github.com/kubeflow/manifests/blob/v1.0-branch/istio/istio-install/base/istio-noauth.yaml#L14047
