### ISSUE TITLE
jupyter-web-app: Add permissions for SubjectAccessReviews

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#654]
Context [kubeflow/2981](https://github.com/kubeflow/kubeflow/issues/2981). We want Jupyter Web App to use k8s `SubjectAccessReviews` for enforcing authorization.

For this we will need to give JWA's ServiceAccount permissions to create `SubjectAccessReviews`.

/assign kimwnasptd
cc @yanniszark @jlewi

**Comment by jlewi** [comment]
@kimwnasptd Could you please triage this issue?

**Comment by kimwnasptd** [comment]
@jlewi I currently don't have permissions to add labels. I'll let @cspavlou add the labels for now and I'll also create a PR to add myself to the maintainers in order to be able to triage future issues.

Chris the labels for this one are: `enhancement`, `p1`, `area/jupyter`

**Comment by jlewi** [comment]
@kimwnasptd you should not need to be a member of the maintainers group to add labels. You can use  the prow chat bot commands to add labels. 

https://prow.k8s.io/command-help

**Comment by kimwnasptd** [comment]
I was under the impression that I had to be in the `project-maintainers` to add labels and completely missed the prow way. Will use prow for the labels from now on.
