### ISSUE TITLE
Remove Ambassador annotations from Jupyter web app

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#670]
We can get rid of the Ambassador annotations on the jupyter web app
https://github.com/kubeflow/manifests/blob/67eabbfd907dbb212b2fa39baeddb3a4b7e9e743/jupyter/jupyter-web-app/base/service.yaml#L5

because we no longer use Ambassador to route traffic.

Ref: kubeflow/kubeflow#3833

**Comment by jlewi** [comment]
@kimwnasptd could you take care of this?

I think we want to get this done before 1.0 just to prevent anyone from depending on Ambssador.

**Comment by kimwnasptd** [comment]
Yes, I'll make a PR for this one to remove it.
/assign kimwnasptd
