### ISSUE TITLE
KFDef for openshift

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#686]
We would like a KFDef and kfctl compatible install process for openshift.

@vpavlin has a WIP PR: opendatahub-io/manifests#4

Related: @animeshsingh 's doc about a kubeflow operator http://bit.ly/kubeflow-operator

/cc @animeshsingh @pdmack

**Comment by animeshsingh** [comment]
/assign @vpavlin 

Any chance we can PR this back to KF master itself? Would it need to be on OpenDataHub fork?

**Comment by vpavlin** [comment]
@animeshsingh Yes, we definitely will contribute it back, but we are basing it on 0.7.0 to make sure things are not changing under our hands and when we are happy with it, we will contribute it back upstream and rebase it also on/for master. After that we will continue any other development upstream
