### ISSUE TITLE
Host manifests release on public read-only GCS

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#701]
Currently manifests are fetched through `https://github.com/kubeflow/manifests/archive/master.tar.gz`
It caused problems like: https://github.com/kubeflow/kfctl/issues/167

Switch to GCS might improve manifests availability.

Besides that GCS will also unblock user from private VPC network.

**Comment by krishnadurai** [comment]
Thanks @kunmingg for filing this. We should look to support:

1. GCS based manifests archives for versioned releases.
1. GitHub archives for pulling from master or other branches.
