### ISSUE TITLE
Unpin GKE from 1.14.8 once a fix for workload identity is released

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#757]
Follow on to kubeflow/kubeflow#4693 GKE has a bug in the latest version of GKE so we are pinning
to 1.14.8.

We will need to revert these changes once a fixed version of GKE is released otherwise we will get
broken when 1.14.8 is no  longer available.

Here's a link to the release notes
https://cloud.google.com/kubernetes-engine/docs/release-notes#january_24_2020

PRs that we need to revert: #741 

We will want to unpin the branches

* 0.7
* 1.0
* master

**Comment by jlewi** [comment]
@kunmingg lets verify #882 on master before cherry-picking onto 1.0 branch. Lets try to leave the cluster up for a while to ensure we don't have problems when it has been running for a while.

**Comment by jlewi** [comment]
@kunmingg any luck verifying this?

**Comment by jlewi** [comment]
@gabrielwen could we use our notebook xgboost_synthetic test to verify that this is working?
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

* Does the notebook E2E test depend on workload identity or is it using some other form of auth?

   * I think its using workload identity https://github.com/kubeflow/examples/blob/master/xgboost_synthetic/testing/job.yaml but lets verify

* Do we trust the signal in our dashboard?
   * Lets verify green means the notebook ran successfully and it ran on a recent master cluster

**Comment by gabrielwen** [comment]
@jlewi 
turns out periodic test points to auto-deployed cluster that is not the latest.  The most recent test was run on `kf-master-0212-921` which points to the `907d9dc` where the most recent deployed cluster should be `kf-master-0212-8de `, which uses the latest commit of `9eeab3e`

could you point me to the codes for the new auto-deployment service?  it seems to be a whole lot different than I remember.

**Comment by jlewi** [comment]
@gabrielwen Could it be that when the latest run ran against kf-master-0212-921 that was the correct cluster? i.e. did the cluster kf-master-0212-8de exist it? Was it ready?

More than 1 auto-deployed cluster can exist at a time. In particular, we won't tear down an existing cluster, until a newer cluster has been created, and we have allowed enough time to pass O(hours) to assume that all tests have switched to the newer cluster.

Did the notebook run successfully against kf-master-0212-921?

I think we need to modify how we run papermill so we can grab the output notebook so we can inspect it to convince ourselves that everything ran correctly

**Comment by gabrielwen** [comment]
The notebook ran successfully against kf-master-0212-921, but I think we need to stop using cluster name in selection:
https://github.com/kubeflow/testing/issues/608

**Comment by jlewi** [comment]
@gabrielwen Thanks; my concern is that the test might be swallowing errors; e.g. there are errors but its not being reported. So what I'd like to do is get the output notebook and be able to manually view it; just to verify it.

I believe papermill writes the output to an .ipynb file.

So we just need to grab that file off pod volume. There's two ways we could do this

1. papermill supports gcs so we might be able to just write to GCS
1. we could have papermill output to local storage and then upload to GCS
   * We might want to do this anyway so that we can run nbconvert to convert it to html.

**Comment by gabrielwen** [comment]
kk, will take a look at papermill.

- turns out we are not selecting by deployment names.  We are actually using insertTime so I think it should be fine.  Let me double check it when we have more than 1 clusters at the same time.
- we are swallowing failures during presubmit, so the failures will still show up in periodic tests:
https://github.com/kubeflow/examples/blob/e91e9c0df3126d1adde625614cb35eaf0e0bd03b/xgboost_synthetic/testing/xgboost_test.py#L18

**Comment by jlewi** [comment]
I did a spot check of a master cluster

Cluster had been up for 4 hours.
and was running 1.14.10-gke.22

```
gcloud config list
[core]
account = kf-master-0214-58e-user@kubeflow-ci-deployment.iam.gserviceaccount.com
disable_usage_reporting = True
project = kubeflow-ci-deployment

Your active configuration is: [default]
```

So it looked good.

#735 also gives me confidence we can trust the tests. 

So lets go ahead and cherry-pick it.

**Comment by jlewi** [comment]
@kunmingg cherry pick is #912

**Comment by jlewi** [comment]
#912 is merged.
