### ISSUE TITLE
Presubmit tests for KFam and Profile controller are failing blocking update on 1.0 branch

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#773]
Here are two PRs updating the profile controller and kfam API on the 1.0-branch to the latest images.

#762 
#769 

The tests are failing for these images. A whole bunch of other PRs were merged so I think it maybe specific to these applications.

This is blocking the 1.0 RC kubeflow/kubeflow#4685

@kunmingg Could you please investigate whether this is a test flake or actual bug?

/assign @kunmingg

**Comment by kunmingg** [comment]
fix merged
