### ISSUE TITLE
Update KF pipelines for the KF 1.0 release

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#796]
The kustomize package for pipelines hasn't been updated since November
https://github.com/kubeflow/manifests/tree/master/pipeline

What version of pipelines should we ship with KF 1.0

/cc @Bobgy

**Comment by Bobgy** [comment]
@jlewi Can you share detailed timeline? If we would like to update, how long can you wait for this?

Considering some recent requests to use latest KFP in KF. I think this is important to do.

**Comment by Bobgy** [comment]
@jlewi A quick question: will `user-gcp-sa` still be available in KF 1.0? That will affect how much work we need to do?

**Comment by jlewi** [comment]
@Bobgy we are trying to cut by the end of this week.  The behavior of secrets hasn't changed with respect to 0.7

**Comment by jlewi** [comment]
@Bobgy I sent you kubeflow/manifests#802 to update master. I would suggest getting that checked in to make it easy to begin testing the latest release to see what problems we hit.

**Comment by jlewi** [comment]
The 0.2.0 images have been merged onto master.

Looks like the APP CR still needs to be updated.

```
        app: ml-pipeline
        app.kubernetes.io/component: api-service
        app.kubernetes.io/instance: api-service-0.1.31
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: api-service
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.1.31

```

**Comment by jlewi** [comment]
I did a quick smoke test of pipelines 0.2.0 on master and everything looked good so I'm going to go ahead and cherry pick it on the 1.0 branch.

**Comment by jlewi** [comment]
This has been merged to the 1.0 branch.

We should still update the application resources.

**Comment by jlewi** [comment]
@Bobgy @richardsliu do we have some automation to update the version and instance tags? it looks like there are quite a few places that would need to be updated.

**Comment by Bobgy** [comment]
Not anything I know.

**Comment by richardsliu** [comment]
I use this script for the rest of the applications: https://github.com/kubeflow/manifests/blob/master/hack/update-instance-labels.sh

**Comment by jlewi** [comment]
Might be worth writing a quick python script that adds a little bit more control.

**Comment by Ark-kun** [comment]
JFYI: For successful deploymentof the Metadata Writer service, the name of the gRPC Metadata Service needs to be the same in KFP and KF. @elikatsis wanted to make a change for that.

**Comment by jlewi** [comment]
@Ark-kun and @elikatsis thanks. I don't consider that release blocking although I'd like to have that working. Lets open up a separate issue to track.

**Comment by jlewi** [comment]
Filed: kubeflow/manifests#897
