### ISSUE TITLE
Dex container to update in manifest

### ISSUE THREAD

**Issue by SebBlin** [kubeflow/manifests#800]
I'm using Dex authentication, with authentication delegated to another OIDC IDP.

In the configmaps of dex, I configured `getUserInfo: true` to make dex retrieve the claim 'name' but it fails with the message `Failed to authenticate: missing "name" claim`. 

The current installation of dex is pointing to the container gcr.io/arrikto/dexidp/dex:4bede5eb80822fc3a7fc9edca0ed2605cd339d17 (in the file dex-auth/dex-crd/base/kustomization.yaml); for which I was not able to retrieve the corresponding Dockerfile.
I made my own overlay to use `quay.io/dexidp/dex:v2.21.0` and it works perfectly.

Would it be possible to get some details about the reason why this specific container was used instead of the standard dex container ? Maybe I will face some issues I'm not aware of. :-(

Maybe it could be a good idea to switch back to the standard dex container.

**Comment by krishnadurai** [comment]
@SebBlin we will soon switch to the standard container. This was done at that time to include a feature we had to release in Dex. This feature was merged later into Dex's release.

**Comment by WillBeebe** [comment]
Hi @SebBlin , I'm looking at the quay.io dex repo and I don't see that tag.
https://quay.io/repository/coreos/dex?tab=tags

I also tried to pull it and no-dice.

```
docker pull quay.io/coreos/dex:v2.21.0
Error response from daemon: manifest for quay.io/coreos/dex:v2.21.0 not found: manifest unknown: manifest unknown
```

I see the dex repo has been active in the past two years...

**Comment by WillBeebe** [comment]
Doh, just figured it out. `s/dex/dexidp/`

https://github.com/dexidp/dex/releases

I'll open a PR.
