### ISSUE TITLE
Cert-manager causing test flakes due to deployment errors

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#806]
I'm noticing test flakes in presubmits deploying Kubeflow related to the cert-manager

```
util.py                     72 INFO     failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubef
low.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout933072035": Internal error occurred: failed calling webhoo
k "webhook.cert-manager.io": the server is currently unable to handle the request
```

The addition of cert-manager is recent: #717

/cc @cliveseldon

**Comment by jlewi** [comment]
Here's a link to a failed test
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_manifests/802/kubeflow-manifests-presubmit/1222524579784691712/

If its flaky in tests its presumably flaky for users.

I think we might want to avoid installing cert-manager by default on the 1.0 branch until we have this resolved.

@cliveseldon is cert-manager a requirement for Seldon?

**Comment by krishnadurai** [comment]
@jlewi This might happen due to the size of the test clusters. Can we check if these servers are able to deploy cert-manager pods in 'cert-manager' namespace within the test cluster?

**Comment by cliveseldon** [comment]
@jlewi @krishnadurai cert-manager is presently the production requirement for seldon and kfserving. To remove it we would need a way to inject certs into the webhooks used by seldon and kfserving. I believe there is a script that is part of kubeflow that could be used for this maybe? As @krishnadurai says can we do some checks to ensure it is cert-manager causing the issue?

I saw in local testing it took up to 60 secs for the kfctl apply to succeed. Is there any way that this would be different than using kustomize directly? Why is the webhook being called as part of the kustomize apply?

**Comment by cliveseldon** [comment]
@jlewi @krishnadurai Actually makes sense. As the seldon resources has a cert-manager Certificate resources which would cause the cert-manager webhook to be called. So obviously this would fail until cert-manager is running. 

Only solution I see is if cert-manager needs to be up and running before any cert-manager resources are applied.

As this is just a internal cert for a webhook maybe the best solution is some script that can be run to inject the certs?

**Comment by yuzisun** [comment]
@cliveseldon in kfserving e2e tests I had to sleep 2 minutes for cert manger to be ready before installing kfserving manifests.

**Comment by cliveseldon** [comment]
@jlewi Does kfdef/kfctl allow for certain manifest to be deployed and ready before others?

**Comment by krishnadurai** [comment]
@cliveseldon It generally follows the order declared in the KFDef, apart from applying LegacyOrderingTransform.

Refer: https://github.com/kubeflow/kfctl/issues/65

**Comment by cliveseldon** [comment]
Thanks @krishnadurai So if retries is the accepted behaviour as described in https://github.com/kubeflow/kfctl/issues/65 can we just increase the number of retries to allow for more exponential backoff?

**Comment by krishnadurai** [comment]
@cliveseldon I'm not sure if the reason for failure is the amount of waiting time required for deployment. An alternative reason for failure could be that the cert-manager pods don't have enough resources to be deployed in the cluster and are failing.

**Comment by cliveseldon** [comment]
@krishnadurai OK yes it would be good to test that hypothesis. But also note @yuzisun and my testing on time for cert-manager to become available.

**Comment by jlewi** [comment]
kfctl has backoff and retry logic
https://github.com/kubeflow/kfctl/blob/c5c55f6d1b79e285f28fa433d6e4e2e739cefb63/pkg/kfapp/kustomize/kustomize.go#L188

It looks like this should be retrying for 5 minutes
https://github.com/kubeflow/kfctl/blob/7a62e58ebf2d844391005d6bc51fc32ac2d5be2c/pkg/utils/k8utils.go#L75

So if it is simply a matter of waiting for the cert manager to become available hopefully that would take care of it.

It would be good to dig deeper to confirm whether backoff and retry is working as expected

**Comment by jlewi** [comment]
Here are the logs for the build deploy step

Note you need to ignore the leftmost timestamps; those are the timestamps which stackdriver applied when injesting the logs. I think pytest is buffering logs so those timestams are all messed up.

We do see retries though. It looks like the first error is.

```
2020-01-29T14:39:30.363112995Z  main            util.py                     72 INFO     validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
2020-01-29T14:39:30.363117215Z  main            util.py                     72 INFO     time="2020-01-29T14:34:06Z" level=warning msg="Encountered error during apply:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating \"/tmp/kout176440889\": Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": the server could not find the requested resource" filename="kustomize/kustomize.go:193"
2020-01-29T14:39:30.363122316Z  main            util.py                     72 INFO     time="2020-01-29T14:34:06Z" level=warning msg="Will retry in 3 seconds." filename="kustomize/kustomize.go:194"
```

The inner time stamp which we can trust is that this is happening at 14:34.

The second to last retry is at 

```
2020-01-29T14:39:30.365061509Z  main            util.py                     72 INFO     time="2020-01-29T14:38:55Z" level=warning msg="Encountered error during apply:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating \"/tmp/kout552906272\": Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": the server is currently unable to handle the request" filename="kustomize/kustomize.go:193"
2020-01-29T14:39:30.365068282Z  main            util.py                     72 INFO     time="2020-01-29T14:38:55Z" level=warning msg="Will retry in 31 seconds." filename="kustomize/kustomize.go:194"
```

So 14:38. 

So it looks like are retrying as expected for 5 minutes.

[kubeflow-manifests-presubmit-kfctl-go-iap-802-6060ebb-1712-7637-3960450054.log.txt](https://github.com/kubeflow/manifests/files/4136896/kubeflow-manifests-presubmit-kfctl-go-iap-802-6060ebb-1712-7637-3960450054.log.txt)

**Comment by jlewi** [comment]
I looked at the event logs. The pod for the certmanager webhook is 
cert-manager-webhook-7bd54f5d57-j5xhg

Here are the event logs for that pod
[webhook.event.logs.csv.txt](https://github.com/kubeflow/manifests/files/4137417/webhook.event.logs.csv.txt)

The container restarted once but after that it looks like it started and was fine.

Here are the pod logs
[cert-manager-webhook-7bd54f5d57-j5xhg.log.txt](https://github.com/kubeflow/manifests/files/4137427/cert-manager-webhook-7bd54f5d57-j5xhg.log.txt)

It looks like its complaining about some flags.

**Comment by jlewi** [comment]
Looks like the deployment is defined here.
https://github.com/kubeflow/manifests/blob/7d36e486210eeec8504d67cb1b1855c1ffc9bd35/cert-manager/cert-manager/base/deployment.yaml#L101

**Comment by jlewi** [comment]
Here are the logs from a healthy certmanager-webhook

```
kubectl -n cert-manager logs cert-manager-webhook-755d75845c-cwclr
flag provided but not defined: -v
Usage of tls:
  -tls-cert-file string
    	
I0131 00:09:12.883314       1 secure_serving.go:123] Serving securely on [::]:6443
I0131 00:09:13.839993       1 mutation.go:120] cert-manager "level"=0 "msg"="generated patch"  "patch"="[{\"op\":\"add\",\"path\":\"/status\",\"value\":{}}]"
```

**Comment by cliveseldon** [comment]
Source issue: https://github.com/jetstack/cert-manager/issues/2537

**Comment by jlewi** [comment]
@cliveseldon Do you know what resource is triggering the call to the "webhook.cert-manager.io"?

Is deploying the cert-manager itself triggering calls to its own webhook? That seems like it
would be a circular dependency.

It looks like kfctl lacks some helpful logging that would make it clear what application was being
deployed when the error occurred.
https://github.com/kubeflow/kfctl/blob/c5c55f6d1b79e285f28fa433d6e4e2e739cefb63/pkg/kfapp/kustomize/kustomize.go#L171


I see a couple potential fixes

1. We could increase the timeout in kfctl
1. We could tell users to just manually rerun kfctl after waiting for the cert-manager to become available
1. We could catch and ignore the error

     i) We could ignore all errors for certain applications
    ii) We could ignore errors due to calling "webhook.cert-manager.io" 

I think I lean towards the latter option.

**Comment by jlewi** [comment]
Actually I don't think we can ignore the errors. My assumption is that these errors are triggered by validating or admission webhooks. So the resources (probably certificates) wouldn't be created in this case. As a result if we ignore the errors the application would end up in a corrupt state.

I sent out kubeflow/kfctl#211 to bump the timeout and improve logging.

**Comment by jlewi** [comment]
Here are the logs from a deploy using kubeflow/kfctl#211 which has improved logging
[kubeflow-kfctl-presubmit-kfctl-go-iap-211-5f27b3e-7488-1cc0-1476697611.log.txt](https://github.com/kubeflow/manifests/files/4145705/kubeflow-kfctl-presubmit-kfctl-go-iap-211-5f27b3e-7488-1cc0-1476697611.log.txt)

The logs show that the webhook error occurs deploying the cert-manager application.

```
2020-02-02T20:13:52.026722662Z  main            util.py                     72 INFO     validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
2020-02-02T20:13:52.027101992Z  main            util.py                     72 INFO     time="2020-02-02T20:13:52Z" level=warning msg="Encountered error appling application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating \"/tmp/kout347187808\": Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": the server is currently unable to handle the request" filename="kustomize/kustomize.go:202"
2020-02-02T20:13:52.027206322Z  main            util.py                     72 INFO     time="2020-02-02T20:13:52Z" level=warning msg="Will retry in 5 seconds." filename="kustomize/
```

Should deploying the cert-manager be triggering its own webhook?

**Comment by jlewi** [comment]
It looks like the cert-manager has a ClusterIssuer for Kubeflow
https://github.com/kubeflow/manifests/blob/d4354a01a1edf122d4e3633cc9c2ae727a42ff12/cert-manager/cert-manager/overlays/self-signed/cluster-issuer.yaml

So I suspect this is triggering the webhooks for the issuers and that's why it fails if the webhooks aren't ready.

Should we make the Kubeflow ClusterIssuer its own kustomize package? That would give us a lit be more flexibility in terms of when we deploy it to increase the likelihood that cert manager is available.

/cc @krishnadurai

**Comment by krishnadurai** [comment]
@jlewi  That's an alternative, though when would we deploy the ClusterIssuer. Would we look to have a job to monitor when the webhook is ready?
Another alternative is to disable the webhook until this issue is resolved in cert-manager (possibly 0.14 release).

**Comment by jlewi** [comment]
@krishnadurai What are the webhooks for? Are they just validating webhooks? I assume if we disable them we increase the likelihood that people submit invalid CertManager resources?

A longer term solution might be kfctl reconcile semantics kubeflow/kfctl#214. Right now the way retry's work is that we keep retrying an application until it succeeds or we timeout.

With kubeflow/kfctl#214 idealy if an application fails, we would keep going with the remaining applications and then rerun apply. This would prevent us from blocking other applications.

@krishnadurai Assuming increasing the timeout works, I think I favor that approach as opposed to disabling the webhooks altogether.

IME submitting invalid CR's can be a very frustrating experience. So I think its worth trying to deploy the webhoos to prevent invalid input.

**Comment by cliveseldon** [comment]
Seldon has MutatingWebhooks which are needed at present for proper functioning. I'd second a solution that keeps webhooks.

**Comment by krishnadurai** [comment]
@jlewi There are two webhooks:

1. Validating Webhook, which validates the cert-manager resources
1. Mutating Webhook, which injects CAs into cert-manager resources. This would have to be done through other automation.

Since we have several components which might use Mutating Webhooks, we will have to retain it.

Let us see if increasing the timeouts work.

**Comment by jlewi** [comment]
I'm going to mark this as fixed.

The increased timeout should be in the latest kfctl RC.
https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.3

I think the longer term fix is to implement reconcile semantics kubeflow/kfctl#214 so that we don't block creation of other resources while waiting for the cert-manager to become available.

**Comment by swiftdiaries** [comment]
Tried out the new RC and it comes up just fine, thanks for the quick fix !

**Comment by jlewi** [comment]
Duplicate of #543

**Comment by amygdala** [comment]
I just hit this, doesn't seem like it's fixed. I'm using `CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml` & the `kfctl` for https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.4 (which is `kfctl v1.0-rc.3-1-g24b60e8`)
