### ISSUE TITLE
Seldon Manifests _only_ support kubernetes 1.15

### ISSUE THREAD

**Issue by WillBeebe** [kubeflow/manifests#832]
The last Seldon operator [manifests](https://github.com/kubeflow/manifests/blob/c4f51b1cc0b4854b6f6180d5a3bb021dd65691a8/seldon/seldon-core-operator/base/resources.yaml#L3522) only support Kubernetes 1.15.

API reference [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector)

The error you'd see trying to apply these on older kubernetes versions is:

```
unable to find api field in struct Webhook for the json field "objectSelector", 
```

**Comment by jlewi** [comment]
We will want to cherry-pick #833 into the Kubeflow 1.0 branch.

**Comment by jlewi** [comment]
Here's the seldon mutating webhook from
https://github.com/kubeflow/manifests/tree/32aba35

The namespace selector is set and there is no object selector

[seldon-mutating-webhook-configuration-kubeflow.yaml.txt](https://github.com/kubeflow/manifests/files/4156822/seldon-mutating-webhook-configuration-kubeflow.yaml.txt)
