### ISSUE TITLE
spark-operator contains a default SA but no default CRB and CR

### ISSUE THREAD

**Issue by jamesthegiantpeach** [kubeflow/manifests#852]
AFAIK the spark-operator manifests base has spark-sa for SparkApplications to use, but it doesn't have any default bindings or roles. 

Should these be added? IMO a reasonable clusterrole should be default such that sparkapplications can be immediately applied if using the default spark-sa.

**Comment by Jeffwan** [comment]
I can help on this issue. It should.
/cc @Jeffwan

**Comment by holdenk** [comment]
This PR is maybe related - https://github.com/kubeflow/manifests/pull/661/files ?

**Comment by jamesthegiantpeach** [comment]
@holdenk ya thanks looks like someone just needs to merge that PR.
