### ISSUE TITLE
oidc-authservice: parameterize auth scopes

### ISSUE THREAD

**Issue by devgrok** [kubeflow/manifests#861]
Some oidc providers don't support the `groups` scope, allow the requested auth scope to be changed.

For example AWS Cognito Identity Pool doesn't define it as a scope, see [Cognito: Allowed OAuth Scopes](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html).
Instead it sends it via `cognito:groups` in the [Access Tokens](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#user-pool-access-token-payload) - which is a different annoying issue.

**Comment by yanniszark** [comment]
Hi @devgrok, can you elaborate a bit on why you need the `groups` scope?
Currently, the oidc-authservice doesn't have any group integration.
The oidc-authservice only adds a header for the user id, which it retrieves from a claim in the OIDC JWT.
The user id claim can be configured.

**Comment by devgrok** [comment]
I was just defaulting to what was there to try and minimise the change.

In theory just `email` should be enough from what i can see from https://github.com/arrikto/oidc-authservice/tree/master -- from memory i can't remember seeing any OIDC providers requiring scope=profile to access email, though I've got a vague memory of seeing it for another attribute.
@ChanYiLin @yanniszark should be able to confirm.

There's merit it allowing it to be configurable (another application/filter might want to decode the JWT) but the minimal scope as a default is a good idea. 
Happy to change it to what people think is the most sensible.

**Comment by yanniszark** [comment]
@devgrok I think I now understand what you mean.
The OIDC scopes are configurable with the OIDC_SCOPES envvar (see: https://github.com/kubeflow/manifests/blob/b3f5b41780a01845619884e638f4f6c9183d8fef/istio/oidc-authservice/base/statefulset.yaml#L36-L37)
We don't currently expose that as a var right now unfortunately :/
You can define your own overlay to patch it or expose it as a var in base.
