### ISSUE TITLE
GCP and AWS Change ingress resources to networking.k8s.io/v1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#869]
See: https://github.com/kubeflow/kubeflow/issues/4680

https://github.com/kubeflow/manifests/blob/830e1a0c87befdaec217564efb2b06ddc02a0cd6/gcp/iap-ingress/base/ingress.yaml#L1

Need to upgrade to networking.k8s.io/v1 to support newer versions of Kubernetes.

Ref: kubeflow/manifests#375

It looks like this was introduced in 1.8 so there shouldn't be any blocker to upgrading our ingresses now
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by Jeffwan** [comment]
EKS doesn't support 1.16 yet and this will be visited later.

**Comment by jlewi** [comment]
Should be fixed by #1287
