### ISSUE TITLE
Replace Deployment Manager with KCC

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#894]
Opening this issue to track using KCC instead of Deployment Manager on GCP.

This should allow us to create a more Kubernetes native approach to managing all of the infrastructure and ultimately create a better GitOps story for Kubeflow

**Comment by AlexBulankou** [comment]
Perhaps worth clarifying that this refers to [Config Connector for K8s](https://cloud.google.com/config-connector/docs/overview) that just announced [General Availability](https://cloud.google.com/blog/products/containers-kubernetes/config-connector-bridges-kubernetes-gcp-resources).
At this time Config Connector [supports about 70+ GCP resources](https://cloud.google.com/config-connector/docs/reference/resources) and integrates with [Config Sync](https://cloud.google.com/kubernetes-engine/docs/add-on/config-sync/overview).

**Comment by jlewi** [comment]
@kunmingg has started working on this and I hope we will ship a KCC configuration in the next release 1.1.

The motivation here is providing a strong security (data exfiltration) story for Kubeflow on GCP.

That requires setting a bunch of GKE settings (e.g. private GKE) and we'd like to publish reference manifests.

I would prefer not to continue to invest in deployment manager configs because it leads to an inconsistent configuration experience. 

In particular by migrating to KCC we should be able to use kustomize to let people/configure the GCP templates we provide. That should lead to a much more consistent experience with better support for advanced customizations.

**Comment by kunmingg** [comment]
KCC config merged:
https://github.com/kubeflow/manifests/tree/master/gcp/v2/cnrm
