### ISSUE TITLE
Enable Metadata Writer for KFP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#897]
See this comment
https://github.com/kubeflow/manifests/issues/796#issuecomment-584491877

KFP and metadata need to be configured correctly to enable the metadata writer service.

/cc @elikatsis @Ark-kun

**Comment by jlewi** [comment]
@Ark-kun any interest in picking this up?

Some relevant links
https://github.com/kubeflow/pipelines/tree/master/backend/metadata_writer

**Comment by elikatsis** [comment]
@jlewi We first need to merge https://github.com/kubeflow/pipelines/pull/3108

**Comment by jlewi** [comment]
@elikatsis @dushyanthsc any update on this?

**Comment by elikatsis** [comment]
Hi @jlewi,

I believe MetadataWriter implementation as well as the related KFP manifests are compatible with KF manifests. So it should be easy to extend these manifests to deploy metadata writer.

I'll let @dushyanthsc or @rmgogogo verify.

**Comment by dushyanthsc** [comment]
We updated the manifest to be consistent. Is there anything else required to change on the Metadata (gRPC) deployments to enable metadata-writer @Ark-kun ?

**Comment by jlewi** [comment]
Downgrading to p2 and removing from KF 1.1. because it doesn't look like we have a clear owner so it doesn't seem like its going to get completed.

/cc @aronchick @karlschriek

**Comment by Ark-kun** [comment]
> Is there anything else required to change on the Metadata (gRPC) deployments to enable metadata-writer @Ark-kun ?

No. Metadata Writer is standalone and should be compatible with the rest of the deployments (after the GRPC vs. HTTP service names were fixed).

**Comment by Ark-kun** [comment]
@jlewi I think we just need to add the Metadata Writer deployment (deployment, SA, role, binding) manifests to KF.

**Comment by Ark-kun** [comment]
Looks like https://github.com/kubeflow/manifests/pull/1248 fixes this issue.
