### ISSUE TITLE
Support external mysql database for metadata and pipeline

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#905]
Currently, we use PersistVolume based mysql database for these projects and upgrade and performance becomes a challenges. 

One solution is to use external mysql database, we can add overlays and make this as another option for users. 

Address https://github.com/kubeflow/kubeflow/issues/4546

**Comment by zhenghuiwang** [comment]
/lgtm

 The metadata part looks good. Do you plan to make it the default overlay for aws?
