### ISSUE TITLE
Bump pipeline version to 0.2.5 in v1.0-branch

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#984]
Pipeline version in Kubeflow v1.0 is 0.2.0 which has been released for 2 months. 
I suggest to bump the version to 0.2.5 in v1.0-branch as it contains some performance critical improvements.

Examples:
https://github.com/kubeflow/pipelines/issues/3165

/cc @richardsliu @Bobgy @Ark-kun

**Comment by Bobgy** [comment]
Yep, I think we should do this. I'd like to know others' opinions too.

Related issues include https://github.com/kubeflow/kubeflow/issues/4829

**Comment by Jeffwan** [comment]
Hi @Bobgy, Not sure any compatibility concerns to use 0.2.5 in v1.0-branch? I think the plan should be use 0.2.5 is master, run some manual tests and if cherry-pick back to v1.0-branch?

**Comment by Bobgy** [comment]
I don't think there are any compatibility issues, KFP has been backward compatible from 0.2.0 to 0.2.5

**Comment by Jeffwan** [comment]
@Bobgy Cool, thanks for the confirmation. Kindly ping @Ark-kun @rmgogogo for their feedbacks

**Comment by Bobgy** [comment]
@Ark-kun @rmgogogo pinging again

**Comment by elikatsis** [comment]
This (important) issue is also resolved in KFP>0.2.0 (included in release 0.2.1): https://github.com/kubeflow/pipelines/issues/2764

**Comment by Bobgy** [comment]
I'd like to send a PR to update KFP to 0.3.0 instead, because we'd make sure kfp is not broken due to https://github.com/kubeflow/kfctl/pull/131.

KFP 0.3.0 included the fix: https://github.com/kubeflow/pipelines/pull/3305

**Comment by Bobgy** [comment]
I didn't see this issue is about v1.0-branch. Actually I only intend to upgrade to 0.3.0 in master branch, because it was not as heavily tested as 0.2.5. I'd still recommend 0.2.5 for v1.0-branch.

**Comment by Jeffwan** [comment]
We need to discuss whether we like to cut v1.1-branch. If it's coming soon, it's fine to leave v1.0-branch with existing version

**Comment by Bobgy** [comment]
@Jeffwan Jeremey mentioned v1.1 is targeted for June, so looks like updating v1.0-branch will be the best option now.

**Comment by apryiomka** [comment]
Do we know when this might be merged to Kubeflow v1.0.2 manifest?
