### ISSUE TITLE
kf-serving gateway for v1.0.0 fails to build with kfctl

### ISSUE THREAD

**Issue by wildermuthn** [kubeflow/manifests#991]
https://github.com/kubeflow/manifests/pull/949 was recently merged into master for a `kf-serving gateway` that fixes `kf-serving` problems. However, `kfctl build` fails with the `gcp_iap_v1.0.0.yaml` due to the `v1.0.0` branch not also being updated with the PR. But It's possible I'm making a mistake here. 

Any help is much appreciated, and I'm grateful for the work @krishnadurai has put into this already.

**Comment by jal06** [comment]
Looks like I have the same problem with application kfserving-gateway
When applying kfctl_gcp_iap.v1.0.1.yaml :
`kfctl apply -V -f ${CONFIG_URI}`

I get this error :
Error: failed to build kfApp from URI https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_gcp_iap.v1.0.1.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway

**Comment by krishnadurai** [comment]
@wildermuthn the current master branch of manifests has the new changes for KFServing's new gateway `kfserving-gateway`. Could you please use the master branch's kfdef instead?

@jal06 this fix lies in master branch of manifests. We haven't yet released it as a patch.

**Comment by wildermuthn** [comment]
@krishnadurai I'm using the master branch, however, the kfdef manifest itself uses the v1 branch here:

https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.v1.0.0.yaml#L425

This causes `kfctl` to pull from branch `v1` which does not include the definition for the gateway. If `master.yaml` is used, this also breaks since master uses KF .7.

**Comment by krishnadurai** [comment]
@wildermuthn you could use this file instead, this file does not have a version pinned on it and works with manifests/master branch:

https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml#L425

**Comment by Lordfourteen** [comment]
I have the same problem when I use kfctl_k8s_istio.v1.0.1.yaml, It seems that released manifests-1.0.1.tar don't contain kfserving-gateway subfile directory. How can I fix it? Just add those file manualy?

**Comment by NicholaiStaalung** [comment]
> @wildermuthn you could use this file instead, this file does not have a version pinned on it and works with manifests/master branch:
> 
> https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml#L425

Tried installing with that file and i got this error:

> Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating datascience-storage error(400): BAD REQUEST

I do have owner permissions. I even tried with the organization admin account.

this issue #3003 talks about it and i think it was closed to early as several people stated they have owner permissions and still exhibits the error

**Comment by NicholaiStaalung** [comment]
> > @wildermuthn you could use this file instead, this file does not have a version pinned on it and works with manifests/master branch:
> > https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml#L425
> 
> Tried installing with that file and i got this error:
> 
> > Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating datascience-storage error(400): BAD REQUEST
> 
> I do have owner permissions. I even tried with the organization admin account.
> 
> this issue [#3003](https://github.com/kubeflow/kubeflow/issues/3003) talks about it and i think it was closed to early as several people stated they have owner permissions and still exhibits the error

I tested a new installation in a sandbox enviroment on GCP that i created which moved past the error i just had. The only difference that between the two enviroments is that i didnt create the production environment that im trying to install kubeflow on. So i guess its not only needed for one to be the project owner, but also the project creator (if there are such thing on GCP). Ill open a new issue.

**Comment by supertetelman** [comment]
I'm getting a similar error using the v.1.0.2 version of the `kfctl_k8s_istio.v1.0.2.yaml` config.

```

ERRO[0003] error evaluating kustomization manifest for kfserving-gateway Error absolute path error in 'kustomize/kfserving-gateway' : evalsymlink failure on 'kustomize/kfserving-gateway' : lstat /home/ubuntu/deepops/config/kubeflow-install/kustomize/kfserving-gateway: no such file or directory  filename="kustomize/kustomize.go:175"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for kfserving-gateway Error absolute path error in 'kustomize/kfserving-gateway' : evalsymlink failure on 'kustomize/kfserving-gateway' : lstat /home/ubuntu/deepops/config/kubeflow-install/kustomize/kfserving-gateway: no such file or directory
```
It works fine when I move up to the master branch and use `kfctl_k8s_istio.yaml`

**Comment by Manvi07** [comment]
The file `kfctl_gcp_iap.yaml` no longer exists on the master. I get a similar error on version v1.0.2:
```
Error: AccumulateTarget: rawResources failed to read Resources: Load from path kfctl_gcp_iap.yaml failed: evalsymlink failure on '/home/user/K8_cluster/manifests/kfdef/source/master/kfctl_gcp_iap.yaml' : lstat /home/user/K8_cluster/manifests/kfdef/source/master/kfctl_gcp_iap.yaml: no such file or directory
```
